Class DDLevelCompatibility : LevelPostProcessor
{
	protected void Apply( Name checksum, String mapname )
	{
		// [Hexen] force Mystic Ambit Incants to spawn outside coop [thanks Marisa :V]
		if (gameinfo.gametype & GAME_Hexen)
		{
			for (int i = 0; i <GetThingCount(); i++)
			{
				if (GetThingEdNum(i) != 10120 ) continue;
				uint flg = GetThingFlags(i);
				SetThingFlags(i,flg|MTF_SINGLE);
			}
		}
	}
}