class ClassID : Inventory
{
	default
	{
		Inventory.MaxAmount 1;
	}
}

class DDPlayerPawn : PlayerPawn
{
	const SKILL_VERY_EASY = 0;
	const SKILL_EASY = 1;
	const SKILL_NORMAL = 2;
	const SKILL_HARD = 3;
	const SKILL_VERY_HARD = 4;
	const SKILL_EXTREME = 5;
	const SKILL_HORRIBLE = 6;
	const SKILL_IMPOSSIBLE = 7;
	const SKILL_OMEGA = 8;
	
	double airreplen, airreplentimer;
	int damagecntfrag;
	int mobjdmg;
	int playoutputdmg;
	int playtookdamage;
	
	bool wasongroundprevtic, wasongroundcurrtic;
	double PlayerDefenseIgnoreFactor, PlayerArmorIgnoreFactor, PlayerArmorIgnoreFactorGeneral;
	int ActualLevel;
	int TruePlayerLevel;
	int TruePlayerATK;
	int TruePlayerDEF;
	int TruePlayerSPD;
	
	actor DmgSource;
	actor DmgInflictor;
	int DmgFlags;
	bool tookflrdmg;

	mixin HUDRecovery;
	mixin DynMusicControl;
	bool IPAttack;
	bool takendrowndmg;
	bool willgasp;
	
	int PoisonDmgPainInt;
	int AirTime, MaxAirTime;
	int InWaterTime;
	
	int ipmodecooldowntimer;
	bool isvoodoodoll;
	int neverbleeds;
	bool recalledall;
	int ipchargesoundtimer;
	double truespeed;
	int armortier;
	int IPLoopTimer;
	int beattimer;
	int beatpulse, hudbeatpulse;
	
	int lasthealth;
	int breathdirection; // 0 = down [size decreases], 1 = up [size increases]
	int breathframe;

	
	int DashTimer; int MaxDashTimer; 
	int cooldash; bool sounddash; 
	int thrudash; bool isdashing;
	double floordashvel, airdashvel, dashjumpstrength;
	double dashvelx, dashvely, dashvelz;

	int dashcooldown;
	int dashcooldownmax;
	
	int deadtimer;
	int fadetime;
	int originalheight;
	int originalradius;
	int originalmass;

	int firsttic;
	int buttons, input;
	
	double TotalAirControl;
	double basexscale, baseyscale;
	double scalexmulti, scaleymulti;
	
	mixin IPCostCheck;
	
	class<Actor> extracheck, extracheck2, extracheck3, extracheck4;
	string nm, nn, no, np;

	default
	{
		+CASTSPRITESHADOW;
		-NOSPRITESHADOW;
		//RenderStyle "Add";
		//Alpha 1.0;
	}
	
	int A_CheckActualLevel(int type = 0)
	{
		actor player = players[0].mo;
		let MiscItem = PlayerStatItem(Player.FindInventory("PlayerStatItem"));

		int Level = 0;
		if (MiscItem)
		{
			if (exex_expenabled) 
			{
				if (type == 0) Level = MiscItem.PlayerLevel;
				if (type >= 1) Level = MiscItem.TruePlayerLevel;
			}
			else
			{
				if (A_CheckDDGame()) Level = MiscItem.TotalNRPGLvlPts;
			}
		}
		if (dydudebug_playerlevelchecks) Console.Printf("\c[green](%s) \c[gold](A_CheckActualLevel - DDPlayerPawn)\c- PlayerLevel: %d [%d]", GetClassName(), level, gametic);
		return Level;
	}

	override void PlayerLandedMakeGruntSound(actor onmobj)
	{
		bool grunted;

		// [RH] only make noise if alive
		if (self.health > 0 && !self.player.morphTics)
		{
			grunted = false;
			// Why should this number vary by gravity?
			double truegruntspeed = self.player.mo.GruntSpeed;
			if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) truegruntspeed *= 1.34;
			//Console.Printf("%.8f (%.8f) [%.8f]", self.Vel.Z, truegruntspeed, self.player.mo.GruntSpeed);
			if (waterlevel <= 1)
			{
				if (self.Vel.Z < -truegruntspeed)
				{
					A_StartSound("*grunt", CHAN_VOICE);
					grunted = true;
				}
				bool isliquid = (pos.Z <= floorz) && HitFloor();
				if (onmobj != NULL || !isliquid)
				{
					A_StartSound("*land", CHAN_BODY);
				}
			}
			else
			{
			}
		}
	}

	override void BeginPlay()
	{
		basexscale = scale.x;
		baseyscale = scale.y;
		scalexmulti = 1.00;
		scaleymulti = 1.00;

		// Player is always considered a Voodoo Doll during BeginPlay, so height/radius have to be saved before the initial change and then reverted back to it for PostBeginPlay/etc when proper doll detection actually works >____>;
		// Also 'isvoodoodoll' CAN'T be set right now, has to be done in PostBeginPlay/Tick as well <____<;
		originalheight = height;
		originalradius = radius;
		originalmass = mass;

		A_SetSize(16,56,false);
		scale.x = 1.0;
		scale.y = 1.0;
		Mass = 100;
		vel.x = vel.y = vel.z = 0;
		if (dydudebug_showvoodoodoll) Console.Printf("VoodooDoll [BeginPlay] - \c[gold]H: %d, R: %d, M: %d, \c[sapphire]Sx: %4f, Sy: %4f, \c[fire]PosX: %d, PosY: %d, PosZ: %d", height, radius, mass, scale.x, scale.y, pos.x, pos.y, pos.z);

		Super.BeginPlay(); 
	}

	override void PostBeginPlay()
	{
		// VOODOO Doll Protection
		if (!player || !player.mo || player.mo != self)
		{
			A_SetSize(16,56,false);
			scale.x = 1.0;
			scale.y = 1.0;
			Mass = 100;
			isvoodoodoll = true;
			if (dydudebug_showvoodoodoll) Console.Printf("VoodooDoll [PostBeginPlay] - \c[gold]H: %d, R: %d, M: %d, \c[sapphire]Sx: %4f, Sy: %4f, \c[fire]PosX: %d, PosY: %d, PosZ: %d", height, radius, mass, scale.x, scale.y, pos.x, pos.y, pos.z);
			Super.PostBeginPlay(); 
			return;
		}
		else
		{
			A_SetSize(originalradius,originalheight,false);
			Mass = originalmass;
			scale.x = basexscale;
			scale.y = baseyscale;
			if (dydudebug_showvoodoodoll) Console.Printf("Player [PostBeginPlay] - \c[gold]H: %d, R: %d, M: %d, \c[sapphire]Sx: %4f, Sy: %4f, \c[fire]PosX: %d, PosY: %d, PosZ: %d", height, radius, mass, scale.x, scale.y, pos.x, pos.y, pos.z);
		}

		if (bNOBLOOD == 1) 
		{
			if (bNOBLOODDECALS == 0) bNOBLOODDECALS == 1;
			neverbleeds = 1;
		}
		if (bNOBLOODDECALS == 1) 
		{
			if (bNOBLOOD == 0) bNOBLOOD == 1;
			neverbleeds = 1;
		}
		
		Super.PostBeginPlay(); // KEEP THIS HERE ELSE OTHER FUNCTIONS RELATED TO PostBeginPlay() BREAK :V
	}
	
	/*
	==================
	=
	= P_CalcHeight
	=
	=
	Calculate the walking / running height adjustment
	=
	==================
	*/

	override void CalcHeight()
	{
		let player = self.player;
		double angle;
		double bob;
		bool still = false;

		// Regular movement bobbing
		// (needs to be calculated for gun swing even if not on ground)

		// killough 10/98: Make bobbing depend only on player-applied motion.
		//
		// Note: don't reduce bobbing here if on ice: if you reduce bobbing here,
		// it causes bobbing jerkiness when the player moves from ice to non-ice,
		// and vice-versa.

		if (player.cheats & CF_NOCLIP2)
		{
			player.bob = 0;
		}
		else if (bNoGravity && !player.onground)
		{
			player.bob = 0.5;
		}
		else
		{
			player.bob = player.Vel dot player.Vel;
			if (player.bob == 0)
			{
				still = true;
			}
			else
			{
				player.bob *= player.GetMoveBob();

				if (player.bob > MAXBOB)
					player.bob = MAXBOB;
			}
		}

		double defaultviewheight = ViewHeight + player.crouchviewdelta;

		if (player.cheats & CF_NOVELOCITY)
		{
			player.viewz = pos.Z + defaultviewheight;

			if (player.viewz > ceilingz-4)
				player.viewz = ceilingz-4;

			return;
		}

		if (still)
		{
			if (player.health > 0)
			{
				angle = Level.maptime / (120 * TICRATE / 35.) * 360.;
				bob = player.GetStillBob() * sin(angle);
			}
			else
			{
				bob = 0;
			}
		}
		else
		{
			angle = Level.maptime / (20 * TICRATE / 35.) * 360.;
			bob = player.bob * sin(angle) * (waterlevel > 1 ? 0.25f : 0.5f);
		}

		// move viewheight
		if (player.playerstate == PST_LIVE)
		{
			player.viewheight += player.deltaviewheight;

			if (player.viewheight > defaultviewheight)
			{
				player.viewheight = defaultviewheight;
				player.deltaviewheight = 0;
			}
			else if (player.viewheight < (defaultviewheight/2))
			{
				player.viewheight = defaultviewheight/2;
				if (player.deltaviewheight <= 0)
					player.deltaviewheight = 1 / 65536.;
			}
			
			if (player.deltaviewheight)	
			{
				player.deltaviewheight += 0.25;
				if (!player.deltaviewheight)
					player.deltaviewheight = 1/65536.;
			}
		}

		if (player.morphTics)
		{
			bob = 0;
		}
		player.viewz = pos.Z + player.viewheight + (bob * clamp(ViewBob, 0. , 1.5)); // [SP] Allow DECORATE changes to view bobbing speed.
		if (Floorclip && player.playerstate != PST_DEAD
			&& pos.Z <= floorz)
		{
			player.viewz -= Floorclip;
		}
		if (player.viewz > ceilingz - 4)
		{
			player.viewz = ceilingz - 4;
		}
		if (player.viewz < floorz + 4)
		{
			player.viewz = floorz + 4;
		}
	}


	//==========================================================================
	//
	// P_DeathThink
	//
	//==========================================================================

	override void DeathThink()
	{
		let player = self.player;
		int dir;
		double delta;

		player.Uncrouch();
		TickPSprites();

		player.onground = (pos.Z <= floorz);
		if (self is "PlayerChunk")
		{ // Flying bloody skull or flying ice chunk
			player.viewheight = 6;
			player.deltaviewheight = 0;
			if (player.onground)
			{
				if (Pitch > -19.)
				{
					double lookDelta = (-19. - Pitch) / 8;
					Pitch += lookDelta;
				}
			}
		}
		else if (!bIceCorpse)
		{ // Fall to ground (if not frozen)
			player.deltaviewheight = 0;
			if (player.viewheight > 6)
			{
				player.viewheight -= 1;
			}
			if (player.viewheight < 6)
			{
				player.viewheight = 6;
			}
			if (Pitch < 0)
			{
				Pitch += 3;
			}
			else if (Pitch > 0)
			{
				Pitch -= 3;
			}
			if (abs(Pitch) < 3)
			{
				Pitch = 0.;
			}
		}
		player.mo.CalcHeight ();
			
		if (player.attacker && player.attacker != self)
		{ // Watch killer
			double diff = deltaangle(angle, AngleTo(player.attacker));
			double delta = abs(diff);
	
			if (delta < 10)
			{ // Looking at killer, so fade damage and poison counters
				if (player.damagecount)
				{
					player.damagecount--;
				}
				if (player.poisoncount)
				{
					player.poisoncount--;
				}
			}
			delta /= 8;
			Angle += clamp(diff, -5., 5.);
		}
		else
		{
			if (player.damagecount)
			{
				player.damagecount--;
			}
			if (player.poisoncount)
			{
				player.poisoncount--;
			}
		}		

		if ((player.cmd.buttons & BT_USE ||
			((deathmatch || alwaysapplydmflags) && sv_forcerespawn)) && !sv_norespawn)
		{
			if (Level.maptime >= player.respawn_time || ((player.cmd.buttons & BT_USE) && player.Bot == NULL))
			{
				player.cls = NULL;		// Force a new class if the player is using a random class
				player.playerstate = (multiplayer || level.AllowRespawn || sv_singleplayerrespawn || G_SkillPropertyInt(SKILLP_PlayerRespawn)) ? PST_REBORN : PST_ENTER;
				if (special1 > 2)
				{
					special1 = 0;
				}
			}
		}
	}
	
	//===========================================================================
	//
	// PlayerPawn :: Die
	//
	//===========================================================================
	
	override void Die (Actor source, Actor inflictor, int dmgflags, Name MeansOfDeath)
	{
		Super.Die (source, inflictor, dmgflags, MeansOfDeath);

		if (player != NULL && player.mo == self) player.bonuscount = 0;

		if (player != NULL && player.mo != self)
		{ // Make the real player die, too
			player.mo.Die (source, inflictor, dmgflags, MeansOfDeath);
		}
		else
		{
			if (player != NULL && sv_weapondrop)
			{ // Voodoo dolls don't drop weapons
				let weap = player.ReadyWeapon;
				if (weap != NULL)
				{
					// kgDROP - start - modified copy from a_action.cpp
					let di = weap.GetDropItems();

					if (di != NULL)
					{
						while (di != NULL)
						{
							if (di.Name != 'None')
							{
								class<Actor> ti = di.Name;
								if (ti) A_DropItem (ti, di.Amount, di.Probability);
							}
							di = di.Next;
						}
					} 
					else if (weap.SpawnState != NULL &&
						weap.SpawnState != GetDefaultByType('Actor').SpawnState)
					{
						let weapitem = Weapon(A_DropItem (weap.GetClass(), -1, 256));
						if (weapitem)
						{
							if (weap.AmmoGive1 && weap.Ammo1)
							{
								weapitem.AmmoGive1 = weap.Ammo1.Amount;
							}
							if (weap.AmmoGive2 && weap.Ammo2)
							{
								weapitem.AmmoGive2 = weap.Ammo2.Amount;
							}
							weapitem.bIgnoreSkill = true;
						}
					}
					else
					{
						let item = Inventory(A_DropItem (weap.AmmoType1, -1, 256));
						if (item != NULL)
						{
							item.Amount = weap.Ammo1.Amount;
							item.bIgnoreSkill = true;
						}
						item = Inventory(A_DropItem (weap.AmmoType2, -1, 256));
						if (item != NULL)
						{
							item.Amount = weap.Ammo2.Amount;
							item.bIgnoreSkill = true;
						}
					}
				}
			}
			if (!multiplayer && level.deathsequence != 'None')
			{
				level.StartIntermission(level.deathsequence, FSTATE_EndingGame);
			}
		}
	}
	
	void ForwardThrust (double move, double angle)
	{
		if ((waterlevel || bNoGravity) && Pitch != 0 && !player.GetClassicFlight())
		{
			double zpush = move * sin(Pitch);
			if (waterlevel && waterlevel < 2 && zpush < 0) zpush = 0;
			Vel.Z -= zpush;
			move *= cos(Pitch);
		}
		Thrust(move, angle);
	}

	override bool ResetAirSupply(bool playgasp)
	{
		let player = self.player;
		let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
		
		bool wasdrowning;
		if (AirTime <= 0) 
		{
			wasdrowning = true;
			AirTime = 0;
			if (dydudebug_airmeter == 1) Console.Printf("wasdrowning");
		}
		
		if (AirTime < MaxAirTime)
		{
			if (ddafd_underwatercompat && (CountInv("IsDynDuchess") || CountInv("IsAppetite") || CountInv("IsCarnOfSouls") || CountInv("IsWeddingCake")))
			{
				if (AirTime != MaxAirTime) AirTime = MaxAirTime;
			}
			else
			{
				if (MaxAirTime > 0) airreplen = ((MaxAirTime / (TICRATE * 5.0)) * 100.0);
				if (airreplen < 1) airreplen = 1;
				if (MiscItem) airreplen *= (1.0 + (ActualLevel * 0.0125));
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) airreplen *= 1.25;
				if (CountInv("PowerNoDrown") || CountInv("PowerIronFeet") || CountInv("PowerIronFeet2") || CountInv("PowerMask")) airreplen *= 1.625;
				if (MiscItem)
				{
					if (!exex_expenabled)
					{
						double DDTFactor = 0.0;
						if ((CountInv("IsDynDuchess") || CountInv("IsAppetite") || CountInv("IsCarnOfSouls") || CountInv("IsWeddingCake")))
						{
							if (MiscItem.DD_RoseMother) DDTFactor += 0.01875;
							if (MiscItem.DD_GameMother) DDTFactor += 0.01875;
							if (MiscItem.DD_MossMother) DDTFactor += 0.01875;
							if (MiscItem.DD_GlobeMother) DDTFactor += 0.01875;
							if (MiscItem.DD_SphinxMother) DDTFactor += 0.01875;
							if (MiscItem.DD_HandMother1) DDTFactor += 0.01875;
							if (MiscItem.DD_HandMother2) DDTFactor += 0.01875;
							if (MiscItem.DD_TrueHandMother) DDTFactor += 0.01875;
							if (MiscItem.AFD_Krag) DDTFactor += 0.025;
							if (MiscItem.AFD_Quisling) DDTFactor += 0.025;
							if (MiscItem.AFD_Lauritz) DDTFactor += 0.025;
							if (MiscItem.AFD_Jorgensen1) DDTFactor += 0.025;
							if (MiscItem.AFD_Jorgensen2) DDTFactor += 0.025;
							if (MiscItem.AFD_JorgCannon) DDTFactor += 0.025;
							if (MiscItem.CoS_Fafnir) DDTFactor += 0.025;
							if (MiscItem.CoS_FractalHens) DDTFactor += 0.025;
							if (MiscItem.CoS_HandMothers) DDTFactor += 0.025;
							if (MiscItem.CoS_ForsakenJorg) DDTFactor += 0.025;
							if (MiscItem.CoS_EvilDinah) DDTFactor += 0.025;
							if (MiscItem.CoS_Tempest) DDTFactor += 0.025;
							if (skill <= 0) DDTFactor *= 4.0;
							if (skill == 1) DDTFactor *= 3.5;
							if (skill == 2) DDTFactor *= 3.0;
							if (skill == 3) DDTFactor *= 2.5;
							if (skill >= 4) DDTFactor *= 2.0;
							DDTFactor *= exex_nrpggeneraleffect;
							DDTFactor += 1.0;
							if (dydudebug_airmeter >= 1) Console.Printf("DDTFactor [airreplen]: %.8f", DDTFactor);
							DDTFactor = int(floor(DDTFactor));
							airreplen *= DDTFactor;
						}
					}
					if (MiscItem.drowndebufflevel)
					{
						airreplen *= (1.00 - (MiscItem.drowndebufflevel * frandompick(0.5,0.0625,0.0625,0.75,0.75,0.75,0.75,0.75,0.875,0.875,0.875,1.0)));
						if (airreplen < 1 && random(1,16) <= (16 - int(MiscItem.drowndebufflevel * frandom(0.8,1.2)))) airreplen = 1;
						if (airreplen < 0) airreplen = 0;
					}
				}
				airreplentimer += airreplen;
				while (airreplentimer > 100)
				{
					AirTime += 1;
					airreplentimer -= 100;
				}
				if (dydudebug_airmeter >= 1) Console.Printf("\c[sapphire]airreplentimer: %d, airreplen: %d (%d / %d)", airreplentimer, airreplen, AirTime, MaxAirTime);
			}
			if (AirTime > MaxAirTime) AirTime = MaxAirTime;
		}

		if (playgasp)
		{
			if (wasdrowning)
			{
				bool emergegaspsnd = false;
				if (takendrowndmg)
				{
					emergegaspsnd = true;
					takendrowndmg = false;
				}
				else if (random(1,9) <= 6) 
				{
					emergegaspsnd = true;
					willgasp = false;
				}

				if (emergegaspsnd)
				{
					if (waterlevel <= 2)
					{
						A_StopSound(CHAN_VOICE);
						if (GetClassName() == "DinahPlayer") A_StartSound("dinah/drowngasp1",CHAN_VOICE,CHANF_DEFAULT,frandom(0.9,1.1),ATTN_NORM,1.0);
					}
					willgasp = false;
				}
			}
			else
			{
				bool emergegaspsnd = false;
				if (willgasp)
				{
					int AirMeterRatio;
					if (MaxAirTime > 0) 
					{
						AirMeterRatio = (AirTime * 100 / MaxAirTime);
						
						if (AirMeterRatio <= 75) emergegaspsnd = true;
						else if (AirMeterRatio <= randompick(87,88) && random(1,16) <= 10) emergegaspsnd = true;
						else if (AirMeterRatio <= 100 && random(1,16) <= 4) emergegaspsnd = true;
						
						if (emergegaspsnd)
						{
							if (waterlevel <= 2)
							{
								A_StopSound(CHAN_VOICE);
								if (GetClassName() == "DinahPlayer") A_StartSound("dinah/watergasp",CHAN_VOICE,CHANF_DEFAULT,frandom(0.9,1.1),ATTN_NORM,1.0);
							}
						}
					}
					willgasp = false;
				}
			}
		}
		return wasdrowning;
	}
	
	void SpawnBubbles(string bubbletype = "AirBubble1", double bubblex = 0, double bubbley = 0, double bubblez = 0)
	{
		bubblex += random(3,11);
		bubblex += random(-2,2);
		bubblez += random((Player.ViewHeight-2),(Player.ViewHeight+2));
		A_SpawnItemEx("AirBubble1",bubblex,bubbley,bubblez,0,0,0,0,SXF_NOCHECKPOSITION);
	}
	
	override void CheckAirSupply()
	{
		if (!player || !player.mo || player.mo != self)
		{
			super.CheckAirSupply();
		}
		else
		{
			let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
			if (ddafd_underwatercompat && (CountInv("IsDynDuchess") || CountInv("IsAppetite") || CountInv("IsCarnOfSouls") || CountInv("IsWeddingCake")))
			{
				MaxAirTime = (20 * TICRATE);
			}
			else
			{
				MaxAirTime = (12 * TICRATE);
				if (!exex_expenabled)
				{
					double DDTFactor = 0.0;
					if ((CountInv("IsDynDuchess") || CountInv("IsAppetite") || CountInv("IsCarnOfSouls") || CountInv("IsWeddingCake")))
					{
						if (MiscItem.DD_RoseMother) DDTFactor += 0.01875;
						if (MiscItem.DD_GameMother) DDTFactor += 0.01875;
						if (MiscItem.DD_MossMother) DDTFactor += 0.01875;
						if (MiscItem.DD_GlobeMother) DDTFactor += 0.01875;
						if (MiscItem.DD_SphinxMother) DDTFactor += 0.01875;
						if (MiscItem.DD_HandMother1) DDTFactor += 0.01875;
						if (MiscItem.DD_HandMother2) DDTFactor += 0.01875;
						if (MiscItem.DD_TrueHandMother) DDTFactor += 0.01875;
						if (MiscItem.AFD_Krag) DDTFactor += 0.025;
						if (MiscItem.AFD_Quisling) DDTFactor += 0.025;
						if (MiscItem.AFD_Lauritz) DDTFactor += 0.025;
						if (MiscItem.AFD_Jorgensen1) DDTFactor += 0.025;
						if (MiscItem.AFD_Jorgensen2) DDTFactor += 0.025;
						if (MiscItem.AFD_JorgCannon) DDTFactor += 0.025;
						if (MiscItem.CoS_Fafnir) DDTFactor += 0.025;
						if (MiscItem.CoS_FractalHens) DDTFactor += 0.025;
						if (MiscItem.CoS_HandMothers) DDTFactor += 0.025;
						if (MiscItem.CoS_ForsakenJorg) DDTFactor += 0.025;
						if (MiscItem.CoS_EvilDinah) DDTFactor += 0.025;
						if (MiscItem.CoS_Tempest) DDTFactor += 0.025;
						if (skill <= 0) DDTFactor *= 2.5;
						if (skill == 1) DDTFactor *= 2.25;
						if (skill == 2) DDTFactor *= 2.0;
						if (skill == 3) DDTFactor *= 1.75;
						if (skill >= 4) DDTFactor *= 1.5;
						DDTFactor *= exex_nrpggeneraleffect;
						DDTFactor += 1.0;
						if (dydudebug_airmeter >= 1) Console.Printf("DDTFactor [MaxAirTime]: %.8f", DDTFactor);
						MaxAirTime *= DDTFactor;
					}
				}
				else
				if (MiscItem) MaxAirTime += (TruePlayerLevel * 2.916666666666667);

			}
			if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) MaxAirTime *= 1.25;
			if (MaxAirTime > 0) MaxAirTime *= AirCapacity;
			if (GetAge() <= 1 && AirTime != MaxAirTime) AirTime = MaxAirTime;

			int DrownDmg = 2 + (-AirTime / TICRATE);
			DrownDmg = ceil(DrownDmg * frandompick(0.625,0.75,0.875,1.000));
			if (DrownDmg < 0) DrownDmg = 0;
			if (dydudebug_airmeter == 1) Console.Printf("InWaterTime: %d, WaterLevel: %d, AirTime: %d / %d, DrownDmg: %d, willgasp: %d, takendrowndmg: %d", InWaterTime, waterlevel, AirTime, MaxAirTime, DrownDmg, willgasp, takendrowndmg);
			// Handle air supply	
			//if (level.airsupply > 0)
			{
				let player = self.player;
				if (waterlevel >= 3)
				{
					if (InWaterTime <= 0)
					{
						A_StartSound("misc/enterwater",215,CHANF_DEFAULT,1.0,ATTN_NORM,frandom(0.8,1.2));
					}
					InWaterTime++;
					
					if (CountInv("PowerNoDrown") || 
							CountInv("PowerIronFeet") || 
							CountInv("PowerIronFeet2") || 
							CountInv("PowerMask"))
					{
						willgasp = false;
					}
					else
					{
						willgasp = true;
					}
				}
				else 
				{
					if (InWaterTime > 0)
					{
						A_StartSound("misc/exitwater2",215,CHANF_DEFAULT,1.0,ATTN_NONE,frandom(0.8,1.2));
						if (dydudebug_airmeter == 1) Console.Printf("misc/exitwater2");
					}
					InWaterTime = 0;
				}
				
				if (waterlevel < 3 || (bInvulnerable) || 
					(player.cheats & (CF_GODMODE | CF_NOCLIP2)) || (player.cheats & CF_GODMODE2) || 
					CountInv("PowerInvulnDD") || CountInv("PowerInvulnerable"))
				{
					ResetAirSupply(true);
				}
				else
				{
					buttons = GetPlayerInput(INPUT_BUTTONS);

					double bubblex, bubbley, bubblez;
					if (!(CountInv("PowerNoDrown") || 
								CountInv("PowerIronFeet") || 
								CountInv("PowerIronFeet2") || 
								CountInv("PowerMask"))) AirTime--;
					if (AirTime > MaxAirTime) AirTime = MaxAirTime;
					if (AirTime <= 0)
					{
						if (!(level.maptime & 31) && DrownDmg)
						{
							DamageMobj(NULL, NULL, DrownDmg, 'Drowning');
							string drownsnd = "misc/drowning";
							if (health <= 0) drownsnd = "misc/drowninglong";
							if (health > 0)
							{
								if (MiscItem)
								{
									MiscItem.drowndebuginit = true;
									if (MiscItem.drowndebufflevel < 10)
									{
										MiscItem.drowndebufflevel++;
										MiscItem.drowndebufftimer += random(25,35);
									}
								}
							}
							A_StopSound(120);
							A_StartSound(drownsnd,120,CHANF_DEFAULT,1.0,ATTN_NORM,frandom(1.375,1.5));
							takendrowndmg = true;
							
							SpawnBubbles("AirBubble1",frandom(-5,5),frandom(-5,5),frandom(-3,3));
							SpawnBubbles("AirBubble1",frandom(-5,5),frandom(-5,5),frandom(-3,3));
							SpawnBubbles("AirBubble1",frandom(-5,5),frandom(-5,5),frandom(-3,3));
							if (random(1,3) <= random(1,2))
							{
								SpawnBubbles("AirBubble1",frandom(-8,8),frandom(-8,8),frandom(-5,5));
								SpawnBubbles("AirBubble1",frandom(-8,8),frandom(-8,8),frandom(-5,5));
								SpawnBubbles("AirBubble1",frandom(-8,8),frandom(-8,8),frandom(-5,5));
								if (random(1,3) <= 1) 
								{
									SpawnBubbles("AirBubble1",frandom(-11,11),frandom(-11,11),frandom(-7,7));
									SpawnBubbles("AirBubble1",frandom(-11,11),frandom(-11,11),frandom(-7,7));
									SpawnBubbles("AirBubble1",frandom(-11,11),frandom(-11,11),frandom(-7,7));
								}
							}
						}
					}
					else
					{
						int basechance = 64;
						bool extrabubbles = true;
						bool moveaffectchance = true;
						if (CountInv("PowerNoDrown") || 
								CountInv("PowerIronFeet") || 
								CountInv("PowerIronFeet2") || 
								CountInv("PowerMask"))
						{
							basechance *= 16;
							extrabubbles = false;
							if (random(1,32) <= 31) moveaffectchance = false;
						}
						
						if (moveaffectchance)
						{
							if (buttons & BT_FORWARD || buttons & BT_BACK || buttons & BT_MOVELEFT || buttons & BT_MOVERIGHT)
							{
								basechance *= frandom(0.6,0.75);
								if (random(1,16) <= random(1,2)) basechance *= 0.5;
							}
							if (buttons & BT_JUMP || buttons & BT_CROUCH)
							{
								basechance *= frandom(0.6,0.75);
								if (random(1,16) <= random(1,2)) basechance *= 0.5;
							}
						}
						
						if (random(1,basechance) <= 1)
						{
							SpawnBubbles("AirBubble1",frandom(-4,4),frandom(-4,4),frandom(-2,2));
							if (extrabubbles)
							{
								if (random(1,(basechance*0.125)) <= 1) SpawnBubbles("AirBubble1",frandom(-5,5),frandom(-5,5),frandom(-3,3));
								if (random(1,(basechance*0.5)) <= 1) SpawnBubbles("AirBubble1",frandom(-5,5),frandom(-5,5),frandom(-3,3));
								if (random(1,(basechance*2)) <= 1) SpawnBubbles("AirBubble1",frandom(-5,5),frandom(-5,5),frandom(-3,3));
								if (random(1,(basechance*8)) <= 1) SpawnBubbles("AirBubble1",frandom(-5,5),frandom(-5,5),frandom(-3,3));
							}
						}
					}
				}
			}
			int tempAirTime = AirTime;
			if (tempAirTime < 0) tempAirTime = 0;
			int tempMaxAirTime = MaxAirTime;
			if (tempMaxAirTime < 0) tempMaxAirTime = 0;
			A_SetInventory("AirMeter", tempAirTime);
			A_SetInventory("MaxAirMeter", tempMaxAirTime);
		}
	}
	
	override void CheckFOV()
	{
		let player = self.player;

		if (!player) return;

		// [RH] Zoom the player's FOV
		float desired = player.DesiredFOV;
		// Adjust FOV using on the currently held weapon.
		if (player.playerstate != PST_DEAD &&		// No adjustment while dead.
			player.ReadyWeapon != NULL &&			// No adjustment if no weapon.
			player.ReadyWeapon.FOVScale != 0)		// No adjustment if the adjustment is zero.
		{
			// A negative scale is used to prevent G_AddViewAngle/G_AddViewPitch
			// from scaling with the FOV scale.
			desired *= abs(player.ReadyWeapon.FOVScale);
		}
		if (player.FOV != desired)
		{
			if (abs(player.FOV - desired) < 7.)
			{
				player.FOV = desired;
			}
			else
			{
				float zoom = MAX(7., abs(player.FOV - desired) * 0.025);
				if (player.FOV > desired)
				{
					player.FOV = player.FOV - zoom;
				}
				else
				{
					player.FOV = player.FOV + zoom;
				}
			}
		}
	}
	
	override void CheckCheats()
	{
		let player = self.player;
		// No-clip cheat
		if ((player.cheats & (CF_NOCLIP | CF_NOCLIP2)) == CF_NOCLIP2)
		{ // No noclip2 without noclip
			player.cheats &= ~CF_NOCLIP2;
		}
		bNoClip = (player.cheats & (CF_NOCLIP | CF_NOCLIP2) || Default.bNoClip);
		if (player.cheats & CF_NOCLIP2)
		{
			bNoGravity = true;
		}
		else if (!bFly && !Default.bNoGravity)
		{
			bNoGravity = false;
		}
	}
	
	override void PlayerThink()
	{
		wasongroundprevtic = player.onground;
		let player = self.player;
		UserCmd cmd = player.cmd;
		
		CheckFOV();

		if (player.inventorytics)
		{
			player.inventorytics--;
		}
		CheckCheats();

		if (bJustAttacked)
		{ // Chainsaw/Gauntlets attack auto forward motion
			cmd.yaw = 0;
			cmd.forwardmove = 0xc800/2;
			cmd.sidemove = 0;
			bJustAttacked = false;
		}

		bool totallyfrozen = CheckFrozen();

		// Handle crouching
		CheckCrouch(totallyfrozen);
		CheckMusicChange();

		if (player.playerstate == PST_DEAD)
		{
			DeathThink ();
			return;
		}
		if (player.jumpTics != 0)
		{
			player.jumpTics--;
			if (player.onground && player.jumpTics < -18)
			{
				player.jumpTics = 0;
			}
			//Console.Printf("player.jumpTics: %d", player.jumpTics);
		}
		if (player.morphTics && !(player.cheats & CF_PREDICTING))
		{
			MorphPlayerThink ();
		}

		CheckPitch();
		HandleMovement();
		CalcHeight ();

		if (!(player.cheats & CF_PREDICTING))
		{
			CheckEnvironment();
			// Note that after this point the PlayerPawn may have changed due to getting unmorphed or getting its skull popped so 'self' is no longer safe to use.
			// This also must not read mo into a local variable because several functions in this block can change the attached PlayerPawn.
			player.mo.CheckUse();
			player.mo.CheckUndoMorph();
			// Cycle psprites.
			player.mo.TickPSprites();
			// Other Counters
			if (player.damagecount)
			{
				if (player.damagecount >= random(93,94)) damagecntfrag -= randompick(0,0,0,1,1,1,2,2,2);
				else if (player.damagecount >= 75) damagecntfrag -= randompick(1,1,2,2,3,3,4,4);
				else if (player.damagecount >= 50) damagecntfrag -= randompick(3,3,4,4,5,5,6,6);
				else if (player.damagecount >= 25) damagecntfrag -= randompick(5,6,6,7,7,8,8,9);
				else damagecntfrag -= randompick(8,8,9,9,9,9,10,10);
				while (damagecntfrag <= 0)
				{
					player.damagecount--;
					damagecntfrag += 10;
					if (player.damagecount <= 0) break;
				}
			}
			else
			{
				damagecntfrag = 10;
			}
			if (dydudebug_countdisplays == 1 && player.damagecount > 0) Console.Printf("player.damagecount: %d, damagecntfrag: %d", player.damagecount, damagecntfrag);
			if (player.bonuscount) player.bonuscount--;
			if (dydudebug_countdisplays == 1 && player.bonuscount > 0) Console.Printf("player.bonuscount: %d", player.bonuscount);

			if (player.hazardcount)
			{
				player.hazardcount--;
				if (player.hazardinterval <= 0)
					player.hazardinterval = 32; // repair invalid hazardinterval
				if (!(Level.maptime % player.hazardinterval) && player.hazardcount > 16*TICRATE)
					player.mo.DamageMobj (NULL, NULL, 5, player.hazardtype);
			}
			if (dydudebug_countdisplays == 2) Console.Printf("player.hazardcount: %d, player.hazardinterval: %d / 32, player.hazardtype: %s", player.hazardcount, player.hazardinterval, player.hazardtype);
			player.mo.CheckPoison();
			player.mo.CheckDegeneration();
			player.mo.CheckAirSupply();
		}
		wasongroundcurrtic = player.onground;
		if (dydudebug_playermove) Console.Printf("wasongroundprevtic: %d, wasongroundcurrtic: %d [gametic: %d]", wasongroundprevtic, wasongroundcurrtic, gametic);
	}

	override void MovePlayer()
	{
		if (!player || !player.mo || player.mo != self)
		{
		}
		else
		{
			let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
			double AirControlBase = frandom(0.2432,0.2436);

			// Level Based AirControl
			double LVLAirControl = 1.00;
			if (exex_expenabled) LVLAirControl = 1.00 + (ActualLevel * 0.01);
			
			// DD NO-RPG Mode Air Control
			double NRPGAirControl = 1.0;
			if (!exex_expenabled)
			{
				if (A_CheckDDGame())
				{
					NRPGAirControl = 0.0;
					if (MiscItem.DD_RoseMother) NRPGAirControl += 0.01875;
					if (MiscItem.DD_GameMother) NRPGAirControl += 0.01875;
					if (MiscItem.DD_MossMother) NRPGAirControl += 0.01875;
					if (MiscItem.DD_GlobeMother) NRPGAirControl += 0.01875;
					if (MiscItem.DD_SphinxMother) NRPGAirControl += 0.01875;
					if (MiscItem.DD_HandMother1) NRPGAirControl += 0.01875;
					if (MiscItem.DD_HandMother2) NRPGAirControl += 0.01875;
					if (MiscItem.DD_TrueHandMother) NRPGAirControl += 0.01875;
					if (MiscItem.AFD_Krag) NRPGAirControl += 0.025;
					if (MiscItem.AFD_Quisling) NRPGAirControl += 0.025;
					if (MiscItem.AFD_Lauritz) NRPGAirControl += 0.025;
					if (MiscItem.AFD_Jorgensen1) NRPGAirControl += 0.025;
					if (MiscItem.AFD_Jorgensen2) NRPGAirControl += 0.025;
					if (MiscItem.AFD_JorgCannon) NRPGAirControl += 0.025;
					if (MiscItem.CoS_Fafnir) NRPGAirControl += 0.025;
					if (MiscItem.CoS_FractalHens) NRPGAirControl += 0.025;
					if (MiscItem.CoS_HandMothers) NRPGAirControl += 0.025;
					if (MiscItem.CoS_ForsakenJorg) NRPGAirControl += 0.025;
					if (MiscItem.CoS_EvilDinah) NRPGAirControl += 0.025;
					if (MiscItem.CoS_Tempest) NRPGAirControl += 0.025;
					if (skill <= 0) NRPGAirControl *= 8;
					if (skill == 1) NRPGAirControl *= 7;
					if (skill == 2) NRPGAirControl *= 6;
					if (skill == 3) NRPGAirControl *= 5;
					if (skill >= 4) NRPGAirControl *= 4;
					NRPGAirControl *= exex_nrpggeneraleffect;
					NRPGAirControl += 1.0;
				}
			}

			// Armor items
			double ArmorAirControl = 1.00;
			if (CountInv("KnightGownItem"))			ArmorAirControl += 0.0667;
			if (CountInv("KnightGownItem2"))		ArmorAirControl += 0.10;
			if (CountInv("KnightGownItem3"))		ArmorAirControl += 0.1334;
			if (CountInv("KnightGownItem4"))		ArmorAirControl += 0.18;
			if (MiscItem)
			{
				if (MiscItem.WineDefTier == 1 || MiscItem.WineDefTier == -1) ArmorAirControl *= frandom(0.98,1.00);
				if (MiscItem.WineDefTier == 2 || MiscItem.WineDefTier == -2) ArmorAirControl *= frandom(0.96,1.00);
				if (MiscItem.WineDefTier == 3 || MiscItem.WineDefTier == -3) ArmorAirControl *= frandom(0.93,1.00);
				if (MiscItem.WineDefTier == 4 || MiscItem.WineDefTier == -4) ArmorAirControl *= frandom(0.88,1.00);
				if (MiscItem.WineDefTier == 5 || MiscItem.WineDefTier == -5) ArmorAirControl *= frandom(0.81,1.00);
			}

			// Buffs
			double BuffAirControl = 1.00;
			if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) BuffAirControl *= 1.334;
			if (CountInv("PowerFruitBuff")) BuffAirControl *= 1.125;
			if (CountInv("PowerEggBuff")) BuffAirControl *= 1.25;
			if (CountInv("PowerRoastBuff")) BuffAirControl *= 1.5;
			if (CountInv("PowerMealBuff")) BuffAirControl *= 2;
			if (CountInv("PowerMeal2Buff")) BuffAirControl *= 2;

			level.aircontrol = AirControlBase
											* NRPGAirControl
											* LVLAirControl
											* ArmorAirControl
											* BuffAirControl;
			if (level.aircontrol > 1.00) level.aircontrol = 1.00;
			level.airfriction = level.aircontrol * -0.0941 + 1.0004;

			if (dydudebug_playermove)
			{
				Console.Printf("    \czSV_AirControl:\c- \cz%.8f\c-  \cwTotalAirControl:\c- \cw%.8f\c-, \cyAirControlBase:\c- \cy%.8f\c-, LVLAirControl: %.8f, NRPGAirControl: %.8f, ArmorAirControl: %.8f, BuffAirControl: %.8f", sv_aircontrol, level.aircontrol, AirControlBase, LVLAirControl, NRPGAirControl, ArmorAirControl, BuffAirControl);
				Console.Printf("    \cwTotalFriction:\c- \cw%.8f\c-, \cyLevelAirFriction:\c- \cy%.8f\c-", friction, level.airfriction);
				Console.Printf("    \c[blue]Player.ForwardMove: (%.2f, %.2f), Player.SideMove: (%.2f, %.2f), Player.ViewBob: %.2f", ForwardMove1, ForwardMove2, SideMove1, SideMove2, ViewBob);
			}
		}
		
		let player = self.player;
		UserCmd cmd = player.cmd;

		// [RH] 180-degree turn overrides all other yaws
		if (player.turnticks)
		{
			player.turnticks--;
			Angle += (180. / TURN180_TICKS);
		}
		else
		{
			Angle += cmd.yaw * (360./65536.);
		}

		player.onground = (pos.z <= floorz) || bOnMobj || bMBFBouncer || (player.cheats & CF_NOCLIP2);

		// killough 10/98:
		//
		// We must apply thrust to the player and bobbing separately, to avoid
		// anomalies. The thrust applied to bobbing is always the same strength on
		// ice, because the player still "works just as hard" to move, while the
		// thrust applied to the movement varies with 'movefactor'.

		if (cmd.forwardmove | cmd.sidemove)
		{
			double forwardmove, sidemove;
			double bobfactor;
			double friction, movefactor;
			double fm, sm;

			[friction, movefactor] = GetFriction();
			bobfactor = friction < ORIG_FRICTION ? movefactor : ORIG_FRICTION_FACTOR;
			if (!player.onground && !bNoGravity && !waterlevel)
			{
				// [RH] allow very limited movement if not on ground.
				movefactor *= level.aircontrol;
				bobfactor*= level.aircontrol;
			}

			fm = cmd.forwardmove;
			sm = cmd.sidemove;
			[fm, sm] = TweakSpeeds (fm, sm);
			fm *= Speed / 256;
			sm *= Speed / 256;

			// When crouching, speed and bobbing have to be reduced
			if (CanCrouch() && player.crouchfactor != 1)
			{
				fm *= player.crouchfactor;
				sm *= player.crouchfactor;
				bobfactor *= player.crouchfactor;
			}

			forwardmove = fm * movefactor * (35 / TICRATE);
			sidemove = sm * movefactor * (35 / TICRATE);

			if (forwardmove)
			{
				Bob(Angle, cmd.forwardmove * bobfactor / 256., true);
				ForwardThrust(forwardmove, Angle);
			}
			if (sidemove)
			{
				let a = Angle - 90;
				Bob(a, cmd.sidemove * bobfactor / 256., false);
				Thrust(sidemove, a);
			}

			if (!(player.cheats & CF_PREDICTING) && (forwardmove != 0 || sidemove != 0))
			{
				PlayRunning ();
			}

			if (player.cheats & CF_REVERTPLEASE)
			{
				player.cheats &= ~CF_REVERTPLEASE;
				player.camera = player.mo;
			}
		}
	}
	
	override void FallAndSink(double grav, double oldfloorz)
	{
		if (dydudebug_playermove && WaterDepth > 0) Console.Printf("Current water depth: %f", WaterDepth);

		let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
		let PlayerWeapon = MiscItem.weapon;
		let player = self.player;
		UserCmd cmd = player.cmd;
		bool berserked;
		if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) berserked = true;
		double SuperVacAmmoFactor;
		
		if (dydudebug_playermove) Console.Printf("\c[orange](FallAndSink() Start)\c- Vel.Z: %.4f [oldfloorz: %.8f, grav: %.8f] [tic: %d]", Vel.Z, oldfloorz, grav, gametic);
		if (Pos.Z > floorz && !bNOGRAVITY)
		{
			if (dydudebug_playermove) Console.Printf("Waterlevel: %d, Pos.Z: %.8f, floorz: %.8f [tic: %d]", waterlevel, pos.z, floorz, gametic);
			double startvelz = Vel.Z;
			
			if (waterlevel == 0 || (player && !(cmd.forwardmove | cmd.sidemove)))
			{
				// [RH] Double gravity only if running off a ledge. Coming down from
				// an upward thrust (e.g. a jump) should not double it.
				if (Vel.Z == 0 && oldfloorz > floorz && Pos.Z == oldfloorz)
				{
					Vel.Z -= grav + grav;
				}
				else
				{
					Vel.Z -= grav;
				}
			}
			
			if (player == NULL)
			{
				if (waterlevel >= 1)
				{
					double sinkspeed;
	
					if (bSPECIAL && !bISMONSTER)
					{ // Pickup items don't sink if placed and drop slowly if dropped
						sinkspeed = bDROPPED ? -0.5 / 8 : 0;
					}
					else
					{
						sinkspeed = -0.5;
	
						// If it's not a player, scale sinkspeed by its mass, with
						// 100 being equivalent to a player.
						if (player == NULL)
						{
							sinkspeed = sinkspeed * clamp(Mass, 1, 4000) / 100;
						}
					}
					if (Vel.Z < sinkspeed)
					{ // Dropping too fast, so slow down toward sinkspeed.
						Vel.Z -= max(sinkspeed * 2, -8.);
						if (Vel.Z > sinkspeed)
						{
							Vel.Z = sinkspeed;
						}
					}
					else if (Vel.Z > sinkspeed)
					{ // Dropping too slow/going up, so trend toward sinkspeed.
						Vel.Z = startvelz + max(sinkspeed / 3, -8.);
						if (Vel.Z < sinkspeed)
						{
							Vel.Z = sinkspeed;
						}
					}
				}
			}
			else
			{
				if (waterlevel > 1)
				{
					double massfactor = (MiscItem.PreBuffMass * 0.01);
					if (massfactor > 40.00) massfactor = 40.00;
					double massfactor2 = 1.0 - (ActualLevel * 0.015);
					if (massfactor2 < 0.25) massfactor2 = 0.25;
					double sinkspeed = -0.5;
					sinkspeed *= massfactor;
					sinkspeed *= massfactor2;
					if (dydudebug_playermove) Console.Printf("\c[sapphire]massfactor: %.8f, massfactor2: %.8f, sinkspeed: %.8f, [tic: %d]", massfactor, massfactor2, sinkspeed, gametic);
					
					double armordiffmod = 1.00;
					if (MiscItem)
					{
						if (MiscItem.armoritemdifficulty == 1) armordiffmod = 2.0;
						if (MiscItem.armoritemdifficulty == 2) armordiffmod = 2.5;
						if (MiscItem.armoritemdifficulty >= 3) armordiffmod = 5.0;
						int ArmorAmt = CountInv("KGArmor");
						double ArmorEnc = 0.00;
						if (armortier == 1 && !CountInv("KnightGownIP1Buff")) ArmorEnc = (ArmorAmt * (0.0001 * armordiffmod)); // 0.025;
						if (armortier == 2 && !CountInv("KnightGownIP2Buff")) ArmorEnc = (ArmorAmt * (0.0000975 * armordiffmod)); // 0.04875;
						if (armortier == 3 && !CountInv("KnightGownIP3Buff")) ArmorEnc = (ArmorAmt * (0.000095 * armordiffmod)); // 0.095;
						if (armortier == 4 && !CountInv("KnightGownIP4Buff")) ArmorEnc = (ArmorAmt * (0.00009 * armordiffmod)); // 0.180;
						ArmorEnc *= exex_armorencumbrance;
						if (A_CheckDDGame()) 
						{
							ArmorEnc *= 3;
							ArmorEnc *= exex_nrpggeneraleffect;
						}
						if (waterlevel >= 2)
						{
							if (A_CheckDDGame()) ArmorEnc *= 2.0;
															else ArmorEnc *= 1.5;
						}
						double lvlfact = 0.02;
						if (A_CheckDDGame()) 
						{
							if (skill <= 0) lvlfact = 0.020;
							if (skill == 1) lvlfact = 0.0175;
							if (skill == 2) lvlfact = 0.015;
							if (skill == 3) lvlfact = 0.0125;
							if (skill >= 4) lvlfact = 0.01;
						}
						else
						{
							if (skill <= 0) lvlfact = 0.04;
							if (skill == 1) lvlfact = 0.035;
							if (skill == 2) lvlfact = 0.03;
							if (skill == 3) lvlfact = 0.025;
							if (skill >= 4) lvlfact = 0.02;
						}
						if (waterlevel >= 2) 
						{
							if (A_CheckDDGame()) lvlfact *= 0.5;
															else lvlfact *= 0.75;
						}
						if (ArmorEnc > 0.0) ArmorEnc *= (1.0 - (ActualLevel * lvlfact));
						sinkspeed -= ArmorEnc;
						
						double weaponsinkfactor = 0.00;
						if (PlayerWeapon is "HandToHand") 
						{
							if (berserked) weaponsinkfactor -= frandom(0.75,0.875);
												else weaponsinkfactor -= frandom(0.50,0.75);
						}
						if (PlayerWeapon is "CricketBat") 
						{
							if (berserked) weaponsinkfactor += 0.000;
												else weaponsinkfactor += 0.125;
						}
						if (PlayerWeapon is "BlunderAxe") 
						{
							if (berserked) weaponsinkfactor += 0.008125;
												else weaponsinkfactor += 0.03125;
						}
						if (PlayerWeapon is "AppleJack") 
						{
							if (berserked) weaponsinkfactor -= 0.05;
												else weaponsinkfactor -= 0.03125;
						}
						if (PlayerWeapon is "Scrambler")
						{
							if (berserked) weaponsinkfactor -= 0.1625;
												else weaponsinkfactor -= 0.125;
						}
						if (PlayerWeapon is "WizardPike")
						{
							if (berserked) weaponsinkfactor -= 0.08125;
												else weaponsinkfactor -= 0.0625;
						}
						if (PlayerWeapon is "FosnianCandle") 
						{
							if (berserked) weaponsinkfactor += 0.008125;
												else weaponsinkfactor += 0.03125;
						}
						if (PlayerWeapon is "SuperVac")
						{
							SuperVacAmmoFactor = MiscItem.SuperVacAmmoFactor;
							if (berserked) weaponsinkfactor += (0.015625 + SuperVacAmmoFactor);
												else weaponsinkfactor += (0.0625 + SuperVacAmmoFactor);
						}
						if (PlayerWeapon is "Grimophone") 
						{
							if (berserked) weaponsinkfactor += 0.03125;
												else weaponsinkfactor += 0.125;
						}
						if (PlayerWeapon is "CandleWhip")
						{
							if (berserked) weaponsinkfactor -= 0.08125;
												else weaponsinkfactor -= 0.0625;
						}
						If (PlayerWeapon is "EvilWarriorShield")
						{
							int HellWarriorShieldLevel = CountInv("HellWarriorShieldLevel");
							if (berserked)
							{
								if (CountInv("HWShieldBlockHold")) weaponsinkfactor += (0.10 * (1.0 + (HellWarriorShieldLevel * 0.00625)));
																							else weaponsinkfactor += (0.05 * (1.0 + (HellWarriorShieldLevel * 0.003125)));
							}
							else
							{
								if (CountInv("HWShieldBlockHold")) weaponsinkfactor = (0.20 * (1.0 + (HellWarriorShieldLevel * 0.0125)));
																							else weaponsinkfactor = (0.10 * (1.0 + (HellWarriorShieldLevel * 0.00625)));
							}
						}
						if (PlayerWeapon is "HandToHand") weaponsinkfactor *= 1.0;
						else
						{
							if (A_CheckDDGame()) weaponsinkfactor *= 3.75;
							else weaponsinkfactor *= 1.875;
						}
						weaponsinkfactor *= exex_weaponencumbrance;
						weaponsinkfactor += 1.00;
						if (dydudebug_playermove) Console.Printf("\c[sapphire]weaponsinkfactor: %.8f, sinkspeed: %.8f [tic: %d]", weaponsinkfactor, sinkspeed, gametic);
						sinkspeed *= weaponsinkfactor;
						
						if (waterlevel == 2) sinkspeed *= 0.25;
						if (dydudebug_playermove) Console.Printf("\c[sapphire]Vel.Z: %.8f, startvelz: %.8f, sinkspeed: %.8f, ArmorEnc: %.8f [tic: %d]", Vel.Z, startvelz, sinkspeed, ArmorEnc, gametic);
					}
				
					if (Vel.Z < sinkspeed)
					{
						Vel.Z = (startvelz < sinkspeed) ? startvelz : sinkspeed;
					}
					else
					{
						double temp = ((Vel.Z - startvelz) * (waterlevel == 1 ? 0.25 : 0.125));
						Vel.Z = startvelz + temp;
					}
				}
			}
		}
		if (dydudebug_playermove) Console.Printf("\c[orange](FallAndSink() End)\c- Vel.Z: %.4f [tic: %d]", Vel.Z, gametic);
	}
	
	Override void Tick()
	{
		// VOODOO Doll Protection
		if ((!player || !player.mo || player.mo != self)) 
		{
			if (dydudebug_showvoodoodoll) Console.Printf("VoodooDoll [Tick] - \c[gold]H: %d, R: %d, M: %d, \c[sapphire]Sx: %4f, Sy: %4f, \c[fire]PosX: %d, PosY: %d, PosZ: %d", height, radius, mass, scale.x, scale.y, pos.x, pos.y, pos.z);
			isvoodoodoll = true;
			Super.Tick();
			return;
		}
		else
		{
			ActualLevel = A_CheckActualLevel(1);
			buttons = GetPlayerInput(INPUT_BUTTONS);
			if (dydudebug_showvoodoodoll) Console.Printf("Player [Tick] - \c[gold]H: %d, R: %d, M: %d, \c[sapphire]Sx: %4f, Sy: %4f, \c[fire]PosX: %d, PosY: %d, PosZ: %d", height, radius, mass, scale.x, scale.y, pos.x, pos.y, pos.z);
			let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
			if (MiscItem && exex_expenabled) 
			{
				TruePlayerLevel = MiscItem.TruePlayerLevel;
				TruePlayerATK = MiscItem.TruePlayerATK;
				TruePlayerDEF = MiscItem.TruePlayerDEF;
				TruePlayerSPD = MiscItem.TruePlayerSPD;
			}
			else
			{
				TruePlayerLevel = 0;
				TruePlayerATK = 0;
				TruePlayerDEF = 0;
				TruePlayerSPD = 0;
			}
			let globalvars = DDGlobalVariables.Get();
			if (dydudebug_mapinfo)
			{
				Console.Printf("Player Age [tics]: %d, levelnum: \cx%d\c-, cluster: \cx%d\c-, clusterflags: \cx%d\c-, NextMap: \cy%s\c-, NextSecretMap: \cy%s\c-,\ntime: \cx%d\c-, maptime: \cx%d\c-, totaltime: \cx%d\c-, starttime: \cx%d\c-, partime: \cx%d\c-, sucktime: \cx%d\c-,\nlevelname: \cy%s\c-, mapname: \cy%s\c-, \ngravity: \cx%.8f\c-, aircontrol: \cx%.8f\c-, airfriction: \cx%.8f\c-, \cxTranslation #:\c- %d, \cyMapCheckSum:\cx %s", 
												GetAge(),
												level.levelnum, level.cluster, level.clusterflags, level.NextMap, level.NextSecretMap,
												level.time, level.maptime, level.totaltime, level.starttime, level.partime, level.sucktime,
												level.levelname, level.mapname,
												level.gravity, level.aircontrol, level.airfriction,
												translation, level.GetChecksum());
			}
			
			// Check IP Buttons [general check for quick editing later across all definitions]
			
			if (ipmodecooldowntimer) ipmodecooldowntimer--;
			int IPbuttonspressed = 0;
			if (buttons & BT_USE) IPbuttonspressed++;
			if (buttons & BT_SPEED) IPbuttonspressed++;
			if (CheckIPEnabled())
			{
				if (exex_ikaripointtechpresstype == 0)
				{
					if (IPbuttonspressed >= 2) 
					{
						A_SetInventory("IPUseMode",1);
					}
					else
					{
						A_SetInventory("IPUseMode",0);
					}
				}
				else
				if (exex_ikaripointtechpresstype >= 1 && exex_ikaripointtechpresstype <= 2)
				{
					if (IPbuttonspressed >= 2) 
					{
						if (ipmodecooldowntimer <= 0)
						{
							ipmodecooldowntimer = random(9,12);
							if (CountInv("IPUseMode")) A_SetInventory("IPUseMode",0);
																		else A_SetInventory("IPUseMode",1);
						}
					}
				}
			}
			else
			{
				A_SetInventory("IPUseMode",0);
			}
			
			// The "Charge" sound[s] that plays in a loop while IP mode is active and the one that plays when it disperses [thanks to LilWhiteMouse for the sounds from Wolfen, wherever she herself had found them] :V
			
			double ipmodevol = 1.0;
			double basevollvl = 0.25;
			double ipmodepitch = 1.0;
			if (!CountInv("INTERMAPChecker"))
			{
				if (health > 0)
				{
					if (MiscItem && globalvars && MiscItem.MaxItemPoints)
					{
						ipmodevol = basevollvl + (double(MiscItem.ItemPoints / MiscItem.MaxItemPoints) * (1.0 - basevollvl));
						if (MiscItem.IPNoGainTimer) ipmodevol *= 0.001;
					}
					if (dydudebug_ipdisplays) Console.Printf("ipmodevol: %.4f, ipmodepitch: %.4f", ipmodevol, ipmodepitch);
					if (CountInv("IPUseMode"))
					{
						if (ipchargesoundtimer == 0)
						{
							if (MiscItem && globalvars)
							{
								ipmodevol = basevollvl + (double(MiscItem.ItemPoints / MiscItem.MaxItemPoints) * (1.0 - basevollvl));
								if (MiscItem.IPNoGainTimer) ipmodevol *= 0.001;
							}
							A_StopSound(255);
							A_StartSound("ipmode/start",255,CHANF_NOSTOP,ipmodevol,ATTN_NORM,ipmodepitch);
						}
						ipchargesoundtimer++;
						if (ipchargesoundtimer >= 56)
						{
							int ipchargesoundtimer2 = ipchargesoundtimer % 56;
							if (ipchargesoundtimer2 == 0) 
							{
								A_StopSound(255);
								A_StartSound("ipmode/loop",255,CHANF_NOSTOP|CHANF_LOOPING,ipmodevol,ATTN_NORM,ipmodepitch);
							}
							if (dydudebug_ipdisplays) Console.Printf("ipchargesoundtimer2: %d / 55", ipchargesoundtimer2);
						}
					}
					else
					{
						if (ipchargesoundtimer != 0)
						{
							ipchargesoundtimer = 0;
							A_StopSound(255);
							A_StartSound("ipmode/disperse",255,CHANF_DEFAULT,ipmodevol,ATTN_NORM,ipmodepitch);
						}
					}
				}
				else
				{
					if (ipchargesoundtimer != 0)
					{
						ipchargesoundtimer = 0;
						A_StopSound(255);
						A_StartSound("ipmode/disperse",255,CHANF_DEFAULT,ipmodevol,ATTN_NORM,ipmodepitch);
					}
					MiscItem.ItemPoints = 0;
					globalvars.ItemPoints = 0;
				}
				if (dydudebug_ipdisplays) Console.Printf("ipchargesoundtimer: %d", ipchargesoundtimer);
			}
			
			// ??????
			double IPLevelGateInc = 1.0;
			if (!CountInv("INTERMAPChecker"))
			{
				if (CheckIPEnabled() && CountInv("IPUseMode") && !ddafd_disableflowercrownip)
				{
					//Console.Printf("TrueIPLevelGate: %d, IP: %d (%d), Level: %d, TrueIPCooldownTimer: %d", MiscItem.TrueIPLevelGate, MiscItem.ItemPoints, globalvars.ItemPoints, ActualLevel, MiscItem.TrueIPCooldownTimer);
					if (buttons & BT_ZOOM && CountInv("FistPlayerBlockItem"))
					{
						bool wasnodmgthrust;
						bool wasforceradius;
						if (bNODAMAGETHRUST) wasnodmgthrust = true;
						if (bFORCERADIUSDMG) wasforceradius = true;
						double cost = A_GetIPCost(-1);
						if (MiscItem.TrueIPLevelGate <= 0 && MiscItem.ItemPoints >= cost && globalvars.ItemPoints >= cost && ActualLevel > 0 && MiscItem.TrueIPCooldownTimer <= 0)
						{
							globalvars.TrueIPTimesUsed += 1;
							A_GiveInventory("AngerLevelEventN",randompick(1,1,2,2,2,3,3,3,4,4,5));
							if (skill == SKILL_VERY_EASY) IPLevelGateInc = int(globalvars.TrueIPTimesUsed * 0.625);
							if (skill == SKILL_EASY) IPLevelGateInc = int(globalvars.TrueIPTimesUsed * 0.75);
							if (skill == SKILL_NORMAL) IPLevelGateInc = int(globalvars.TrueIPTimesUsed * 0.875);
							if (skill == SKILL_HARD) IPLevelGateInc = int(globalvars.TrueIPTimesUsed * 1.0);
							if (skill == SKILL_VERY_HARD) IPLevelGateInc = int(globalvars.TrueIPTimesUsed * 1.125);
							if (IPLevelGateInc < 1) IPLevelGateInc = 1;
							MiscItem.TrueIPLevelGate += IPLevelGateInc;
							int truecost = MiscItem.ItemPoints;
							MiscItem.ItemPoints -= cost;
							globalvars.ItemPoints -= cost;
							A_IPUseHUD(truecost);
							
							if (MiscItem.IPDissipateTimer > 0) MiscItem.IPDissipateTimer = 0;
							MiscItem.IPNoGainTimer = 60 * TICRATE;
							MiscItem.TrueIPCooldownTimer = ((300 * TICRATE) * (1.0 - (ActualLevel * 0.008)));
							if (MiscItem.TrueIPCooldownTimer <= (60 * TICRATE)) MiscItem.TrueIPCooldownTimer = 60 * TICRATE;
							A_SetBlend("ff c0 00",1.00,(random(40,70)*2));
							double xp = pos.x;
							double yp = pos.y;
							double zp = pos.z;
							ThinkerIterator MonsterFinder = ThinkerIterator.Create("Actor");
							Actor mo;
							EECreature mo2;
							int numfound = 0;
							nm = "CCardGhostMarker";
							while (mo = Actor(MonsterFinder.Next()))
							{
								mo2 = EECreature(mo);
								if (mo.bISMONSTER && 
										mo.bSHOOTABLE && 
										(mo.bCOUNTKILL || mo.CountInv(nm)) && 
										mo.health > 0 &&
										!mo.bFRIENDLY && 
										!DDAFDNPC(mo) &&
										!EEProp(mo))
								{
									if (abs(xp - mo.pos.x) <= 32768 || 
											abs(yp - mo.pos.y) <= 32768 ||
											abs(zp - mo.pos.z) <= 32768)
									{
										numfound++;
										int dmginf = (mo.health * frandompick(0.2,0.25,0.25,0.25,0.25,0.334));
										if (mo.CountInv(nm)) dmginf = ((mo.SpawnHealth() + mo.Stamina) * 2.0);
										mo.DamageMobj(self, self, dmginf, "TrueIP", DMG_NO_ARMOR|DMG_FORCED|DMG_NO_FACTOR|DMG_NO_PROTECT|DMG_NO_ENHANCE|DMG_EXPLOSION|DMG_THRUSTLESS, angle);
									}
								}
							}
							if (dydudebug_ipdisplays) Console.Printf("%d", numfound);
							if (numfound)
							{
								string sndname = "dinah/superdie";
								if (random(1,2) <= 1) sndname =  "dinah/YoullPayForThat";
								A_StopSound(CHAN_VOICE);
								A_StopSound(303);
								A_StopSound(304);
								A_StopSound(401);
								A_StopSound(402);
								A_StopSound(403);
								A_StartSound(sndname,CHAN_VOICE,CHANF_OVERLAP,0.8,ATTN_NONE,1.0);
								A_StartSound(sndname,303,CHANF_OVERLAP,0.7,ATTN_NONE,0.97);
								A_StartSound(sndname,304,CHANF_OVERLAP,0.7,ATTN_NONE,1.03);
								A_StartSound("DinahIP/IPBoom1",401,CHANF_OVERLAP,1.0,ATTN_NONE,frandom(0.9,1.1));
								A_StartSound("DinahIP/IPBoom2",402,CHANF_OVERLAP,1.0,ATTN_NONE,frandom(0.9,1.1));
								A_StartSound("DinahIP/IPBoom3",403,CHANF_OVERLAP,1.0,ATTN_NONE,frandom(0.9,1.1));
							}
							
							A_StopSound(501);
							A_StopSound(502);
							A_StopSound(503);
							A_StopSound(504);
							A_StartSound("DinahIP/IPActivate1",501,CHANF_OVERLAP,1.0,ATTN_NONE,frandom(0.9,1.1));
							A_StartSound("DinahIP/IPActivate2",502,CHANF_OVERLAP,1.0,ATTN_NONE,frandom(0.9,1.1));
							A_StartSound("DinahIP/IPActivate3",503,CHANF_OVERLAP,1.0,ATTN_NONE,frandom(0.9,1.1));
							A_StartSound("DinahIP/IPActivate4",504,CHANF_OVERLAP,1.0,ATTN_NONE,frandom(0.9,1.1));
							if (!CountInv("DinahTrueIPState")) 
							{
								A_SetInventory("DinahTrueIPState",1);
								let TrueIPItem = DinahTrueIPState(FindInventory("DinahTrueIPState"));
								if (TrueIPItem) TrueIPItem.EffectTics = ((60 * TICRATE) * (1.0 + ((ActualLevel - 1) * 0.005)));
							}
							else
							{
								let TrueIPItem = DinahTrueIPState(FindInventory("DinahTrueIPState"));
								if (TrueIPItem) TrueIPItem.EffectTics += ((60 * TICRATE) * (1.0 + ((ActualLevel - 1) * 0.005)));
							}
						}
					}
				}
			}
			
			int IPLoopInt;
			if (!CountInv("INTERMAPChecker"))
			{
				if (CountInv("DinahTrueIPState"))
				{
					let TrueIPItem = DinahTrueIPState(FindInventory("DinahTrueIPState"));
					double raddmg = random(6,12) * 4;
					double radradius = (radius * 3.75);
					double radradius2 = (radius * 2.875);
					if (TrueIPItem)
					{
						raddmg = (random(6,12) * 4) * (frandom(0.475,0.525) + (TrueIPItem.EffectTics * 1.0 / (60 * TICRATE)));
						if (CountInv("PowerInvulnDD") || CountInv("PowerInvulnerable"))
						{
							raddmg *= randompick(12,16,20,24,32,36,40,48,60);
							radradius *= 2.0;
							radradius2 *= 2.0;
						}
					}
					bool wasnodmgthrust;
					bool wasforceradius;
					if (bNODAMAGETHRUST) wasnodmgthrust = true;
					if (bFORCERADIUSDMG) wasforceradius = true;
					if (!wasnodmgthrust) bNODAMAGETHRUST = true;
					if (!wasforceradius) bFORCERADIUSDMG = true;
					A_Explode(raddmg,radradius,0,0,radradius2,0,0,"","TrueIP");
					if (!wasforceradius) bFORCERADIUSDMG = false;
					if (!wasnodmgthrust) bNODAMAGETHRUST = false;
					double loopvol = frandom(0.45,0.55);
					if (TrueIPItem) loopvol = frandom(0.475,0.525) * (TrueIPItem.EffectTics * 1.0 / (60 * TICRATE));
					//Console.Printf("loopvol: %.2f", loopvol);
					IPLoopTimer++;
					IPLoopInt = IPLoopTimer % 91;
					if (IPLoopInt == 0)
					{
						A_StopSound(701);
						A_StartSound("DinahIP/IPLoop3",701,CHANF_NOSTOP|CHANF_LOOPING,loopvol,ATTN_NORM,frandom(0.9,1.1));
					}
				}
				else
				{
					IPLoopTimer = 0;
					A_StopSound(701);
				}
			}
			
			//
			double fademax = 1.00;
			if (health <= 0)
			{
				if (deadtimer <= 0) 
				{
					fadetime = int(TICRATE*frandom(2.1667,2.8334));
					A_SetBlend("00 00 00",0.00, fadetime, "00 00 00",fademax);
				}
				if (deadtimer > (fadetime-2)) A_SetInventory("BlackScreenHUD",1);
				deadtimer++;
				//Console.Printf("DeadTimer: %d, FadeTime: %d", deadtimer, fadetime);
			}
			else 
			{
				if (deadtimer > 0) 
				{
					fadetime *= 0.25;
					A_SetBlend("00 00 00",fademax, fadetime, "00 00 00",0.00);
					A_SetInventory("BlackScreenHUD",0);
					//Console.Printf("DeadTimer: %d, FadeTime: %d", deadtimer, fadetime);
				}
				deadtimer = 0;
			}
			
			// Heartbeat [low health]
			if (exex_playerbpm)
			{
				double bmpbasevol = 1.00;
				double MaxHealthTrue = CountInv("PlayerMaxHP");
				if (MiscItem && MiscItem.IsMorphed == 1) MaxHealthTrue *= 0.3;
				if (CountInv("IsUnconscious")) bmpbasevol = frandom(0.25,0.334);
				if (health > 0)
				{
					beattimer++;
					if (health <= (MaxHealthTrue * 0.01))
					{
						if (beattimer >= beatpulse)
						{
							A_StopSound(134);
							A_StartSound("heartb2",134,CHANF_DEFAULT,(frandom(1.0,1.2)*bmpbasevol),ATTN_NORM,frandom(0.9,1.1));
							beatpulse = hudbeatpulse = random(10,11);
							beattimer = 0;
						}
					}
					else
					if (health <= (MaxHealthTrue * 0.05))
					{
						if (beattimer >= beatpulse)
						{
							A_StopSound(134);
							A_StartSound("heartb2",134,CHANF_DEFAULT,(frandom(1.0,1.2)*bmpbasevol),ATTN_NORM,frandom(0.9,1.1));
							beatpulse = hudbeatpulse = random(15,17);
							beattimer = 0;
						}
					}
					else
					if (health <= (MaxHealthTrue * 0.10))
					{
						if (beattimer >= beatpulse)
						{
							A_StopSound(134);
							A_StartSound("heartb2",134,CHANF_DEFAULT,(frandom(0.9,1.1)*bmpbasevol),ATTN_NORM,frandom(0.9,1.1));
							beatpulse = hudbeatpulse = random(28,42);
							beattimer = 0;
						}
					}
					else
					if (health <= (MaxHealthTrue * 0.25))
					{
						if (beattimer >= beatpulse)
						{
							A_StopSound(134);
							A_StartSound("heartb2",134,CHANF_DEFAULT,(frandom(0.675,0.825)*bmpbasevol),ATTN_NORM,frandom(0.9,1.1));
							beatpulse = hudbeatpulse = random(49,55);
							beattimer = 0;
						}
					}
					else
					if (health <= (MaxHealthTrue * 0.5))
					{
						if (beattimer >= beatpulse)
						{
							A_StopSound(134);
							A_StartSound("heartb2",134,CHANF_DEFAULT,(frandom(0.45,0.55)*bmpbasevol),ATTN_NORM,frandom(0.9,1.1));
							beatpulse = random(66,74);
							hudbeatpulse = random(49,55);
							beattimer = 0;
						}
					}
					else
					{
						beatpulse = random(124,128);
						hudbeatpulse = random(49,55);
						beattimer = 0;
					}
				}
				else
				{
					beatpulse = 5000;
				}
			}
			
			// Armor
			armortier = 0;
			double SavePercent = 0.000000;
			int MaxAbsorb = 0;
			int MaxFullAbsorb = 0;
			
			name armorclasstype = "KGArmor";
			
			let armor = KGArmor(player.mo.FindInventory(armorclasstype));
			if (armor != null && armor.Amount > 0)
			{
				SavePercent = armor.SavePercent;
				MaxAbsorb = armor.MaxAbsorb;
				MaxFullAbsorb = armor.MaxFullAbsorb;
				if (savepercent >= 0.00000 && savepercent <= 0.49999) armortier = 0;
				if (savepercent >= 0.50000 && savepercent <= 0.74999) armortier = 1;
				if (savepercent >= 0.75000 && savepercent <= 0.87499) armortier = 2;
				if (savepercent >= 0.87500 && savepercent <= 0.93749) armortier = 3;
				if (savepercent >= 0.93750 && savepercent <= 0.99999) armortier = 4;
				if (savepercent >= 1.00000) armortier = 5;
				
				if (dydudebug_armordisplays) Console.Printf("\c[sapphire]Armor -\c- SavePercent: %.8f, Tier: %d, MaxAbsorb: %d, MaxFullAbsorb: %d", savepercent, armortier, MaxAbsorb, MaxFullAbsorb);
			}
			
			if (CountInv(armorclasstype) <= 0) A_SetInventory("NoKnightGownItem",1); else A_SetInventory("NoKnightGownItem",0);
			if (armortier == 1) A_SetInventory("KnightGownItem",1); else A_SetInventory("KnightGownItem",0);
			if (armortier == 2) A_SetInventory("KnightGownItem2",1); else A_SetInventory("KnightGownItem2",0);
			if (armortier == 3) A_SetInventory("KnightGownItem3",1); else A_SetInventory("KnightGownItem3",0);
			if (armortier == 4) A_SetInventory("KnightGownItem4",1); else A_SetInventory("KnightGownItem4",0);
			
			if (MiscItem) MiscItem.GetSpeedFactor();
			isvoodoodoll = false;
		}

		// Recall All
		if (recalledall)
		{
			if (dydudebug_recalldisplays) Console.Printf("Recall All Attempt");

			actor recalleetarg;
			recalleetarg = actor(AimTarget());

			int numberrecalled = 0;
			ActorIterator it = Level.CreateActorIterator(1000);
			Actor recallee;
			while (recallee = it.Next())
			{
				if (recallee.bISMONSTER && recallee.bFRIENDLY)
				{
					if (dydudebug_recalldisplays) Console.Printf("\cx(Recall All)\c- Name: %s (TID: %d)", recallee.GetClassName(), recallee.tid);
					Vector3 savedpos = (pos.x, pos.y, (pos.z + random(6.0,12.0)));
					recallee.SetOrigin(savedpos,false);
					recallee.angle += frandom(0.0,360.0);
					recallee.vel.x += frandom(-4.0,4.0);
					recallee.vel.y += frandom(-4.0,4.0);
					recallee.vel.z += frandom(4.0,8.0);
					numberrecalled++;
					if (recalleetarg && recalleetarg.bISMONSTER && !recalleetarg.bFRIENDLY) recallee.target = recalleetarg;
				}
			}
			
			if (numberrecalled > 0)
			{
				//A_StartSound("monstersummon", 161, CHANF_DEFAULT);
				A_SpawnItemEx("PlayerWhistle",0.0,0.0,32.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION);
				Vector3 savedpos2 = (pos.x, pos.y, pos.z+(height*0.25));
				Actor fog = Spawn("TeleportFogDD", savedpos2, ALLOW_REPLACE); 
				if (fog != null)
				{
					fog.scale.x *= frandom(0.375, 0.625);
					fog.scale.y *= frandom(0.375, 0.625);
					fog.A_SetRenderStyle(frandom(0.375, 0.625),STYLE_Add);
				}
				
				if (recalleetarg && recalleetarg.bISMONSTER && !recalleetarg.bFRIENDLY)
				{
					A_DynamicMusic();
					A_PrintBold(String.Format("\cfRecalled all allies to your location and gave them a new target!"), frandom(0.685,0.8));
				}
				else
				{
					A_PrintBold(String.Format("\cfRecalled all allies to your location!"), frandom(0.685,0.8));
				}
			}
			else
			{
				A_StartSound("inv_fail",84,CHANF_DEFAULT,1.0,ATTN_NORM);
				A_PrintBold(String.Format("\cgRecall Failed: No creatures available to recall!"), frandom(0.685,0.8));
			}

			recalledall = false;
		}
		
		//****************************************************
		//*Flicker the Player when they survive a mortal hit *
		//****************************************************
		if (self.health == 1 && (player.cheats & CF_BUDDHA || player.cheats & CF_BUDDHA2) && lasthealth > 1)
		{
			let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
			if (MiscItem)
			{
				MiscItem.MercyInvulnOn = true;
				MiscItem.MercyInvulnTimer = 1210; // 1.5 Seconds
				MiscItem.MercyInvulnTimer += int(ActualLevel * 3.65);
				A_GiveInventory("AngerLevelEventN",randompick(1,1,2,2,2,3,3,3,4,4,5));
				if (CountInv("PlayingBlooM")) A_GiveInventory("AngerLevelEvent",randompick(1,1,1,2,2,3));
				
				// IP Cost Reduction Bonuses do NOT occur for having Ultimate Buddha Mode [i.e. CF_BUDDHA2 flag] on by itself
				if (player.cheats & CF_BUDDHA)
				{
					if (ActualLevel >= (exex_mortalblowipcostlvlrequirement * 5))
					{
						if (MiscItem.IPNoGainTimer) MiscItem.IPNoGainTimer = 0;
						MiscItem.IPMortalBlowReduceTimer += 525;
					}
					else if (ActualLevel >= (exex_mortalblowipcostlvlrequirement * 4))
					{
						if (MiscItem.IPNoGainTimer) MiscItem.IPNoGainTimer *= 0.2;
						MiscItem.IPMortalBlowReduceTimer += random(437,438);
					}
					else if (ActualLevel >= (exex_mortalblowipcostlvlrequirement * 3))
					{
						if (MiscItem.IPNoGainTimer) MiscItem.IPNoGainTimer *= 0.4;
						MiscItem.IPMortalBlowReduceTimer += 350;
					}
					else if (ActualLevel >= (exex_mortalblowipcostlvlrequirement * 2))
					{
						if (MiscItem.IPNoGainTimer) MiscItem.IPNoGainTimer *= 0.6;
						MiscItem.IPMortalBlowReduceTimer += random(262,263);
					}
					else if (ActualLevel >= (exex_mortalblowipcostlvlrequirement))
					{
						if (MiscItem.IPNoGainTimer) MiscItem.IPNoGainTimer *= 0.8;
						MiscItem.IPMortalBlowReduceTimer += 175;
					}
					else
					{
						if (MiscItem.IPNoGainTimer) MiscItem.IPNoGainTimer *= 0.98;
						MiscItem.IPMortalBlowReduceTimer += random(37,38);
					}
				}
				
				player.health = player.mo.health = 1;
			}
		}

		int basespeedvelsx;
		int basespeedvelsy;
		int basespeedvelsz;
		double basespeedvelsxd = 16.66666667;
		double basespeedvelsyd = 16.66666667;
		double basespeedvelszd = 16.66666667;

		basespeedvelsxd *= ForwardMove2;
		basespeedvelsyd *= SideMove2;
		basespeedvelszd *= 0;
		if (waterlevel >= 1) basespeedvelszd *= ForwardMove2;
		basespeedvelsx = (basespeedvelsxd * 65536);
		basespeedvelsy = (basespeedvelsyd * 65536);
		if (waterlevel >= 1) basespeedvelsz = (basespeedvelszd * 65536);

		double newspeedvelsxd = basespeedvelsxd * truespeed;
		double newspeedvelsyd = basespeedvelsyd * truespeed;
		double newspeedvelszd = 0;
		if (waterlevel >= 1) newspeedvelszd = basespeedvelszd * truespeed;
		int newspeedvelsx = newspeedvelsxd * 65536;
		int newspeedvelsy = newspeedvelsyd * 65536;
		int newspeedvelsz = 0;
		if (waterlevel >= 1) newspeedvelszd * 65536;
		if (dydudebug_playermove) Console.Printf("\cz WaterLevel: %d\c-, \cz Angle: %.8f, Pitch: %.8f\c-, \czPosX: %d, PosY: %d, PosZ: %d\c-,\nVelX: %.8f/\cx%.8f\c- (%d/\cx%d\c-), VelY: %.8f/\cx%.8f\c- (%d/\cx%d\c-), VelZ: %.8f/\cx%.8f\c- (%d/\cx%d\c-)\c-", waterlevel, (angle % 360), pitch, pos.x, pos.y, pos.z, vel.x, newspeedvelsxd, (vel.x * 65536), newspeedvelsx, vel.y, newspeedvelsyd, (vel.y * 65536), newspeedvelsy, vel.z, newspeedvelszd, (vel.z * 65536), newspeedvelsz);

		lasthealth = health;
		Super.Tick();
	}

	override void CheckCrouch(bool totallyfrozen)
	{
		let player = self.player;
		UserCmd cmd = player.cmd;

		if (cmd.buttons & BT_JUMP)
		{
			cmd.buttons &= ~BT_CROUCH;
		}
		if (CanCrouch() && player.health > 0 && level.IsCrouchingAllowed())
		{
			if (dydudebug_crouchdisplays) Console.Printf("Can Crouch");
			if (!totallyfrozen)
			{
				int crouchdir = player.crouching;

				if (crouchdir == 0)
				{
					crouchdir = (cmd.buttons & BT_CROUCH) ? -1 : 1;
				}
				else if (cmd.buttons & BT_CROUCH)
				{
					player.crouching = 0;
				}
				if (crouchdir == 1 && player.crouchfactor < 1 && pos.Z + height < ceilingz)
				{
					CrouchMove(1);
					if (dydudebug_crouchdisplays) Console.Printf("CrouchMove(1)");
				}
				else if (crouchdir == -1 && player.crouchfactor > 0.5)
				{
					CrouchMove(-1);
					if (dydudebug_crouchdisplays) Console.Printf("CrouchMove(-1)");
				}
				if (dydudebug_crouchdisplays) Console.Printf("player.crouching: %d, player.crouchfactor: %.8f, crouchdir: %d", player.crouching, player.crouchfactor, crouchdir);
			}
		}
		else
		{
			player.Uncrouch();
			if (dydudebug_crouchdisplays) Console.Printf("Uncrouched");
		}

		player.crouchoffset = -(ViewHeight) * (1 - player.crouchfactor);
		if (dydudebug_crouchdisplays) Console.Printf("player.crouching: %d, CanCrouch: %d, sv_allowcrouch: %d, IsCrouchingAllowed: %d", player.crouching, CanCrouch(), sv_allowcrouch, level.IsCrouchingAllowed());
	}

	override void CheckJump()
	{
		let player = self.player;
		// [RH] check for jump
		if (player.cmd.buttons & BT_JUMP)
		{
			if (player.crouchoffset != 0)
			{
				// Jumping while crouching will force an un-crouch but not jump
				player.crouching = 1;
			}
			else if (waterlevel >= 2)
			{
				Vel.Z = 4 * Speed;
			}
			else if (bNoGravity)
			{
				Vel.Z = 3.;
			}
			else if (level.IsJumpingAllowed() && player.onground && player.jumpTics == 0)
			{
				double jumpvelz = JumpZ * 35 / TICRATE;
				double jumpfac = 0;

				// [BC] If the player has the high jump power, double his jump velocity.
				// (actually, pick the best factors from all active items.)
				for (let p = Inv; p != null; p = p.Inv)
				{
					let pp = PowerHighJump(p);
					if (pp)
					{
						double f = pp.Strength;
						if (f > jumpfac) jumpfac = f;
					}
				}
				if (jumpfac > 0) jumpvelz *= jumpfac;

				Vel.Z += jumpvelz;
				bOnMobj = false;
				player.jumpTics = -1;
				if (!(player.cheats & CF_PREDICTING)) A_StartSound("*jump", CHAN_BODY);
			}
		}
	}
	
	override int DoSpecialDamage(Actor target, int damage, Name damagetype)
	{
		//Console.Printf("DoSpecialDamage: DDPlayPawn, target: %s, damage: %d, damagetype: %s", target.GetClassName(), damage, damagetype);
		damage = super.DoSpecialDamage(target, damage, damagetype);
		// New Code goes here
		return damage;
	}
	
	// Reset Breathing Scale
	void A_APPBreatheReset()
	{
		if (!isvoodoodoll) 
		{
			scaleymulti = 1.00;
			breathdirection = 0;
			breathframe = 0;
			A_SetScale(basexscale,baseyscale*scaleymulti);
		}
		if (dydudebug_playerbreathedisplays) Console.Printf("(A_APPBreatheReset)");
	}
	
	// Breathing Function
	void A_APPBreathe(double startpoint = 1.00625, double endpoint = 0.99375, double breathincrementbase = 0.0025, double basetics = 4)
	{
		if (!isvoodoodoll) 
		{
			double HealthBreathSpeed = 1.0;
			double HealthRatio; 
			int MaxHealthTrue = CountInv("PlayerMaxHP");
			if (dydudebug_playerbreathedisplays) Console.Printf("(breathe-check) MaxHealthTrue: %d", MaxHealthTrue);
			if (MaxHealthTrue > 0)
			{
				HealthRatio = (health * 1.00) / (MaxHealthTrue * 1.00);
				if (dydudebug_playerbreathedisplays) Console.Printf("(breathe-check) %.8f", HealthRatio);
				if (health > 0)
				{
					if (HealthRatio >= 1.75001) HealthBreathSpeed = 0.01;
					if (HealthRatio >= 1.62501 && HealthRatio <= 1.75000) HealthBreathSpeed = 0.175;
					if (HealthRatio >= 1.50001 && HealthRatio <= 1.62500) HealthBreathSpeed = 0.34;
					if (HealthRatio >= 1.37501 && HealthRatio <= 1.50000) HealthBreathSpeed = 0.505;
					if (HealthRatio >= 1.25001 && HealthRatio <= 1.37500) HealthBreathSpeed = 0.67;
					if (HealthRatio >= 1.12501 && HealthRatio <= 1.25000) HealthBreathSpeed = 0.835;
					if (HealthRatio >= 0.87501 && HealthRatio <= 1.12500) HealthBreathSpeed = 1.00;
					if (HealthRatio >= 0.75001 && HealthRatio <= 0.87500) HealthBreathSpeed = 1.165;
					if (HealthRatio >= 0.62501 && HealthRatio <= 0.75000) HealthBreathSpeed = 1.33;
					if (HealthRatio >= 0.50001 && HealthRatio <= 0.62500) HealthBreathSpeed = 1.495;
					if (HealthRatio >= 0.37501 && HealthRatio <= 0.50000) HealthBreathSpeed = 1.66;
					if (HealthRatio >= 0.25001 && HealthRatio <= 0.37500) HealthBreathSpeed = 1.825;
					if (HealthRatio >= 0.12501 && HealthRatio <= 0.25000) HealthBreathSpeed = 1.99;
					if (HealthRatio >= 0.00001 && HealthRatio <= 0.12500) HealthBreathSpeed = 2.155;
					if (Health == 1) HealthBreathSpeed = 2.485;
				}
				breathincrementbase *= HealthBreathSpeed;
				if (dydudebug_playerbreathedisplays) Console.Printf("(breathe-check) breathincrementbase: %d", breathincrementbase);
				
				double ticmulti = 1.00 * (tics / basetics);
				breathincrementbase *= ticmulti;
				if (dydudebug_playerbreathedisplays) Console.Printf("(breathe-check) breathincrementbase: %d", breathincrementbase);

				if (breathdirection == 0)
				{
					breathframe++;
					scaleymulti -= breathincrementbase;
					if (scaleymulti <= endpoint) { scaleymulti = endpoint; breathdirection = 1; breathframe = 0; }
				}
				else
				{
					breathframe++;
					scaleymulti += breathincrementbase;
					if (scaleymulti >= startpoint) { scaleymulti = startpoint; breathdirection = 0; breathframe = 0; }
				}
				if (dydudebug_playerbreathedisplays) Console.Printf("(breathe-check) breathdirection: %d", breathdirection);

				if (dydudebug_playerbreathedisplays)
				{
					Console.Printf("scaleymulti = %.8f, breathincrementbase = %.8f, breathdirection = %d, breathframe = %d, HealthBreathSpeed = %.8f, ticmulti = %.8f, actualtics = %d, basetics = %d [gametic: %d]", 
													scaleymulti, 
													breathincrementbase, 
													breathdirection, 
													breathframe, 
													HealthBreathSpeed, 
													ticmulti, 
													tics, 
													basetics,
													gametic);
				}
			}
			else
			{
				scaleymulti = 1.00;
				breathdirection = 0;
				breathframe = 0;
			}
			A_SetScale(basexscale,baseyscale*scaleymulti);
		}
		if (dydudebug_playerbreathedisplays) Console.Printf("(A_APPBreathe)");
	}
	
	void A_CheckNeverBleed(int type, int damage, int flags)
	{
		if (type == 0)
		{
			if (neverbleeds == 0)
			{
				if (bNOBLOOD) bNOBLOOD = false;
				if (bNOBLOODDECALS) bNOBLOODDECALS = false;
			}
		}
		else
		{
			if (flags & !DMG_EXPLOSION)
			{
				if (neverbleeds == 0)
				{
					bNOBLOOD = true;
					bNOBLOODDECALS = true;
				}
			}
		}
		if (dydudebug_playerdamagemobj) Console.Printf("(A_CheckNeverBleed [player], type: %d, damage: %d)", type, damage);
	}
	
	bool CheckFallDamageDMobj()
	{
		bool takefalldamage = true;
		if (bFLY || bNOGRAVITY || waterlevel >= 1) 
		{
			takefalldamage = false;
			if (dydudebug_playerdamagemobj) Console.Printf("bFLY: %d, bNOGRAVITY: %d, waterlevel: %d", bFLY, bNOGRAVITY, waterlevel);
		}
		else
		{
			bool onground2 = (pos.z <= floorz) || bOnMobj || bMBFBouncer || (player.cheats & CF_NOCLIP2);
			if (wasongroundprevtic == onground2)
			{
				takefalldamage = false;
				if (dydudebug_playerdamagemobj) Console.Printf("wasongroundprevtic: %d, onground2: %d", wasongroundprevtic, onground2);
			}
		}
		if (dydudebug_playerdamagemobj) Console.Printf("takefalldamage: %d", takefalldamage);
		
		return takefalldamage;
	}
	
	double A_DefenseIgnoreFactor(Actor inflictor, Actor source, int damage, Name mod, int flags, double angle, bool bellefishzap, bool isbarrierbeam)
	{
		let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
		let globalvars = DDGlobalVariables.Get();
		string infl, sour, vict;
		vict = GetClassName();
		if (inflictor == null) infl = "NONE"; else infl = inflictor.GetClassName();
		if (source == null) sour = "NONE"; else sour = source.GetClassName();

		// (Partial) Defense Ignoring Attacks
		PlayerDefenseIgnoreFactor = 0.00;
		if (damage > 0)
		{
			if (mod == 'Dashing') PlayerDefenseIgnoreFactor += (0.2 * (1.00 - PlayerDefenseIgnoreFactor));
			if (mod == 'DashingBG') PlayerDefenseIgnoreFactor += (0.375 * (1.00 - PlayerDefenseIgnoreFactor));
			if (mod == 'DashingSD') PlayerDefenseIgnoreFactor += (0.375 * (1.00 - PlayerDefenseIgnoreFactor));

			if (inflictor == null && source == null)
			{
			}
			else
			{
				if (!CountInv("DinahTrueIPState")) // The Flower Crown IP Mode Negates most Defense Ignoring attacks :V
				{
					double PikeAOEFactor = 0.334;
					if (mod == 'Zap') PlayerDefenseIgnoreFactor += (PikeAOEFactor * (1.00 - PlayerDefenseIgnoreFactor));
					if (mod == 'Zap' && flags & DMG_EXPLOSION) PlayerDefenseIgnoreFactor += (PikeAOEFactor * (1.00 - PlayerDefenseIgnoreFactor));
					if (flags & DMG_INFLICTOR_IS_PUFF && (PikePuff(inflictor) || PikePuff(source))) PlayerDefenseIgnoreFactor += (PikeAOEFactor * (1.00 - PlayerDefenseIgnoreFactor));
					
					double BeatsFactor = (frandompick(0.25,0.334,0.334,0.334,0.334,0.334,0.5) * 0.5);
					if (mod == 'Beats') PlayerDefenseIgnoreFactor += (BeatsFactor * (1.00 - PlayerDefenseIgnoreFactor));
					double BeatsAOEFactor = (frandompick(0.25,0.334,0.334,0.334,0.334,0.334,0.5) * 0.5);
					if (mod == 'Beats' && flags & DMG_EXPLOSION) PlayerDefenseIgnoreFactor += (BeatsAOEFactor * (1.00 - PlayerDefenseIgnoreFactor));
					
					double BarrelFactor = 0.50;
					if (skill <= 0) BarrelFactor = 0.0;
					if (skill == 1) BarrelFactor = 0.25;
					if (skill == 2) BarrelFactor = 0.5;
					if (skill == 3) BarrelFactor = 0.75;
					if (skill >= 4) BarrelFactor = 1.0;
					if ((ExplosiveBarrel(inflictor) || ExplosiveBarrel(source) || Pod(inflictor) || Pod(source)) && (flags & DMG_EXPLOSION || mod == 'Explosive')) PlayerDefenseIgnoreFactor += (BarrelFactor * (1.00 - PlayerDefenseIgnoreFactor));
					
					double SuckFactor = 0.334;
					if (mod == 'Suck') PlayerDefenseIgnoreFactor += (SuckFactor * (1.00 - PlayerDefenseIgnoreFactor));
					
					double PuddingFactor = 0.667;
					if (PuddingDog(inflictor) || PuddingPup(inflictor) || PupGrenade(inflictor) || PuddingDog(source) || PuddingPup(source) || PupGrenade(source)) PlayerDefenseIgnoreFactor += (PuddingFactor * (1.00 - PlayerDefenseIgnoreFactor));
					
					if (bellefishzap)
					{
						if (CountInv("PowerNoDrown"))
						{
							if (waterlevel >= 3) PlayerDefenseIgnoreFactor += (0.0500 * (1.00 - PlayerDefenseIgnoreFactor));
															else PlayerDefenseIgnoreFactor += (0.4750 * (1.00 - PlayerDefenseIgnoreFactor));
						}
						else PlayerDefenseIgnoreFactor += (0.5 * (1.00 - PlayerDefenseIgnoreFactor));
					}

					double RailFactor = frandom(0.3,0.334);
					if (mod == 'Railgun') PlayerDefenseIgnoreFactor += (RailFactor * (1.00 - PlayerDefenseIgnoreFactor));
					
					double HWShieldFactor = 0.125;
					if (EvilWarriorShieldBall(inflictor) || EvilWarriorShieldBall(source) ||
							HellWarriorBall2(inflictor) || HellWarriorBall2(source)) PlayerDefenseIgnoreFactor += (HWShieldFactor * (1.00 - PlayerDefenseIgnoreFactor));
					
					if ((source && PushyArchAngel(source)) || (inflictor && PushyArchAngel(inflictor)))
					{
						PlayerDefenseIgnoreFactor += (frandom(0.000,0.250) * (1.00 - PlayerDefenseIgnoreFactor));
					}
				}
				
				if (isbarrierbeam) PlayerDefenseIgnoreFactor += (frandom(0.9,1.0) * (1.00 - PlayerDefenseIgnoreFactor));
			}
			
			double BuffFactor = 0.00;
			if (CountInv("PowerGuard")) BuffFactor += 0.75; // Guard Sphere
			if (BuffFactor > 0.00) PlayerDefenseIgnoreFactor = (PlayerDefenseIgnoreFactor * (1.00 - BuffFactor));
			
			double FoodFactor = 0.00;
			if (CountInv("PowerRoastBuff")) FoodFactor += 0.0625; // Pig Roast
			if (CountInv("PowerMealBuff")) FoodFactor += 0.25; // Gourmet Meal
			if (CountInv("PowerMeal2Buff")) FoodFactor += 0.0625; // Turkey Dinner
			if (FoodFactor > 0.00) PlayerDefenseIgnoreFactor = (PlayerDefenseIgnoreFactor * (1.00 - FoodFactor));
		}
		
		if (PlayerDefenseIgnoreFactor <= 0.0) PlayerDefenseIgnoreFactor = 0.0;
		if (PlayerDefenseIgnoreFactor > 1.00) PlayerDefenseIgnoreFactor = 1.00;
		if (dydudebug_playerdamagemobj) Console.Printf("\c[orange]PlayerDefenseIgnoreFactor: %.8f", PlayerDefenseIgnoreFactor);

		return PlayerDefenseIgnoreFactor;
	}
	
	double A_ArmorIgnoreFactor(Actor inflictor, Actor source, int damage, Name mod, int flags, double angle, bool bellefishzap, bool isbarrierbeam)
	{
		let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
		let globalvars = DDGlobalVariables.Get();
		string infl, sour, vict;
		vict = GetClassName();
		if (inflictor == null) infl = "NONE"; else infl = inflictor.GetClassName();
		if (source == null) sour = "NONE"; else sour = source.GetClassName();

		// Intended to ignore aspects of armor items
		PlayerArmorIgnoreFactor = 0.00;
		if (isbarrierbeam) PlayerArmorIgnoreFactor += (0.50 * (1.00 - PlayerArmorIgnoreFactor));
		
		if (source && exex_enemyarmorignorefactor >= 0.001)
		{
			int ignoretier = 0;
			if (dydudebug_playerdamagemobj) Console.Printf("\c[orange]Enemy Bypasses armor [attempt]");
			EECreature EESource;
			EESource = EECreature(source);
			if (EESource)
			{
				if (dydudebug_playerdamagemobj) Console.Printf("\c[sapphire]EESource found [armor bypass]");
				int rand1;
				double randarmign;

				// Tier 2 Enemies [i.e. very-high armor bypass, usually named bosses [Serpent Riders, Pennywise in HTC2, and the Dinah Doppelgangers] V:]
				if (sour == "PennywiseBoss" ||
						sour == "ThamuzNew" ||
						sour == "TchernobogNew" ||
						EvilDinah(EESource) || 
						Sorcerer2New(EESource) || 
						KoraxNew(EESource))
				{
					ignoretier = 2;
					rand1 += 5 + ((source.CountInv("MonsterLevel")) * 0.5);
					randarmign += (frandompick(0.015,0.0175,0.02,0.0225,0.025) * exex_enemyarmorignorefactor);
				}
				else // Tier 1 Enemies [i.e. medium-high armor bypass, usually standard boss/mini-bosses, and BlackBears V:]
				if (sour == "BlackBearNew" ||
						RailArachnotron(EESource) ||
						ArchvileNew(EESource) ||
						Diabloist(EESource) ||
						FlyingBalrogDVDS(EESource) ||
						BruiserDemon(EESource) ||
						FighterBossNew(EESource) ||
						ClericBossNew(EESource) ||
						MageBossNew(EESource) ||
						Minotaur(EESource) ||
						MinotaurFriend(EESource) ||
						CyberdemonNew(EESource) ||
						Annihilator(EESource) ||
						SpiderMastermindNew(EESource) ||
						Demolisher(EESource) ||
						HandMotherVac(EESource) ||
						HandMotherPhaseA(EESource) ||
						HandMotherPhaseB(EESource) ||
						HandMotherPhaseC(EESource) ||
						GlobeMother(EESource) ||
						MossMother(EESource) ||
						SphinxMother(EESource) ||
						RoseMother(EESource) ||
						GameMother(EESource) ||
						Teacher_Krag(EESource) ||
						Teacher_Lauritz(EESource) ||
						Teacher_Quis(EESource) ||
						Teacher_Jorg(EESource) ||
						JorgSphereCannon(EESource) ||
						Teacher_Vokter(EESource) ||
						Sorcerer1New(EESource))
				{
					ignoretier = 1;
					rand1 += randompick(2,3) + ((source.CountInv("MonsterLevel")) * 0.25);
					randarmign += (frandompick(0.0075,0.00875,0.01,0.01125,0.0125) * exex_enemyarmorignorefactor);
				}
				else // Tier -1 Enemies (enemies with WEAKER armor bypass on average versus even Tier 0s :V)
				if (sour == "EvilDeadHandNew" ||
						sour == "JumpingSkullNew" ||
						sour == "TinyBingoNew" ||
						sour == "BabyClownNew" ||
						sour == "BabyClown2New" ||
						sour == "PossessedBalloonNew")
				{
					ignoretier = -1;
					rand1 += randompick(0,0,0,0,0,1,1,1) + ((source.CountInv("MonsterLevel")) * 0.0625);
					randarmign += ((frandompick(0.00375,0.004375,0.005,0.0056125,0.00625) * 0.5) * exex_enemyarmorignorefactor);
				}
				else // Tier 0 Enemies [i.e. average armor bypass]
				{
					ignoretier = 0;
					rand1 += randompick(1,1,1,2) + ((source.CountInv("MonsterLevel")) * 0.125);
					randarmign += (frandompick(0.00375,0.004375,0.005,0.0056125,0.00625) * exex_enemyarmorignorefactor);
				}

				if (source.bBOSS)
				{
					rand1 *= int(frandom(1.75,2.25));
					randarmign *= frandom(1.75,2.25);
				}
				
				double finalsourceignore = (random(0,rand1) * randarmign);
				if (finalsourceignore > 0.75) finalsourceignore = 0.75;
				PlayerArmorIgnoreFactor += (finalsourceignore * (1.00 - PlayerArmorIgnoreFactor));
				if (dydudebug_playerdamagemobj) Console.Printf("Tier %d Armor Ignoring Type: [Level: %d], rand1: %d, randarmign: %.8f, PlayerArmorIgnoreFactor: %.8f", ignoretier, source.CountInv("MonsterLevel"), rand1, randarmign, PlayerArmorIgnoreFactor);
			}
		}
		
		if (inflictor)
		{
			if (infl == 'RecordShot' || infl == 'BadRecordShot') PlayerArmorIgnoreFactor += (frandom(0.225,0.275) * (1.00 - PlayerArmorIgnoreFactor));
			if (infl == 'HellWarriorBall2') PlayerArmorIgnoreFactor += (frandom(0.1125,0.1375) * (1.00 - PlayerArmorIgnoreFactor));
		}
		
		if (mod == 'Deadlight') 
		{
			if ((inflictor && infl == "PennywiseBoss") || 
					(source && sour == "PennywiseBoss")) PlayerArmorIgnoreFactor += (frandom(0.45,0.55) * (1.00 - PlayerArmorIgnoreFactor));

			if ((inflictor && infl == "BeefyNew") || 
					(source && sour == "BeefyNew")) PlayerArmorIgnoreFactor += (frandom(0.225,0.275) * (1.00 - PlayerArmorIgnoreFactor));
		}

		if (PlayerArmorIgnoreFactor <= 0.0) PlayerArmorIgnoreFactor = 0.0;
		if (PlayerArmorIgnoreFactor > 1.0) PlayerArmorIgnoreFactor = 1.0;
		if (dydudebug_playerdamagemobj) Console.Printf("\c[darkgreen]PlayerArmorIgnoreFactor: %.8f", PlayerArmorIgnoreFactor);
		
		if (CountInv("PowerGuard")) PlayerArmorIgnoreFactor *= 0.25;
		
		if (CountInv("KnightGownIP1Buff")) PlayerArmorIgnoreFactor *= 0.5;
		if (CountInv("KnightGownIP2Buff")) PlayerArmorIgnoreFactor *= 0.25;
		if (CountInv("KnightGownIP3Buff")) PlayerArmorIgnoreFactor *= 0.125;
		if (CountInv("KnightGownIP4Buff")) PlayerArmorIgnoreFactor *= 0.0625;
		
		if (MiscItem)
		{
			if (MiscItem.WineDefTier == 1) PlayerArmorIgnoreFactor *= 0.995;
			else if (MiscItem.WineDefTier == 2) PlayerArmorIgnoreFactor *= 0.985;
			else if (MiscItem.WineDefTier == 3) PlayerArmorIgnoreFactor *= 0.970;
			else if (MiscItem.WineDefTier == 4) PlayerArmorIgnoreFactor *= 0.950;
			else if (MiscItem.WineDefTier == 5) PlayerArmorIgnoreFactor *= 0.925;
			else if (MiscItem.WineDefTier == -1) PlayerArmorIgnoreFactor *= 0.975;
			else if (MiscItem.WineDefTier == -2) PlayerArmorIgnoreFactor *= 0.925;
			else if (MiscItem.WineDefTier == -3) PlayerArmorIgnoreFactor *= 0.850;
			else if (MiscItem.WineDefTier == -4) PlayerArmorIgnoreFactor *= 0.750;
			else if (MiscItem.WineDefTier == -5) PlayerArmorIgnoreFactor *= 0.625;
		}
		
		if (MiscItem)
		{
			if (MiscItem.armoritemdifficulty == 1) PlayerArmorIgnoreFactor *= 0.8;
			if (MiscItem.armoritemdifficulty == 2) PlayerArmorIgnoreFactor *= 0.75;
			if (MiscItem.armoritemdifficulty >= 3) PlayerArmorIgnoreFactor *= 0.5;
		}

		return PlayerArmorIgnoreFactor;
	}
	
	override int DamageMobj(Actor inflictor, Actor source, int damage, Name mod, int flags, double angle)
	{
		let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
		if (inflictor && MorphProjectile(inflictor) || source && MorphProjectile(source)) A_GiveInventory("HitByMorphProj",1);
		
		if (CountInv("PlayingBlooM"))
		{
			if (mod == 'axe') mod = "Chop";
			if (mod == 'SpecialFire') mod = 'Fire';
			if (mod == 'Flare') 
			{
				mod = "Fire";
				damage *= 3.0;
			}
			if (mod == 'Blast') mod = "Explosive";
		}
		
		let NoU = D_NoUCard(FindInventory("D_NoUCard"));
		if (NoU)
		{
			A_StopSound(104);
			A_StartSound("ReflectDmg1",104,CHANF_DEFAULT,1.5,ATTN_NORM,frandom(0.875,1.125));
			flags |= DMG_NO_ARMOR;
			flags |= DMG_NO_PROTECT;
			flags |= DMG_THRUSTLESS;
			//Console.Printf("NoU Found!");
			if (source && source != self)
			{
				//Console.Printf("NoU Found! [source]");
				source.A_StopSound(104);
				source.A_StartSound("ReflectDmg2",104,CHANF_DEFAULT,1.5,ATTN_NORM,frandom(0.875,1.125));
				source.DamageMobj(self, self, damage, mod, flags, angle);
			}
			else
			{
				if (inflictor && inflictor != self)
				{
					//Console.Printf("NoU Found! [inflictor]");
					inflictor.A_StopSound(104);
					inflictor.A_StartSound("ReflectDmg2",104,CHANF_DEFAULT,1.5,ATTN_NORM,frandom(0.875,1.125));
					inflictor.DamageMobj(self, self, damage, mod, flags, angle);
				}
			}
			damage = 0;
			return 0;
		}

		bool isbarrierbeam = false;
		if (BarrierBeam(inflictor) || BarrierBeam(source)) isbarrierbeam = true;
		if (mod == 'Falling')
		{
			if (CheckFallDamageDMobj() == false) 
			{
				if (dydudebug_playerdamagemobj) Console.Printf("Fall Damage Nullified");
				return -1;
			}
			else
			{
				double landdmgfactor = (1.0 - player.crouchfactor);
				landdmgfactor *= frandompick(0.1,0.2,0.2,0.25,0.25,0.25,0.3334,0.3334,0.3334,0.3334,0.3334,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.6667,0.6667,0.6667,0.6667,0.6667,0.75,0.75,0.75,0.8,0.8,0.9);
				landdmgfactor = (1.0 - landdmgfactor);
				int olddmg = damage;
				damage = floor(damage * landdmgfactor);
				if (A_CheckDDGame())
				{
					double PerkFactor2 = 0.00;
					if (MiscItem.DD_RoseMother) PerkFactor2 -= 0.01875;
					if (MiscItem.DD_GameMother) PerkFactor2 -= 0.01875;
					if (MiscItem.DD_MossMother) PerkFactor2 -= 0.01875;
					if (MiscItem.DD_GlobeMother) PerkFactor2 -= 0.01875;
					if (MiscItem.DD_SphinxMother) PerkFactor2 -= 0.01875;
					if (MiscItem.DD_HandMother1) PerkFactor2 -= 0.01875;
					if (MiscItem.DD_HandMother2) PerkFactor2 -= 0.01875;
					if (MiscItem.DD_TrueHandMother) PerkFactor2 -= 0.01875;
					if (MiscItem.AFD_Krag) PerkFactor2 -= 0.025;
					if (MiscItem.AFD_Quisling) PerkFactor2 -= 0.025;
					if (MiscItem.AFD_Lauritz) PerkFactor2 -= 0.025;
					if (MiscItem.AFD_Jorgensen1) PerkFactor2 -= 0.025;
					if (MiscItem.AFD_Jorgensen2) PerkFactor2 -= 0.025;
					if (MiscItem.AFD_JorgCannon) PerkFactor2 -= 0.025;
					if (MiscItem.CoS_Fafnir) PerkFactor2 -= 0.025;
					if (MiscItem.CoS_FractalHens) PerkFactor2 -= 0.025;
					if (MiscItem.CoS_HandMothers) PerkFactor2 -= 0.025;
					if (MiscItem.CoS_ForsakenJorg) PerkFactor2 -= 0.025;
					if (MiscItem.CoS_EvilDinah) PerkFactor2 -= 0.025;
					if (MiscItem.CoS_Tempest) PerkFactor2 -= 0.025;
					PerkFactor2 *= 2.5;
					if (skill <= 0) PerkFactor2 *= 1.5;
					if (skill == 1) PerkFactor2 *= 1.25;
					if (skill == 2) PerkFactor2 *= 1.0;
					if (skill == 3) PerkFactor2 *= 0.75;
					if (skill >= 4) PerkFactor2 *= 0.5;
					if (PerkFactor2 <= 0.125) PerkFactor2 = 0.125;
					PerkFactor2 *= exex_nrpggeneraleffect;
					if (PerkFactor2 < 0.00) PerkFactor2 = 0.00;
					PerkFactor2 += 1.0;
					damage = floor(damage * PerkFactor2);
				}
				flags |= DMG_NO_FACTOR;
				flags |= DMG_NO_PROTECT;
				flags |= DMG_NO_ENHANCE;
				flags |= DMG_THRUSTLESS;
				if (dydudebug_playerdamagemobj) Console.Printf("Fall Damage [Crouching]: %d [prev: %d] (Factor: %.8f)", damage, olddmg, landdmgfactor);
			}
		}
		
		if (CountInv("EvadeAnAttack"))
		{
			if (EggShot(inflictor) ||
			    EggGrenade(inflictor) ||
			    EggMini(inflictor))
			{
				if (dydudebug_playerdamagemobj) Console.Printf("Evasion (Eggs) - no damage");
				return 0;
			}
			else 
			if (isbarrierbeam) A_SetInventory("EvadeAnAttack",0);
			else
			{
				if (!(((source == null && inflictor == null) &&
						(mod == 'Slime' || mod == 'Lava' || mod == 'Magma' || mod == 'IceWater' || mod == 'Crush' || mod == 'Drowning' || mod == 'SigilDrain' || mod == 'Falling')) || mod == 'SigilDrain'))
				{
					A_StartSound("player/dodge",305,CHANF_OVERLAP|CHANF_LOCAL,frandom(0.75,1.25),ATTN_NORM,frandom(0.75,1.25));
					if (exex_playerdmglog)
					{
						if (mod == 'NONE') mod = 'Typeless';
						string combatlogmsg = "\c[sapphire]*\c- Dodged";
						if (source) // Has a source
						{
							combatlogmsg.AppendFormat(" \c[purple]%s\c-", source.GetTag());
							if (inflictor && inflictor != source) combatlogmsg.AppendFormat("\c[purple]'s\c- \c[brick]%s\c-", inflictor.GetTag());
						}
						else
						if (inflictor) // No source, but has an inflictor
						{
							combatlogmsg.AppendFormat(" \c[brick]%s!", inflictor.GetTag());
						}
						else // If no source OR inflictor
						{
							if (mod == 'Slime') combatlogmsg.AppendFormat(" a damaging surface");
							else if (mod == 'Lava' || mod == 'Magma' || mod == 'IceWater') combatlogmsg.AppendFormat(" a damaging surface");
							else if (mod == 'Crush') combatlogmsg.AppendFormat(" a crushing ceiling");
							combatlogmsg.AppendFormat("!");
						}
						combatlogmsg.AppendFormat(" [%s]", mod);
						if (flags & DMG_EXPLOSION) combatlogmsg.AppendFormat(" \c[brick][AOE]\c-");
						if (dydudebug_showgametic) combatlogmsg.AppendFormat(" \c[green][tic: %d]\c-", gametic);
						Console.Printf(combatlogmsg);
					}
					if (dydudebug_playerdamagemobj) Console.Printf("Evasion - no damage");
					return 0;
				}
				else
				{
					int prevdmg = damage;
					damage *= (frandompick(0.2,0.2,0.2,0.25,0.25,0.25,0.25,0.25,0.25,0.334) * randompick(1,1,1,2,2,2,2,2,2,3));
					if (damage > prevdmg) damage = prevdmg;
				}
			}
		}

		class<Actor> extracheck, extracheck2, extracheck3, extracheck4;
		string nm, nn, no, np;
		
		int firstdmg = damage;
		let globalvars = DDGlobalVariables.Get();
		
		Actor AttackingActor;
		Actor UniqueProjectile;
		FastProjectile UniqueProjectileFast;
		Actor ailmentproj;
		FastProjectile ailmentprojfast;
		Actor singleripproj;
		FastProjectile singlefastripproj;
		
		if (dydudebug_playerdamagemobj)
		{
			if (flags & DMG_NO_ARMOR) Console.Printf("    (\cyIgnoresArmor?: yes)");
			if (flags & DMG_INFLICTOR_IS_PUFF) Console.Printf("    (\cyInflictorIsPuff?: yes)");
			if (flags & DMG_THRUSTLESS) Console.Printf("    (\cyThrustless?: yes)");
			if (flags & DMG_FORCED) Console.Printf("    (\cyForcedDamage?: yes)");
			if (flags & DMG_NO_FACTOR) Console.Printf("    (\cyNoDmgFactor?: yes)");
			if (flags & DMG_PLAYERATTACK) Console.Printf("    (\cyPlayerAttack?: yes)");
			if (flags & DMG_FOILINVUL) Console.Printf("    (\cyFoilInvuln?: yes)");
			if (flags & DMG_FOILBUDDHA) Console.Printf("    (\cyFoilBuddha?: yes)");
			if (flags & DMG_NO_PROTECT) Console.Printf("    (\cyBypassPowerProtection?: yes)");
			if (flags & DMG_NO_ENHANCE) Console.Printf("    (\cyBypassPowerDamage?: yes)");
			if (flags & DMG_USEANGLE) Console.Printf("    (\cyUsesAngle?: yes)");
			if (flags & DMG_EXPLOSION) Console.Printf("    (\cyIsAoEBurst?: yes)");
			if (flags & DMG_NO_PAIN) Console.Printf("    (\cyPainless?: yes)");
		}
		if (dydudebug_playerdamagemobj) Console.Printf("DamageType: %s", mod);
		
		if (source) AttackingActor = Actor(source);
		if (inflictor) 
		{
			UniqueProjectile = Actor(inflictor);
			UniqueProjectileFast = FastProjectile(inflictor);
			ailmentproj = Actor(inflictor);
			ailmentprojfast = FastProjectile(inflictor);
			singleripproj = Actor(inflictor);
			singlefastripproj = FastProjectile(inflictor);
		}
		
		int oldhealthratio;
		int oldhealth = health;
		if (CountInv("NormalHealth")) oldhealthratio = 0;
		if (CountInv("DecentHealth")) oldhealthratio = 1;
		if (CountInv("LowHealth")) oldhealthratio = 2;
		if (CountInv("CriticalHealth")) oldhealthratio = 3;
		
		A_CheckNeverBleed(0, damage, flags);
		string infl, sour, vict;
		vict = GetClassName();
		if (inflictor == null) infl = "NONE"; else infl = inflictor.GetClassName();
		if (source == null) sour = "NONE"; else sour = source.GetClassName();
		
		if (sour == "BlackBearNew" || infl == "BlackBearNew")
		{
			mod = 'Melee';
			flags |= DMG_THRUSTLESS;
			flags &= ~DMG_EXPLOSION;
			if (dydudebug_playerdamagemobj) Console.Printf("BlackBear 'Explosion'");
		}
		
		if (sour == "JSkull_Image1" || sour == "JSkull_Image2" || sour == "JSkull_Image3" ||
				infl == "JSkull_Image1" || infl == "JSkull_Image2" || infl == "JSkull_Image3")
		{
			flags &= ~DMG_NO_ARMOR;
			flags &= ~DMG_NO_PROTECT;
			if (dydudebug_playerdamagemobj) Console.Printf("Jumping Skull Afterimage");
		}
		
		bool bellefishzap;
		if (mod == 'Melee' && flags & DMG_EXPLOSION && (BelleFish(Source) || BelleFish(Inflictor)))
		{
			int prevdmg = damage;
			flags |= DMG_THRUSTLESS;
			flags &= ~DMG_EXPLOSION;
			bellefishzap = true;
			if (CountInv("PowerNoDrown")) 
			{
				if (waterlevel >= 3) damage *= 0.4;
												else damage *= 0.94;
			}
			if (dydudebug_playerdamagemobj) Console.Printf("Bellefish Zap Melee: damage: %d [%d]", damage, prevdmg);
		}
		if (mod == 'Beats' && flags & DMG_EXPLOSION) flags &= ~DMG_EXPLOSION;
		
		if (isbarrierbeam)
		{
			flags |= DMG_NO_FACTOR;
			flags |= DMG_NO_PROTECT;
			flags |= DMG_NO_ENHANCE;
			flags |= DMG_THRUSTLESS;
		}

		int olddmg;
		armortier = 0;
		double SavePercent = 0.000000;
		int MaxAbsorb = 0;
		int MaxFullAbsorb = 0;
		
		int flatdefense;
		int baseflatdefense;
		bool useflatdefense;
		name armorclasstype = "KGArmor";
		let armor = KGArmor(FindInventory(armorclasstype));
		int armoramt;
		
		if (armor != null && CountInv(armorclasstype) > 0)
		{
			armoramt = armor.Amount;
			SavePercent = armor.SavePercent;
			MaxAbsorb = armor.MaxAbsorb;
			MaxFullAbsorb = armor.MaxFullAbsorb;
			if (savepercent >= 0.00000 && savepercent <= 0.49999) armortier = 0;
			if (savepercent >= 0.50000 && savepercent <= 0.74999) armortier = 1;
			if (savepercent >= 0.75000 && savepercent <= 0.87499) armortier = 2;
			if (savepercent >= 0.87500 && savepercent <= 0.93749) armortier = 3;
			if (savepercent >= 0.93750 && savepercent <= 0.99999) armortier = 4;
			if (savepercent >= 1.00000) armortier = 5;
			
			if (dydudebug_playerdamagemobj) Console.Printf("Armor SavePercent: %.8f, Tier: %d", savepercent, armortier);
		}
		
		bool SigilDrain;
		if (dydudebug_playerdamagemobj) Console.Printf("PDamage [Step 1] - Base: %d", damage);
		if (mod == 'PSI') flags |= DMG_NO_ARMOR;
		if (mod == 'Drowning' && source == null && inflictor == null)
		{
			flags |= DMG_NO_FACTOR;
			flags |= DMG_NO_PROTECT;
			flags |= DMG_NO_ENHANCE;
			flags |= DMG_NO_ARMOR;
			if (dydudebug_playerdamagemobj) Console.Printf("Drowning", damage);
		}
		if (mod == 'SigilDrain' && source == null && inflictor == self && flags & DMG_NO_ARMOR)
		{
			flags |= DMG_NO_FACTOR;
			flags |= DMG_NO_PROTECT;
			flags |= DMG_NO_ENHANCE;
			flags |= DMG_THRUSTLESS;
			flags |= DMG_NO_PAIN;
			SigilDrain = true;
			if (dydudebug_playerdamagemobj) Console.Printf("SigilDrain"); 
		}
		if (mod == 'Crush' && source == null && inflictor == null)
		{
			if (random(1,8) <= 7) flags |= DMG_NO_ARMOR;
			if (random(1,8) <= 1) flags |= DMG_NO_FACTOR;
			if (random(1,32) <= 1) flags |= DMG_NO_PROTECT;
			if (dydudebug_playerdamagemobj) Console.Printf("Crush"); 
		}
		
		if (mod != 'Slime' || 
				mod != 'Magma' || 
				mod != 'Crush' || 
				mod != 'Falling' || 
				mod != 'Poison' || 
				mod != 'PoisonCloud' || 
				mod != 'Magic' || 
				mod != 'Eldritch' || 
				mod != 'Sigil' || 
				mod != 'SigilDrain' || 
				mod != 'SpectralLow')
		{
			if (mod == 'Beats' && AttackingActor == self)
			{
				flags |= DMG_NO_ARMOR;
				flags |= DMG_THRUSTLESS;
				damage = ceil(damage * frandompick(1.0,1.0,1.0,1.125,1.125));
				if (dydudebug_playerdamagemobj) Console.Printf("Grimophone Alt-Fire (%d)", damage);
				if (damage >= health) return 0;
			}
			else
			{
				if (SigilDrain) { } 
				else damage = ceil(damage * 1.125);
			}
			if (SigilDrain) { } else if (CountInv("DoingSpinAttack")) damage *= 0.1667;
			if (dydudebug_playerdamagemobj) Console.Printf("PDamage [Step 1ba]: %d", damage);
		}
		else
		if (mod == 'Magic' || 
				mod == 'Poison' || 
				mod == 'PoisonCloud' || 
				mod == 'Eldritch' || 
				mod == 'Sigil' ||
				mod == 'SigilDrain' ||
				mod == 'SpectralLow')
		{
			if (SigilDrain) { } else damage = ceil(damage * 0.875);
			if (SigilDrain) { } else if (CountInv("DoingSpinAttack")) damage *= 0.1667;
			if (dydudebug_playerdamagemobj) Console.Printf("PDamage (non-normal base) [Step 1bb]: %d", damage);
		}
		else
		if (mod == 'Slime' || 
				mod == 'Lava' || 
				mod == 'Magma' || 
				mod == 'IceWater' || 
				mod == 'Crush' || 
				mod == 'Falling')
		{
			if (SigilDrain) { }
			else damage = ceil(damage * frandompick(0.75,0.875,0.875,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.125,1.125,1.25));
			if (dydudebug_playerdamagemobj) Console.Printf("PDamage (misc base) [Step 1bc]: %d", damage);
		}
		
		// VOODOO Doll Protection
		if (!player || !player.mo || player.mo != self)  
		{
			if (dydudebug_playerdamagemobj) Console.Printf("\cyIS A VOODOO DOLL\c-)", damage);
			//*********************************************************************
			return super.DamageMobj(inflictor, source, damage, mod, flags, angle); 
			//*********************************************************************
		}
		
		// (Partial) Defense Ignoring Attacks
		PlayerDefenseIgnoreFactor = A_DefenseIgnoreFactor(inflictor, source, damage, mod, flags, angle, bellefishzap, isbarrierbeam);

		// (Partial) Armor Ignoring Attacks
		PlayerArmorIgnoreFactor = A_ArmorIgnoreFactor(inflictor, source, damage, mod, flags, angle, bellefishzap, isbarrierbeam);

		// Direct Damage Changes
		if (flags & DMG_INFLICTOR_IS_PUFF)
		{
			if (AttackingActor != self)
			{
				if (BulletPuff(self))
				{
					olddmg = damage;
					if (dydudebug_playerdamagemobj) Console.Printf("Hit by Doom Bullet");
					if (armortier == 0) damage = ceil(damage * 0.9375);
					if (armortier == 1) damage = ceil(damage * 0.875);
					if (armortier == 2) damage = ceil(damage * 0.75);
					if (armortier == 3) damage = ceil(damage * 0.625);
					if (armortier == 4) damage = ceil(damage * 0.5);
					if (CountInv("CricketBatGuard")) damage = ceil(damage * frandompick(0.667,0.75,0.75,0.75,0.75,0.75,0.834));
					if (CountInv("CricketBatGuard2")) damage = ceil(damage * (frandompick(0.667,0.75,0.75,0.75,0.75,0.75,0.834) * 0.25));
					if (CountInv("CricketBatGuard3")) damage = ceil(damage * (frandompick(0.667,0.75,0.75,0.75,0.75,0.75,0.834) * 0.0625));
					if (CountInv("DoingSpinAttack")) damage *= 0.1667; // Cricket Bat Spin Attack almost entirely negates bullet damage

					if (dydudebug_playerdamagemobj) Console.Printf("PDamage [Bullet Buff]: %d (%d)", damage, olddmg);
				}
				useflatdefense = true;
			}
		}
		
		olddmg = damage;
		if (flags & DMG_EXPLOSION || mod == 'Explosive')
		{
			if (AttackingActor == self)
			{
				if (dydudebug_playerdamagemobj) Console.Printf("Damage Is Own AOE");
				
				if (mod == 'Beats')
				{
					damage = ceil(damage * (0.10 - (ActualLevel * 0.002)));
					if (ActualLevel <= 250 && damage < 1) damage = 1;
					if (armortier == 1) damage = ceil(damage * 0.9875);
					if (armortier == 2) damage = ceil(damage * 0.98125);
					if (armortier == 3) damage = ceil(damage * 0.975);
					if (armortier == 4) damage = ceil(damage * 0.9625);
				}
				else
				{
					damage = ceil(damage * (0.25 - (ActualLevel * 0.005)));
					if (ActualLevel <= 100 && damage < 1) damage = 1;
					if (armortier == 1) damage = ceil(damage * 0.975);
					if (armortier == 2) damage = ceil(damage * 0.9625);
					if (armortier == 3) damage = ceil(damage * 0.95);
					if (armortier == 4) damage = ceil(damage * 0.925);
				}
				useflatdefense = false;
			}
			else
			{
				double set1, set2, set3;
				if (dydudebug_playerdamagemobj) Console.Printf("Damage Is Not Own AOE");
				set1 = (0.750 - (ActualLevel * 0.0150));
				set2 = (0.875 - (ActualLevel * 0.0175));
				set3 = (1.000 - (ActualLevel * 0.0200));
				if (set1 <= 0.175) set1 = 0.175;
				if (set2 <= 0.21875) set2 = 0.21875;
				if (set3 <= 0.25) set3 = 0.25;
				if (AttackingActor != null)
				{
					if (Cyberdemon(source) || CyberdemonNew(source) || Annihilator(source)) 
					{
						if (RocketMonster(inflictor) || Rocket2(inflictor) || HomRocket1(inflictor))
						{
							set1 = (0.875 - (ActualLevel * 0.0175));
							set2 = (0.9375 - (ActualLevel * 0.01875));
							set3 = (1.0 - (ActualLevel * 0.02));
							if (set1 <= 0.21875) set1 = 0.21875;
							if (set2 <= 0.234375) set2 = 0.234375;
							if (set3 <= 0.25) set3 = 0.25;
						}
						else
						{
							set1 = (0.750 - (ActualLevel * 0.0150));
							set2 = (0.875 - (ActualLevel * 0.0175));
							set3 = (1.000 - (ActualLevel * 0.0200));
							if (set1 <= 0.175) set1 = 0.175;
							if (set2 <= 0.21875) set2 = 0.21875;
							if (set3 <= 0.25) set3 = 0.25;
						}
					}
					else 
					if (Archvile(source) || ArchvileNew(source) || Diabloist(source)) 
					{
						set1 = (0.50 - (ActualLevel * 0.01));
						set2 = (0.625 - (ActualLevel * 0.0125));
						set3 = (0.75 - (ActualLevel * 0.015));
						if (set1 <= 0.125) set1 = 0.125;
						if (set2 <= 0.15625) set2 = 0.15625;
						if (set3 <= 0.1875) set3 = 0.1875;
					}
				}
				if (dydudebug_playerdamagemobj) Console.Printf("set1: %.8f, set2: %.8f, set3: %.8f", set1, set2, set3);
				damage = ceil(damage * frandompick(set1,set1,set2,set2,set2,set2,set2,set2,set3,set3));
				if (ActualLevel <= 100 && damage < 1) damage = 1;
				if (armortier == 1) damage = ceil(damage * 0.9875);
				if (armortier == 2) damage = ceil(damage * 0.975);
				if (armortier == 3) damage = ceil(damage * 0.9625);
				if (armortier == 4) damage = ceil(damage * 0.95);
				useflatdefense = true;
			}

			// Prevents AOE from IP Attacks that somehow still manage to deal you damage from being able to kill you
			EEProjectile IPAtkSource;
			if (inflictor)
			{
				if (dydudebug_playerdamagemobj) Console.Printf("\c[fire](IP ATTACK W/ AOE [INFLICTOR] ATTEMPT)");
				IPAtkSource = EEProjectile(inflictor);
				if (dydudebug_playerdamagemobj && IPAtkSource) Console.Printf("\c[fire](IP ATTACK W/ AOE [INFLICTOR] ATTEMPT [2])");
				if (IPAtkSource && IPAtkSource.IPattack)
				{
					damage = 0;
					if (dydudebug_playerdamagemobj) Console.Printf("\c[fire]END DAMAGE ATTEMPT (IP ATTACK W/ AOE [INFLICTOR])");
					return 0;
				}
			}
			if (!IPAtkSource && source)
			{
				if (dydudebug_playerdamagemobj) Console.Printf("\c[fire](IP ATTACK W/ AOE [SOURCE] ATTEMPT)");
				IPAtkSource = EEProjectile(source);
				if (dydudebug_playerdamagemobj && IPAtkSource) Console.Printf("\c[fire](IP ATTACK W/ AOE [SOURCE] ATTEMPT [2])");
				if (IPAtkSource && IPAtkSource.IPAttack)
				{
					damage = 0;
					if (dydudebug_playerdamagemobj) Console.Printf("\c[fire]END DAMAGE ATTEMPT (IP ATTACK W/ AOE [SOURCE])");
					return 0;
				}
			}
			
			if (EggShot(inflictor) ||
			    EggGrenade(inflictor) ||
			    EggMini(inflictor))
			{
				flags |= DMG_THRUSTLESS;
				damage = 0;
				if (dydudebug_playerdamagemobj) Console.Printf("\c[fire]END DAMAGE ATTEMPT (FRACTAL EGG [AOE])");
				return 0;
			}
			if (EggShot(source) ||
			    EggGrenade(source) ||
			    EggMini(source))
			{
				flags |= DMG_THRUSTLESS;
				damage = 0;
				if (dydudebug_playerdamagemobj) Console.Printf("\c[fire]END DAMAGE ATTEMPT (FRACTAL EGG [AOE])");
				return 0;
			}

			if (CountInv("CricketBatGuard")) damage = ceil(damage * frandompick(0.334,0.5,0.5,0.5,0.5,0.5,0.667));
			if (CountInv("CricketBatGuard2")) damage = ceil(damage * (frandompick(0.334,0.5,0.5,0.5,0.5,0.5,0.667) * 0.25));
			if (CountInv("CricketBatGuard3")) damage = ceil(damage * (frandompick(0.334,0.5,0.5,0.5,0.5,0.5,0.667) * 0.0625));
			if (CountInv("DoingSpinAttack")) damage *= 0.0334; // Cricket Bat Spin Attack almost entirely negates AOE damage
			
			if (dydudebug_playerdamagemobj) Console.Printf("PDamage [AOE]: %d (%d)", damage, olddmg);
		}
		else
		{
			// Prevents IP Attacks that somehow still manage to deal you damage from being able to kill you
			EEProjectile IPAtkSource;
			if (inflictor)
			{
				IPAtkSource = EEProjectile(inflictor);
				if (IPAtkSource && IPAtkSource.IPAttack)
				{
					damage = 0;
					if (dydudebug_playerdamagemobj) Console.Printf("\c[fire]END DAMAGE ATTEMPT (IP ATTACK [INFLICTOR])");
					return 0;
				}
			}
			if (!IPAtkSource && source)
			{
				IPAtkSource = EEProjectile(source);
				if (IPAtkSource && IPAtkSource.IPAttack)
				{
					damage = 0;
					if (dydudebug_playerdamagemobj) Console.Printf("\c[fire]END DAMAGE ATTEMPT (IP ATTACK [SOURCE])");
					return 0;
				}
			}
			
			if (EggShot(inflictor) ||
			    EggGrenade(inflictor) ||
			    EggMini(inflictor))
			{
				damage = 0;
				if (dydudebug_playerdamagemobj) Console.Printf("\c[fire]END DAMAGE ATTEMPT (FRACTAL EGG)");
				return 0;
			}
			if (EggShot(source) ||
			    EggGrenade(source) ||
			    EggMini(source))
			{
				damage = 0;
				if (dydudebug_playerdamagemobj) Console.Printf("\c[fire]END DAMAGE ATTEMPT (FRACTAL EGG)");
				return 0;
			}
			if (AttackingActor != self) useflatdefense = true;
		}
		
		olddmg = damage;
		if (source != null)
		{
			if (Crusader(source))
			{
				if (flags & DMG_EXPLOSION || mod == 'Explosive') // The Crusader's death AOE does very little damage to Dinah (37.5% and dropping)
				{
					damage = ceil(damage * frandompick(0.375,0.375,0.375,0.5,0.5,0.625,0.625,0.75,0.75,0.75) - 0.375);
					if (armortier == 1) damage *= 0.90;
					if (armortier == 2) damage *= 0.80;
					if (armortier == 3) damage *= 0.60;
					if (armortier == 4) damage *= 0.20;
					if (dydudebug_playerdamagemobj) Console.Printf("PDamage [CrusaderAOE]: %d (%d)", damage, olddmg);
				}
				if (inflictor != null)
				{
					if (CrusaderMissile(inflictor) || FastFlameMissile(inflictor)) // The Crusader's attacks are very wanting against Dinah overall (37.5% and dropping)
					{
						damage = ceil(damage * frandompick(0.375,0.375,0.375,0.5,0.5,0.625,0.625,0.75,0.75,0.75) - 0.375);
						if (armortier == 1) damage *= 0.90;
						if (armortier == 2) damage *= 0.80;
						if (armortier == 3) damage *= 0.60;
						if (armortier == 4) damage *= 0.20;
						if (dydudebug_playerdamagemobj) Console.Printf("PDamage [CrusaderProj]: %d (%d)", damage, olddmg);
					}
				}
			}
			
			if (Revenant(source) || RevenantNew(source))
			{
				if (inflictor != null)
				{
					if (RevenantTracer(inflictor) || RevenantTracerNew(inflictor))
					{
						damage = ceil(damage * frandompick(0.375,0.5,0.5,0.625,0.625,0.75,0.75,0.875,0.875,1.0) - 0.25);
						if (armortier == 1) damage *= 0.95;
						if (armortier == 2) damage *= 0.90;
						if (armortier == 3) damage *= 0.80;
						if (armortier == 4) damage *= 0.60;
						if (dydudebug_playerdamagemobj) Console.Printf("PDamage [RevMissile]: %d (%d)", damage, olddmg);
					}
				}
			}
		}
		
		olddmg = damage;
		let weapon = player.ReadyWeapon;
		if (mod == 'Zap' && weapon is "WizardPike")
		{
			if (!(ddafd_disablepikegiveszapres && (CountInv("IsDynDuchess") || CountInv("IsAppetite") || CountInv("IsCarnOfSouls") || CountInv("IsWeddingCake"))))
			{
				if (!(DDPlayerPawn(source) || EvilDinah(source))) damage *= frandompick(0.1667,0.20,0.20,0.20,0.25,0.25,0.25,0.25,0.25,0.25,0.334,0.334,0.334,0.40);
																										 else damage *= frandompick(0.3334,0.40,0.40,0.40,0.5,0.5,0.5,0.5,0.5,0.5,0.667,0.667,0.667,0.80);
				if (dydudebug_playerdamagemobj) Console.Printf("PDamage [ZapShot w/ Pike Equipped]: %d (%d)", damage, olddmg);
			}
		}

		// Check FRIGHTENED/FRIENDLY flags
		if (damage > 0)
		{
			if (AttackingActor)
			{
				if (AttackingActor != self)
				{
					if (AttackingActor.bFRIENDLY)
					{
						damage = 0;
						if (dydudebug_playerdamagemobj) Console.Printf("END DAMAGE ATTEMPT (FRIENDLY)");
						return 0;
					}
					else
					{
						if (AttackingActor.CountInv("ScramblerConfusion")) // If the attacker is under the effect of the Confusion debuff from the Scrambler
						{
							damage = ceil(damage * frandompick(0,0,0.125,0.25,0.375,0.5,0.625,0.75,0.875,1.0));
							if (damage == 0) return 0;
						}
						else
						{
							if (AttackingActor.bFRIGHTENED) // Attacker is frightened, AND the Player is the one that is doing the frightening
							{
								if (player.cheats & CF_FRIGHTENING || bFRIGHTENING) damage = ceil(damage * frandompick(0.625,0.6875,0.75)); else damage = ceil(damage * frandompick(0.9375,0.95,0.9625));
							}
						}
					}
					if (dydudebug_playerdamagemobj) Console.Printf("PDamage [Friendly/Frighten Check]: %d (%d)", damage, olddmg);
				}
			}
		}
		
		// Armor/Defense Checks
		int basearmorflat;
		int basearmormax = 1;
		if (MiscItem)
		{
			if (armortier == 1) basearmormax = MiscItem.ArmorItemMax1;
			if (armortier == 2) basearmormax = MiscItem.ArmorItemMax2;
			if (armortier == 3) basearmormax = MiscItem.ArmorItemMax3;
			if (armortier == 4) basearmormax = MiscItem.ArmorItemMax4;
		}
		if (dydudebug_playerdamagemobj) Console.Printf("useflatdefense: %d", useflatdefense);
		if (!(mod == 'Slime' || mod == 'Lava' || mod == 'Magma' || mod == 'IceWater' || mod == 'Drowning' || mod == 'Falling'))
		{
			olddmg = damage;
			if (mod == 'Drowning') useflatdefense = false;
			if (mod == 'SigilDrain') useflatdefense = false;
			if (mod == 'Crush')
			{
				double basecrushdmgfact;
				if (PowerStrength(FindInventory("PowerStrength")) || PowerStrengthDD(FindInventory("PowerStrengthDD")))
				{
					basecrushdmgfact = frandompick(25,33.4,33.4,50,50,50,50,50,50,66.7,66.7,75);
				}
				else
				{
					basecrushdmgfact = frandompick(75,87.5,87.5,100,100,100,100,100,100,112.5,112.5,125);
				}
				damage *= double(basecrushdmgfact / mass);
				damage *= (basecrushdmgfact * 0.01);
				if (damage <= (olddmg * 0.1)) damage = (olddmg * 0.1);
				if (damage >= (olddmg * 10)) damage = (olddmg * 10);

				if (useflatdefense)
				{
					if (MiscItem) baseflatdefense += MiscItem.BaseFlatDefValueCrush;
					flatdefense = random((baseflatdefense*0.5),baseflatdefense);
					if (flags & !DMG_NO_ARMOR)
					{
						basearmorflat = 0;
						if (MiscItem) basearmorflat = MiscItem.ArmorDefValueCrush;
						
						if (basearmormax > 0) 
						{
							basearmorflat *= (1.0 - PlayerArmorIgnoreFactor);
							double armfactor = double(armoramt * 1.0 / basearmormax);

							flatdefense += (basearmorflat * armfactor);
							if (dydudebug_playerdamagemobj) Console.Printf("BaseArmorFlat: %d, Amt: %d / %d, armfactor: %.8f", basearmorflat, armoramt, basearmormax, armfactor);
						}
					}
					flatdefense *= (1.00 - PlayerDefenseIgnoreFactor);
					damage -= flatdefense;
					if (dydudebug_playerdamagemobj) Console.Printf("Flat Defense Calc [Crush Damage]: %d (damage: %d vs %d)", flatdefense, damage, olddmg);
				}
				if (damage <= 0)
				{
					if (armortier == 1) damage = 1;
					if (armortier == 2 && random(1,32) > 1) damage = 1;
					if (armortier == 3 && random(1,32) > 2) damage = 1;
					if (armortier >= 4 && random(1,32) > 4) damage = 1;
				}
			}
			else
			{
				if (mod == 'Drowning') useflatdefense = false;
				if (mod == 'SigilDrain') useflatdefense = false;
				if (useflatdefense)
				{
					if (MiscItem) baseflatdefense += MiscItem.BaseFlatDefValue;
					flatdefense = random((baseflatdefense*0.5),baseflatdefense);
					if (flags & !DMG_NO_ARMOR)
					{
						basearmorflat = 0;
						if (MiscItem) basearmorflat = MiscItem.ArmorDefValue;
						
						if (basearmormax > 0) 
						{
							basearmorflat *= (1.0 - PlayerArmorIgnoreFactor);
							double armfactor = double(armoramt * 1.0 / basearmormax);

							flatdefense += (basearmorflat * armfactor);
							if (dydudebug_playerdamagemobj) Console.Printf("BaseArmorFlat: %d, Amt: %d / %d, armfactor: %.8f", basearmorflat, armoramt, basearmormax, armfactor);
						}
					}
					flatdefense *= (1.00 - PlayerDefenseIgnoreFactor);
					damage -= flatdefense;
					if (dydudebug_playerdamagemobj) Console.Printf("Flat Defense Calc [Non-Crush Damage]: %d (damage: %d vs %d)", flatdefense, damage, olddmg);
				}
				if (damage <= 0)
				{
					if (armortier == 1) damage = 1;
					if (armortier == 2 && random(1,8) > 1) damage = 1;
					if (armortier == 3 && random(1,8) > 2) damage = 1;
					if (armortier >= 4 && random(1,8) > 4) damage = 1;
				}
			}
			if (dydudebug_playerdamagemobj) Console.Printf("PDamage [Raw Armor Def]: %d", damage, olddmg);
		}
		else // Slime Damage
		{
			if (mod == 'Drowning') useflatdefense = false;
			if (mod == 'SigilDrain') useflatdefense = false;
			if (useflatdefense)
			{
				if (MiscItem) baseflatdefense += MiscItem.BaseFlatDefValueDmgFlr;
				flatdefense = random((baseflatdefense*0.5),baseflatdefense);
				if (flags & !DMG_NO_ARMOR)
				{
					basearmorflat = 0;
					if (MiscItem) basearmorflat = MiscItem.ArmorDefValueDmgFlr;
					
					if (basearmormax > 0) 
					{
						basearmorflat *= (1.0 - PlayerArmorIgnoreFactor);
						double armfactor = double(armoramt * 1.0 / basearmormax);

						flatdefense += (basearmorflat * armfactor);
						if (dydudebug_playerdamagemobj) Console.Printf("BaseArmorFlat: %d, Amt: %d / %d, armfactor: %.8f", basearmorflat, armoramt, basearmormax, armfactor);
					}
				}
				flatdefense *= (1.00 - PlayerDefenseIgnoreFactor);
				damage -= flatdefense;
				if (dydudebug_playerdamagemobj) Console.Printf("Flat Defense Calc [DmgFloor Damage]: %d (damage: %d vs %d)", flatdefense, damage, olddmg);
			}
		}
		
		if (CountInv("PowerRatMorph") && mod == 'Falling') damage = floor(damage * frandom(0.15625,0.1875));
		
		// Berserk Effects
		if (CountInv("PowerStrength") || CountInv("PowerStrengthDD") && !SigilDrain)
		{
			olddmg = damage;
			if (mod == 'Falling') damage = ceil(damage * frandom(0.625,0.75));
			if (mod == 'Crush') 
			{
				damage = ceil(damage * frandom(0.75,0.875));
				if (damage < 1) damage = 1;
			}
			if (mod == 'Drowning') 
			{
				damage = ceil(damage * frandom(0.625,1.000));
				if (damage < 1) damage = 1;
			}
			if (dydudebug_playerdamagemobj) Console.Printf("PDamage [Berserk Effects]: %d", damage, olddmg);
		}
		else
		{
			if (mod == 'Drowning' && damage < 1) damage = 1;
		}
		

		if (CountInv("PlayerDashing") && !SigilDrain)
		{
			if (BarrierBeam(inflictor) || BarrierBeam(source))
			{
			}
			else
			{
				if (dydudebug_playerdamagemobj) Console.Printf("PDamage [Dashing Avoids Damage]");
				return 0;
			}
		}

		if (CountInv("PowerTimeFreezer") || 
				CountInv("DDMiscTimeFreezer") || 
				(CountInv("DebugTimeFreezer") && dydudebug_timeslowinterval > 1) || 
				CountInv("TimePotionTimeFreezer") || 
				CountInv("DashTimeFreezer"))
		{
			if (mod == 'Slime' || mod == 'Lava' || mod == 'Magma' || mod == 'IceWater')
			{
				if (dydudebug_playerdamagemobj) Console.Printf("PDamage [TimeFreeze on Slime abort]");
				return 0;
			}
		}
		
		olddmg = damage;
		if (mod == "CCardsPoison")
		{
			double dmg1base = 0.00;
			if (armortier == 1) 
			{
				damage *= frandom(0.875,1.000);
				dmg1base = 6.25;
			}
			if (armortier == 2) 
			{
				damage *= frandom(0.625,0.875);
				dmg1base = 12.5;
			}
			if (armortier == 3) 
			{
				damage *= frandom(0.25,0.625);
				dmg1base = 43.75;
			}
			if (armortier == 4) 
			{
				damage *= frandom(0.0,0.25);
				dmg1base = 87.5;
			}
			if (frandom(0.1,100.0) > dmg1base && damage < 1) damage = 1;
			if (dydudebug_playerdamagemobj) Console.Printf("PDamage [CCards Acid w/ Armor]: %d (%d)", damage, olddmg);
		}
		
		bool isinvuln = false;
		// If Invulnerable
		{
			if (bINVULNERABLE || player.cheats & CF_GODMODE2 || player.cheats & CF_GODMODE || CountInv("PowerInvulnDD") || CountInv("PowerInvulnerable"))
			{ 
				if (SigilDrain) damage = 0;
				A_StartSound("Player/TookNoDamageInvuln",199,CHANF_DEFAULT,frandom(0.5,0.75),ATTN_NORM);
				isinvuln = true;
			}
		}
		
		if (dydudebug_playerdamagemobj)
		{
			olddmg = damage;
			int projdam;
			double endmgmultS = 1.0;
			double endmgmultI = 1.0;
			if (source) endmgmultS = source.DamageMultiply;
			if (!source && inflictor) endmgmultI = inflictor.DamageMultiply;
			projdam = damage * endmgmultS * endmgmultI;
			Console.Printf("Projected Dmg: %d vs (%d), Source's DamageMultiply: %.8f, Inflictor's DamageMultiply: %.8f", projdam, olddmg, endmgmultS, endmgmultI);
		}
		
		olddmg = damage;
		damage *= exex_pdmgtakenfactor;
		if (dydudebug_playerdamagemobj) Console.Printf("PDamage [Damage Cheat]: %d [%d]", damage, olddmg);
		
		if (dydudebug_playerdamagemobj) Console.Printf("PDamage [Final] - Final Damage: %d", damage);
		
		if (dydudebug_playerdamagemobj && armoramt) Console.Printf("Armor Amount: %d", armoramt);
		DmgSource = source;
		DmgInflictor = inflictor;
		DmgFlags = flags;
		mobjdmg = damage;
		if (dydudebug_playerdamagemobj) Console.Printf("damage [pre-ssa]: %d", damage);
		double ssa = 1.00;
		if (CountInv("ExpeditionHat")) ssa -= frandompick(0.15,0.20,0.25);
		if (CountInv("ClassyRibbon")) ssa -= frandompick(0.075,0.100,0.125);
		damage = int(damage * ssa);
		if (dydudebug_playerdamagemobj) Console.Printf("damage [post-ssa]: %d, ssa: %.8f", damage, ssa);
		if (mod == 'Slime' || mod == 'Lava' || mod == 'Magma' || mod == 'IceWater') tookflrdmg = true;
		if (mod == 'IceWater') mod = 'Ice';
		//******************************
		let ret = super.DamageMobj(inflictor, source, damage, mod, flags, angle);
		//******************************
		if (dydudebug_playerdamagemobj) Console.Printf("ret [PDM]: %d", ret);
		ret = PostDamageMobj(inflictor, source, damage, mod, flags, angle, 
												 ret, armoramt, firstdmg, isinvuln, oldhealth, oldhealthratio, SigilDrain,
												 infl, sour, vict);
		if (dydudebug_playerdamagemobj) Console.Printf("ret [final]: %d", ret);
		
		tookflrdmg = false;
		return ret;
	}
	
	int PostDamageMobj(Actor inflictor, Actor source, int damage, Name mod, int flags, double angle, int ret, int armoramt, int firstdmg, bool isinvuln, int oldhealth, int oldhealthratio, bool SigilDrain, string infl, string sour, string vict)
	{
		let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
		let globalvars = DDGlobalVariables.Get();
		bool isCCardsIllusion = false;

		if (source)
		{
			if (source.bNOBLOOD == true && 
					source.bNOPAIN == true &&
					source.bNOTARGETSWITCH == true &&
					source.bNOINFIGHTING == true &&
					source.bFULLVOLACTIVE == false && 
					source.bFULLVOLDEATH == false &&
					source.bBOSS == false) isCCardsIllusion = true;
			if (source.bISMONSTER && !source.bFRIENDLY && !isCCardsIllusion) A_DynamicMusic(forcedplay:true);
		}
		else
		if (inflictor)
		{
			if (inflictor.bNOBLOOD == true && 
					inflictor.bNOPAIN == true &&
					inflictor.bNOTARGETSWITCH == true &&
					inflictor.bNOINFIGHTING == true &&
					inflictor.bFULLVOLACTIVE == false && 
					inflictor.bFULLVOLDEATH == false &&
					inflictor.bBOSS == false) isCCardsIllusion = true;
			if (inflictor.bISMONSTER && !inflictor.bFRIENDLY && !isCCardsIllusion) A_DynamicMusic(forcedplay:true);
		}
		
		string combatlogmsg = "\c[sapphire]*\c- ";
		name armorclasstype = "KGArmor";
		int armdmg = (armoramt - CountInv(armorclasstype));
		if (armdmg <= 0) armdmg = 0;
		if (dydudebug_playerdamagemobj && armdmg) Console.Printf("Armor Damage: %d", armdmg);
		if (armdmg && exex_armordmgsounds && !isCCardsIllusion)
		{
			A_StopSound(213);
			if (CountInv(armorclasstype)) A_StartSound("armordamaged",213,CHANF_DEFAULT,1.0,ATTN_NORM);
															 else A_StartSound("armorbroken",213,CHANF_DEFAULT,1.0,ATTN_NORM);
		}
		if (exex_playerdmglog)
		{
			if (!isCCardsIllusion)
			{
				if (ret || armdmg)
				{
					if (armdmg && !ret) combatlogmsg.AppendFormat("\c[darkgreen]%d AP\c- ", armdmg);
					else if (armdmg && ret) combatlogmsg.AppendFormat("\c[darkred]%d HP\c- & \c[darkgreen]%d AP\c- ", ret, armdmg);
					else combatlogmsg.AppendFormat("\c[darkred]%d HP\c- ", ret);
					if (dydudebug_dmgdiffdebug)
					{
						int dmgdiff = ((ret + armdmg) - firstdmg);
						if (dmgdiff)
						{
							//Console.Printf("Dmgdiff: %d, FinalDmg: %d, OrigDmg: %d", dmgdiff, (ret + armdmg), firstdmg);
							if (dydudebug_dmgdiffdebug >= 1 && dydudebug_dmgdiffdebug <= 2)
							{
								combatlogmsg.AppendFormat("[", dmgdiff);
								if (dmgdiff < 0) combatlogmsg.AppendFormat("\c[lightblue]%d\c-", dmgdiff);
								if (dmgdiff == 0) combatlogmsg.AppendFormat("0", dmgdiff);
								if (dmgdiff > 0) combatlogmsg.AppendFormat("\c[brick]+%d\c-", dmgdiff);
								if (firstdmg) combatlogmsg.AppendFormat(" (", dmgdiff);
							}
							else
							{
								combatlogmsg.AppendFormat("[", dmgdiff);
							}
							if (dydudebug_dmgdiffdebug >= 2 && dydudebug_dmgdiffdebug <= 3 && MiscItem)
							{
								double dmgdiffper;
								if (firstdmg) 
								{
									dmgdiffper = ((((ret + armdmg) * 100.0 / firstdmg)) - 100.0);
									if (dmgdiffper < 0) combatlogmsg.AppendFormat("\c[lightblue]%.2f%%\c-", dmgdiffper);
									if (dmgdiffper == 0) combatlogmsg.AppendFormat("0%%", dmgdiffper);
									if (dmgdiffper > 0) combatlogmsg.AppendFormat("\c[brick]+%.2f%%\c-", dmgdiffper);
									if (dydudebug_dmgdiffdebug >= 3) combatlogmsg.AppendFormat("] ", dmgdiff);
																							else combatlogmsg.AppendFormat(")", dmgdiff);
								}
							}
							if (dydudebug_dmgdiffdebug >= 1 && dydudebug_dmgdiffdebug <= 2) combatlogmsg.AppendFormat("] ", dmgdiff);
						}
					}
					if (mod == 'SigilDrain') combatlogmsg.AppendFormat("of damage drained");
															else combatlogmsg.AppendFormat("of damage taken");
				}
				else
				{
					if (isinvuln) 
					{
						combatlogmsg.AppendFormat("\c[green]Invulnerable!\c- No Damage \c-");
					}
					else
					{
						A_StartSound("Player/TookNoDamage",199,CHANF_DEFAULT,frandom(0.5,0.75),ATTN_NORM);
						combatlogmsg.AppendFormat("\c[white]No Damage \c-");
					}
					if (dydudebug_dmgdiffdebug)
					{
						int dmgdiff = ((ret + armdmg) - firstdmg);
						if (dmgdiff)
						{
							//Console.Printf("Dmgdiff: %d, FinalDmg: %d, OrigDmg: %d", dmgdiff, (ret + armdmg), firstdmg);
							if (dydudebug_dmgdiffdebug >= 1 && dydudebug_dmgdiffdebug <= 2)
							{
								combatlogmsg.AppendFormat("[", dmgdiff);
								if (dmgdiff < 0) combatlogmsg.AppendFormat("\c[lightblue]%d\c-", dmgdiff);
								if (dmgdiff == 0) combatlogmsg.AppendFormat("0", dmgdiff);
								if (dmgdiff > 0) combatlogmsg.AppendFormat("\c[brick]+%d\c-", dmgdiff);
								if (firstdmg) combatlogmsg.AppendFormat(" (", dmgdiff);
							}
							else
							{
								combatlogmsg.AppendFormat("[", dmgdiff);
							}
							if (dydudebug_dmgdiffdebug >= 2 && dydudebug_dmgdiffdebug <= 3 && MiscItem)
							{
								double dmgdiffper;
								if (firstdmg) 
								{
									dmgdiffper = ((((ret + armdmg) * 100.0 / firstdmg)) - 100.0);
									if (dmgdiffper < 0) combatlogmsg.AppendFormat("\c[lightblue]%.2f%%\c-", dmgdiffper);
									if (dmgdiffper == 0) combatlogmsg.AppendFormat("0%%", dmgdiffper);
									if (dmgdiffper > 0) combatlogmsg.AppendFormat("\c[brick]+%.2f%%\c-", dmgdiffper);
									if (dydudebug_dmgdiffdebug >= 3) combatlogmsg.AppendFormat("] ", dmgdiff);
																							else combatlogmsg.AppendFormat(")", dmgdiff);
								}
							}
							if (dydudebug_dmgdiffdebug >= 1 && dydudebug_dmgdiffdebug <= 2) combatlogmsg.AppendFormat("] ", dmgdiff);
						}
					}
					combatlogmsg.AppendFormat("\c[white]taken\c-");
				}
				if (source) // Has a source
				{
					combatlogmsg.AppendFormat(" from \c[purple]%s\c-", source.GetTag());
					if (inflictor && inflictor != source) combatlogmsg.AppendFormat("\c[purple]'s\c- \c[brick]%s\c-", inflictor.GetTag());
				}
				else
				if (inflictor) // No source, but has an inflictor
				{
					if (mod == 'SigilDrain') combatlogmsg.AppendFormat(" by the Sigil!");
															else combatlogmsg.AppendFormat(" from \c[brick]%s!", inflictor.GetTag());
				}
				else // If no source OR inflictor
				{
					if (mod == 'Slime') combatlogmsg.AppendFormat(" from a damaging surface");
					else if (mod == 'Lava' || mod == 'Magma' || mod == 'IceWater' || tookflrdmg) combatlogmsg.AppendFormat(" from a damaging surface");
					else if (mod == 'Crush') combatlogmsg.AppendFormat(" from a crushing ceiling");
					else if (mod == 'Falling') combatlogmsg.AppendFormat(" from falling");
					else if (mod == 'Drowning') combatlogmsg.AppendFormat(" from drowning");
					combatlogmsg.AppendFormat("!");
				}
				combatlogmsg.AppendFormat(" [%s]", mod);
				//Console.Printf("armoramt: %d, PlayerArmorIgnoreFactor: %.8f", armoramt, PlayerArmorIgnoreFactor);
				if ((ret || armdmg) && armoramt && PlayerArmorIgnoreFactor)
				{
					double temp = (PlayerArmorIgnoreFactor * 100.0);
					combatlogmsg.AppendFormat(" \c[orange](");
					combatlogmsg.AppendFormat("%.2f%%", temp);
					combatlogmsg.AppendFormat("  armor bypass)\c-");
				}
				if (flags & DMG_EXPLOSION) combatlogmsg.AppendFormat(" \c[brick][AOE]\c-");
				if (dydudebug_showgametic) combatlogmsg.AppendFormat(" \c[green][tic: %d]\c-", gametic);
				Console.Printf(combatlogmsg);
			}
		}
		
		// Interrupt HP Regen For a Bit
		if (MiscItem && ret > 0)
		{
			double regenintfactor = 1.0;
			if (A_CheckDDGame())
			{
				if (skill <= 0) regenintfactor = 2.0;
				if (skill == 1) regenintfactor = 2.25;
				if (skill == 2) regenintfactor = 2.5;
				if (skill == 3) regenintfactor = 2.75;
				if (skill >= 4) regenintfactor = 3.0;
			}
			else
			{
				if (skill <= 0) regenintfactor = 1.0;
				if (skill == 1) regenintfactor = 1.125;
				if (skill == 2) regenintfactor = 1.25;
				if (skill == 3) regenintfactor = 1.375;
				if (skill >= 4) regenintfactor = 1.5;
			}
			if (mod == 'Ice' || mod == 'IceWater') 
			{
				if (tookflrdmg) regenintfactor *= frandompick(1.375,1.5,1.5,1.5,1.5,1.5,1.625);
									 else regenintfactor *= frandompick(1.1875,1.25,1.25,1.25,1.25,1.25,1.3125);
			}
			if (mod == 'Fire' || mod == 'Boiling' || mod == 'Lava' || mod == 'Magma') 
			{
				if (tookflrdmg) regenintfactor *= frandompick(0.6875,0.75,0.75,0.75,0.75,0.75,0.8125);
									 else regenintfactor *= frandompick(0.375,0.5,0.5,0.5,0.5,0.5,0.625);
			}
			int regendmg = (randompick(9,10,10,11,11,12,13) * ((ret * frandompick(0.875,1.0625)) * regenintfactor));
			MiscItem.HPRegenBoostTimer -= regendmg;
			if (MiscItem.HPRegenBoostTimer < (-350 * regenintfactor)) MiscItem.HPRegenBoostTimer = (-350 * regenintfactor);
			if (dydudebug_playerdamagemobj) Console.Printf("MiscItem.HPRegenBoostTimer: %d, regendmg: %d, regenintfactor: %.8f, dmgfactor: %s, tookflrdmg: %d", MiscItem.HPRegenBoostTimer, regendmg, regenintfactor, mod, tookflrdmg);
		}
		
		// Item/Ikari Point Gains
		if (CheckIPEnabled() && ret && MiscItem && globalvars && health > 0 && !isCCardsIllusion)
		{
			int gain = 0;
			if ((source && source != self) && (inflictor && inflictor != self)) gain += 1;
			if (!(mod == 'Slime' || mod == 'Lava' || mod == 'Magma' || tookflrdmg || mod == 'Drowning' || mod == 'Falling' || mod == 'Crush')) gain += 1;
			if ((mod == 'Slime' || mod == 'Lava' || mod == 'Magma' || tookflrdmg || mod == 'Drowning' || mod == 'Falling' || mod == 'Crush') && !inflictor && !source) gain -= 1;
			//Console.Printf("IP Gain: %d", gain);
			if (gain > 0 && MiscItem.IPNoGainTimer <= 0)
			{
				double base;
				// The mod's first and original formula
				if (exex_ikaripointscalctype <= 0)
				{
					base = ret * 100.0 / MiscItem.MaxHealthTrue;
					if (oldhealthratio == 0) base *= 1.0;
					if (oldhealthratio == 1) base *= 1.125;
					if (oldhealthratio == 2) base *= 1.25;
					if (oldhealthratio == 3) base *= 1.5;
					if (oldhealthratio == 4) base *= 2.25;
					if (oldhealth > 1 && health == 1) base *= 3.25;
					if (MiscItem.PlayerLUCK) base *= (0.125 + (ActualLevel * 0.00125) + (random(1,MiscItem.PlayerLUCK) * frandompick(0.0005,0.0005,0.0005,0.0005,0.0005,0.0005,0.0005,0.0005,0.001,0.001,0.001,0.001,0.001,0.001,0.002,0.002,0.002,0.002,0.003,0.003)));
															else base *= (0.125 + (ActualLevel * 0.00125));
					
				}
				// The more Lufia II equse formula
				if (exex_ikaripointscalctype >= 0)
				{
					base = ret * 100.0 / oldhealth; // % of remaining HP removed
					if (base >= 0.001)
					{
						if (base >= 0.001 && base <= 50.000) base *= 0.50; // <= 50% equals half of the percent in IP points given [up to 25%]
						if (base >= 50.001 && base <= 65.000) base *= 0.558077; 
						if (base >= 65.001 && base <= 75.000) base *= 0.646154;
						if (base >= 75.001 && base <= 85.000) base *= 0.76; 
						if (base >= 85.001 && base <= 90.000) base *= 0.90; 
						if (base >= 90.001 && base <= 100.000) base *= 1.00; 
						if (base >= 100.001) base *= 1.25;
						if (oldhealth > 1 && health == 1) base += MiscItem.MaxItemPoints;
					}
				}
				nm = "CCards_Actor_AcidBlood"; extracheck = nm;
				if (infl == extracheck || sour == extracheck) base *= frandompick(1.375,1.5,1.5,1.5,1.5,1.5,1.625);
				nm = "CCards_Actor_HighVoltageZapp"; extracheck = nm;
				if (infl == extracheck || sour == extracheck) base *= frandompick(1.5625,1.75,1.75,1.75,1.75,1.75,1.9375);
				nm = "CCards_Actor_ThrownCorpseHitbox"; extracheck = nm;
				if (infl == extracheck || sour == extracheck) base *= frandompick(1.1875,1.25,1.25,1.25,1.25,1.25,1.3125);
				if (mod == 'SigilDrain')
				{
					base *= frandompick(0.2,0.25,0.25,0.25,0.25,0.25,0.334);
				}
				if (DDOrigCreature(source) || DDOrigCreature(inflictor))
				{
					base *= frandompick(1.667,2.0,2.0,2.0,2.0,2.5,2.5,2.5,2.5,3);
				}
				if (DDOrigBoss(source) || DDOrigBoss(inflictor))
				{
					base *= (frandompick(1.667,2.0,2.0,2.0,2.0,2.5,2.5,2.5,2.5,3) * frandompick(1.5,2.0));
				}
				double basef = base;
				if (SigilDrain)
				{
					base *= (1.0 / frandompick(1.5,1.75,1.75,2,2,2,2.25,2.25,2.5));
					basef *= (0.334 / frandompick(1.5,1.75,1.75,2,2,2,2.25,2.25,2.5));
				}
				A_AddIP(base, basef, true, true);
			}
		}
		
		if (ret)
		{
			int damagetakefactor = ret * 100 / MiscItem.MaxHealthTrue;
			if (damagetakefactor < 1) damagetakefactor = 1;
			if (MiscItem)
			{
				MiscItem.HPHUDShakeType = 1;
				if (damagetakefactor >= 10) MiscItem.HPHUDShakeType = 2;
				if (damagetakefactor >= 50) MiscItem.HPHUDShakeType = 3;
				if (damagetakefactor >= 100) MiscItem.HPHUDShakeType = 4;
			}
			player.damagecount -= ret;
			if (player.damagecount < 0) player.damagecount = 0;
			player.damagecount += damagetakefactor;
			if (player.damagecount > 100) player.damagecount = 100;
			if (dydudebug_countdisplays) Console.Printf("player.damagecount: %d, damagetakefactor: %d, dmg: %d / %d", player.damagecount, damagetakefactor, ret, MiscItem.MaxHealthTrue);
		}
		
		if (armdmg && armortier)
		{
			int armmax;
			if (MiscItem)
			{
				if (armortier == 1) armmax = MiscItem.ArmorItemMax1;
				if (armortier == 2) armmax = MiscItem.ArmorItemMax2;
				if (armortier == 3) armmax = MiscItem.ArmorItemMax3;
				if (armortier == 4) armmax = MiscItem.ArmorItemMax4;
			}
			if (armmax > 0)
			{
				int damagetakefactor = armdmg * 100 / armmax;
				if (MiscItem)
				{
					MiscItem.APHUDShakeType = 1;
					if (damagetakefactor >= 10) MiscItem.APHUDShakeType = 2;
					if (damagetakefactor >= 50) MiscItem.APHUDShakeType = 3;
					if (damagetakefactor >= 100) MiscItem.APHUDShakeType = 4;
				}
			}
		}
		
		A_LossHUD(ret, 0, true);
		A_LossHUD(armdmg, 1, true);
		
		PlayerArmorIgnoreFactor = 0.00;
		PlayerDefenseIgnoreFactor = 0.00;
		return ret;
	}

	override bool CanCollideWith(Actor other, bool passive)
	{
		if (!player || !player.mo || player.mo != self)
		{
			if (!passive)
			{
				if (dydudebug_generalcollisions) Console.Printf("\c[brick]Collision:\c- NotPassive - %s vs (%s) [PPawnVoodoo] {gametic: %d}", other.GetClassName(), GetClassName(), gametic); 
				return true;
			}
			else
			{
				if (dydudebug_generalcollisions) Console.Printf("\c[red]Collision:\c- Passive - (%s) [PPawnVoodoo] vs %s {gametic: %d}", GetClassName(), other.GetClassName(), gametic); 
				return true;
			}
		}
		else
		{
			// Non-passive means the one moving into the other is performing the checks.
			if (!passive)
			{
				if (dydudebug_generalcollisions) Console.Printf("\c[brick]Collision:\c- NotPassive - %s vs (%s) [PlayerPawn] {gametic: %d}", other.GetClassName(), GetClassName(), gametic); 
				// Pass through different species of select types.
				if (other.bFRIENDLY == 1)
				{
					if (dydudebug_generalcollisions) Console.Printf("\c[lightblue]Collision:\c- NotPassive - %s [Friendly] vs (%s) [PlayerPawn] = False/No Collision {gametic: %d}", other.GetClassName(), GetClassName(), gametic);
					return false;
				}
			}
			else
			{
				if (dydudebug_generalcollisions) Console.Printf("\c[red]Collision:\c- Passive - (%s) [PlayerPawn] vs %s {gametic: %d}", GetClassName(), other.GetClassName(), gametic); 
				return true;
			}
		}

		// We don't really care about others making the check.
		return true;
	}
	
	void A_DDPain()
	{
		if (GetClassName() == "DinahPlayer")
		{
			double MaxHealthTrue = CountInv("PlayerMaxHP");
			if ((!player || !player.mo || player.mo != self) || !MaxHealthTrue) MaxHealthTrue = SpawnHealth();
			double HealthRatio = health / MaxHealthTrue;
			// Console.Printf("%.8f", HealthRatio);
			if (health > 0)
			{
				string painsnd = "";
				if (HealthRatio >= 0.751) painsnd = "Dinah/Pain1A";
				else if (HealthRatio >= 0.501 && HealthRatio < 0.750) painsnd = "Dinah/Pain2A";
				else if (HealthRatio >= 0.251 && HealthRatio <= 0.500) painsnd = "Dinah/Pain3A";
				else if (HealthRatio < 0.251) painsnd = "Dinah/Pain4A";
				A_StopSound(CHAN_VOICE);
				A_StartSound(painsnd,CHAN_VOICE,CHANF_DEFAULT,1.0,ATTN_NORM);
			}
		}
	}
	
	int HasBuddha()
	{
		if (player.playerstate == PST_DEAD) return 0;
		if (player.cheats & CF_BUDDHA2) return 2;
		
		if ((player.cheats & CF_BUDDHA) ||
				(player.mo.bBUDDHA) ||
				 player.mo.FindInventory("PowerBuddha") != null) return 1;
		
		return 0;
	}
	
	const PPD_ALLOWPOWERFACTORS = 1;
	const PPD_ALLOWDAMAGEFACTORS = 2;
	const PPD_ALLOWSKILLDAMAGEFACTORS = 4;
	const PPD_POISONCANKILL = 8;
	const PPD_ALLOWAUTOHEALTH = 16;
	const PPD_ALLOWSTRIFEAUTOHEALTH = 32;
	
	void PlayerPoisonDamage(actor source, int damage, bool playPainSound, int PoisonFlags = 63, int PainInterval = 63)
	{
		bool allowpowerups, allowdmgfactors, allowskilldmgfactor, cankill, allowautohealth, allowstrifeautohealth;
		
		if (PoisonFlags & PPD_ALLOWPOWERFACTORS) allowpowerups = true;
		if (PoisonFlags & PPD_ALLOWDAMAGEFACTORS) allowdmgfactors = true;
		if (PoisonFlags & PPD_ALLOWSKILLDAMAGEFACTORS) allowskilldmgfactor = true;
		if (PoisonFlags & PPD_POISONCANKILL) cankill = true;
		if (PoisonFlags & PPD_ALLOWAUTOHEALTH) allowautohealth = true;
		if (PoisonFlags & PPD_ALLOWSTRIFEAUTOHEALTH) allowstrifeautohealth = true;
		
		actor target;
		
		if (player == null)
		{
			return;
		}
		target = player.mo;
		if (target.health <= 0)
		{
			return;
		}
		
		// This must be checked before any modifications. Otherwise, power amplifiers
		// may result in doing too much damage that cannot be negated by regular buddha,
		// which is inconsistent. The raw damage must be the only determining factor for
		// determining if telefrag is actually desired.
		bool telefragDamage = (damage >= TELEFRAG_DAMAGE && !(target.bLAXTELEFRAGDMG));
		
		if ((player.cheats & CF_GODMODE2) || (target.bNODAMAGE) || //These two are never subjected to telefrag thresholds.
			(!telefragDamage && ((target.bINVULNERABLE) || (player.cheats & CF_GODMODE))))
		{ // target is invulnerable
			return;
		}
		
		if (dydudebug_playerpoisondisplays) Console.Printf("poison - damage (pre-factor): %d", damage);
		if (allowskilldmgfactor)
		{
			// Take half damage in trainer mode
			damage = int(damage * SKILLP_DamageFactor * sv_damagefactorplayer);
			if (dydudebug_playerpoisondisplays) Console.Printf("allowskilldmgfactor - damage: %d", damage);
		}
		if (allowpowerups)
		{
			// Handle passive damage modifiers (e.g. PowerProtection)
			damage = target.GetModifiedDamage(player.poisontype, damage, true, null, source);
			if (dydudebug_playerpoisondisplays) Console.Printf("allowpowerups - damage: %d", damage);
		}
		if (allowdmgfactors)
		{
			// Modify with damage factors
			damage = target.ApplyDamageFactor(player.poisontype, damage);
			if (dydudebug_playerpoisondisplays) Console.Printf("allowdmgfactors - damage: %d", damage);
		}
		if (dydudebug_playerpoisondisplays) Console.Printf("poison - damage (post-factor): %d", damage);
		
		if (damage <= 0)
		{ // Damage was reduced to 0, so don't bother further.
			return;
		}
		
		if (allowautohealth)
		{
			if (damage >= player.health
				&& (SKILLP_AutoUseHealth || deathmatch)
				&& !player.morphTics)
			{ // Try to use some inventory health
				AutoUseHealth(damage - player.health+1);
			}
		}
		player.health -= damage; // mirror mobj health here for Dave
		if (allowstrifeautohealth)
		{
			int threshold = 50;
			let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
			if (MiscItem) threshold = (MiscItem.MaxHealthTrue * 0.5);
			if (player.health < threshold && !deathmatch)
			{
				AutoUseStrifeHealth();
			}
		}
		
		int healthfloor;
		if (cankill) healthfloor = 0; else healthfloor = 1;
		
		if (player.health < healthfloor) player.health = healthfloor;
		
		player.attacker = source;
		
		//*****************
		//* do the damage *
		//*****************
		if (dydudebug_playerpoisondisplays) Console.Printf("poison - damage: %d", damage);
		target.health -= damage;
		if (target.health < healthfloor) target.health = healthfloor;
		if (target.health <= 0)
		{ // Death
			int buddha = HasBuddha();
			if (telefragDamage && buddha == 1) buddha = 0;
			if (buddha)
			{ // [SP] Save the player... 
				player.health = target.health = 1;
			}
			else
			{
				target.special1 = damage;
				if (player && !player.morphTics)
				{ // Check for flame death
					if ((player.poisontype == 'Fire') && (target.health > -50) && (damage > 25))
					{
						target.DamageType = 'Fire';
					}
					else
					{
						target.DamageType = player.poisontype;
					}
				}
				target.Die(source, source);
				return;
			}
		}
		if (PainInterval <= 0) PainInterval = 63;
		int PoisonTargInv = randompick(4,5,5,5,5,5,6);
		if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) PoisonTargInv -= randompick(0,1,1,1,1,1,1,1,1,1,1,1,1,2);
		int targtime = target.level.time & 63; // target.level.time % PainInterval;
		if (playPainSound)
		{
			bool PainSnd = false;
			if (!(targtime & 63))
			{
				PainSnd = true;
			}
			else
			{
				PoisonDmgPainInt++;
			}
			if (PoisonDmgPainInt >= PoisonTargInv) 
			{
				PainSnd = true;
				PoisonDmgPainInt = 0;
			}
			
			if (PainSnd)
			{
				state painstate = target.FindState("Pain", player.poisonpaintype);
				if (painstate != null) target.SetState(painstate);
			}
			if (dydudebug_playerpoisondisplays) Console.Printf("targtime: %d / %d, PoisonDmgPainInt: %d / %d", targtime, PainInterval, PoisonDmgPainInt, PoisonTargInv);
		}
	}
	
	override void CheckPoison()
	{
		int oldhealthratio;
		int oldhealth = health;
		if (CountInv("NormalHealth")) oldhealthratio = 0;
		if (CountInv("DecentHealth")) oldhealthratio = 1;
		if (CountInv("LowHealth")) oldhealthratio = 2;
		if (CountInv("CriticalHealth")) oldhealthratio = 3;
		
		int countdec = randompick(3,4,4,4,5,5,5,5,5,5,5,6,6,6,7);
		int countint = randompick(14,15,15,15,15,15,15,15,15,15);
		if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
		{
			countdec = (randompick(3,4,4,4,5,5,5,5,5,5,5,6,6,6,7) - randompick(0,1,1,1,1,1,1,1,1,2));
			countint = randompick(13,13,13,14,14,14,14,14,14,15);
		}
		if (CountInv("ExpeditionHat"))
		{
			countdec += (randompick(0,1,1,1,1,1,1,1,1,2) + 1);
			countint += randompick(0,2);
		}
		let player = self.player;
		let MiscItem = PlayerStatItem(player.mo.FindInventory("PlayerStatItem"));
		if (player.poisoncount && !(Level.maptime & countint))
		{
			player.poisoncount -= countdec;
			if (player.poisoncount < 0) player.poisoncount = 0;
			if (dydudebug_playerpoisondisplays) Console.Printf("poisoncount: %d [\c[green]-%d\c-]", player.poisoncount, countdec);

			if (!(bINVULNERABLE ||
						CountInv("PowerInvulnerable") ||
						CountInv("PowerInvulnDD") ||
						player.cheats & CF_GODMODE2 ||
						player.cheats & CF_GODMODE))
			{
				int poisdmg = randompick(1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,3);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					poisdmg = randompick(1,1,1,1,1,1,1,1,1,1,2,2,2,2,3,3);
					poisdmg *= frandompick(1.25,1.375,1.375,1.5,1.5,1.5,1.5,1.5,1.5,1.625,1.625,1.75);
				}
				if (MiscItem) 
				{
					poisdmg = ((randompick(1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,3) * 0.01) * MiscItem.MaxHealthTrue);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
					{
						poisdmg = ((randompick(1,1,1,1,1,1,1,1,1,1,2,2,2,2,3,3) * 0.01) * MiscItem.MaxHealthTrue);;
						poisdmg *= frandompick(1.25,1.375,1.375,1.5,1.5,1.5,1.5,1.5,1.5,1.625,1.625,1.75);
					}
					if (poisdmg < 1) poisdmg = 1;
					poisdmg *= exex_pdmgtakenfactor;
				}
				if (poisdmg > 0 && health > poisdmg)
				{
					int PainInterval = (63 - (player.poisoncount / randompick(4,5,5,5,5,6)));
					if (PainInterval < 15) PainInterval = 15;
					if (random(1,4) <= 1) 
					{
						if (random(1,8) <= 1) PainInterval *= 0.25;
														 else PainInterval *= 0.5;
					}
					PlayerPoisonDamage(player.poisoner, poisdmg, true, PPD_ALLOWAUTOHEALTH|PPD_ALLOWSTRIFEAUTOHEALTH, PainInterval);
					//player.PoisonDamage(player.poisoner, poisdmg, true);
					
					A_LossHUD(poisdmg, 0, true);
					if (exex_playerdmglog)
					{
						string combatlogmsg = "\c[sapphire]*\c- Took";
						combatlogmsg.AppendFormat(" \c[darkred]%d damage\c-", poisdmg);
						combatlogmsg.AppendFormat(" from poisoning!");
						if (dydudebug_showgametic) combatlogmsg.AppendFormat(" \c[green][tic: %d]\c-", gametic);
						Console.Printf(combatlogmsg);
					}

					let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
					let globalvars = DDGlobalVariables.Get();
					// Item/Ikari Point Gains
					if (CheckIPEnabled() && poisdmg && MiscItem && globalvars && health > 0)
					{
						if (MiscItem.IPNoGainTimer <= 0)
						{
							double base;
							// The mod's first and original formula
							if (exex_ikaripointscalctype <= 0)
							{
								base = poisdmg * 100.0 / MiscItem.MaxHealthTrue;
								if (oldhealthratio == 0) base *= 1.0;
								if (oldhealthratio == 1) base *= 1.125;
								if (oldhealthratio == 2) base *= 1.25;
								if (oldhealthratio == 3) base *= 1.5;
								if (oldhealthratio == 4) base *= 2.25;
								if (oldhealth > 1 && health == 1) base *= 3.25;
								if (MiscItem.PlayerLUCK) base *= (0.125 + (ActualLevel * 0.00125) + (random(1,MiscItem.PlayerLUCK) * frandompick(0.0005,0.0005,0.0005,0.0005,0.0005,0.0005,0.0005,0.0005,0.001,0.001,0.001,0.001,0.001,0.001,0.002,0.002,0.002,0.002,0.003,0.003)));
																		else base *= (0.125 + (ActualLevel * 0.00125));
								
							}
							// The more Lufia II equse formula
							if (exex_ikaripointscalctype >= 0)
							{
								base = poisdmg * 100.0 / oldhealth; // % of remaining HP removed
								if (base >= 0.001)
								{
									if (base >= 0.001 && base <= 50.000) base *= 0.50; // <= 50% equals half of the percent in IP points given [up to 25%]
									if (base >= 50.001 && base <= 65.000) base *= 0.558077; 
									if (base >= 65.001 && base <= 75.000) base *= 0.646154;
									if (base >= 75.001 && base <= 85.000) base *= 0.76; 
									if (base >= 85.001 && base <= 90.000) base *= 0.90; 
									if (base >= 90.001 && base <= 100.000) base *= 1.00; 
									if (base >= 100.001) base *= 1.25;
									if (oldhealth > 1 && health == 1) base += MiscItem.MaxItemPoints;
								}
							}
							base *= (frandompick(3.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,6.0,6.0,6.0,7.0) * 0.5);
							double basef = base;
							A_AddIP(base, basef, true, true);
						}
					}
				}
				if (dydudebug_playerdamagemobj) Console.Printf("poisoncount: %d (maptime: %d)", player.poisoncount, Level.maptime);
			}
		}
	}
}

class DinahPlayer : DDPlayerPawn // HereticPlayer
{
	int breathtic;
	default
	{
		Player.DisplayName "Dinah Wyck";
		Player.SoundClass "DinahPlayer";
		Player.StartItem "ClassID", 1;
		Player.StartItem "PlayerStatItem";
		//Player.StartItem "DynamicMusic";
		Player.StartItem "PlayerDashJump";
		Player.StartItem "ResetInventory";
		Player.StartItem "CricketBat";
		Player.StartItem "HandToHand";
		Player.StartItem "MalletAmmo", 10;
		Player.Weaponslot 1, "HandToHand";
		Player.Weaponslot 2, "CricketBat";
		Player.Weaponslot 3, "Blundaxe", "Scrambler";
		Player.Weaponslot 4, "AppleJack";
		Player.Weaponslot 5, "WizardPike";
		Player.Weaponslot 6, "SuperVac";
		Player.Weaponslot 7, "Grimophone";
		Player.WeaponSlot 8, "SigilDD", "CandleWhip";
		Player.WeaponSlot 9, "CrazyBallDD";
		Player.WeaponSlot 0, "FosnianCandle";
		Player.ForwardMove 0.75, 0.75; // 0.75
		Player.SideMove 0.65, 0.65; // 0.65
		Player.ViewBob 0.5;
		Player.AttackZOffset 8;
		Player.AirCapacity 1;
		Player.JumpZ 9;
		//Player.GruntSpeed 12;
		Player.ViewHeight 36;
		Player.InvulnerabilityMode "Reflective";
		Species "Players";
		Health 80; // 100
		Player.MaxHealth 80;
		Player.MugShotMaxHealth -1; // 100
		XScale 1.0; //0.8572;
		YScale 0.95; //0.8572;
		Mass 60;
		Height 48; // Slightly Shorter than Flora in Aetherius
		Radius 12; // Dinah is actually SLIGHTLY thinner than even Flora is in Aetherius
		Tag "Dinah Wyck";
		+PLAYERPAWN.NOTHRUSTWHENINVUL
	}
	
	override void Tick()
	{
		super.Tick(); // KEEP THIS HERE ELSE OTHER FUNCTIONS RELATED TO THIS BREAK :V
		
		if (InStateSequence(curstate,ResolveState("Death")) ||
				InStateSequence(curstate,ResolveState("XDeath")) ||
				InStateSequence(curstate,ResolveState("Burn")) ||
				InStateSequence(curstate,ResolveState("Ice")))
		{
			A_APPBreatheReset();
		}
		else
		{
			breathtic++;
			if (breathtic >= 4)
			{
				A_APPBreathe();
				breathtic = 0;
			}
		}
	}

	States
	{
		Spawn:
			DINA A 4
			{
			}
			Loop;
		See:
			DINA BCDE 4
			{
				tics = 4;
				let MiscItem = PlayerStatItem(FindInventory("PlayerStatItem"));
				if (MiscItem)
				{
					if (MiscItem.HUDSpeed >= 2.25) tics = ceil(tics *= 0.875);
					if (MiscItem.HUDSpeed >= 1.5) tics = ceil(tics *= 0.9375);
					if (MiscItem.HUDSpeed <= 0.667) tics = ceil(tics *= 1.25);
					if (MiscItem.HUDSpeed <= 0.334) tics = ceil(tics *= 1.5);
				}
				if (CountInv("PowerWineBuffIPWeak")) tics = ceil(tics *= 1.032258064516129);
				if (CountInv("PowerWineBuffIPStrong")) tics = ceil(tics *= 1.066666666666667);
				if (CountInv("PowerWineBuffIPStrongest")) tics = ceil(tics *= 1.103448275862069);
				if (CountInv("PowerWineBuffIPStrongestEven")) tics = ceil(tics *= 1.142857142857143);
				if (CountInv("PowerWineBuffIPMaximum")) tics = ceil(tics *= 1.230769230769231);
				if (CountInv("PowerWineBuffWeak")) tics = ceil(tics *= 1.142857142857143);
				if (CountInv("PowerWineBuffStrong")) tics = ceil(tics *= 1.333333333333333);
				if (CountInv("PowerWineBuffStrongest")) tics = ceil(tics *= 1.6);
				if (CountInv("PowerWineBuffStrongestEven")) tics = ceil(tics *= 2.0);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tics = ceil(tics *= 0.875);
				if (CountInv("OverFullHealth3")) tics = ceil(tics *= 0.85);
				if (CountInv("OverFullHealth2")) tics = ceil(tics *= 0.9);
				if (CountInv("OverFullHealth1")) tics = ceil(tics *= 0.95);
				if (CountInv("NormalHealth")) tics = ceil(tics *= 1);
				if (CountInv("DecentHealth")) tics = ceil(tics *= 1.125);
				if (CountInv("LowHealth")) tics = ceil(tics *= 1.25);
				if (CountInv("CriticalHealth")) tics = ceil(tics *= 1.375);
				
				if (dydudebug_playerwalkdisplays) Console.Printf("Tics (See): %d", tics);
				if (tics < 1) tics = 1;
				A_SetTics(tics);
			}
			Loop;
		Pain:
			DINA H 6 
			{
				A_DDPain();
			}
			Goto Spawn;
		Missile:
			DINA F 0 A_DynamicMusic(200,0);
			DINA FG 6
			{
			}
			Goto Spawn;
		Melee:
			DINA F 0 A_DynamicMusic(200,1);
			DINA FGF 4
			{
			}
			Goto Spawn;
		BatGuard:
			DINA LL 1
			{
			}
			DINA L 0
			{
			}
			Goto Spawn;
		ShieldGuard:
			DINA LL 2
			{
			}
			DINA L 0
			{
			}
			Goto Spawn;
		SpinAttackBatPre:
			DINA F 0 A_DynamicMusic(200,1);
			DINA FF 1
			{
			}
			DINA F 0
			{
			}
			Goto Spawn;
		SpinAttackBat:
			DINA G 0 A_DynamicMusic(200,1);
			DINA GG 1
			{
			}
			DINA G 0
			{
			}
			Goto Spawn;
		PreKick:
			DINA A 0 A_DynamicMusic(200,1);
			DINK A 0
			{
				A_SetInventory("PKicking",0);
			}
			Goto Spawn;
		Kick:
			DINK AA 1
			{
				A_SetInventory("PKicking",1);
			}
			DINK A 0
			{
				A_SetInventory("PKicking",0);
			}
			Goto Spawn;
		Kick2:
			DINK BB 1
			{
				A_SetInventory("PKicking",1);
			}
			DINK B 0
			{
				A_SetInventory("PKicking",0);
			}
			Goto Spawn;
		Death:
			DINA H 0 A_APPBreatheReset();
			DINA H 9 A_PlayerScream;
			DINA I 9 A_NoBlocking();
			DINA JK 9;
			DINA K -1;
			Stop;
		XDeath:
			DINA H 0 A_APPBreatheReset();
			DINA H 9 A_PlayerScream;
			DINA I 9 A_NoBlocking();
			DINA JK 9;
			DINA K -1;
			Stop;
		AltSkinDeath:
			DINA H 0 A_APPBreatheReset();
			DINA H 9 A_PlayerScream;
			DINA I 9 A_NoBlocking();
			DINA JK 9;
			DINA K -1;
			Stop;
		AltSkinXDeath:
			DINA H 0 A_APPBreatheReset();
			DINA H 9 A_PlayerScream;
			DINA I 9 A_NoBlocking();
			DINA JK 9;
			DINA K -1;
			Stop;
		Burn:
			goto Death;
		Ice:
			goto Death;
  }
}

class RavenPlayer : DDPlayerPawn
{
	default
	{
		Player.DisplayName "Dinah Wyck [Raven Form]";
		Tag "Dinah Wyck [Raven Form]";
		Health 30;
		ReactionTime 0;
		PainChance 255;
		Radius 16;
		Height 32;
		Speed 0.5;
		+NoSkin
		-PickUp
		+NoTarget
		Player.Viewheight 32;
		Player.DisplayName "Raven";
		Player.MorphWeapon "RavenWeapon";
	}
	States
	{
		Spawn:
			RVPL A 0;
			RVPL ABCD 5 A_GiveInventory("RavenPowerups", 1);
			Loop;
		See:
			RVPL ABCD 5 A_GiveInventory("RavenPowerups", 1);
			Loop;
		Pain:
			RVPL C 4 A_Pain();
			Goto Spawn;
		Death:
			TNT1 A -1;
			Stop;
	}
}

class RatPlayer : DDPlayerPawn
{
	default
	{
		Player.DisplayName "Dinah Wyck [Rat Form]";
		Tag "Dinah Wyck [Rat Form]";
		Health 30;
		ReactionTime 0;
		PainChance 255;
		Radius 10;
		Height 16;
		Speed 1;
		+NOSKIN
		-PICKUP
		PainSound "Rat/Pain";
		DeathSound "Rat/Death";
		Player.JumpZ 3;
		Player.Viewheight 14;
		Player.ForwardMove 0.75, 0.75;
		Player.SideMove 0.65, 0.65;
		Player.SpawnClass "Rat";
		Player.SoundClass "Rat";
		Player.DisplayName "Rat";
		Player.MorphWeapon "RatNose";
	}
	
	States
	{
		Spawn:
			RATS A 0 A_StopSound(5);
			RATS A -1;
			Stop;
		See:
			RATS ABC 3;
			Loop;
		Melee:
		Missile:
			RATS B 8;
			RATS A 8;
			Goto Spawn;
		Pain:
			RATS C 4 A_Pain();
			Goto Spawn;
		Death:
			RATS D 6 A_Scream();
			RATS E 6 A_NoBlocking();
			RATS F 6;
			TNT1 A 1 A_CheckPlayerDone();
			Wait;
	}
}