//*************************************************************************************************
//* A special inventory item intended for any NON-"EECreatre" class across other possible games,  *
//* mapsets or mods [i.e. BlooM, etc] that will give them varied resistances and weaknesses based *
//* on things like hybrids, etc.
//*************************************************************************************************
class CompatVulnItem : PlaceholderItem 
{
	string ownername;
	string nl, nm, nn, no, np, nq, nr, ns, nt, nu, nv, nw, nx, ny, nz, na, nb, nc, nd, ne, nf, ng, nh, ni, nj, nk;
	bool found;
	double lastTOTALFactor;
	
	double GetDoomResistances(int damage, Name damageType, out int newdamage, bool passive, Actor inflictor, Actor source, int flags)
	{
		if (dydudebug_actordmgdisplays) Console.Printf("[Doom]");
		double TOTALFactor = 1.0;
		/*
		nm = "";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.0;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		*/
		nm = "ZombieMan";
		nn = "ZombieMan_";
		no = "PossessedZombieMan";
		if (ownername == nm || 
				ownername == nn ||
				ownername == no)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.34;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == "CherryBomb") TOTALFactor = 1.5;
			if (damageType == "BRocket") TOTALFactor = 1.0;
			if (damageType == "Spinner") TOTALFactor = 1.0;
			if (damageType == "Popper") TOTALFactor = 1.0;
			if (damageType == "Bonk") TOTALFactor = 1.0;
			if (damageType == "Cricket") TOTALFactor = 1.0;
			if (damageType == "Chop") TOTALFactor = 1.25;
			if (damageType == "Lead") TOTALFactor = 1.0;
			if (damageType == "Breakfast") TOTALFactor = 1.0;
			if (damageType == "Dust") TOTALFactor = 1.0;
			if (damageType == "Zap") TOTALFactor = 1.0;
			if (damageType == "Beats") TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "ShotgunGuy";
		nn = "ShotgunGuy_";
		no = "PossessedShotgunGuy";
		if (ownername == nm || 
				ownername == nn ||
				ownername == no)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.34;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.5;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.25;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "ChaingunGuy";
		nn = "ChaingunGuy_";
		no = "PossessedChaingunGuy";
		if (ownername == nm || 
				ownername == nn ||
				ownername == no)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.34;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.5;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.25;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "WolfensteinSS";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.34;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.5;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.25;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "DoomImp";
		nn = "DoomImp_";
		if (ownername == nm || 
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.4;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.6;
			if (damageType == 'BRocket') TOTALFactor = 1.125;
			if (damageType == 'Spinner') TOTALFactor = 0.8;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.5;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "Demon";
		nn = "Demon_";
		no = "Spectre";
		np = "Spectre_";
		if (ownername == nm || 
				ownername == nn ||
				ownername == no ||
				ownername == np)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.625;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 0.875;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.125;
			if (damageType == 'Cricket') TOTALFactor = 1.5;
			if (damageType == 'Chop') TOTALFactor = 0.625;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 2.5;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "LostSoul";
		nn = "LostSoul_";
		if (ownername == nm || 
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.334;
			if (damageType == "Ice") TOTALFactor = 3.001;
			if (damageType == "Suck") TOTALFactor = 15.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.25;
			if (damageType == 'BRocket') TOTALFactor = 0.5;
			if (damageType == 'Spinner') TOTALFactor = 1.25;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.25;
			if (damageType == 'Cricket') TOTALFactor = 2.5;
			if (damageType == 'Chop') TOTALFactor = 5.0;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.75;
			if (damageType == 'Dust') TOTALFactor = 0.25;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "Cacodemon";
		nn = "Cacodemon_";
		if (ownername == nm || 
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.25;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.25;
			if (damageType == 'BRocket') TOTALFactor = 2.5;
			if (damageType == 'Spinner') TOTALFactor = 3.75;
			if (damageType == 'Popper') TOTALFactor = 0.25;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 5.0;
			if (damageType == 'Dust') TOTALFactor = 5.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "PainElemental";
		nn = "PainElemental_";
		if (ownername == nm || 
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.5;
			if (damageType == "Ice") TOTALFactor = 1.75;
			if (damageType == "Suck") TOTALFactor = 7.5;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 2.5;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 5.0;
			if (damageType == 'Dust') TOTALFactor = 5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "Arachnotron";
		nn = "Arachnotron_";
		if (ownername == nm || 
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.334;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.875;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 0.625;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.5;
			if (damageType == 'Dust') TOTALFactor = 5;
			if (damageType == 'Zap') TOTALFactor = 1.5;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "Revenant";
		nn = "Revenant_";
		if (ownername == nm || 
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.25;
			if (damageType == "Ice") TOTALFactor = 1.75;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.125;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 0.75;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 0.5;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.5;
			if (damageType == 'Beats') TOTALFactor = 0.75;
			found = true;
		}
		
		nm = "Fatso";
		nn = "Fatso_";
		if (ownername == nm || 
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.667;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 0.5;
			if (damageType == 'CherryBomb') TOTALFactor = 2.0;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.75;
			if (damageType == 'Popper') TOTALFactor = 1.25;
			if (damageType == 'Bonk') TOTALFactor = 3.75;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 5.0;
			if (damageType == 'Lead') TOTALFactor = 1.25;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}

		nm = "Archvile";
		nn = "Archvile_";
		if (ownername == nm || 
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.1;
			if (damageType == "Ice") TOTALFactor = 5.0;
			if (damageType == "Suck") TOTALFactor = 3.75;
			if (damageType == 'CherryBomb') TOTALFactor = 0.25;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 1.5;
			if (damageType == 'Bonk') TOTALFactor = 2.5;
			if (damageType == 'Cricket') TOTALFactor = 5.0;
			if (damageType == 'Chop') TOTALFactor = 5.0;
			if (damageType == 'Lead') TOTALFactor = 1.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "HellKnight";
		nn = "HellKnight_";
		no = "BaronOfHell";
		np = "BaronOfHell_";
		if (ownername == nm || 
				ownername == nn ||
				ownername == no ||
				ownername == np)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.5;
			if (damageType == "Ice") TOTALFactor = 2.0;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 3.75;
			if (damageType == 'BRocket') TOTALFactor = 2.5;
			if (damageType == 'Spinner') TOTALFactor = 2.5;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "SpiderMastermind";
		nn = "SpiderMastermind_";
		if (ownername == nm || 
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.1;
			if (damageType == "Ice") TOTALFactor = 3.5;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.65;
			if (damageType == 'BRocket') TOTALFactor = 10;
			if (damageType == 'Spinner') TOTALFactor = 1.25;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "Cyberdemon";
		nn = "Cyberdemon_";
		if (ownername == nm || 
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.1;
			if (damageType == "Ice") TOTALFactor = 3.5;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.65;
			if (damageType == 'BRocket') TOTALFactor = 10;
			if (damageType == 'Spinner') TOTALFactor = 1.25;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		if (dydudebug_actordmgdisplays) Console.Printf("[Doom] TOTALFactor: %.8f, damageType: %s", TOTALFactor, damageType);
		return TOTALFactor;
	}
	
	// For BlooM/Blood mods in general [the default monsters as define in other mods/mapsets, NOT BlooM's hybrids :V]
	double GetBloodResistances1(int damage, Name damageType, out int newdamage, bool passive, Actor inflictor, Actor source, int flags)
	{
		if (dydudebug_actordmgdisplays) Console.Printf("[Blood (1)]");
		double TOTALFactor = 1.0;
		/*
		nm = "";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.0;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		*/
		
		nm = "ChokingHand";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 0.4;
			if (damageType == "Kick") TOTALFactor = 2.5;
			if (damageType == "Dashing") TOTALFactor = 1.5;
			if (damageType == "DashingBG") TOTALFactor = 1.5;
			if (damageType == "DashingSD") TOTALFactor = 1.5;
			if (damageType == "Fire") TOTALFactor = 2.0; // It has a base 2x factor to fire
			if (damageType == "Ice") TOTALFactor = 1.25;
			if (damageType == "Suck") TOTALFactor = 15.0; // Goes down as fast as a Lost Soul, if not faster :V
			if (damageType == 'CherryBomb') TOTALFactor = 1.5;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 1.15;
			if (damageType == 'Bonk') TOTALFactor = 1.25;
			if (damageType == 'Cricket') TOTALFactor = 1.25;
			if (damageType == 'Chop') TOTALFactor = 1.5;
			if (damageType == 'Lead') TOTALFactor = 1.25;
			if (damageType == 'Breakfast') TOTALFactor = 1.25;
			if (damageType == 'Dust') TOTALFactor = 0.1;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 0.5;
			found = true;
		}
		
		nm = "BloodGargoyle";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = frandom(0.55,0.61); // Correlates to 'Fire' and 'Napalm' damagetypes, so randomize between both values. :V
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'BRocket') TOTALFactor = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Spinner') TOTALFactor = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.5; // Bonk can correlate to a 'Pitchfork' poke
			if (damageType == 'Cricket') TOTALFactor = 2.0;
			if (damageType == 'Chop') TOTALFactor = 1.5;
			if (damageType == 'Lead') TOTALFactor = 0.8; // Correlates to 'SawedOff' DamageType
			if (damageType == 'Breakfast') TOTALFactor = 0.775;
			if (damageType == 'Dust') TOTALFactor = 1.5; // Are weak to Dust unlike GALgoyles are :P
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 2.5;
			found = true;
		}
		
		nm = "BloatedButcher";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 0.5;
			if (damageType == "Kick") TOTALFactor = 0.5;
			if (damageType == "Dashing") TOTALFactor = 0.75;
			if (damageType == "DashingBG") TOTALFactor = 0.75;
			if (damageType == "DashingSD") TOTALFactor = 0.75;
			if (damageType == "Fire") TOTALFactor = frandom(frandom(2.0,3.0),6.0);
			if (damageType == "Ice") TOTALFactor = 0.25;
			if (damageType == "Suck") TOTALFactor = 0.5;
			if (damageType == 'CherryBomb') TOTALFactor = 4.2;
			if (damageType == 'BRocket') TOTALFactor = 2.4;
			if (damageType == 'Spinner') TOTALFactor = 2.4;
			if (damageType == 'Popper') TOTALFactor = 0.75;
			if (damageType == 'Bonk') TOTALFactor = 0.5;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 2.5;
			if (damageType == 'Lead') TOTALFactor = 0.25;
			if (damageType == 'Breakfast') TOTALFactor = 1.75;
			if (damageType == 'Dust') TOTALFactor = 0.25;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "BrownCultist";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.0;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 0.7;
			if (damageType == 'Cricket') TOTALFactor = 0.85;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "GreyCultist";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.0;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.7;
			if (damageType == 'BRocket') TOTALFactor = 0.7;
			if (damageType == 'Spinner') TOTALFactor = 0.7;
			if (damageType == 'Popper') TOTALFactor = 0.85;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "RedCultist";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.0;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "GreenCultist";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = frandom(0.25,0.35);
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = frandom(0.5,0.625);
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "BlueCultist";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.75;
			if (damageType == 'BRocket') TOTALFactor = 0.75;
			if (damageType == 'Spinner') TOTALFactor = 0.75;
			if (damageType == 'Popper') TOTALFactor = 1.334;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 0.9;
			if (damageType == 'Breakfast') TOTALFactor = 0.75;
			if (damageType == 'Dust') TOTALFactor = 1.334;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.1;
			found = true;
		}
		
		nm = "BloodZombie";
		nn = "BuriedZombie";
		if (ownername == nm ||
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 0.75;
			if (damageType == "Kick") TOTALFactor = 0.75;
			if (damageType == "Dashing") TOTALFactor = 0.75;
			if (damageType == "DashingBG") TOTALFactor = 0.75;
			if (damageType == "DashingSD") TOTALFactor = 0.75;
			if (damageType == "Fire") TOTALFactor = frandom(3.35,3.5);
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 2.5;
			if (damageType == 'BRocket') TOTALFactor = 2.25;
			if (damageType == 'Spinner') TOTALFactor = 2.25;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 2.5;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.25;
			if (damageType == 'Beats') TOTALFactor = 1.25;
			found = true;
		}
		
		nm = "GillBeast";
		nn = "Hellfish";
		if (ownername == nm ||
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.5;
			if (damageType == "Ice") TOTALFactor = 1.5;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 2.2;
			if (damageType == 'BRocket') TOTALFactor = 1.6;
			if (damageType == 'Spinner') TOTALFactor = 1.6;
			if (damageType == 'Popper') TOTALFactor = 1.4;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.334;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 0.25;
			if (damageType == 'Dust') TOTALFactor = 3.667;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 0.125;
			found = true;
		}
		
		nm = "Phantasm"; // >:V
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 5.0;
			if (damageType == "Kick") TOTALFactor = 5.0;
			if (damageType == "Dashing") TOTALFactor = 7.5;
			if (damageType == "DashingBG") TOTALFactor = 7.5;
			if (damageType == "DashingSD") TOTALFactor = 7.5;
			if (damageType == "Fire") TOTALFactor = 0.125;
			if (damageType == "Ice") TOTALFactor = 0.125;
			if (damageType == "Suck") TOTALFactor = 5.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.625;
			if (damageType == 'BRocket') TOTALFactor = 0.625;
			if (damageType == 'Spinner') TOTALFactor = 0.625;
			if (damageType == 'Popper') TOTALFactor = 0.625;
			if (damageType == 'Bonk') TOTALFactor = 0.25;
			if (damageType == 'Cricket') TOTALFactor = 0.25;
			if (damageType == 'Chop') TOTALFactor = 0.125;
			if (damageType == 'Lead') TOTALFactor = frandom(3.75,6.25);
			if (damageType == 'Breakfast') TOTALFactor = 0.25;
			if (damageType == 'Dust') TOTALFactor = 0.125;
			if (damageType == 'Zap') TOTALFactor = 12.5;
			if (damageType == 'Beats') TOTALFactor = 1.25;
			found = true;
		}
		
		nm = "Hellhound";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = frandom(0.0,0.4);
			if (damageType == "Ice") TOTALFactor = 2.25;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.125;
			if (damageType == 'BRocket') TOTALFactor = 0.125;
			if (damageType == 'Spinner') TOTALFactor = 0.125;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.25;
			if (damageType == 'Cricket') TOTALFactor = 1.125;
			if (damageType == 'Chop') TOTALFactor = 1.75;
			if (damageType == 'Lead') TOTALFactor = 1.375;
			if (damageType == 'Breakfast') TOTALFactor = 0.55;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.5;
			if (damageType == 'Beats') TOTALFactor = 3.75;
			found = true;
		}
		
		nm = "BloodBeast";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 2.0;
			if (damageType == "DashingBG") TOTALFactor = 2.0;
			if (damageType == "DashingSD") TOTALFactor = 2.0;
			if (damageType == "Fire") TOTALFactor = 0.0;
			if (damageType == "Ice") TOTALFactor = 4.0;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.05;
			if (damageType == 'BRocket') TOTALFactor = 0.625;
			if (damageType == 'Spinner') TOTALFactor = 0.625;
			if (damageType == 'Popper') TOTALFactor = 0.875;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 0.25;
			if (damageType == 'Lead') TOTALFactor = 4.0;
			if (damageType == 'Breakfast') TOTALFactor = 0.5;
			if (damageType == 'Dust') TOTALFactor = 0.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 0.5;
			found = true;
		}
		
		nm = "Cheogh";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 0.75;
			if (damageType == "Kick") TOTALFactor = 0.75;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.0;
			if (damageType == "Ice") TOTALFactor = 4.0;
			if (damageType == "Suck") TOTALFactor = 0.0625;
			if (damageType == 'CherryBomb') TOTALFactor = 0.0625;
			if (damageType == 'BRocket') TOTALFactor = 0.25;
			if (damageType == 'Spinner') TOTALFactor = 0.25;
			if (damageType == 'Popper') TOTALFactor = 0.4375;
			if (damageType == 'Bonk') TOTALFactor = 0.75;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 0.25;
			if (damageType == 'Lead') TOTALFactor = 4.0;
			if (damageType == 'Breakfast') TOTALFactor = 0.125;
			if (damageType == 'Dust') TOTALFactor = 0.0;
			if (damageType == 'Zap') TOTALFactor = 2.5;
			if (damageType == 'Beats') TOTALFactor = 0.125;
			found = true;
		}
		
		nm = "Cerberus";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = frandom(0.05,0.1);
			if (damageType == "Ice") TOTALFactor = 1.625;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 2.25;
			if (damageType == 'BRocket') TOTALFactor = 0.28125;
			if (damageType == 'Spinner') TOTALFactor = 0.28125;
			if (damageType == 'Popper') TOTALFactor = 0.5;
			if (damageType == 'Bonk') TOTALFactor = 0.875;
			if (damageType == 'Cricket') TOTALFactor = 0.9375;
			if (damageType == 'Chop') TOTALFactor = 1.125;
			if (damageType == 'Lead') TOTALFactor = 1.1875;
			if (damageType == 'Breakfast') TOTALFactor = 0.775;
			if (damageType == 'Dust') TOTALFactor = 0.5;
			if (damageType == 'Zap') TOTALFactor = 1.25;
			if (damageType == 'Beats') TOTALFactor = 1.6875;
			found = true;
		}
		
		nm = "Tchernobog";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 2.5;
			if (damageType == "DashingBG") TOTALFactor = 2.5;
			if (damageType == "DashingSD") TOTALFactor = 2.5;
			if (damageType == "Fire") TOTALFactor = frandom(0.10,0.175);
			if (damageType == "Ice") TOTALFactor = 0.5;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.75;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 2.5;
			if (damageType == 'Chop') TOTALFactor = 1.375;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 0.125;
			if (damageType == 'Dust') TOTALFactor = 0.0;
			if (damageType == 'Zap') TOTALFactor = 3.25;
			if (damageType == 'Beats') TOTALFactor = 2.5;
			found = true;
		}
		
		nm = "ChrysalidPod";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.0;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "LavaPod";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.334;
			if (damageType == "Ice") TOTALFactor = 3.000;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.667;
			if (damageType == 'BRocket') TOTALFactor = 0.25;
			if (damageType == 'Spinner') TOTALFactor = 0.25;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 0.667;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 0.445;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "BatFamiliar";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.0;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "BloodRat";
		nn = "BloodRatBlack";
		no = "BloodRatGrey";
		np = "BloodRatWhite";
		if (ownername == nm ||
				ownername == nn ||
				ownername == no ||
				ownername == np)
		{
			if (damageType == "Fist") TOTALFactor = 0.4;
			if (damageType == "Kick") TOTALFactor = 2.5;
			if (damageType == "Dashing") TOTALFactor = 1.75;
			if (damageType == "DashingBG") TOTALFactor = 1.75;
			if (damageType == "DashingSD") TOTALFactor = 1.75;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 2.0;
			if (damageType == 'BRocket') TOTALFactor = 2.0;
			if (damageType == 'Spinner') TOTALFactor = 2.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 2.0;
			if (damageType == 'Dust') TOTALFactor = 5.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "SpiderMother";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 0.667;
			if (damageType == "Kick") TOTALFactor = 1.5;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = frandom(1.01,1.02);
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 0.5;
			if (damageType == 'CherryBomb') TOTALFactor = 1.45;
			if (damageType == 'BRocket') TOTALFactor = 1.6;
			if (damageType == 'Spinner') TOTALFactor = 1.6;
			if (damageType == 'Popper') TOTALFactor = 0.667;
			if (damageType == 'Bonk') TOTALFactor = 1.42;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "NewSpiderRed";
		nn = "NewRedSpider";
		no = "SpiderClimber";
		if (ownername == nm ||
				ownername == nn ||
				ownername == no)
		{
			if (damageType == "Fist") TOTALFactor = 0.667;
			if (damageType == "Kick") TOTALFactor = 1.5;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.5;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 2.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.75;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 2.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 0.75;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "SpiderGreen";
		nn = "GreenSpider";
		if (ownername == nm ||
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 0.667;
			if (damageType == "Kick") TOTALFactor = 1.5;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.35;
			if (damageType == "Ice") TOTALFactor = 1.25;
			if (damageType == "Suck") TOTALFactor = 2.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.334;
			if (damageType == 'BRocket') TOTALFactor = 1.25;
			if (damageType == 'Spinner') TOTALFactor = 1.25;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 2.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 0.75;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		
		if (dydudebug_actordmgdisplays) Console.Printf("[Blood] TOTALFactor: %.8f, damageType: %s", TOTALFactor, damageType);
		return TOTALFactor;
	}
	
	double GetBloodResistances2(int damage, Name damageType, out int newdamage, bool passive, Actor inflictor, Actor source, int flags)
	{
		if (dydudebug_actordmgdisplays) Console.Printf("[Blood (2)]");
		double TOTALFactor = 1.0;

		nm = "YellowSpider";
		nm = "SpiderYellow";
		if (ownername == nm ||
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 0.667;
			if (damageType == "Kick") TOTALFactor = 1.5;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.5;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 2.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.75;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 2.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 0.75;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "BlackSpider";
		nn = "SpiderBlack";
		if (ownername == nm ||
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 0.667;
			if (damageType == "Kick") TOTALFactor = 1.5;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.5;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 2.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.75;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 2.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 0.75;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "WhiteSpider";
		nn = "SpiderWhite";
		if (ownername == nm ||
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 0.667;
			if (damageType == "Kick") TOTALFactor = 1.5;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.5;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 2.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.75;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 2.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 0.75;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "BlueSpider";
		nn = "SpiderBlue";
		if (ownername == nm ||
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 0.667;
			if (damageType == "Kick") TOTALFactor = 1.5;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.5;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 2.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.75;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 2.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 0.75;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "CyanSpider";
		nn = "SpiderCyan";
		if (ownername == nm ||
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 0.667;
			if (damageType == "Kick") TOTALFactor = 1.5;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.5;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 2.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.75;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 2.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 0.75;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		nm = "PurpleSpider";
		nn = "SpiderPurple";
		if (ownername == nm ||
				ownername == nn)
		{
			if (damageType == "Fist") TOTALFactor = 0.667;
			if (damageType == "Kick") TOTALFactor = 1.5;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.5;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 2.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.75;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 2.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 0.75;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		
		if (dydudebug_actordmgdisplays) Console.Printf("[Blood] TOTALFactor: %.8f, damageType: %s", TOTALFactor, damageType);
		return TOTALFactor;
	}
	
	double GetMiscResistances1(int damage, Name damageType, out int newdamage, bool passive, Actor inflictor, Actor source, int flags)
	{
		if (dydudebug_actordmgdisplays) Console.Printf("[Misc1]");
		double TOTALFactor = 1.0;
		double temp2 = 1.0;
		/*
		nm = "";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Melee") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.0;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Melee") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Explosive") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 1.0;
			if (damageType == 'BRocket') temp2 = 1.0;
			if (damageType == 'Spinner') temp2 = 1.0;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		*/
		
		// BlooM's hybrid monsters and their vulnerabilities are taken from combining the factors of all component parts, then dividing the total by the # of components
		nm = "Cacoyle";
		nn = "Cacoyle_Variant";
		if (ownername == nm ||
				ownername == nn)
		{
			// Cacodemon - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.25;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.25;
			if (damageType == 'BRocket') TOTALFactor = 2.5;
			if (damageType == 'Spinner') TOTALFactor = 3.75;
			if (damageType == 'Popper') TOTALFactor = 0.25;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 5.0;
			if (damageType == 'Dust') TOTALFactor = 5.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Flesh Gargoyle - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = frandom(0.55,0.61); // Correlates to 'Fire' and 'Napalm' damagetypes, so randomize between both values. :V
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'BRocket') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Spinner') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Popper') temp2 = 2.5;
			if (damageType == 'Bonk') temp2 = 1.5; // Bonk can correlate to a 'Pitchfork' poke
			if (damageType == 'Cricket') temp2 = 2.0;
			if (damageType == 'Chop') temp2 = 1.5;
			if (damageType == 'Lead') temp2 = 0.8; // Correlates to 'SawedOff' DamageType
			if (damageType == 'Breakfast') temp2 = 0.775;
			if (damageType == 'Dust') temp2 = 1.5; // Are weak to Dust unlike GALgoyles are :P
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 2.5;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "GargoylSoul";
		if (ownername == nm)
		{
			// Lost Soul - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.334;
			if (damageType == "Ice") TOTALFactor = 3.001;
			if (damageType == "Suck") TOTALFactor = 15.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.25;
			if (damageType == 'BRocket') TOTALFactor = 0.5;
			if (damageType == 'Spinner') TOTALFactor = 1.25;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.25;
			if (damageType == 'Cricket') TOTALFactor = 2.5;
			if (damageType == 'Chop') TOTALFactor = 5.0;
			if (damageType == 'Lead') TOTALFactor = 0.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.75;
			if (damageType == 'Dust') TOTALFactor = 0.25;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Flesh Gargoyle - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = frandom(0.55,0.61); // Correlates to 'Fire' and 'Napalm' damagetypes, so randomize between both values. :V
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'BRocket') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Spinner') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Popper') temp2 = 2.5;
			if (damageType == 'Bonk') temp2 = 1.5; // Bonk can correlate to a 'Pitchfork' poke
			if (damageType == 'Cricket') temp2 = 2.0;
			if (damageType == 'Chop') temp2 = 1.5;
			if (damageType == 'Lead') temp2 = 0.8; // Correlates to 'SawedOff' DamageType
			if (damageType == 'Breakfast') temp2 = 0.775;
			if (damageType == 'Dust') temp2 = 1.5; // Are weak to Dust unlike GALgoyles are :P
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 2.5;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Elemental_Gargoyle";
		if (ownername == nm)
		{
			// Pain Elemental - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.5;
			if (damageType == "Ice") TOTALFactor = 1.75;
			if (damageType == "Suck") TOTALFactor = 7.5;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 2.5;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 5.0;
			if (damageType == 'Dust') TOTALFactor = 5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Flesh Gargoyle - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = frandom(0.55,0.61); // Correlates to 'Fire' and 'Napalm' damagetypes, so randomize between both values. :V
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'BRocket') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Spinner') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Popper') temp2 = 2.5;
			if (damageType == 'Bonk') temp2 = 1.5; // Bonk can correlate to a 'Pitchfork' poke
			if (damageType == 'Cricket') temp2 = 2.0;
			if (damageType == 'Chop') temp2 = 1.5;
			if (damageType == 'Lead') temp2 = 0.8; // Correlates to 'SawedOff' DamageType
			if (damageType == 'Breakfast') temp2 = 0.775;
			if (damageType == 'Dust') temp2 = 1.5; // Are weak to Dust unlike GALgoyles are :P
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 2.5;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Gargovile";
		nn = "Flying_Gargovile";
		if (ownername == nm ||
				ownername == nn)
		{
			// Archvile - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.1;
			if (damageType == "Ice") TOTALFactor = 5.0;
			if (damageType == "Suck") TOTALFactor = 3.75;
			if (damageType == 'CherryBomb') TOTALFactor = 0.25;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 1.5;
			if (damageType == 'Bonk') TOTALFactor = 2.5;
			if (damageType == 'Cricket') TOTALFactor = 5.0;
			if (damageType == 'Chop') TOTALFactor = 5.0;
			if (damageType == 'Lead') TOTALFactor = 1.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Flesh Gargoyle - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = frandom(0.55,0.61); // Correlates to 'Fire' and 'Napalm' damagetypes, so randomize between both values. :V
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'BRocket') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Spinner') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Popper') temp2 = 2.5;
			if (damageType == 'Bonk') temp2 = 1.5; // Bonk can correlate to a 'Pitchfork' poke
			if (damageType == 'Cricket') temp2 = 2.0;
			if (damageType == 'Chop') temp2 = 1.5;
			if (damageType == 'Lead') temp2 = 0.8; // Correlates to 'SawedOff' DamageType
			if (damageType == 'Breakfast') temp2 = 0.775;
			if (damageType == 'Dust') temp2 = 1.5; // Are weak to Dust unlike GALgoyles are :P
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 2.5;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "ArchZombie";
		if (ownername == nm)
		{
			// Archvile - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.1;
			if (damageType == "Ice") TOTALFactor = 5.0;
			if (damageType == "Suck") TOTALFactor = 3.75;
			if (damageType == 'CherryBomb') TOTALFactor = 0.25;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.5;
			if (damageType == 'Popper') TOTALFactor = 1.5;
			if (damageType == 'Bonk') TOTALFactor = 2.5;
			if (damageType == 'Cricket') TOTALFactor = 5.0;
			if (damageType == 'Chop') TOTALFactor = 5.0;
			if (damageType == 'Lead') TOTALFactor = 1.5;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Axe Zombie - Component #2
			if (damageType == "Fist") temp2 = 0.75;
			if (damageType == "Kick") temp2 = 0.75;
			if (damageType == "Dashing") temp2 = 0.75;
			if (damageType == "DashingBG") temp2 = 0.75;
			if (damageType == "DashingSD") temp2 = 0.75;
			if (damageType == "Fire") temp2 = frandom(3.35,3.5);
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 2.5;
			if (damageType == 'BRocket') temp2 = 2.25;
			if (damageType == 'Spinner') temp2 = 2.25;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 2.5;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.25;
			if (damageType == 'Beats') temp2 = 1.25;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "KingCacoyle";
		if (ownername == nm)
		{
			// Cacodemon - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.25;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.25;
			if (damageType == 'BRocket') TOTALFactor = 2.5;
			if (damageType == 'Spinner') TOTALFactor = 3.75;
			if (damageType == 'Popper') TOTALFactor = 0.25;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 5.0;
			if (damageType == 'Dust') TOTALFactor = 5.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Stone Gargoyle/Cheogh - Component #2
			if (damageType == "Fist") temp2 = 0.75;
			if (damageType == "Kick") temp2 = 0.75;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 0.0;
			if (damageType == "Ice") temp2 = 4.0;
			if (damageType == "Suck") temp2 = 0.0625;
			if (damageType == 'CherryBomb') temp2 = 0.0625;
			if (damageType == 'BRocket') temp2 = 0.25;
			if (damageType == 'Spinner') temp2 = 0.25;
			if (damageType == 'Popper') temp2 = 0.4375;
			if (damageType == 'Bonk') temp2 = 0.75;
			if (damageType == 'Cricket') temp2 = 0.5;
			if (damageType == 'Chop') temp2 = 0.25;
			if (damageType == 'Lead') temp2 = 4.0;
			if (damageType == 'Breakfast') temp2 = 0.125;
			if (damageType == 'Dust') temp2 = 0.0;
			if (damageType == 'Zap') temp2 = 2.5;
			if (damageType == 'Beats') temp2 = 0.125;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "CyberCheogh";
		if (ownername == nm)
		{
			// Cyberdemon - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.1;
			if (damageType == "Ice") TOTALFactor = 3.5;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.65;
			if (damageType == 'BRocket') TOTALFactor = 10;
			if (damageType == 'Spinner') TOTALFactor = 1.25;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Stone Gargoyle/Cheogh - Component #2
			if (damageType == "Fist") temp2 = 0.75;
			if (damageType == "Kick") temp2 = 0.75;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 0.0;
			if (damageType == "Ice") temp2 = 4.0;
			if (damageType == "Suck") temp2 = 0.0625;
			if (damageType == 'CherryBomb') temp2 = 0.0625;
			if (damageType == 'BRocket') temp2 = 0.25;
			if (damageType == 'Spinner') temp2 = 0.25;
			if (damageType == 'Popper') temp2 = 0.4375;
			if (damageType == 'Bonk') temp2 = 0.75;
			if (damageType == 'Cricket') temp2 = 0.5;
			if (damageType == 'Chop') temp2 = 0.25;
			if (damageType == 'Lead') temp2 = 4.0;
			if (damageType == 'Breakfast') temp2 = 0.125;
			if (damageType == 'Dust') temp2 = 0.0;
			if (damageType == 'Zap') temp2 = 2.5;
			if (damageType == 'Beats') temp2 = 0.125;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Sloth";
		if (ownername == nm)
		{
			// Cyberdemon - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.1;
			if (damageType == "Ice") TOTALFactor = 3.5;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.65;
			if (damageType == 'BRocket') TOTALFactor = 10;
			if (damageType == 'Spinner') TOTALFactor = 1.25;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// ? - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Melee") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Explosive") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 1.0;
			if (damageType == 'BRocket') temp2 = 1.0;
			if (damageType == 'Spinner') temp2 = 1.0;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Pinkberus";
		if (ownername == nm)
		{
			// Pinky - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.625;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 0.875;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.125;
			if (damageType == 'Cricket') TOTALFactor = 1.5;
			if (damageType == 'Chop') TOTALFactor = 0.625;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 2.5;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Cerberus - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = frandom(0.05,0.1);
			if (damageType == "Ice") temp2 = 1.625;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 2.25;
			if (damageType == 'BRocket') temp2 = 0.28125;
			if (damageType == 'Spinner') temp2 = 0.28125;
			if (damageType == 'Popper') temp2 = 0.5;
			if (damageType == 'Bonk') temp2 = 0.875;
			if (damageType == 'Cricket') temp2 = 0.9375;
			if (damageType == 'Chop') temp2 = 1.125;
			if (damageType == 'Lead') temp2 = 1.1875;
			if (damageType == 'Breakfast') temp2 = 0.775;
			if (damageType == 'Dust') temp2 = 0.5;
			if (damageType == 'Zap') temp2 = 1.25;
			if (damageType == 'Beats') temp2 = 1.6875;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "TchernoDemon";
		nn = "Cyberbog";
		if (ownername == nm ||
				ownername == nn)
		{
			// Cyberdemon - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.1;
			if (damageType == "Ice") TOTALFactor = 3.5;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.65;
			if (damageType == 'BRocket') TOTALFactor = 10;
			if (damageType == 'Spinner') TOTALFactor = 1.25;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Tchernobog - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 2.5;
			if (damageType == "DashingBG") temp2 = 2.5;
			if (damageType == "DashingSD") temp2 = 2.5;
			if (damageType == "Fire") temp2 = frandom(0.10,0.175);
			if (damageType == "Ice") temp2 = 0.5;
			if (damageType == "Suck") temp2 = 0.25;
			if (damageType == 'CherryBomb') temp2 = 0.75;
			if (damageType == 'BRocket') temp2 = 1.5;
			if (damageType == 'Spinner') temp2 = 1.5;
			if (damageType == 'Popper') temp2 = 2.5;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 2.5;
			if (damageType == 'Chop') temp2 = 1.375;
			if (damageType == 'Lead') temp2 = 0.5;
			if (damageType == 'Breakfast') temp2 = 0.125;
			if (damageType == 'Dust') temp2 = 0.0;
			if (damageType == 'Zap') temp2 = 3.25;
			if (damageType == 'Beats') temp2 = 2.5;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "HandMastermind";
		nn = "HandSlavedmind";
		if (ownername == nm ||
				ownername == nn)
		{
			// Spider Mastermind - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.1;
			if (damageType == "Ice") TOTALFactor = 3.5;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.65;
			if (damageType == 'BRocket') TOTALFactor = 10;
			if (damageType == 'Spinner') TOTALFactor = 1.25;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Hell Hand - Component #2
			if (damageType == "Fist") temp2 = 0.4;
			if (damageType == "Kick") temp2 = 2.5;
			if (damageType == "Dashing") temp2 = 1.5;
			if (damageType == "DashingBG") temp2 = 1.5;
			if (damageType == "DashingSD") temp2 = 1.5;
			if (damageType == "Fire") temp2 = 2.0; // It has a base 2x factor to fire
			if (damageType == "Ice") temp2 = 1.25;
			if (damageType == "Suck") temp2 = 15.0; // Goes down as fast as a Lost Soul, if not faster :V
			if (damageType == 'CherryBomb') temp2 = 1.5;
			if (damageType == 'BRocket') temp2 = 1.5;
			if (damageType == 'Spinner') temp2 = 1.5;
			if (damageType == 'Popper') temp2 = 1.15;
			if (damageType == 'Bonk') temp2 = 1.25;
			if (damageType == 'Cricket') temp2 = 1.25;
			if (damageType == 'Chop') temp2 = 1.5;
			if (damageType == 'Lead') temp2 = 1.25;
			if (damageType == 'Breakfast') temp2 = 1.25;
			if (damageType == 'Dust') temp2 = 0.1;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 0.5;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Cerbcubus";
		if (ownername == nm)
		{
			// Mancubus - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.667;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 0.5;
			if (damageType == 'CherryBomb') TOTALFactor = 2.0;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.75;
			if (damageType == 'Popper') TOTALFactor = 1.25;
			if (damageType == 'Bonk') TOTALFactor = 3.75;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 5.0;
			if (damageType == 'Lead') TOTALFactor = 1.25;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Cerberus - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = frandom(0.05,0.1);
			if (damageType == "Ice") temp2 = 1.625;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 2.25;
			if (damageType == 'BRocket') temp2 = 0.28125;
			if (damageType == 'Spinner') temp2 = 0.28125;
			if (damageType == 'Popper') temp2 = 0.5;
			if (damageType == 'Bonk') temp2 = 0.875;
			if (damageType == 'Cricket') temp2 = 0.9375;
			if (damageType == 'Chop') temp2 = 1.125;
			if (damageType == 'Lead') temp2 = 1.1875;
			if (damageType == 'Breakfast') temp2 = 0.775;
			if (damageType == 'Dust') temp2 = 0.5;
			if (damageType == 'Zap') temp2 = 1.25;
			if (damageType == 'Beats') temp2 = 1.6875;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "ShialMastermind";
		if (ownername == nm)
		{
			// Spider Mastermind - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.1;
			if (damageType == "Ice") TOTALFactor = 3.5;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.65;
			if (damageType == 'BRocket') TOTALFactor = 10;
			if (damageType == 'Spinner') TOTALFactor = 1.25;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Shial/Mother Spider - Component #2
			if (damageType == "Fist") temp2 = 0.667;
			if (damageType == "Kick") temp2 = 1.5;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = frandom(1.01,1.02);
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 0.5;
			if (damageType == 'CherryBomb') temp2 = 1.45;
			if (damageType == 'BRocket') temp2 = 1.6;
			if (damageType == 'Spinner') temp2 = 1.6;
			if (damageType == 'Popper') temp2 = 0.667;
			if (damageType == 'Bonk') temp2 = 1.42;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 0.5;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.5;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Eeldercubus";
		if (ownername == nm)
		{
			// Mancubus - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.667;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 0.5;
			if (damageType == 'CherryBomb') TOTALFactor = 2.0;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.75;
			if (damageType == 'Popper') TOTALFactor = 1.25;
			if (damageType == 'Bonk') TOTALFactor = 3.75;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 5.0;
			if (damageType == 'Lead') TOTALFactor = 1.25;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Gill Beast - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.25;
			if (damageType == "Ice") temp2 = 1.25;
			if (damageType == "Suck") temp2 = 0.375;
			if (damageType == 'CherryBomb') temp2 = 1.3;
			if (damageType == 'BRocket') temp2 = 1.3;
			if (damageType == 'Spinner') temp2 = 1.3;
			if (damageType == 'Popper') temp2 = 1.2;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.167;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 2.334;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 0.025;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Jojo";
		if (ownername == nm)
		{
			// Chaingun Guy - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.5;
			if (damageType == "Ice") TOTALFactor = 1.167;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.25;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.125;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Fanatic - Component 2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 0.4;
			if (damageType == 'BRocket') temp2 = 0.4;
			if (damageType == 'Spinner') temp2 = 0.4;
			if (damageType == 'Popper') temp2 = 0.70;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "HoundBaronOfHell";
		if (ownername == nm)
		{
			// Baron of Hell - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.5;
			if (damageType == "Ice") TOTALFactor = 2.0;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 3.75;
			if (damageType == 'BRocket') TOTALFactor = 2.5;
			if (damageType == 'Spinner') TOTALFactor = 2.5;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Hellhound - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = frandom(0.0,0.4);
			if (damageType == "Ice") temp2 = 2.25;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 0.125;
			if (damageType == 'BRocket') temp2 = 0.125;
			if (damageType == 'Spinner') temp2 = 0.125;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.25;
			if (damageType == 'Cricket') temp2 = 1.125;
			if (damageType == 'Chop') temp2 = 1.75;
			if (damageType == 'Lead') temp2 = 1.375;
			if (damageType == 'Breakfast') temp2 = 0.55;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.5;
			if (damageType == 'Beats') temp2 = 3.75;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Arachnoid";
		if (ownername == nm)
		{
			// Arachnotron - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.334;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.875;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 0.625;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.5;
			if (damageType == 'Dust') TOTALFactor = 5;
			if (damageType == 'Zap') TOTALFactor = 1.5;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Mother Spider - Component #2
			if (damageType == "Fist") temp2 = 0.667;
			if (damageType == "Kick") temp2 = 1.5;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = frandom(1.01,1.02);
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 0.5;
			if (damageType == 'CherryBomb') temp2 = 1.45;
			if (damageType == 'BRocket') temp2 = 1.6;
			if (damageType == 'Spinner') temp2 = 1.6;
			if (damageType == 'Popper') temp2 = 0.667;
			if (damageType == 'Bonk') temp2 = 1.42;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 0.5;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.5;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Green_Arachnopod";
		if (ownername == nm)
		{
			// Arachnotron - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.334;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.875;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 0.625;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.5;
			if (damageType == 'Dust') TOTALFactor = 5;
			if (damageType == 'Zap') TOTALFactor = 1.5;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Chrystalis Pod - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 1.0;
			if (damageType == 'BRocket') temp2 = 1.0;
			if (damageType == 'Spinner') temp2 = 1.0;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Magma_Arachnopod";
		if (ownername == nm)
		{
			// Arachnotron - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.334;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.875;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 0.625;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.5;
			if (damageType == 'Dust') TOTALFactor = 5;
			if (damageType == 'Zap') TOTALFactor = 1.5;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Magma Pod - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 0.334;
			if (damageType == "Ice") temp2 = 3.000;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 0.667;
			if (damageType == 'BRocket') temp2 = 0.25;
			if (damageType == 'Spinner') temp2 = 0.25;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 0.667;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 0.445;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Ice_Arachnopod";
		if (ownername == nm)
		{
			// Arachnotron - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.334;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.875;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 0.625;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.5;
			if (damageType == 'Dust') TOTALFactor = 5;
			if (damageType == 'Zap') TOTALFactor = 1.5;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// ??? Pod - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 3.00;
			if (damageType == "Ice") temp2 = 0.334;
			if (damageType == "Suck") temp2 = 0.125;
			if (damageType == 'CherryBomb') temp2 = 2.00;
			if (damageType == 'BRocket') temp2 = 1.5;
			if (damageType == 'Spinner') temp2 = 1.5;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.75;
			if (damageType == 'Cricket') temp2 = 1.5;
			if (damageType == 'Chop') temp2 = 0.334;
			if (damageType == 'Lead') temp2 = 0.25;
			if (damageType == 'Breakfast') temp2 = 0.445;
			if (damageType == 'Dust') temp2 = 0.25;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "RomeroTron";
		if (ownername == nm)
		{
			// Arachnotron - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.334;
			if (damageType == "Suck") TOTALFactor = 0.25;
			if (damageType == 'CherryBomb') TOTALFactor = 0.875;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 0.625;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.5;
			if (damageType == 'Dust') TOTALFactor = 5;
			if (damageType == 'Zap') TOTALFactor = 1.5;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// ??? - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Melee") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Explosive") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 1.0;
			if (damageType == 'BRocket') temp2 = 1.0;
			if (damageType == 'Spinner') temp2 = 1.0;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "HellButcher";
		nn = "HellButcherAlt";
		if (ownername == nm ||
				ownername == nn)
		{
			// Baron of Hell - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.5;
			if (damageType == "Ice") TOTALFactor = 2.0;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 3.75;
			if (damageType == 'BRocket') TOTALFactor = 2.5;
			if (damageType == 'Spinner') TOTALFactor = 2.5;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Bloated Butcher - Component #2
			if (damageType == "Fist") temp2 = 0.5;
			if (damageType == "Kick") temp2 = 0.5;
			if (damageType == "Dashing") temp2 = 0.75;
			if (damageType == "DashingBG") temp2 = 0.75;
			if (damageType == "DashingSD") temp2 = 0.75;
			if (damageType == "Fire") temp2 = frandom(frandom(2.0,3.0),6.0);
			if (damageType == "Ice") temp2 = 0.25;
			if (damageType == "Suck") temp2 = 0.5;
			if (damageType == 'CherryBomb') temp2 = 4.2;
			if (damageType == 'BRocket') temp2 = 2.4;
			if (damageType == 'Spinner') temp2 = 2.4;
			if (damageType == 'Popper') temp2 = 0.75;
			if (damageType == 'Bonk') temp2 = 0.5;
			if (damageType == 'Cricket') temp2 = 0.5;
			if (damageType == 'Chop') temp2 = 2.5;
			if (damageType == 'Lead') temp2 = 0.25;
			if (damageType == 'Breakfast') temp2 = 1.75;
			if (damageType == 'Dust') temp2 = 0.25;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "HoundKnightOfHell";
		if (ownername == nm)
		{
			// Knight of Hell - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.5;
			if (damageType == "Ice") TOTALFactor = 2.0;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 3.75;
			if (damageType == 'BRocket') TOTALFactor = 2.5;
			if (damageType == 'Spinner') TOTALFactor = 2.5;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Stone Beast - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 2.0;
			if (damageType == "DashingBG") temp2 = 2.0;
			if (damageType == "DashingSD") temp2 = 2.0;
			if (damageType == "Fire") temp2 = 0.0;
			if (damageType == "Ice") temp2 = 4.0;
			if (damageType == "Suck") temp2 = 0.25;
			if (damageType == 'CherryBomb') temp2 = 0.05;
			if (damageType == 'BRocket') temp2 = 0.625;
			if (damageType == 'Spinner') temp2 = 0.625;
			if (damageType == 'Popper') temp2 = 0.875;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 0.25;
			if (damageType == 'Lead') temp2 = 4.0;
			if (damageType == 'Breakfast') temp2 = 0.5;
			if (damageType == 'Dust') temp2 = 0.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 0.5;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "ZombaronOfHell";
		nn = "AxeZombaronOfHell";
		no = "BuriedZombaronOfHell";
		np = "BuriedAxeZombaronOfHell";
		if (ownername == nm ||
				ownername == nn ||
				ownername == no ||
				ownername == np)
		{
			// Baron of Hell - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.5;
			if (damageType == "Ice") TOTALFactor = 2.0;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 3.75;
			if (damageType == 'BRocket') TOTALFactor = 2.5;
			if (damageType == 'Spinner') TOTALFactor = 2.5;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Axe Zombie - Component #2
			if (damageType == "Fist") temp2 = 0.75;
			if (damageType == "Kick") temp2 = 0.75;
			if (damageType == "Dashing") temp2 = 0.75;
			if (damageType == "DashingBG") temp2 = 0.75;
			if (damageType == "DashingSD") temp2 = 0.75;
			if (damageType == "Fire") temp2 = frandom(3.35,3.5);
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 2.5;
			if (damageType == 'BRocket') temp2 = 2.25;
			if (damageType == 'Spinner') temp2 = 2.25;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 2.5;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.25;
			if (damageType == 'Beats') temp2 = 1.25;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "WereWolfOfHell";
		nn = "WereWolfOfHellAlt";
		if (ownername == nm ||
				ownername == nn)
		{
			// Baron of Hell - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.5;
			if (damageType == "Ice") TOTALFactor = 2.0;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 3.75;
			if (damageType == 'BRocket') TOTALFactor = 2.5;
			if (damageType == 'Spinner') TOTALFactor = 2.5;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Stone Beast - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 2.0;
			if (damageType == "DashingBG") temp2 = 2.0;
			if (damageType == "DashingSD") temp2 = 2.0;
			if (damageType == "Fire") temp2 = 0.0;
			if (damageType == "Ice") temp2 = 4.0;
			if (damageType == "Suck") temp2 = 0.25;
			if (damageType == 'CherryBomb') temp2 = 0.05;
			if (damageType == 'BRocket') temp2 = 0.625;
			if (damageType == 'Spinner') temp2 = 0.625;
			if (damageType == 'Popper') temp2 = 0.875;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 0.25;
			if (damageType == 'Lead') temp2 = 4.0;
			if (damageType == 'Breakfast') temp2 = 0.5;
			if (damageType == 'Dust') temp2 = 0.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 0.5;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Cvltimp";
		nn = "CvltimpAlt";
		if (ownername == nm ||
				ownername == nn)
		{
			// Imp - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.4;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.6;
			if (damageType == 'BRocket') TOTALFactor = 1.125;
			if (damageType == 'Spinner') TOTALFactor = 0.8;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.5;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Cultist - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = frandom(0.7,1.0);
			if (damageType == 'BRocket') temp2 = frandom(0.7,1.0);
			if (damageType == 'Spinner') temp2 = frandom(0.7,1.0);
			if (damageType == 'Popper') temp2 = frandom(0.7,0.85);
			if (damageType == 'Cricket') temp2 = frandom(0.85,1.0);
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "DeepOne_Base";
		if (ownername == nm)
		{
			// ? - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Melee") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.0;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Gill Beast - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.5;
			if (damageType == "Ice") temp2 = 1.5;
			if (damageType == "Suck") temp2 = 0.75;
			if (damageType == 'CherryBomb') temp2 = 2.2;
			if (damageType == 'BRocket') temp2 = 1.6;
			if (damageType == 'Spinner') temp2 = 1.6;
			if (damageType == 'Popper') temp2 = 1.4;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.334;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 0.25;
			if (damageType == 'Dust') temp2 = 3.667;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 0.125;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "DeepOneShot";
		if (ownername == nm)
		{
			// Shotgun Guy - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.34;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.5;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.25;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Gill Beast - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.5;
			if (damageType == "Ice") temp2 = 1.5;
			if (damageType == "Suck") temp2 = 0.75;
			if (damageType == 'CherryBomb') temp2 = 2.2;
			if (damageType == 'BRocket') temp2 = 1.6;
			if (damageType == 'Spinner') temp2 = 1.6;
			if (damageType == 'Popper') temp2 = 1.4;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.334;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 0.25;
			if (damageType == 'Dust') temp2 = 3.667;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 0.125;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "DeepOneChain";
		if (ownername == nm)
		{
			// Chaingun Guy - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.34;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.5;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.25;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Gill Beast - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.5;
			if (damageType == "Ice") temp2 = 1.5;
			if (damageType == "Suck") temp2 = 0.75;
			if (damageType == 'CherryBomb') temp2 = 2.2;
			if (damageType == 'BRocket') temp2 = 1.6;
			if (damageType == 'Spinner') temp2 = 1.6;
			if (damageType == 'Popper') temp2 = 1.4;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.334;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 0.25;
			if (damageType == 'Dust') temp2 = 3.667;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 0.125;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "DeepOneTri";
		if (ownername == nm)
		{
			// ? - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.34;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.5;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.25;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Gill Beast - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.5;
			if (damageType == "Ice") temp2 = 1.5;
			if (damageType == "Suck") temp2 = 0.75;
			if (damageType == 'CherryBomb') temp2 = 2.2;
			if (damageType == 'BRocket') temp2 = 1.6;
			if (damageType == 'Spinner') temp2 = 1.6;
			if (damageType == 'Popper') temp2 = 1.4;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.334;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 0.25;
			if (damageType == 'Dust') temp2 = 3.667;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 0.125;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "DeepOneTri";
		if (ownername == nm)
		{
			// Shotgun Guy - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.34;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.5;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.25;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Gill Beast - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.5;
			if (damageType == "Ice") temp2 = 1.5;
			if (damageType == "Suck") temp2 = 0.75;
			if (damageType == 'CherryBomb') temp2 = 2.2;
			if (damageType == 'BRocket') temp2 = 1.6;
			if (damageType == 'Spinner') temp2 = 1.6;
			if (damageType == 'Popper') temp2 = 1.4;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.334;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 0.25;
			if (damageType == 'Dust') temp2 = 3.667;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 0.125;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "DemonHound";
		nn = "DemonHoundAlt";
		no = "SpectreHound";
		np = "SpectreHoundAlt";
		if (ownername == nm ||
				ownername == nn ||
				ownername == no ||
				ownername == np)
		{
			// Pinky/Spectre - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.625;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 0.875;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.125;
			if (damageType == 'Cricket') TOTALFactor = 1.5;
			if (damageType == 'Chop') TOTALFactor = 0.625;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 2.5;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Hellhound - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = frandom(0.0,0.4);
			if (damageType == "Ice") temp2 = 2.25;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 0.125;
			if (damageType == 'BRocket') temp2 = 0.125;
			if (damageType == 'Spinner') temp2 = 0.125;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.25;
			if (damageType == 'Cricket') temp2 = 1.125;
			if (damageType == 'Chop') temp2 = 1.75;
			if (damageType == 'Lead') temp2 = 1.375;
			if (damageType == 'Breakfast') temp2 = 0.55;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.5;
			if (damageType == 'Beats') temp2 = 3.75;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "GargoDemon";
		nn = "PinkGargoyle";
		if (ownername == nm ||
				ownername == nn)
		{
			// Pinky/Spectre - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.625;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 0.875;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.125;
			if (damageType == 'Cricket') TOTALFactor = 1.5;
			if (damageType == 'Chop') TOTALFactor = 0.625;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 2.5;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Flesh Gargoyle - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = frandom(0.55,0.61); // Correlates to 'Fire' and 'Napalm' damagetypes, so randomize between both values. :V
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'BRocket') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Spinner') temp2 = 0.55; // Correlates to 'Dynamite' DamageType
			if (damageType == 'Popper') temp2 = 2.5;
			if (damageType == 'Bonk') temp2 = 1.5; // Bonk can correlate to a 'Pitchfork' poke
			if (damageType == 'Cricket') temp2 = 2.0;
			if (damageType == 'Chop') temp2 = 1.5;
			if (damageType == 'Lead') temp2 = 0.8; // Correlates to 'SawedOff' DamageType
			if (damageType == 'Breakfast') temp2 = 0.775;
			if (damageType == 'Dust') temp2 = 1.5; // Are weak to Dust unlike GALgoyles are :P
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 2.5;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Eelcubus";
		nn = "Gillcubus";
		if (ownername == nm ||
				ownername == nn)
		{
			// Mancubus - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.667;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 0.5;
			if (damageType == 'CherryBomb') TOTALFactor = 2.0;
			if (damageType == 'BRocket') TOTALFactor = 1.5;
			if (damageType == 'Spinner') TOTALFactor = 1.75;
			if (damageType == 'Popper') TOTALFactor = 1.25;
			if (damageType == 'Bonk') TOTALFactor = 3.75;
			if (damageType == 'Cricket') TOTALFactor = 0.5;
			if (damageType == 'Chop') TOTALFactor = 5.0;
			if (damageType == 'Lead') TOTALFactor = 1.25;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Gill Beast - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.5;
			if (damageType == "Ice") temp2 = 1.5;
			if (damageType == "Suck") temp2 = 0.75;
			if (damageType == 'CherryBomb') temp2 = 2.2;
			if (damageType == 'BRocket') temp2 = 1.6;
			if (damageType == 'Spinner') temp2 = 1.6;
			if (damageType == 'Popper') temp2 = 1.4;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.334;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 0.25;
			if (damageType == 'Dust') temp2 = 3.667;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 0.125;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Fanatic_Chaingunner";
		nn = "Fanatic_ChaingunnerAlt";
		if (ownername == nm ||
				ownername == nn)
		{
			// Chaingun Guy - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.34;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.5;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.25;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Fanatic - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 0.7;
			if (damageType == 'BRocket') temp2 = 0.7;
			if (damageType == 'Spinner') temp2 = 0.7;
			if (damageType == 'Popper') temp2 = 0.85;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Ghost_Revenant";
		nn = "Ghost_Revenant_Alt";
		no = "Shielded_Ghost_Revenant";
		np = "Shielded_Ghost_Revenant_Alt";
		nq = "GhostRevenantTerrain";
		nr = "GhostRevenantTerrainAlt";
		if (ownername == nm ||
				ownername == nn ||
				ownername == no ||
				ownername == np ||
				ownername == nr ||
				ownername == nq)
		{
			// Revenant - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.25;
			if (damageType == "Ice") TOTALFactor = 1.75;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.125;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 0.75;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 0.5;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.5;
			if (damageType == 'Beats') TOTALFactor = 0.75;
			
			// Phantasm - Component #2
			if (damageType == "Fist") temp2 = 5.0;
			if (damageType == "Kick") temp2 = 5.0;
			if (damageType == "Dashing") temp2 = 7.5;
			if (damageType == "DashingBG") temp2 = 7.5;
			if (damageType == "DashingSD") temp2 = 7.5;
			if (damageType == "Fire") temp2 = 0.125;
			if (damageType == "Ice") temp2 = 0.125;
			if (damageType == "Suck") temp2 = 5.0;
			if (damageType == 'CherryBomb') temp2 = 0.625;
			if (damageType == 'BRocket') temp2 = 0.625;
			if (damageType == 'Spinner') temp2 = 0.625;
			if (damageType == 'Popper') temp2 = 0.625;
			if (damageType == 'Bonk') temp2 = 0.25;
			if (damageType == 'Cricket') temp2 = 0.25;
			if (damageType == 'Chop') temp2 = 0.125;
			if (damageType == 'Lead') temp2 = frandom(3.75,6.25);
			if (damageType == 'Breakfast') temp2 = 0.25;
			if (damageType == 'Dust') temp2 = 0.125;
			if (damageType == 'Zap') temp2 = 12.5;
			if (damageType == 'Beats') temp2 = 1.25;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "RevenantMoron";
		nm = "RevenantMoronAlt";
		nm = "RevenantMoronAlt2";
		if (ownername == nm ||
				ownername == nn)
		{
			// Revenant - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.25;
			if (damageType == "Ice") TOTALFactor = 1.75;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.125;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 0.75;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 0.5;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.5;
			if (damageType == 'Beats') TOTALFactor = 0.75;
			
			// ? - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Melee") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Explosive") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 1.0;
			if (damageType == 'BRocket') temp2 = 1.0;
			if (damageType == 'Spinner') temp2 = 1.0;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "Ghoul1";
		nn = "Ghoul2";
		no = "Ghoul3";
		np = "Ghoul4";
		nq = "Ghoul5";
		nr = "Ghoul6";
		ns = "BuriedGhoul1";
		nt = "BuriedGhoul2";
		nu = "BuriedGhoul3";
		nv = "BuriedGhoul4";
		nw = "BuriedGhoul5";
		nx = "BuriedGhoul6";
		ny = "FastBuriedGhoul1";
		nz = "FastBuriedGhoul2";
		na = "FastBuriedGhoul3";
		nb = "FastBuriedGhoul4";
		nc = "FastBuriedGhoul5";
		nd = "FastBuriedGhoul6";
		if (ownername == nm ||
				ownername == nn ||
				ownername == no ||
				ownername == np ||
				ownername == nr ||
				ownername == nq ||
				ownername == ns ||
				ownername == nt ||
				ownername == nu ||
				ownername == nv ||
				ownername == nw ||
				ownername == nx ||
				ownername == ny ||
				ownername == nz ||
				ownername == na ||
				ownername == nb ||
				ownername == nc ||
				ownername == nd)
		{
			// Zombieman/Shotgunner/Marine - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.34;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == "CherryBomb") TOTALFactor = 1.5;
			if (damageType == "BRocket") TOTALFactor = 1.0;
			if (damageType == "Spinner") TOTALFactor = 1.0;
			if (damageType == "Popper") TOTALFactor = 1.0;
			if (damageType == "Bonk") TOTALFactor = 1.0;
			if (damageType == "Cricket") TOTALFactor = 1.0;
			if (damageType == "Chop") TOTALFactor = 1.25;
			if (damageType == "Lead") TOTALFactor = 1.0;
			if (damageType == "Breakfast") TOTALFactor = 1.0;
			if (damageType == "Dust") TOTALFactor = 1.0;
			if (damageType == "Zap") TOTALFactor = 1.0;
			if (damageType == "Beats") TOTALFactor = 1.0;
			
			// Axe Zombie - Component #2
			if (damageType == "Fist") temp2 = 0.75;
			if (damageType == "Kick") temp2 = 0.75;
			if (damageType == "Dashing") temp2 = 0.75;
			if (damageType == "DashingBG") temp2 = 0.75;
			if (damageType == "DashingSD") temp2 = 0.75;
			if (damageType == "Fire") temp2 = frandom(3.35,3.5);
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 2.5;
			if (damageType == 'BRocket') temp2 = 2.25;
			if (damageType == 'Spinner') temp2 = 2.25;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 2.5;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.25;
			if (damageType == 'Beats') temp2 = 1.25;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "RevenantMime";
		nn = "RevenantMimeAlt";
		no = "RevenantMimeAlt2";
		if (ownername == nm ||
				ownername == nn ||
				ownername == no)
		{
			// Revenant - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.25;
			if (damageType == "Ice") TOTALFactor = 1.75;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.125;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 0.75;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 0.5;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.5;
			if (damageType == 'Beats') TOTALFactor = 0.75;
			
			// ? - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Melee") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Explosive") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 1.0;
			if (damageType == 'BRocket') temp2 = 1.0;
			if (damageType == 'Spinner') temp2 = 1.0;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "NeoCvltist_Base";
		nn = "Apocalyptic_NeoCvltist";
		no = "NeoCvltist";
		if (ownername == nm ||
				ownername == nn ||
				ownername == no)
		{
			// Imp - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.4;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.6;
			if (damageType == 'BRocket') TOTALFactor = 1.125;
			if (damageType == 'Spinner') TOTALFactor = 0.8;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.5;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Cultist - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = frandom(0.7,1.0);
			if (damageType == 'BRocket') temp2 = frandom(0.7,1.0);
			if (damageType == 'Spinner') temp2 = frandom(0.7,1.0);
			if (damageType == 'Popper') temp2 = frandom(0.7,0.85);
			if (damageType == 'Cricket') temp2 = frandom(0.85,1.0);
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "ShotgunMonk";
		if (ownername == nm)
		{
			// Shotgun Guy - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 2.0;
			if (damageType == "Ice") TOTALFactor = 1.34;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.5;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.25;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Cultist - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = frandom(0.7,1.0);
			if (damageType == 'BRocket') temp2 = frandom(0.7,1.0);
			if (damageType == 'Spinner') temp2 = frandom(0.7,1.0);
			if (damageType == 'Popper') temp2 = frandom(0.7,0.85);
			if (damageType == 'Cricket') temp2 = frandom(0.85,1.0);
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "PossessedNeoCultist";
		nn = "PossessedApocalypticNeoCultist";
		if (ownername == nm ||
				ownername == nn)
		{
			// Imp - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.4;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.6;
			if (damageType == 'BRocket') TOTALFactor = 1.125;
			if (damageType == 'Spinner') TOTALFactor = 0.8;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.5;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Cultist - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = frandom(0.7,1.0);
			if (damageType == 'BRocket') temp2 = frandom(0.7,1.0);
			if (damageType == 'Spinner') temp2 = frandom(0.7,1.0);
			if (damageType == 'Popper') temp2 = frandom(0.7,0.85);
			if (damageType == 'Cricket') temp2 = frandom(0.85,1.0);
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "RatDemon_Brown";
		nn = "RatDemon_Grey";
		no = "RatDemon_Black";
		np = "RatDemon_White";
		if (ownername == nm ||
				ownername == nn ||
				ownername == no ||
				ownername == np)
		{
			// Pinky - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.75;
			if (damageType == "Ice") TOTALFactor = 1.625;
			if (damageType == "Suck") TOTALFactor = 0.75;
			if (damageType == 'CherryBomb') TOTALFactor = 0.875;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.125;
			if (damageType == 'Cricket') TOTALFactor = 1.5;
			if (damageType == 'Chop') TOTALFactor = 0.625;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 2.5;
			if (damageType == 'Dust') TOTALFactor = 1.5;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Rat - Component #2
			if (damageType == "Fist") temp2 = 0.4;
			if (damageType == "Kick") temp2 = 2.5;
			if (damageType == "Dashing") temp2 = 1.75;
			if (damageType == "DashingBG") temp2 = 1.75;
			if (damageType == "DashingSD") temp2 = 1.75;
			if (damageType == "Fire") temp2 = 2.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = 2.0;
			if (damageType == 'BRocket') temp2 = 2.0;
			if (damageType == 'Spinner') temp2 = 2.0;
			if (damageType == 'Popper') temp2 = 1.0;
			if (damageType == 'Bonk') temp2 = 1.0;
			if (damageType == 'Cricket') temp2 = 1.0;
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 2.0;
			if (damageType == 'Dust') temp2 = 5.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		nm = "ZombImp1";
		nn = "ZombImp2";
		no = "ZombImp3";
		np = "ZombImp4";
		nq = "ZombImp5";
		nr = "BuriedZombImp1";
		ns = "BuriedZombImp2";
		nt = "BuriedZombImp3";
		nu = "BuriedZombImp4";
		nv = "BuriedZombImp5";
		if (ownername == nm ||
				ownername == nn ||
				ownername == no ||
				ownername == np ||
				ownername == nq ||
				ownername == nr ||
				ownername == ns ||
				ownername == nt ||
				ownername == nu ||
				ownername == nv)
		{
			// Imp - Component #1
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 0.4;
			if (damageType == "Ice") TOTALFactor = 2.5;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.6;
			if (damageType == 'BRocket') TOTALFactor = 1.125;
			if (damageType == 'Spinner') TOTALFactor = 0.8;
			if (damageType == 'Popper') TOTALFactor = 2.5;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.5;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			
			// Cultist - Component #2
			if (damageType == "Fist") temp2 = 1.0;
			if (damageType == "Kick") temp2 = 1.0;
			if (damageType == "Dashing") temp2 = 1.0;
			if (damageType == "DashingBG") temp2 = 1.0;
			if (damageType == "DashingSD") temp2 = 1.0;
			if (damageType == "Fire") temp2 = 1.0;
			if (damageType == "Ice") temp2 = 1.0;
			if (damageType == "Suck") temp2 = 1.0;
			if (damageType == 'CherryBomb') temp2 = frandom(0.7,1.0);
			if (damageType == 'BRocket') temp2 = frandom(0.7,1.0);
			if (damageType == 'Spinner') temp2 = frandom(0.7,1.0);
			if (damageType == 'Popper') temp2 = frandom(0.7,0.85);
			if (damageType == 'Cricket') temp2 = frandom(0.85,1.0);
			if (damageType == 'Chop') temp2 = 1.0;
			if (damageType == 'Lead') temp2 = 1.0;
			if (damageType == 'Breakfast') temp2 = 1.0;
			if (damageType == 'Dust') temp2 = 1.0;
			if (damageType == 'Zap') temp2 = 1.0;
			if (damageType == 'Beats') temp2 = 1.0;
			found = true;
			TOTALFactor += temp2;
			TOTALFactor /= 2;
		}
		
		if (dydudebug_actordmgdisplays) Console.Printf("[Misc1] TOTALFactor: %.8f, damageType: %s", TOTALFactor, damageType);
		return TOTALFactor;
	}
	
	double GetMiscResistances2(int damage, Name damageType, out int newdamage, bool passive, Actor inflictor, Actor source, int flags)
	{
		if (dydudebug_actordmgdisplays) Console.Printf("[Misc2]");
		double TOTALFactor = 1.0;
		/*
		nm = "";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 1.0;
			if (damageType == "Kick") TOTALFactor = 1.0;
			if (damageType == "Dashing") TOTALFactor = 1.0;
			if (damageType == "DashingBG") TOTALFactor = 1.0;
			if (damageType == "DashingSD") TOTALFactor = 1.0;
			if (damageType == "Explosive") TOTALFactor = 1.0;
			if (damageType == "Fire") TOTALFactor = 1.0;
			if (damageType == "Ice") TOTALFactor = 1.0;
			if (damageType == "Suck") TOTALFactor = 1.0;
			if (damageType == 'CherryBomb') TOTALFactor = 1.0;
			if (damageType == 'BRocket') TOTALFactor = 1.0;
			if (damageType == 'Spinner') TOTALFactor = 1.0;
			if (damageType == 'Popper') TOTALFactor = 1.0;
			if (damageType == 'Bonk') TOTALFactor = 1.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 1.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 1.0;
			if (damageType == 'Dust') TOTALFactor = 1.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 1.0;
			found = true;
		}
		*/

		nm = "ChtonBloom";
		if (ownername == nm)
		{
			if (damageType == "Fist") TOTALFactor = 0.25;
			if (damageType == "Kick") TOTALFactor = 0.25;
			if (damageType == "Dashing") TOTALFactor = 0.25;
			if (damageType == "DashingBG") TOTALFactor = 0.25;
			if (damageType == "DashingSD") TOTALFactor = 0.25;
			if (damageType == "Explosive") TOTALFactor = 0.25;
			if (damageType == "Fire") TOTALFactor = 0.0;
			if (damageType == "Ice") TOTALFactor = 5.0;
			if (damageType == "Suck") TOTALFactor = 0.0;
			if (damageType == 'CherryBomb') TOTALFactor = 0.0;
			if (damageType == 'BRocket') TOTALFactor = 0.0;
			if (damageType == 'Spinner') TOTALFactor = 0.0;
			if (damageType == 'Popper') TOTALFactor = 10.0;
			if (damageType == 'Bonk') TOTALFactor = 0.0;
			if (damageType == 'Cricket') TOTALFactor = 1.0;
			if (damageType == 'Chop') TOTALFactor = 0.0;
			if (damageType == 'Lead') TOTALFactor = 1.0;
			if (damageType == 'Breakfast') TOTALFactor = 10.0;
			if (damageType == 'Dust') TOTALFactor = 0.0;
			if (damageType == 'Zap') TOTALFactor = 1.0;
			if (damageType == 'Beats') TOTALFactor = 10.0;
			found = true;
		}
		
		if (dydudebug_actordmgdisplays) Console.Printf("[Misc2] TOTALFactor: %.8f, damageType: %s", TOTALFactor, damageType);
		return TOTALFactor;
	}
	
	
	//*************************************
	actor prevtarget;
	actor prevmaster;
	actor prevtracer;
	state prevstate;
	override void Tick()
	{
		super.Tick();
		prevtarget = null;
		if (owner) 
		{
			if (owner.target) prevtarget = owner.target;
			if (owner.tracer) prevtracer = owner.tracer;
			if (owner.master) prevmaster = owner.master;
		}
	}
	
	override void ModifyDamage(int damage, Name damageType, out int newdamage, bool passive, Actor inflictor, Actor source, int flags)
	{
		bool surprisehit;
		if (owner)
		{
			if (!owner.bISMONSTER) Destroy();
			
			ownername = owner.GetClassName();
			if (passive && damage > 0) // If the owner [usually the player] of the item is the DEFENDER
			{
				if ((dydudebug_actordmgdisplays || dydudebug_defensebuffs)) Console.Printf("\c[sapphire]CompatVulnItem\c-: pre-damage: %d, damagetype: %s", damage, damageType);
				double TOTALFactor = 1.00;
				//
				found = false;
				if (!found) TOTALFactor *= GetDoomResistances(damage, damageType, newdamage, passive, inflictor, source, flags);
				if (!found) TOTALFactor *= GetBloodResistances1(damage, damageType, newdamage, passive, inflictor, source, flags);
				if (!found) TOTALFactor *= GetBloodResistances2(damage, damageType, newdamage, passive, inflictor, source, flags);
				if (!found) TOTALFactor *= GetMiscResistances1(damage, damageType, newdamage, passive, inflictor, source, flags);
				if (!found) TOTALFactor *= GetMiscResistances2(damage, damageType, newdamage, passive, inflictor, source, flags);
						
				newdamage = max(0, ApplyDamageFactors(GetClass(), damageType, damage, damage * TOTALFactor));
				lastTOTALFactor = TOTALFactor;
				if ((dydudebug_actordmgdisplays || dydudebug_defensebuffs)) Console.Printf("\c[sapphire]CompatVulnItem\c- (%s): post-damage: %d, damagetype: %s, TOTALFactor: %.8f", ownername, newdamage, damageType, TOTALFactor);
				//
				if ((dydudebug_actordmgdisplays || dydudebug_defensebuffs) && source) Console.Printf("(source: \c[green]%p\c-) %s", source, source.GetClassName());
				if ((dydudebug_actordmgdisplays || dydudebug_defensebuffs) && inflictor) Console.Printf("(inflictor: \c[green]%p\c-) %s", inflictor, inflictor.GetClassName());
				if ((dydudebug_actordmgdisplays || dydudebug_defensebuffs) && prevtarget) Console.Printf("(owner.target: \c[green]%p\c-) %s", prevtarget, prevtarget.GetClassName());
				if (source && 
						prevtarget != source && 
						(PlayerPawn(source) || source.bFRIENDLY) && 
						!owner.bFRIENDLY && 
						damageType != 'TrueIP' &&
						!owner.bDORMANT)
				{
					int initdmg = newdamage;
					surprisehit = true;
					A_StopSound(32);
					if (owner.InStateSequence(owner.curstate,owner.ResolveState("Spawn")))
					{
						owner.A_SetInventory("JustSurprised",1);
						if (exex_hitweaksounds) owner.A_StartSound("Misc/WeaknessHitMid", 32, CHANF_DEFAULT, (exex_hitweaksoundvol * frandom(0.75,1.25)), ATTN_NONE, 0.67);
						newdamage *= frandompick(1.3334,1.50);
					}
					else
					{
						if (exex_hitweaksounds) owner.A_StartSound("Misc/WeaknessHit", 32, CHANF_DEFAULT, (exex_hitweaksoundvol * frandom(0.75,1.25)), ATTN_NONE, 0.67);
						newdamage *= frandompick(1.0667,1.10);
					}
					if ((dydudebug_actordmgdisplays || dydudebug_defensebuffs)) Console.Printf("(\c[green]%s\c-) surprisehit: damage: %d (initdmg: %d)", GetClassName(), newdamage, initdmg);
				}
				
				if (inflictor)
				{
					if ((KickPuff(inflictor) || KickPuffNoThrust(inflictor) || BadKickPuff(inflictor) || damageType == 'Kick') && newdamage > 0) owner.A_SetInventory("JustKicked",1);
					if ((UppercutPuff(inflictor) && damageType == 'Fist') && newdamage > 0) owner.A_SetInventory("JustUppercutted",1);
					if ((FistPuff(inflictor) && damageType == 'Fist') && newdamage > 0) owner.A_SetInventory("JustPunched",1);
					if (damageType == 'DashingBG' && newdamage > 0) owner.A_SetInventory("JustBatDashed",1);
					if (damageType == 'DashingSD' && newdamage > 0) owner.A_SetInventory("JustShieldDashed",1);
				}
				//
				bool wasblastedimpact = false;
				if (inflictor == null && source == null && damageType == 'Melee') 
				{
					wasblastedimpact = true;
					if (owner.bBLASTED && random(1,20) <= 19) 
					{
						newdamage *= 0.0625;
						owner.bBLASTED = false;
					}
					else
					{
						newdamage *= 0.25;
					}
					if (owner.vel.x != 0.0) owner.vel.x *= 0.1;
					if (owner.vel.y != 0.0) owner.vel.y *= 0.1;
					if (dydudebug_actordmgdisplays && wasblastedimpact) Console.Printf("(\c[green]%s\c-) (\czwasblastedimpact?: %d", owner.GetClassName(), wasblastedimpact);
				}
			}
		}
	}
}
