// Base Custom Weapon Class
class DDWeapon : Weapon
{
	mixin DmgCalc;
	// Misc
	const BerserkRecoilMulti = 2.5;
	const minxymoveneg = -3.814697266;
	const minxymovepos = 3.814697266;
	const minzmoveneg = -1.907348633;
	const minzmovepos = 1.907348633;

	int kickspeed;
	int punchspeed;
	int buttons;
	
	default
	{
		+WEAPON.NOAUTOAIM
	}
	
	action void A_Destroy()
	{
		self.Destroy();
	}
	
	action double A_LowerRaiseCheck(double movespeed)
	{
		double bufffactor = 1.0;
		if (player.mo)
		{
			let MiscItem = PlayerStatItem(Player.mo.FindInventory("PlayerStatItem"));
			if (MiscItem) movespeed *= (1.0 + (MiscItem.PlayerLevel * 0.025));
			if (player.mo.CountInv("PowerRoastBuff")) bufffactor += 0.125;
			if (player.mo.CountInv("PowerMealBuff") || player.mo.CountInv("PowerMealBuff2")) bufffactor += 0.25;
			if (player.mo.CountInv("PowerMeal2Buff") || player.mo.CountInv("PowerMeal2Buff2")) bufffactor += 0.25;
			if (player.ReadyWeapon is "HandToHand") bufffactor += 0.25;
			if (player.ReadyWeapon is "SuperVac") bufffactor -= (0.25 + (player.mo.CountInv("VacAmmo") * (0.25 / 24)));
			if (player.ReadyWeapon is "Grimophone") bufffactor -= 0.50;
			movespeed *= bufffactor;
			if (player.mo.CountInv("PowerStrength") || player.mo.CountInv("PowerStrengthDD")) movespeed *= 2.0;
		}
		return movespeed;
	}
	
	action void A_Lower(int movespeed = 6)
	{
		movespeed = A_LowerRaiseCheck(movespeed);
		if (dydudebug_weaponstatdisplays) Console.Printf("A_Lower: (%d)", movespeed);
		let player = player;

		if (null == player)
		{
			return;
		}
		if (null == player.ReadyWeapon)
		{
			player.mo.BringUpWeapon();
			return;
		}
		let psp = player.GetPSprite(PSP_WEAPON);
		if (!psp) return;
		if (player.morphTics || player.cheats & CF_INSTANTWEAPSWITCH)
		{
			psp.y = WEAPONBOTTOM;
		}
		else
		{
			psp.y += movespeed;
		}
		if (psp.y < WEAPONBOTTOM)
		{ // Not lowered all the way yet
			return;
		}
		ResetPSprite(psp);
		
		if (player.playerstate == PST_DEAD)
		{ // Player is dead, so don't bring up a pending weapon
			// Player is dead, so keep the weapon off screen
			player.SetPsprite(PSP_FLASH, null);
			psp.SetState(player.ReadyWeapon.FindState('DeadLowered'));
			return;
		}
		// [RH] Clear the flash state. Only needed for Strife.
		player.SetPsprite(PSP_FLASH, null);
		player.mo.BringUpWeapon ();
		return;
	}
	
	action void A_Raise(int movespeed = 6)
	{
		movespeed = A_LowerRaiseCheck(movespeed);
		if (dydudebug_weaponstatdisplays) Console.Printf("A_Lower: (%d)", movespeed);
		let player = player;

		if (null == player)
		{
			return;
		}
		if (player.PendingWeapon != WP_NOCHANGE)
		{
			player.mo.DropWeapon();
			return;
		}
		if (player.ReadyWeapon == null)
		{
			return;
		}
		let psp = player.GetPSprite(PSP_WEAPON);
		if (!psp) return;

		if (psp.y <= WEAPONBOTTOM)
		{
			ResetPSprite(psp);
		}
		psp.y -= movespeed;
		if (psp.y > WEAPONTOP)
		{ // Not raised all the way yet
			return;
		}
		psp.y = WEAPONTOP;
		
		psp.SetState(player.ReadyWeapon.GetReadyState());
		return;
	}

	// Fist Block Function
	action void A_PFistBlockOn()
	{
		A_SetInventory("FistPlayerBlock",0);
		A_SetInventory("FistPlayerBlock2",0);
		A_SetInventory("FistPlayerBlock3",0);
		A_SetInventory("FistPlayerSpeedFactor",0);
		A_SetInventory("FistPlayerSpeedFactor2",0);
		A_SetInventory("FistPlayerSpeedFactor3",0);
		A_SetInventory("FistPlayerBlockExtra",0);
		A_SetInventory("FistPlayerBlock",1);
		if (random(1,16) <= 1) { A_SetInventory("FistPlayerBlockExtra",1); }
	}

	action void A_PFistBlockOff()
	{
		A_SetInventory("FistPlayerBlock",0);
		A_SetInventory("FistPlayerBlock2",0);
		A_SetInventory("FistPlayerBlock3",0);
		A_SetInventory("FistPlayerSpeedFactor",0);
		A_SetInventory("FistPlayerSpeedFactor2",0);
		A_SetInventory("FistPlayerSpeedFactor3",0);
		A_SetInventory("FistPlayerBlockExtra",0);
		A_SetInventory("FistPlayerBlockItem",0);
		//bREFLECTIVE = 0;
		//bSHIELDREFLECT = 0;
	}

	action double A_SetShieldPieceDist(double basedist = 32.0)
	{
		double result = basedist;
		return result;
	}

	action void A_GetPunchSwingRecoil(int attacktype = 0)
	{
		if (exex_meleerecoil)
		{
			int IsMoving = 0;
			if (vel.x < minxymoveneg || vel.x > minxymovepos) IsMoving++;
			if (vel.y < minxymoveneg || vel.y > minxymovepos) IsMoving++;
			if (vel.z < minzmoveneg || vel.z > minzmovepos) IsMoving++;

			if (CountInv("PlayerDashing")) { }
			else if (IsMoving) { }
			else
			{
				let weapon = player.ReadyWeapon;
				string weaponname = weapon.GetClassName();
				string actorname = GetClassName();
				double recoil;
				double recoilmulti;
				int previousdamage;
				int PerkFactor;
				bool debugrecoil = false;
				int PlayerLevel = CountInv("PlayerLevel");
				int BerserkAdd;

				// Base "Recoil"
				double baserecoil = -0.125;
				baserecoil = frandom(-0.125,-0.075);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) BerserkAdd = randompick(1,1,1,1,1,1,1,2,2); else BerserkAdd = 0;

				recoil = baserecoil * (random(3,9) + BerserkAdd);
				if (debugrecoil) Console.Printf("\cxRecoil [Base]: %.8f", recoil);

				// Berserk
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
				{
					recoil *= BerserkRecoilMulti;
					if (debugrecoil) Console.Printf("\cxRecoil [Berserk]: %.8f", recoil);
				}

				// Stat/Level Mitigation
				recoilmulti = (1.0 - (PlayerLevel * 0.01171875));
				recoil *= recoilmulti;
				if (recoilmulti < 0.0) recoilmulti = 0.0;
				if (debugrecoil) Console.Printf("\cxRecoil [Stats]: %.8f, Multiplier: %.8f", recoil, recoilmulti);

				// Random Chance for 0 recoil
				if (attacktype == 1)
				{
					if (random(1,96) <= 1) recoil = 0.0;
				}
				else
				{
					if (random(1,48) <= 1) recoil = 0.0;
				}
				if (debugrecoil) Console.Printf("\cxRecoil [Final]: %.8f", recoil);

				A_Recoil(recoil);
			}
		}
	}
	
	action void A_KickDecelerate(int minval = 0, int maxval = 2, int chance = 192)
	{
		bool debug = false;
		int prev = invoker.kickspeed;
		if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) chance = ceil(chance * frandom(0.25,0.75));
		if (debug) Console.Printf("chance: %d", chance);
		if (random(1,256) <= chance)
		{
			invoker.kickspeed -= random(minval,maxval);
			if (invoker.kickspeed < 0) invoker.kickspeed = 0;
			if (debug) Console.Printf("%d [%d]", invoker.kickspeed, prev);
		}
	}

	action void A_KickTicCheck()
	{
		if (invoker.kickspeed >= 8 && invoker.kickspeed <= 17)
		{
			if (random(1,8) == 1) { A_SetTics(0); }
		}
		if (invoker.kickspeed >= 16 && invoker.kickspeed <= 31)
		{
			if (random(1,6) == 1) { A_SetTics(0); }
		}
		if (invoker.kickspeed >= 32 && invoker.kickspeed <= 47)
		{
			if (random(1,4) == 1) { A_SetTics(0); }
		}
		if (invoker.kickspeed >= 48 && invoker.kickspeed <= 64)
		{
			if (random(1,2) == 1) { A_SetTics(0); }
		}
	}
	
	action void A_KickTicCheck2(int minrange = 0, int maxrange = 8)
	{
		if (random(1,64) <= (random(minrange,maxrange) + invoker.kickspeed)) { A_SetTics(0); }
	}
	
	action void A_KickAccelerate(int minval = 1, int maxval = 1, int limit = 48, int chance = 256)
	{
		bool debug = false;
		int prev = invoker.kickspeed;

		if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) chance = floor(chance * frandom(1.125,1.375));
		if (debug) Console.Printf("chance: %d", chance);
		int chance2;
		if (chance > 256) chance2 = (chance % 256);
		if (random(1,256) <= chance) invoker.kickspeed += random(minval,maxval);
		if (random(1,256) <= chance2) invoker.kickspeed += random(minval,maxval);

		if (random(1,256) <= chance) { if (invoker.kickspeed == 5) invoker.kickspeed++; }
		if (random(1,256) <= chance2) { if (invoker.kickspeed == 5) invoker.kickspeed++; }
		if (random(1,256) <= chance) { if (invoker.kickspeed == 8) invoker.kickspeed++; }
		if (random(1,256) <= chance2) { if (invoker.kickspeed == 8) invoker.kickspeed++; }
		if (random(1,256) <= chance) { if (invoker.kickspeed == 10) invoker.kickspeed++; }
		if (random(1,256) <= chance2) { if (invoker.kickspeed == 10) invoker.kickspeed++; }
		if (invoker.kickspeed >= 11) 
		{
			if (random(1,256) <= chance) invoker.kickspeed++;
			if (random(1,256) <= chance2) invoker.kickspeed++;
			if (random(1,256) <= chance) { if (invoker.kickspeed == 17) invoker.kickspeed++; }
			if (random(1,256) <= chance2) { if (invoker.kickspeed == 17) invoker.kickspeed++; }
			if (random(1,256) <= chance) { if (invoker.kickspeed == 20) invoker.kickspeed++; }
			if (random(1,256) <= chance2) { if (invoker.kickspeed == 20) invoker.kickspeed++; }
			if (random(1,256) <= chance) { if (invoker.kickspeed == 23) invoker.kickspeed++; }
			if (random(1,256) <= chance2) { if (invoker.kickspeed == 23) invoker.kickspeed++; }
			if (random(1,256) <= chance) { if (invoker.kickspeed == 25) invoker.kickspeed++; }
			if (random(1,256) <= chance2) { if (invoker.kickspeed == 25) invoker.kickspeed++; }
			if (random(1,256) <= chance) { if (invoker.kickspeed >= 26) invoker.kickspeed++; }
			if (random(1,256) <= chance2) { if (invoker.kickspeed >= 26) invoker.kickspeed++; }
		}
		if (invoker.kickspeed > limit) invoker.kickspeed = limit;
		if (debug) Console.Printf("%d [%d]", invoker.kickspeed, prev);
	}
	
	action void A_WeaponReady(int flags = 0)
	{
		if (CountInv("IsUnconscious"))
		{
			if (dydudebug_weaponstatdisplays2) Console.Printf("Flags (Pre [Base]): %d", flags);
			// Enforces Various Locks on weapons if the player is "Unconscious"
			if (!(flags & WRF_NOBOB)) flags |= WRF_NOBOB; // Turns on WRF_NOBOB
			if (!(flags & WRF_NOFIRE)) flags |= WRF_NOFIRE; // Turns on WRF_NOFIRE
			if (!(flags & WRF_NOPRIMARY)) flags |= WRF_NOPRIMARY; // Turns on WRF_NOPRIMARY
			if (!(flags & WRF_NOSECONDARY)) flags |= WRF_NOSECONDARY; // Turns on WRF_NOSECONDARY
			if (!(flags & WRF_NOSWITCH)) flags |= WRF_NOSWITCH; // Turns on WRF_NOSWITCH
			if (!(flags & WRF_DISABLESWITCH)) flags |= WRF_DISABLESWITCH; // Turns on WRF_DISABLESWITCH

			if ((flags & WRF_ALLOWRELOAD)) flags &= ~WRF_ALLOWRELOAD; // Turns off WRF_ALLOWRELOAD
			if ((flags & WRF_ALLOWZOOM)) flags &= ~WRF_ALLOWZOOM; // Turns off WRF_ALLOWZOOM
			if ((flags & WRF_ALLOWUSER1)) flags &= ~WRF_ALLOWUSER1; // Turns off WRF_ALLOWUSER1
			if ((flags & WRF_ALLOWUSER2)) flags &= ~WRF_ALLOWUSER2; // Turns off WRF_ALLOWUSER2
			if ((flags & WRF_ALLOWUSER3)) flags &= ~WRF_ALLOWUSER3; // Turns off WRF_ALLOWUSER3
			if ((flags & WRF_ALLOWUSER4)) flags &= ~WRF_ALLOWUSER4; // Turns off WRF_ALLOWUSER4
			if (dydudebug_weaponstatdisplays2) Console.Printf("Flags (post [Base]): %d", flags);
		}

		if (!player) return;
														DoReadyWeaponToSwitch(player, !(flags & WRF_NOSWITCH));
		if ((flags & WRF_NOFIRE) != WRF_NOFIRE)			DoReadyWeaponToFire(player.mo, !(flags & WRF_NoPrimary), !(flags & WRF_NoSecondary));
		if (!(flags & WRF_NOBOB))						DoReadyWeaponToBob(player);

		A_Overlay(-1000,"GrandControlLayer",true);
		player.WeaponState |= GetButtonStateFlags(flags);
		DoReadyWeaponDisableSwitch(player, flags & WRF_DisableSwitch);
		if (dydudebug_weaponstatdisplays2) Console.Printf("Flags (final [Base]): %d", flags);
	}
	
	States
	{
		GrandControlLayer: // layer -1000
			TNT1 A 1
			{
			}
			loop;
	}
}

class DinahWeapon : DDWeapon
{
	action void A_QMWKickInit()
	{
		A_GunFlash("LightDone",GFF_NOEXTCHANGE); // A_ClearFlash;
		if (random(1,256) >= 253)
		{
			if (CountInv("PlayingStrife") > 0) { } // Strife mode makes the punch work like the Punch Dagger where it NEVER makes sound
			else { A_AlertMonsters(); } // Sometimes a swing will be enough to wake up all monsters in the area.
		}
	}

	action void A_WeaponReady(int flags = 0)
	{
		if (CountInv("IsUnconscious"))
		{
			if (dydudebug_weaponstatdisplays2) Console.Printf("Flags (Pre [QuickMelee]): %d", flags);
			// Enforces Various Locks on weapons if the player is "Unconscious"
			if (!(flags & WRF_NOBOB)) flags |= WRF_NOBOB; // Turns on WRF_NOBOB
			if (!(flags & WRF_NOFIRE)) flags |= WRF_NOFIRE; // Turns on WRF_NOFIRE
			if (!(flags & WRF_NOPRIMARY)) flags |= WRF_NOPRIMARY; // Turns on WRF_NOPRIMARY
			if (!(flags & WRF_NOSECONDARY)) flags |= WRF_NOSECONDARY; // Turns on WRF_NOSECONDARY
			if (!(flags & WRF_NOSWITCH)) flags |= WRF_NOSWITCH; // Turns on WRF_NOSWITCH
			if (!(flags & WRF_DISABLESWITCH)) flags |= WRF_DISABLESWITCH; // Turns on WRF_DISABLESWITCH

			if ((flags & WRF_ALLOWRELOAD)) flags &= ~WRF_ALLOWRELOAD; // Turns off WRF_ALLOWRELOAD
			if ((flags & WRF_ALLOWZOOM)) flags &= ~WRF_ALLOWZOOM; // Turns off WRF_ALLOWZOOM
			if ((flags & WRF_ALLOWUSER1)) flags &= ~WRF_ALLOWUSER1; // Turns off WRF_ALLOWUSER1
			if ((flags & WRF_ALLOWUSER2)) flags &= ~WRF_ALLOWUSER2; // Turns off WRF_ALLOWUSER2
			if ((flags & WRF_ALLOWUSER3)) flags &= ~WRF_ALLOWUSER3; // Turns off WRF_ALLOWUSER3
			if ((flags & WRF_ALLOWUSER4)) flags &= ~WRF_ALLOWUSER4; // Turns off WRF_ALLOWUSER4
			if (dydudebug_weaponstatdisplays2) Console.Printf("Flags (post [QuickMelee]): %d", flags);
		}

		if (!player) return;
														DoReadyWeaponToSwitch(player, !(flags & WRF_NoSwitch));
		if ((flags & WRF_NoFire) != WRF_NoFire)			DoReadyWeaponToFire(player.mo, !(flags & WRF_NoPrimary), !(flags & WRF_NoSecondary));
		if (!(flags & WRF_NoBob))						DoReadyWeaponToBob(player);

		A_Overlay(-1000,"GrandControlLayer",true);
		player.WeaponState |= GetButtonStateFlags(flags);														
		DoReadyWeaponDisableSwitch(player, flags & WRF_DisableSwitch);
		if (dydudebug_weaponstatdisplays2) Console.Printf("Flags (final [QuickMelee]): %d", flags);
	}
	
	states
	{
		GrandControlLayer: // layer -1000
			TNT1 A 1
			{
				let weapon = player.ReadyWeapon;
				if (player.mo.health > 0)
				{
					if (dydudebug_weaponstatdisplays2) Console.Printf("GrandControlLayer - 2a");
					if (GetPlayerInput(INPUT_BUTTONS) & BT_USER1)
					{
						if (CountInv("IsUnconscious"))
						{
							A_PrintBold(String.Format("\cgYou're currently incapacitated, and this can't quick kick!"), frandom(0.685,0.8));
						}
						else
						{
							A_Overlay(-2,"Kick",true);
						}
					}
				}
				else
				{
					if (dydudebug_weaponstatdisplays2) Console.Printf("GrandControlLayer - 2b");
					A_ClearOverlays(-2,-2,true);
					A_ClearOverlays(8,8,true);
				}
			}
			loop;

		Kick:
			TNT1 A 0 A_QMWKickInit();
			goto KickStart;

		KickStart:
			TNT1 A 0 
			{
				A_KickAccelerate();
			}
			TNT1 A 1
			{
				if (random(1,4) == 1)
				{
					A_SetTics(0);
				}
				else
				{
					A_KickTicCheck2();
				}
			}
			TNT1 AAA 1
			{
				A_KickTicCheck2();
			}
			TNT1 A 1
			{
				if (random(1,4) == 1)
				{
					A_SetTics(0);
				}
				else
				{
					A_KickTicCheck2();
				}
			}
			DKIC A 1
			{
				A_KickTicCheck();
			}
			DKIC B 1
			{
				A_StartSound("fistswingmedium0",CHAN_BODY);
				A_KickTicCheck();
			}
			DKIC C 1
			{
				int basechance = 128;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) basechance *= frandompick(1.5,1.5,1.5,1.625,1.625,1.75);
				if (random(1,256) <= basechance)
				{
					string voicenm;
					double voicevol = frandom(0.90,1.45);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) voicevol *= frandompick(1.125,1.125,1.125,1.25,1.25,1.5);
					int randvoice = random(1,5);
					if (randvoice == 1) voicenm = "dinah/Jump";
					if (randvoice >= 2 && randvoice <= 3) voicenm = "dinah/kick1";
					if (randvoice == 4) voicenm = "dinah/kiah4";
					if (randvoice == 5) voicenm = "dinah/kiah5";
					if (exex_dinahextravoices)
					{
						A_StopSound(CHAN_VOICE);
						A_StartSound(voicenm,CHAN_VOICE,CHANF_DEFAULT,voicevol); 
					}
				} 
				A_KickTicCheck();
			}
			DKIC DEFG 1
			{
				A_KickTicCheck();
			}
			DKIC H 1
			{
				int KPower = (player.mo.Stamina / 10);
				if (KPower > 10) KPower = 10;
				double recl = frandom(-0.125,-0.075);
				int dmg = random(28,52) + (KPower * 3.275);
				if (KPower) dmg *= frandom(1.00,(1.00 + (KPower * frandompick(0.667,0.75,0.834))));

				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					dmg *= 10;
				}
				if (dydudebug_meleedmg) Console.Printf("dmg: %d, recl: %.8f", dmg, recl);
				A_Recoil(recl);
				A_CustomPunch(dmg,true,CPF_NOTURN,"KickPuff",104,0,0,"","","");
			}
			DKIC GFEDCBA 1
			{
				A_KickTicCheck();
			}
			TNT1 A 1
			{
				if (random(1,4) == 1)
				{
					A_SetTics(0);
				}
				else
				{
					A_KickTicCheck2();
				}
			}
			TNT1 AAA 1
			{
				A_KickTicCheck2();
			}
			TNT1 A 1
			{
				if (random(1,4) == 1)
				{
					A_SetTics(0);
				}
				else
				{
					A_KickTicCheck2();
				}
			}
			goto KickEnd;
		// KICK END
		KickEnd:
			TNT1 A 0
			{
				A_KickDecelerate();
			}
			stop;
	}
}

class DDBeak : DDWeapon
{
	Default
	{
		Weapon.SelectionOrder 10000;
		+WEAPON.DONTBOB
		+WEAPON.MELEEWEAPON
		Weapon.YAdjust 15;
		Weapon.SisterWeapon "BeakPowered";
	}
	
	States
	{
		Ready:
			BEAK A 1 A_WeaponReady;
			Loop;
		Deselect:
			BEAK A 1 A_Lower(12);
			Loop;
		Select:
			BEAK A 1 A_BeakRaise;
			Loop;
		Fire:
			BEAK A 18 A_BeakAttackPL1;
			Goto Ready;
	}
	
	//---------------------------------------------------------------------------
	//
	// PROC A_BeakRaise
	//
	//---------------------------------------------------------------------------

	action void A_BeakRaise ()
	{
		if (player == null)
		{
			return;
		}
		let psp = player.GetPSprite(PSP_WEAPON);
		if (psp)
		{
			psp.y = WEAPONTOP;
			ResetPSprite(psp);
		}
		player.SetPsprite(PSP_WEAPON, player.ReadyWeapon.GetReadyState());
	}

	//----------------------------------------------------------------------------
	//
	// PROC A_BeakAttackPL1
	//
	//----------------------------------------------------------------------------

	action void A_BeakAttackPL1()
	{
		FTranslatedLineTarget t;

		if (player == null)
		{
			return;
		}

		int damage = random[BeakAtk](1,3);
		double ang = angle;
		double slope = AimLineAttack (ang, DEFMELEERANGE);
		LineAttack (ang, DEFMELEERANGE, slope, damage, 'Melee', "BeakPuff", true, t);
		if (t.linetarget)
		{
			angle = t.angleFromSource;
		}
		A_StartSound ("chicken/peck", CHAN_VOICE);
		player.chickenPeck = 12;
		let psp = player.GetPSprite(PSP_WEAPON);
		if (psp)
		{
			psp.Tics -= random[BeakAtk](0,7);
		}
	}
}

class HandToHand : DinahWeapon replaces Fist
{
	default
	{
		Weapon.SelectionOrder 3700;
		Weapon.Kickback 80;
		+SPECTRAL
		+WEAPON.NOALERT
		+WEAPON.MELEEWEAPON
		+INVENTORY.UNDROPPABLE
		+INVENTORY.UNTOSSABLE
		Tag "Hand to Hand: Normal attack punches, Alt attack uppercuts. <USER4> enters a cross-armed guarding stance to heavily reduce most damage, moreso melee types of damage.";
		Obituary "%o was give a good kick in the arse by %k.";
	}
	
	states
	{
		Ready:
			DHND A 1
			{
				A_KickDecelerate();
				A_WeaponReady(WRF_ALLOWUSER4);
			}
			loop;
		Deselect:
			DHND A 1
			{
				A_KickDecelerate();
				A_Lower(12);
			}
			loop;
		Select:
			DHND A 1
			{
				A_KickDecelerate();
				A_Raise(12);
			}
			loop;
		Fire:
			TNT1 A 0
			{
				int basechance = 31;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) basechance *= frandompick(2.25,2.25,2.25,2.4375,2.4375,2.625);
				if (random(1,256) <= basechance) 
				{
					string voicenm;
					double voicevol = frandom(0.90,1.45);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) voicevol *= frandompick(1.125,1.125,1.125,1.25,1.25,1.5);
					int randvoice = random(1,7);
					if (randvoice == 1) voicenm = "Dinah/Jump";
					if (randvoice == 2) voicenm = "Dinah/Kiai1";
					if (randvoice == 3) voicenm = "Dinah/Kiai2";
					if (randvoice == 4) voicenm = "Dinah/Kiai3";
					if (randvoice == 5) voicenm = "Dinah/Kiai4";
					if (randvoice == 6) voicenm = "Dinah/Kiai5";
					if (randvoice == 7) voicenm = "Dinah/Jump1";
					if (exex_dinahextravoices)
					{
						A_StopSound(CHAN_VOICE);
						A_StartSound(voicenm,CHAN_VOICE,CHANF_DEFAULT,voicevol); 
					}
				}
				if (random(1,2) == 1)
				{
					return resolvestate("PunchStartL"); 
				}
				else
				{
					return resolvestate("PunchStartR"); 
				}
				return resolvestate(null);
			}
		PunchStartL:
			DHND B 3
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 3;
				if (PlayerLevel >= 15) tic -= 1;
				if (PlayerLevel >= 45) tic -= 1;
				if (tic < 1) tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DPUN A 3
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 3;
				if (PlayerLevel >= 20) tic -= 1;
				if (PlayerLevel >= 50) tic -= 1;
				if (tic < 1) tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);

				if (random(1,64) <= 1 && !CountInv("PlayingStrife",AAPTR_PLAYER1)) { A_AlertMonsters(); }

				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					if (random(1,256) <= 192) { A_StartSound("fistswingheavy",CHAN_WEAPON); }
					else { A_StartSound("fistswingmedium",CHAN_WEAPON); }
				}
				else
				{
					A_StartSound("fistswingmedium",CHAN_BODY);
				}
				
				A_GetPunchSwingRecoil(0);
				A_CustomPunch(A_GetPunchDamage(0,0,false),true,CPF_NOTURN,"FistPuff",64,0,0,"","","");
			}
			DPUN B 4
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 4;
				if (PlayerLevel >= 10) tic -= 1;
				if (PlayerLevel >= 40) tic -= 1;
				if (tic < 1) tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DPUN A 3
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 3;
				if (PlayerLevel >= 5) tic -= 1;
				if (PlayerLevel >= 35) tic -= 1;
				if (tic < 1) tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DHND B 4
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 4;
				if (PlayerLevel >= 25) tic -= 1;
				if (PlayerLevel >= 55) tic -= 1;
				if (tic < 1) tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);

				A_ReFire();
			}
			goto Ready;
		PunchStartR:
			DHND C 3
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 3;

				if (PlayerLevel >= 15) tic -= 1;
				if (PlayerLevel >= 45) tic -= 1;
				if (tic < 1) tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DPUN C 3
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 3;
				if (PlayerLevel >= 20) tic -= 1;
				if (PlayerLevel >= 50) tic -= 1;
				if (tic < 1) tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);

				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					if (random(1,256) <= 192) { A_StartSound("fistswingheavy",CHAN_WEAPON); }
					else { A_StartSound("fistswingmedium",CHAN_WEAPON); }
				}
				else
				{
					A_StartSound("fistswingmedium",CHAN_BODY);
				}

				A_GetPunchSwingRecoil(0);
				A_CustomPunch(A_GetPunchDamage(0,0,false),true,CPF_NOTURN,"FistPuff",64,0,0,"","","");
			}
			DPUN D 4
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 4;
				if (PlayerLevel >= 10) tic -= 1;
				if (PlayerLevel >= 40) tic -= 1;
				if (tic < 1) tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DPUN C 3
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 3;
				if (PlayerLevel >= 5) tic -= 1;
				if (PlayerLevel >= 35) tic -= 1;
				if (tic < 1) tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DHND B 4
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 4;
				if (PlayerLevel >= 25) tic -= 1;
				if (PlayerLevel >= 55) tic -= 1;
				if (tic < 1) tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);

				A_ReFire();
			}
			goto Ready;

		AltFire:
			goto UppercutStart;
		UppercutStart:
			DNUP A 1
			{ 
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNUP B 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 25) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNUP C 1
			{ 
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNUP D 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 35) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNUP E 1
			{ 
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			//
			DNU2 A 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 16) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);

				if (random(1,256) >= 253)
				{
					if (CountInv("PlayingStrife")) { } // Strife mode makes the punch work like the Punch Dagger where it NEVER makes sound
					else { A_AlertMonsters(); } // Sometimes a swing will be enough to wake up all monsters in the area.
				}
	
				int basechance = 75;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) basechance *= frandompick(2,2,2,2.5,2.5,3);
				if (random(1,256) <= basechance)
				{
					string voicenm;
					double voicevol = frandom(0.90,1.45);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) basechance *= frandompick(1.125,1.125,1.125,1.25,1.25,1.5);
					int randvoice = random(1,7);
					if (randvoice >= 1 && randvoice <= 3) voicenm = "Dinah/Jump";
					if (randvoice == 4) voicenm = "Dinah/Kiai4";
					if (randvoice == 5) voicenm = "Dinah/Kiai5";
					if (randvoice >= 6 && randvoice <= 7) voicenm = "Dinah/Kiai6";
					if (exex_dinahextravoices)
					{
						A_StopSound(CHAN_VOICE);
						A_StartSound(voicenm,CHAN_VOICE,CHANF_DEFAULT,voicevol); 
					}
				} 
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					if (random(1,256) <= 192) { A_StartSound("fistswingheavy0",CHAN_WEAPON); }
					else { A_StartSound("fistswingmedium0",CHAN_WEAPON); }
				}
				else
				{
					A_StartSound("fistswingmedium0",CHAN_WEAPON); 
				}
			}
			DNU2 B 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNU2 C 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 32) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNU2 D 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNU2 E 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 8) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNU2 F 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);

				A_GetPunchSwingRecoil(1);
				A_CustomPunch(A_GetPunchDamage(1,0,false),true,CPF_NOTURN,"UppercutPuff",58,0,0,"","","");
			}
			DNU2 G 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 24) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNU2 F 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 12) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNU2 E 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNU2 D 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 24) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNU2 C 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNU2 B 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 36) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNU2 A 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNU2 A 0 { return resolvestate("UppercutEnd"); }
		UppercutEnd:
			DNUP E 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 45) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNUP D 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNUP C 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 5) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNUP B 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) tic *= frandom(0.34,0.67);
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			DNUP A 1
			{
				int PlayerLevel = CountInv("PlayerLevel");
				int tic = 1;
				if (PlayerLevel >= 15) tic -= 1;
				if (dydudebug_weaponstatdisplays) Console.Printf("%d", tic);
				A_SetTics(tic);
			}
			TNT1 A 0
			{
				A_ReFire();
				return resolvestate("Ready");
			}
			goto Ready;
			
		// Crossed-Arm Guard
		User4:
			DNGU A 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_PFistBlockOn();
			}
			DNGU B 1
			{
				A_PFistBlockOn();
			}
			DNGU C 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_GiveInventory("FistPlayerBlockItem",1);
				A_PFistBlockOn();
			}
			DNGU D 1
			{
				A_PFistBlockOn();
			}
			DNGU E 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_PFistBlockOn();
			}
			DNGU F 1
			{
				A_PFistBlockOn();
			}
			DNGU G 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_PFistBlockOn();
			}
			DNGU H 1
			{
				A_PFistBlockOn();
			}
			DNGU I 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_PFistBlockOn();
			}
		User4Hold:
			DNGU J 1
			{
				A_PFistBlockOn();

				A_GiveInventory("FistPlayerBlockHold",1);
				A_WeaponReady(WRF_NOFIRE|WRF_DISABLESWITCH);
			}
			DNGU J 0 A_Refire("User4End");
			loop;
		User4End:
			DNGU I 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_PFistBlockOn();
				A_SetInventory("FistPlayerBlockHold",0);
			}
			DNGU H 1
			{
				A_PFistBlockOn();
				A_SetInventory("FistPlayerBlockHold",0);
			}
			DNGU G 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_PFistBlockOn();
				A_SetInventory("FistPlayerBlockHold",0);
			}
			DNGU F 1
			{
				A_PFistBlockOn();
				A_SetInventory("FistPlayerBlockHold",0);
			}
			DNGU E 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_PFistBlockOn();
				A_SetInventory("FistPlayerBlockHold",0);
			}
			DNGU D 1
			{
				A_PFistBlockOn();
				A_SetInventory("FistPlayerBlockHold",0);
			}
			DNGU C 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_PFistBlockOn();
				A_SetInventory("FistPlayerBlockHold",0);
			}
			DNGU B 1
			{
				A_PFistBlockOn();
				A_SetInventory("FistPlayerBlockHold",0);
			}
			DNGU A 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_PFistBlockOn();
				A_SetInventory("FistPlayerBlockHold",0);
			}
			DNGU A 0
			{
				A_PFistBlockOff();
			}
			goto Ready;
	}
}

class FistPuff : DDPuff
{
	default
	{
		Tag "Fist";
		Species "Players";
		+NOBLOCKMAP
		+NOGRAVITY
		+ALLOWPARTICLES
		+RANDOMIZE
		+FORCERADIUSDMG +PUFFGETSOWNER +PUFFONACTORS 
		+THRUSPECIES +MTHRUSPECIES
		RenderStyle "Translucent";
		Alpha 0.5;
		VSpeed 1;
		Mass 5;
		damagetype "Fist";
		SeeSound "null"; // "FistHit"
		AttackSound "null";
	}

	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				user_randompain = 44;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.44);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }

				int dmg = A_GetPunchDamage(0,1,true);
				int radi = 16 * frandom(0.84375,1.15625);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserkwall", 56); 
				} else { A_StartSound("FistHitWall", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
				//Console.Printf("Spawn");
			}
		SpawnSparks:
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
		Melee:
			TNT1 A 0
			{
				user_randompain = 44;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.44);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }

				int dmg = A_GetPunchDamage(0,1,true);
				int radi = 16 * frandom(0.84375,1.15625);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserk", 56); 
				} else { A_StartSound("FistHit", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
				//Console.Printf("Melee");
			}
		MeleeSparks:
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
		Crash:
			PUFF C 0
			{
				user_randompain = 44;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.44);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }

				int dmg = A_GetPunchDamage(0,1,true);
				int radi = 16 * frandom(0.84375,1.15625);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserkwall", 56); 
				} else { A_StartSound("FistHitWall", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
				//Console.Printf("Crash");
			}
		CrashSparks:
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
	}
}

class UppercutPuff : FistPuff
{
	default
	{
		Tag "Uppercut";
		ProjectileKickback 0;
		+NODAMAGETHRUST
		RenderStyle "Translucent";
		Alpha 0.875;
	}

	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				user_randompain = 32;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.32);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }
				
				int dmg = A_GetPunchDamage(1,1,true);
				int radi = 16 * frandom(0.84375,1.15625);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserkwall", 56);
				} else { A_StartSound("FistHitWall", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
			}
		SpawnSparks:
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
		Melee:
			TNT1 A 0
			{
				user_randompain = 32;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.32);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }
				
				int dmg = A_GetPunchDamage(1,1,true);
				int radi = 16 * frandom(0.84375,1.15625);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserk", 56); 
				} else { A_StartSound("FistHit", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
			}
		MeleeSparks:
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
		Crash:
			PUFF C 0
			{
				user_randompain = 32;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.32);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }
				
				int dmg = A_GetPunchDamage(1,1,true);
				int radi = 16 * frandom(0.84375,1.15625);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserkwall", 56);
				} else { A_StartSound("FistHitWall", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
			}
		CrashSparks:
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
	}
}

class KickPuff : DDPuff
{
	default
	{
		Tag "Kick";
		Species "Players";
		+NOBLOCKMAP
		+NOGRAVITY
		+ALLOWPARTICLES
		+RANDOMIZE
		+FORCERADIUSDMG +PUFFGETSOWNER +PUFFONACTORS 
		+THRUSPECIES +MTHRUSPECIES
		RenderStyle "Translucent";
		ProjectileKickback 375; // 1500
		Alpha 0.5;
		VSpeed 1;
		Mass 5;
		damagetype "Kick";
		SeeSound "null"; // "FistHit"
		AttackSound "null";
	}

	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				user_randompain = 4;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.04);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }

				int KPower = (target.player.mo.Stamina / 10);
				if (KPower > 10) KPower = 10;
				double recl = frandom(-0.125,-0.075);
				int dmg = random(28,52) + (KPower * 3.275);
				if (KPower) dmg *= frandom(1.00,(1.00 + (KPower * frandompick(0.667,0.75,0.834))));

				int radi = 24 * frandom(0.84375,1.15625);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserkwall", 56);
				} else { A_StartSound("FistHitWall", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
			}
		Spawn2:
			TNT1 A 2 
			{
				int dist = randompick(3,3,4);
				A_RadiusThrust(375,dist,0,dist);
			}
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
		Melee:
			TNT1 A 0
			{
				user_randompain = 4;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.04);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }
				
				int KPower = (target.player.mo.Stamina / 10);
				if (KPower > 10) KPower = 10;
				double recl = frandom(-0.125,-0.075);
				int dmg = random(28,52) + (KPower * 3.275);
				if (KPower) dmg *= frandom(1.00,(1.00 + (KPower * frandompick(0.667,0.75,0.834))));
				int radi = 24 * frandom(0.84375,1.15625);

				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserk", 56); 
				} else { A_StartSound("FistHit", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
			}
		Melee2:
			TNT1 A 2 
			{
				int dist = randompick(3,3,4);
				A_RadiusThrust(375,dist,0,dist);
			}
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
		Crash:
			PUFF C 0
			{
				user_randompain = 4;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.04);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }

				int KPower = (target.player.mo.Stamina / 10);
				if (KPower > 10) KPower = 10;
				double recl = frandom(-0.125,-0.075);
				int dmg = random(28,52) + (KPower * 3.275);
				if (KPower) dmg *= frandom(1.00,(1.00 + (KPower * frandompick(0.667,0.75,0.834))));

				int radi = 24 * frandom(0.84375,1.15625);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserkwall", 56);
				} else { A_StartSound("FistHitWall", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
			}
		Crash2:
			TNT1 A 2 
			{
				int dist = randompick(3,3,4);
				A_RadiusThrust(375,dist,0,dist);
			}
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
	}
}

class KickPuffNoThrust : KickPuff
{
	default
	{
		ProjectileKickback 0;
		+NODAMAGETHRUST
	}
	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				user_randompain = 4;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.04);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }

				int KPower = (target.player.mo.Stamina / 10);
				if (KPower > 10) KPower = 10;
				double recl = frandom(-0.125,-0.075);
				int dmg = random(28,52) + (KPower * 3.275);
				if (KPower) dmg *= frandom(1.00,(1.00 + (KPower * frandompick(0.667,0.75,0.834))));
				int radi = 24 * frandom(0.84375,1.15625);

				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserkwall", 56);
				} else { A_StartSound("FistHitWall", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
			}
		Spawn2:
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
		Melee:
			TNT1 A 0
			{
				user_randompain = 4;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.04);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }
				
				int KPower = (target.player.mo.Stamina / 10);
				if (KPower > 10) KPower = 10;
				double recl = frandom(-0.125,-0.075);
				int dmg = random(28,52) + (KPower * 3.275);
				if (KPower) dmg *= frandom(1.00,(1.00 + (KPower * frandompick(0.667,0.75,0.834))));
				int radi = 24 * frandom(0.84375,1.15625);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserk", 56); 
				} else { A_StartSound("FistHit", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
			}
		Melee2:
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
		Crash:
			PUFF C 0
			{
				user_randompain = 4;
				let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
				if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.04);
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }
				
				int KPower = (target.player.mo.Stamina / 10);
				if (KPower > 10) KPower = 10;
				double recl = frandom(-0.125,-0.075);
				int dmg = random(28,52) + (KPower * 3.275);
				if (KPower) dmg *= frandom(1.00,(1.00 + (KPower * frandompick(0.667,0.75,0.834))));
				int radi = 24 * frandom(0.84375,1.15625);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					radi *= 2.5;
					A_StartSound("fisthitberserkwall", 56);
				} else { A_StartSound("FistHitWall", 56); }

				A_Explode((dmg * frandom(0.05,0.15)), radi, 0, 0, (radi*0.25));
			}
		Crash2:
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			TNT1 A 2;
			Stop;
	}
}

// Cricket Bat
class CricketShieldPart : ShieldPart
{
	default
	{
		-AIMREFLECT
		+DEFLECT
		Radius 8; // out of 32
		Height 16; // out of 32
		Scale 0.5;
	}
	states
	{
		Spawn:
			HEXA C 2 bright NoDelay
			{
				//A_SetTics(randompick(1,2,2,2,3));
				//if (CountInv("PlayingDoom64")) { A_SetSize(19,19); }
			}
			stop;
		Pain:
			TNT1 A 1 bright 
			{
				A_StartSound("CricketBat/ShieldHit", CHAN_WEAPON);
			}
			stop;
	}
}

class CricketShieldPartNoReflect : ShieldPartNoReflect
{
	default
	{
		Radius 8; // out of 32
		Height 16; // out of 32
		Scale 0.5;
	}
	states
	{
		Spawn:
			HEXA A 2 bright NoDelay
			{
				//A_SetTics(randompick(1,2,2,2,3));
				//if (CountInv("PlayingDoom64")) { A_SetSize(19,19); }
			}
			stop;
		Pain:
			TNT1 A 1 bright 
			{
				A_StartSound("CricketBat/ShieldHit", CHAN_WEAPON);
			}
			stop;
	}
}

class CricketSwingShieldPart : SwingShieldPart
{
	default
	{
		-AIMREFLECT
		+DEFLECT
		Radius 8; // out of 32
		Height 16; // out of 32
		Scale 0.5;
	}
	states
	{
		Spawn:
			HEXA C 3 bright NoDelay
			{
				//A_SetTics(randompick(1,2,2,2,3));
				//if (CountInv("PlayingDoom64")) { A_SetSize(19,19); }
			}
			stop;
		Pain:
			TNT1 A 1 bright 
			{
				A_StartSound("CricketBat/ShieldHit", CHAN_WEAPON);
			}
			stop;
	}
}

class CricketSwingPartNoReflect : SwingShieldPartNoReflect
{
	default
	{
		Radius 8; // out of 32
		Height 16; // out of 32
		Scale 0.5;
	}
	states
	{
		Spawn:
			HEXA A 3 bright NoDelay
			{
				//A_SetTics(randompick(1,2,2,2,3));
				//if (CountInv("PlayingDoom64")) { A_SetSize(19,19); }
			}
			stop;
		Pain:
			TNT1 A 1 bright 
			{
				A_StartSound("CricketBat/ShieldHit", CHAN_WEAPON);
			}
			stop;
	}
}

//***************
//* Cricket Bat *
//***************
class CricketBat : DinahWeapon replaces Pistol
{
	default
	{
		//$Category RPWeapons
		Weapon.SelectionOrder 100;
		Weapon.SlotNumber 2;
		Weapon.Kickback 50;
		Weapon.AmmoType2 "MalletAmmo";
		Weapon.AmmoGive2 5;
		//Weapon.AmmoUse2 0;
		+WEAPON.NOALERT
		+WEAPON.MELEEWEAPON
		+PUFFONACTORS
		+FLOATBOB
		Inventory.Icon "SPBTA0";
		Inventory.Pickupsound "DinahWeap";
		Inventory.PickupMessage "\c[gold]A Cricket Bat! Yeeeesireeee I'll be taking this!";
		Tag "Cricket Bat: Dinah's old reliable. Normal attack is melee. Alt attack is a cricket ball shot. <USER4> key allows you to guard/defend from attacks, and blocks/reflects projectiles from the front. Swings can also affect enemy projectiles.";
		Obituary "%k scored a point with %o.";
	}
	
	action void A_GiveGuardBuff(int type = 0)
	{
		let MiscItem = PlayerStatItem(player.mo.FindInventory("PlayerStatItem"));
		if (MiscItem) 
		{
			MiscItem.CricketBatBuffTimer = randompick(1,1,1,1,1,1,1,1,1,2);
			if (type >= 1) MiscItem.CricketBatBuffTimer2 = randompick(1,1,1,1,1,1,1,1,1,2);
		}
	}

	action void A_BatGuardDashOff()
	{
		invoker.guardtimer = 0;
		A_SetInventory("IsInBatGuardFrame",0);
	}

	action void A_CricketBatGuard(int type = 0)
	{
		A_SetInventory("IsInBatGuardFrame",1);

		string vispart = "CricketShieldPartNoReflect";
		if (type == 1) vispart = "CricketShieldPart";
		else
		{
			if (random(1,16) <= 5) vispart = "CricketShieldPart";
		}

		double yoffset = frandompick(-0.3125,0,0.3125);

		double distx, disty, distz;
		double heightmulti = 0.5;
		double ydistseperator1 = 3.75;
		double ydistseperator2 = 10.00;
		double sa = sin(angle);
		double ca = cos(angle);
		if (dydudebug_cricketbatguard) Console.Printf("angle sine: %.3f, angle cosine: %.3f", sa, ca);
		double sp = sin(pitch);
		double cp = cos(pitch);
		if (dydudebug_cricketbatguard) Console.Printf("pitch sine: %.3f, pitch cosine: %.3f", sp, cp);
		int m = frandom(30.0,34.0);

		distx = (m * frandom(0.925,0.95));
		disty = 0.0;
		distz = (height * heightmulti) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty = ydistseperator2;
		distz = ((height * heightmulti) - 10.0) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty *= -1;
		distz = ((height * heightmulti) + 10.0) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		
		if (random(1,8) <= 7)
		{
			distx = (m * frandom(0.675,0.70));
			disty = 0.0;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = ydistseperator2;
			distz = ((height * heightmulti) - 10.0) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = ((height * heightmulti) + 10.0) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		}

		if (random(1,12) <= randompick(3,3,4,4,4,4,4,5,5))
		{
			distx = (m * frandom(0.425,0.45));
			disty = ydistseperator1;
			distz = ((height * heightmulti) + 5.0) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = ((height * heightmulti) + 5.0) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = ydistseperator1;
			distz = ((height * heightmulti) - 5.0) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = ((height * heightmulti) - 5.0) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		}
		
		
		if (type == 1) A_GiveGuardBuff(1);
							else A_GiveGuardBuff(0);
	}

	action void A_CricketBatSwing(int type = 0, double dist = 112.0)
	{
		A_BatGuardDashOff();
		string vispart = "CricketSwingPartNoReflect";
		if (random(1,16) <= 5) vispart = "CricketSwingShieldPart";

		double yoffset = frandompick(-0.1625,0,0.1625);

		double distx, disty, distz;
		double heightmulti = 0.5;
		double heightmultivari = 0.125;
		double yseperation = -5.2;
		double sa = sin(angle);
		double ca = cos(angle);
		if (dydudebug_cricketbatguard) Console.Printf("angle sine: %.3f, angle cosine: %.3f", sa, ca);
		double sp = sin(pitch);
		double cp = cos(pitch);
		if (dydudebug_cricketbatguard) Console.Printf("pitch sine: %.3f, pitch cosine: %.3f", sp, cp);
		int m = dist;

		if (type == 1) m *= 1.2;
		int m2 = m;

		distx = (m * frandom(0.95,1.05));
		disty = 0.0;
		distz = (height * heightmulti) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		distx = (m * frandom(0.90,0.95));
		disty = (yseperation * 2);
		distz = (height * heightmulti) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty *= -1;
		distz = (height * heightmulti) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty = yseperation;
		distz = (height * (heightmulti - heightmultivari)) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty *= -1;
		distz = (height * (heightmulti - heightmultivari)) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty = yseperation;
		distz = (height * (heightmulti + heightmultivari)) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty *= -1;
		distz = (height * (heightmulti + heightmultivari)) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);

		if ((random (1,16) <= 14) || (type == 1 && (random (1,32) <= 31)))
		{
			m = (m2 * 0.667);

			distx = (m * frandom(0.95,1.05));
			disty = 0.0;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = (m * frandom(0.90,0.95));
			disty = (yseperation * 2);
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = yseperation;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = yseperation;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		}


		if ((random (1,16) <= 12) || (type == 1 && (random (1,16) <= 15)))
		{
			m = (m2 * 0.334);

			distx = (m * frandom(0.95,1.05));
			disty = 0.0;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = (m * frandom(0.90,0.95));
			disty = (yseperation * 2);
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = yseperation;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = yseperation;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		}
		
		A_GiveGuardBuff(0);
	}
	
	int guardstate;
	int guardtimer, guardtimerlimit;
	int sguardtimeextra;
	int guardcooldown;
	
	int spintimes;
	int spinsoundinc;
	
	action int A_BatDamageSet(int type = 0)
	{
		let MiscItem = PlayerStatItem(Player.mo.FindInventory("PlayerStatItem"));
		int LevelInc = 12;

		int dmg = random(6,8);
		if (MiscItem)
		{
			if (MiscItem.PlayerLevel >= (LevelInc*12)) dmg *= random(7,14);
			else if (MiscItem.PlayerLevel >= (LevelInc*11)) dmg *= random(7,13);
			else if (MiscItem.PlayerLevel >= (LevelInc*10)) dmg *= random(6,13);
			else if (MiscItem.PlayerLevel >= (LevelInc*9)) dmg *= random(6,12);
			else if (MiscItem.PlayerLevel >= (LevelInc*8)) dmg *= random(5,12);
			else if (MiscItem.PlayerLevel >= (LevelInc*7)) dmg *= random(5,11);
			else if (MiscItem.PlayerLevel >= (LevelInc*6)) dmg *= random(4,11);
			else if (MiscItem.PlayerLevel >= (LevelInc*5)) dmg *= random(4,10);
			else if (MiscItem.PlayerLevel >= (LevelInc*4)) dmg *= random(3,10);
			else if (MiscItem.PlayerLevel >= (LevelInc*3)) dmg *= random(3,9);
			else if (MiscItem.PlayerLevel >= (LevelInc*2)) dmg *= random(2,9);
			else if (MiscItem.PlayerLevel >= (LevelInc*1)) dmg *= random(2,8);
			else dmg *= random(1,8);
		}
		else
		{
			dmg *= random(1,8);
		}
		if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) dmg *= 10;
		if (type == 1) // type 1 = Spin attack
		{
			LevelInc = 24;
			if (MiscItem)
			{
				if (MiscItem.PlayerLevel >= (LevelInc*8)) dmg /= frandom(2.0,4.0);
				else if (MiscItem.PlayerLevel >= (LevelInc*7)) dmg /= frandom(2.5,4.0);
				else if (MiscItem.PlayerLevel >= (LevelInc*6)) dmg /= frandom(2.5,4.5);
				else if (MiscItem.PlayerLevel >= (LevelInc*5)) dmg /= frandom(3.0,4.5);
				else if (MiscItem.PlayerLevel >= (LevelInc*4)) dmg /= frandom(3.0,5.0);
				else if (MiscItem.PlayerLevel >= (LevelInc*3)) dmg /= frandom(3.5,5.0);
				else if (MiscItem.PlayerLevel >= (LevelInc*2)) dmg /= frandom(3.5,5.5);
				else if (MiscItem.PlayerLevel >= (LevelInc*1)) dmg /= frandom(4,5.5);
				else dmg /= frandom(4.0,6.0);
			}
			else
			{
				dmg /= frandom(4.0,6.0); 
			}
		}
		if (dydudebug_meleedmg) Console.Printf("dmg: %d", dmg);

		return dmg;
	}
	
	action void A_GuardToggleCountdown()
	{
		if (invoker.guardcooldown) invoker.guardcooldown--;
		if (dydudebug_cricketbatguard) Console.Printf("Countdown (CricketBat): %d", invoker.guardcooldown);
	}

	override void DoEffect()
	{
		super.DoEffect();
		A_GuardToggleCountdown();
	}
	
	action void A_CheckGuardState()
	{
		invoker.buttons = GetPlayerInput(INPUT_BUTTONS);
		if (dydudebug_cricketbatguard) Console.Printf("buttons: %d [GuardState: %d, Cooldown: %d, Timer: %d]", invoker.buttons, invoker.guardstate, invoker.guardcooldown, invoker.guardtimer);
		
		if (invoker.guardcooldown <= 0)
		{
			if (invoker.buttons & BT_USER4 || 
					invoker.buttons & BT_ATTACK || 
					invoker.buttons & BT_ALTATTACK) 
			{
				if (invoker.guardstate == 0) invoker.guardstate = 1;
																else invoker.guardstate = 0;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) invoker.guardcooldown = random(5,7);
																																 else invoker.guardcooldown = random(6,8);
			}
		}
	}
	
	States
	{
		Pickup:
			SPBT A 0;
			SPBT A 0 A_StartSound("misc/w_pkup",CHAN_WEAPON);
			SPBT A 0;
			Fail;

		Spawn:
			SPBT A 6;
			loop;
		Ready:
			DBID A 1 
			{
				A_SetInventory("DoingSpinAttack",0);
				A_BatGuardDashOff();
				A_KickDecelerate();
				A_WeaponReady(WRF_ALLOWUSER4);
			}
			loop;
		Deselect:
			DBID A 1
			{
				A_SetInventory("DoingSpinAttack",0);
				A_BatGuardDashOff();
				A_KickDecelerate();
				A_Lower(12);
			}
			loop;
		Select: 
			DBID A 1
			{
				A_SetInventory("DoingSpinAttack",0);
				A_BatGuardDashOff();
				A_KickDecelerate();
				A_Raise(12);
			}
			loop;
		Fire:
			DBID A 1
			{
				int PlayerLevel;
				int buttons = GetPlayerInput(INPUT_BUTTONS);
				let MiscItem = PlayerStatItem(Player.mo.FindInventory("PlayerStatItem"));
				A_SetInventory("DoingSpinAttack",0);
				A_BatGuardDashOff();
				if (exex_cricketbatcanspinattack)
				{
					if (MiscItem) PlayerLevel = MiscItem.PlayerLevel;
					if (PlayerLevel >= exex_cricketspinlvlrequirement)
					{
						if (buttons & BT_MOVELEFT && buttons & BT_MOVERIGHT)
						{
							return resolvestate("SpinAttackStart");
						}
						return resolvestate(null);
					}
					return resolvestate(null);
				}
				return resolvestate(null);
			}
			DBID B 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			DBID C 1
			{
			}
			DBID D 1 
			{
				A_StartSound("MalletSwing",CHAN_WEAPON);
				if (random(1,32) <= 1 && !CountInv("PlayingStrife",AAPTR_PLAYER1)) { A_AlertMonsters(); }
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			DBID E 1 
			{
				A_GiveGuardBuff(0);
			}
			DBID F 1 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_GiveGuardBuff(0);
			}
			DBID G 1 
			{
				int dmg = A_BatDamageSet(0);
				A_CustomPunch(dmg, true, 0, "BatPuff", 112);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
				{
					A_CricketBatSwing(1);
				}
				else
				{
					A_CricketBatSwing(0);
				}
			}
			DBID H 1 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_GiveGuardBuff(0);
			}
			DBID I 2
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(randompick(0,1,1,1,1,1)); }
				A_GiveGuardBuff(0);
			}
			DBID JCCBA 2
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(randompick(0,1,1,1,1,1)); }
			}
			goto Ready;
		AltFire:
			DBID A 0
			{
				if (!CountInv("MalletAmmo")) { return resolvestate("Fire"); }
				return resolvestate(null);
			}
			DBID A 1
			{
				A_BatGuardDashOff();
			}
			DBID B 1 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			DBID C 1
			{
			}
			DBID D 1
			{
				A_StartSound("MalletSwing",CHAN_WEAPON);
				if (random(1,32) <= 1 && !CountInv("PlayingStrife",AAPTR_PLAYER1)) { A_AlertMonsters(); }
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			DBID E 1
			{
				A_GiveGuardBuff(0);
			}
			DBID F 1 
			{
				A_StartSound("croquet/ballfire",CHAN_WEAPON);
				if (random(1,8) <= 1 && !CountInv("PlayingStrife",AAPTR_PLAYER1)) { A_AlertMonsters(); }
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_GiveGuardBuff(0);
			}
			DBID G 1 
			{
				int dmg = A_BatDamageSet(0);
				A_CustomPunch(dmg, true, 0, "BatPuff", 112);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
				{
					A_FireProjectile("MalletShotBerserk",0,1,0,0);
					A_CricketBatSwing(1);
				}
				else
				{
					A_FireProjectile("MalletShot",0,1,0,0);
					A_CricketBatSwing(0);
				}
				A_TakeInventory("MalletAmmo",1);
			}
			DBID H 1 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
				A_GiveGuardBuff(0);
			}
			DBID I 2 
			{
				A_GiveGuardBuff(0);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			DBID JC 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			DBID BA 3
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(random(1,2)); }
			}
			goto Ready;
		SpinAttackStart:
			DBID B 1
			{
				A_SetInventory("DoingSpinAttack",0);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			DBID C 1
			{
				A_SetInventory("DoingSpinAttack",0);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			DBID D 1
			{
				A_SetInventory("DoingSpinAttack",0);
				A_StartSound("MalletSwing",CHAN_WEAPON);
				if (random(1,32) <= 1 && !CountInv("PlayingStrife",AAPTR_PLAYER1)) { A_AlertMonsters(); }
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			DBID E 1
			{
				A_SetInventory("DoingSpinAttack",0);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			DBID F 1
			{
				A_SetInventory("DoingSpinAttack",0);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			goto SpinAttack;
		SpinAttackPre:
			DBID G 0
			{
				int maxspinsoundinc = 4;
				if (exex_cricketspinattacktype == 1) maxspinsoundinc = 2;
				if (exex_cricketspinattacktype == 2) maxspinsoundinc = 1;
				A_SetInventory("DoingSpinAttack",1);
				invoker.spinsoundinc++;;
				if (invoker.spinsoundinc >= maxspinsoundinc)
				{
					invoker.spinsoundinc = 0;
					A_StartSound("MalletSwing",CHAN_WEAPON);
					if (random(1,32) <= 1 && !CountInv("PlayingStrife",AAPTR_PLAYER1)) { A_AlertMonsters(); }
				}
			}
		SpinAttack:
			DBID G 1
			{
				A_SetInventory("DoingSpinAttack",1);
				let MiscItem = PlayerStatItem(Player.mo.FindInventory("PlayerStatItem"));
				int dmg = A_BatDamageSet(1);
				int range = 112 + (random(0,2) * 8);
				if (MiscItem) { range *= (1.125 + ((MiscItem.PlayerLevel - exex_cricketspinlvlrequirement) * 0.00625)); }

				int maxspintimes = 5;
				for (int i = 0; i < maxspintimes; i++)
				{
					A_SetAngle(angle+22.5);
					//A_FireBullets(0,0,1,dmg,"BatPuffNoSound",FBF_NORANDOM|FBF_NORANDOMPUFFZ|FBF_NOFLASH,range,"",0,0);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_CricketBatSwing(1,range); } else { A_CricketBatSwing(0,range); }
					A_SetAngle(angle+22.5);
					//A_FireBullets(0,0,1,dmg,"BatPuffNoSound",FBF_NORANDOM|FBF_NORANDOMPUFFZ|FBF_NOFLASH,range,"",0,0);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_CricketBatSwing(1,range); } else { A_CricketBatSwing(0,range); }
					A_SetAngle(angle+22.5);
					A_FireBullets(0,0,1,dmg,"BatPuffNoSound",FBF_NORANDOM|FBF_NORANDOMPUFFZ|FBF_NOFLASH,range,"",0,0);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_CricketBatSwing(1,range); } else { A_CricketBatSwing(0,range); }
					A_SetAngle(angle-135);
					A_FireBullets(0,0,1,dmg,"BatPuff",FBF_NORANDOM|FBF_NORANDOMPUFFZ|FBF_NOFLASH,range,"",0,0);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_CricketBatSwing(1,range); } else { A_CricketBatSwing(0,range); }
					A_SetAngle(angle+22.5);
					A_FireBullets(0,0,1,dmg,"BatPuffNoSound",FBF_NORANDOM|FBF_NORANDOMPUFFZ|FBF_NOFLASH,range,"",0,0);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_CricketBatSwing(1,range); } else { A_CricketBatSwing(0,range); }
					A_SetAngle(angle+22.5);
					//A_FireBullets(0,0,1,dmg,"BatPuffNoSound",FBF_NORANDOM|FBF_NORANDOMPUFFZ|FBF_NOFLASH,range,"",0,0);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_CricketBatSwing(1,range); } else { A_CricketBatSwing(0,range); }
					A_SetAngle(angle+22.5);
					//A_FireBullets(0,0,1,dmg,"BatPuffNoSound",FBF_NORANDOM|FBF_NORANDOMPUFFZ|FBF_NOFLASH,range,"",0,0);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_CricketBatSwing(1,range); } else { A_CricketBatSwing(0,range); }
					
					A_SetAngle(angle+6);
				}
				// +30 Degrees per frame [6*5]
				invoker.spintimes += 1;
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			DBID G 0
			{
				int maxspintimes = 3; // 30*3 = 90;
				if (exex_cricketspinattacktype == 1) maxspintimes = 6; // 30*6 = 90;
				if (exex_cricketspinattacktype == 2) maxspintimes = 12; // 30*12 = 90;
				if (invoker.spintimes >= maxspintimes)
				{
					invoker.spintimes = 0;
					int PlayerLevel;
					int buttons = GetPlayerInput(INPUT_BUTTONS);
					let MiscItem = PlayerStatItem(Player.mo.FindInventory("PlayerStatItem"));
					if (MiscItem) PlayerLevel = MiscItem.PlayerLevel;
					if (PlayerLevel >= exex_cricketspinlvlrequirement)
					{
						if (buttons & BT_MOVELEFT && buttons & BT_MOVERIGHT && buttons & BT_ATTACK)
						{
							return resolvestate("SpinAttackPre");
						}
						return resolvestate("SpinAttackEnd");
					}
					return resolvestate(null);
				}
				return resolvestate(null);
			}
			loop;
		SpinAttackEnd:
			DBID H 1
			{
				A_SetInventory("DoingSpinAttack",0);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			DBID I 1
			{
				A_SetInventory("DoingSpinAttack",0);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			DBID J 1
			{
				A_SetInventory("DoingSpinAttack",0);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			TNT1 A 1
			{
				A_SetInventory("DoingSpinAttack",0);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			TNT1 A 1
			{
				A_SetInventory("DoingSpinAttack",0);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			goto Ready;
			
		// Bat Guard
		User4:
			DBIG A 0
			{
				if (exex_cricketbatguardtype == 1)
				{
					if (invoker.guardcooldown) { return resolvestate("Ready"); }
					return resolvestate(null);
				}
				return resolvestate(null);
			}
		Guard:
			DBGR A 1
			{
				if (random(1,4) == 1) { A_GiveGuardBuff(0); }
				A_CheckGuardState();
				A_BatGuardDashOff();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			DBGR B 1
			{
				if (random(1,2) == 1) { A_GiveGuardBuff(0); }
				A_CheckGuardState();
				A_BatGuardDashOff();
			}
			DBGR C 1
			{
				invoker.guardtimerlimit = 7;
				invoker.sguardtimeextra = 0;
				let MiscItem = PlayerStatItem(Player.mo.FindInventory("PlayerStatItem"));
				if (MiscItem)
				{
					if (MiscItem.PlayerLevel >= 160) invoker.guardtimerlimit += random(17,18);
					else if (MiscItem.PlayerLevel >= 112) invoker.guardtimerlimit += random(14,14);
					else if (MiscItem.PlayerLevel >= 72) invoker.guardtimerlimit += random(10,11);
					else if (MiscItem.PlayerLevel >= 40) invoker.guardtimerlimit += random(7,7);
					else if (MiscItem.PlayerLevel >= 16) invoker.guardtimerlimit += random(3,4);

					invoker.sguardtimeextra += (random(0,2) + (MiscItem.PlayerLevel * 0.2));
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
					{
						invoker.sguardtimeextra += (random(2,3) + (MiscItem.PlayerLevel * 0.4));
					}
				}
				if (random(1,4) <= 3) { A_GiveGuardBuff(0); }
				A_CheckGuardState();
				A_BatGuardDashOff();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			goto GuardHold;
		GuardPreSet:
			DBGR D 1
			{
			}
			goto GuardHold;
		GuardHold:
			DBGR D 1
			{
				A_CheckGuardState();
				if (invoker.guardtimer <= (invoker.guardtimerlimit + invoker.sguardtimeextra))
				{
					A_CricketBatGuard(1); // Gives Guaranteed Reflect on the Bat Shield and Elevated Defense for the duration of the above tics [~7] when first entering proper guard stance
					invoker.guardtimer++;
				}
				else
				{
					A_CricketBatGuard(0);
				}
				A_WeaponReady(WRF_NOBOB|WRF_NOFIRE|WRF_NOPRIMARY|WRF_NOSECONDARY|WRF_NOSWITCH);
			}
			DBGR D 0
			{
				if (exex_cricketbatguardtype == 1)
				{
					if (dydudebug_cricketbatguard) Console.Printf("guardtype: %d", exex_cricketbatguardtype);
					if (invoker.guardstate == 0) { return resolvestate("UnGuard"); }
																	else { return resolvestate("GuardHold"); } 

					return resolvestate(null);
				}
				else
				{
					A_Refire("GuardHold");
				}
				return resolvestate(null);
			}
			goto Unguard;
		UnGuard:
			DBGR C 1
			{
				if (random(1,4) <= 3) { A_GiveGuardBuff(0); }
				A_CheckGuardState();
				A_BatGuardDashOff();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			DBGR B 1
			{
				if (random(1,2) == 1) { A_GiveGuardBuff(0); }
				A_CheckGuardState();
				A_BatGuardDashOff();
			}
			DBGR A 1
			{
				if (random(1,4) == 1) { A_GiveGuardBuff(0); }
				A_CheckGuardState();
				A_BatGuardDashOff();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			goto Ready;
	}
}

class BatPuff : DDPuff
{
	default
	{
		Tag "Cricket Bat Smack";
		+NOBLOCKMAP
		+NOGRAVITY
		//+NOEXTREMEDEATH
		+PUFFONACTORS
		+FORCERADIUSDMG
		RenderStyle "Translucent";
		Alpha 0.6;
		SeeSound "MalletHit";
		AttackSound "MalletWall";
		VSpeed 1;
		DamageType "Bonk";
	}
	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				if (random(1,4) == 1) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
		Melee:
			TNT1 A 0
			{
				if (random(1,4) == 1) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
		Crash:
			TNT1 A 0
			{
				if (random(1,4) == 1) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
	}
}

class BatPuffNoSound : BatPuff
{
	default
	{
		Tag "Cricket Bat Smack";
		+NOBLOCKMAP
		+NOGRAVITY
		//+NOEXTREMEDEATH
		+PUFFONACTORS
		+FORCERADIUSDMG
		RenderStyle "Translucent";
		Alpha 0.6;
		SeeSound "";
		AttackSound "";
		VSpeed 1;
		DamageType "Bonk";
	}
	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				if (random(1,4) == 1) { bFORCEPAIN = true; }
			}
			TNT1 A 1 Bright;
			Stop;
		Melee:
			TNT1 A 0
			{
				if (random(1,4) == 1) { bFORCEPAIN = true; }
			}
			TNT1 A 1 Bright;
			Stop;
		Crash:
			TNT1 A 0
			{
				if (random(1,4) == 1) { bFORCEPAIN = true; }
			}
			TNT1 A 1 Bright;
			Stop;
	}
}

class MalletShot : DDProjectile
{
	default
	{
		Tag "Cricket Ball";
		Radius 3;
		Height 3;
		Speed 70;
		Damage 12;
		DamageType "Cricket";
		Projectile;
		-NOGRAVITY
		//+NOEXTREMEDEATH
		+FORCERADIUSDMG
		+USEBOUNCESTATE
		RENDERSTYLE "Normal";
		DeathSound "croquet/ballhit";
		BounceType "Hexen";
		BounceCount 0;
		BounceFactor 0.0;
		WallBounceFactor 0.0;
	}
	
	int minbouncelvl;
	double bouncelvlfactor;
	int nogravtimer;

	override void PostBeginPlay()
	{
		super.PostBeginPlay();
		if (target && target.GetClassName() == "DinahPlayer")
		{
			minbouncelvl = 8;
			bouncelvlfactor = (1.0 / (minbouncelvl * 1.5));

			let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
			if (MiscItem)
			{
				if (MiscItem.PlayerLevel >= minbouncelvl)
				{
					double extratimes = ((MiscItem.PlayerLevel - minbouncelvl) * bouncelvlfactor);
					if (dydudebug_attackstuff) Console.Printf("[%s] extratimes: %.8f", GetClassName(), extratimes);
					if (extratimes < 0) extratimes = 0;
					bSKYEXPLODE = true;
					bBOUNCEONWALLS = true;
					bBOUNCEONFLOORS = true;
					bBOUNCEONCEILINGS = true;
					bCANBOUNCEWATER = true;
					bDONTBOUNCEONSHOOTABLES = true;
					BounceCount = 2 + extratimes;
					BounceFactor = 1.00;
					WallBounceFactor = 1.00;
				}
				else
				{
					bBOUNCEONWALLS = false;
					bBOUNCEONFLOORS = false;
					bBOUNCEONCEILINGS = false;
					bCANBOUNCEWATER = false;
					bDONTBOUNCEONSHOOTABLES = true;
					bALLOWBOUNCEONACTORS = false;
					BounceCount = 0;
					BounceFactor = 0;
					WallBounceFactor = 0;
				}
			}
			if (dydudebug_attackstuff) Console.Printf("[%s] BounceCount: %d", GetClassName(), BounceCount);
		}

		user_randompain = 16;
		if (target && target.GetClassName() == "DinahPlayer")
		{
			let MiscItem = PlayerStatItem(target.player.mo.FindInventory("PlayerStatItem"));
			if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.16);
		}
		if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }
	}
	
	States
	{
		Spawn:
			CBAL AAABBB 1 NoDelay
			{
				if (bNOGRAVITY && nogravtimer) 
				{
					nogravtimer--;
					if (!nogravtimer) bNOGRAVITY = false;
				}
			}
			loop;
		Death:
			CBAL C 0 
			{
				bNOGRAVITY = true;
			}
			CBAL CDEF 4 Bright;
			stop;
		Crash:
			CBAL C 0 
			{
				bNOGRAVITY = true;
			}
			CBAL CDEF 4 Bright;
			stop;
		XDeath:
			TNT1 A 1
			{
				bNOGRAVITY = true;
			}
			stop;
		Bounce:
			TNT1 A 0
			{
				bNOGRAVITY = false;
			}
			goto Spawn;
	}
}

class MalletShotBerserk : DDFastProjectile
{
	default
	{
		Tag "-Cricket Ball-";
		Radius 3;
		Height 3;
		Speed 140;
		Damage 60;
		DamageType "Cricket";
		Projectile;
		-NOGRAVITY
		+FORCERADIUSDMG
		//+NOEXTREMEDEATH
		RENDERSTYLE "Normal";
		DeathSound "croquet/ballhit";
	}
	
	int minbouncelvl;
	double bouncelvlfactor;
	int nogravtimer;
	
	int A_GetImpactAOE(int type = 0)
	{
		int result;
		if (type == 0) result = 16; // Damage
		if (type == 1) result = 24; // Radius
		if (target && target.GetClassName() == "DinahPlayer")
		{
			let MiscItem = PlayerStatItem(target.FindInventory("PlayerStatItem"));
			if (MiscItem)
			{
				if (type == 0) result += (MiscItem.PlayerLevel * 0.09375);
				if (type == 1) result += (MiscItem.PlayerLevel * 0.125);
				if (MiscItem.PlayerLevel >= 50)
				{
					if (type == 0) result += (MiscItem.PlayerLevel * 0.046875);
					if (type == 1) result += (MiscItem.PlayerLevel * 0.0625);
				}
				if (MiscItem.PlayerLevel >= 100)
				{
					if (type == 0) result += (MiscItem.PlayerLevel * 0.0234375);
					if (type == 1) result += (MiscItem.PlayerLevel * 0.03125);
				}
			}
		}
		if (dydudebug_attackstuff) Console.Printf("[%s] result: %d, type: %d", GetClassName(), result, type);
		return result;
	}
	
	States
	{
		Spawn:
			CBAL AAABBB 1 NoDelay
			{
				if (bNOGRAVITY && nogravtimer) 
				{
					nogravtimer--;
					if (!nogravtimer) bNOGRAVITY = false;
				}
			}
			loop;
		Death:
			CBAL C 0 
			{
				bNOGRAVITY = true;
				A_Explode(A_GetImpactAOE(0),A_GetImpactAOE(1),0,0,(A_GetImpactAOE(1)*0.34));
			}
			CBAL CDEF 4 Bright;
			stop;
		Crash:
			CBAL C 0 
			{
				A_Explode(A_GetImpactAOE(0),A_GetImpactAOE(1),0,0,(A_GetImpactAOE(1)*0.34));
				bNOGRAVITY = true;
			}
			CBAL CDEF 4 Bright;
			stop;
		XDeath:
			TNT1 A 1
			{
				A_Explode(A_GetImpactAOE(0),A_GetImpactAOE(1),0,0,(A_GetImpactAOE(1)*0.34));
				bNOGRAVITY = true;
			}
			stop;
	}
}

class MalletAmmo : Ammo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 2; // 3
		Inventory.MaxAmount 60; // 45
		Ammo.BackpackAmount 2; // 3
		Ammo.BackpackMaxAmount 90;
		Inventory.Icon "CBAMI0";
		Inventory.PickupMessage "A cricket ball";
		+FLOATBOB
	}
	
	States
	{
		Spawn:
			CBAM A -1;
			Loop;
	}
}

class MalletAmmoBig : MalletAmmo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 6; // 3
		Inventory.MaxAmount 60; // 45
		Ammo.BackpackAmount 6; // 3
		Ammo.BackpackMaxAmount 90;
		Inventory.Icon "CBAMI0";
		Inventory.PickupMessage "A set of cricket balls";
		+FLOATBOB
	}
	
	States
	{
		Spawn:
			CBAM B -1;
			Loop;
	}
}

//**************
//* Blunderaxe *
//**************
class Blunderaxe : DinahWeapon replaces Shotgun
{
	double rrecoil;
	default
	{
		//$Category RPWeapons
		Weapon.SelectionOrder 200;
		Weapon.SlotNumber 3;
		Weapon.Kickback 40;
		Weapon.AmmoType2 "BlunderAmmo";
		Weapon.AmmoGive2 6;
		//Weapon.AmmoUse2 0;
		+WEAPON.NOALERT
		+WEAPON.MELEEWEAPON
		+PUFFONACTORS
		+FLOATBOB
		Inventory.Icon "BLAXP0";
		Inventory.PickupMessage "Blunderaxe";
		inventory.pickupsound "misc/w_pkup"; //"Dinah/marvelous"
		Tag "Blunderaxe: Normal fire chops enemies in melee. Alt-fire shoots a spread of Blundershot. Chop attack occasionally inflicts a defensive debuff [up to 4 tiers] on enemies.";
		Obituary "%k used %o for target practice.";
	}
	
	States
	{
		Spawn:
			BLAX P 0 NoDelay;
			BLAX P 0 
			{
				if (bDROPPED) { SetStateLabel("Dropp"); }
			}
			BLAX P 0
			{
				if (random(1,8) == 1)
				{
					A_SpawnItemEx("Scrambler",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION);
					Thing_Remove(0); 
				}
			}
			goto Idle;
		Dropp:
			BLAX P 0
			{
				if (random(1,64) == 1)
				{
					A_SpawnItemEx("Scrambler",0.0,0.0,0.0,0.0,0.0,0.0,SXF_NOCHECKPOSITION);
					Thing_Remove(0); 
				}
			}
			goto Idle;

		Idle:
			BLAX P 6;
			loop;
		Ready:
			BLAX A 1 
			{
				A_KickDecelerate();
				A_WeaponReady();
			}
			loop;
		Deselect:
			BLAX A 1
			{
				A_KickDecelerate();
				A_Lower(12);
			}
			loop;
		Select: 
			BLAX A 1
			{
				A_KickDecelerate();
				A_Raise(12);
			}
			loop;
		Fire:
			BLAX D 1;
			BLAX F 1;
			TNT1 A 1;
			BLAX G 2 
			{
				A_StartSound("Blunderswing",CHAN_WEAPON);
				if (random(1,32) <= 1 && !CountInv("PlayingStrife",AAPTR_PLAYER1)) { A_AlertMonsters(); }
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			BLAX HI 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			BLAX J 2 
			{
				int dmg = (random(16,20) * random(1,8));
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) dmg *= 10;
				if (dydudebug_meleedmg) Console.Printf("dmg: %d", dmg);
				A_CustomPunch(dmg, true, 0, "BlunderPuff", 96);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
				{
					A_SetTics(1);
				}
				else
				{
				}
			}
			BLAX KLMN 3 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(random(1,2)); }
			}
			BLAX O 4
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(randompick(1,2,2,3,3,3)); }
			}
			goto Ready;
		AltFire:
			BLAX A 0
			{
				if (!CountInv("BlunderAmmo")) { return resolvestate("Fire"); }
				return resolvestate(null);
			}
			BLAX A 0 
			{
				A_StartSound("blunderfire",CHAN_WEAPON);
				if (random(1,32) <= 31) { A_AlertMonsters(); }
			}
			BLAX B 3 Bright
			{
				if (CountInv("BlunderShotUpgrade") >= 3)
				{
					if (random(1,4) <= 1)
					{
						A_FireProjectile("BlunderShot",random(-1,1),0,0,0,0,random(-1,1));
						A_FireProjectile("BlunderShot",random(-3,3),0,0,0,0,random(-1,1));
					}
					if (random(1,12) <= 1)
					{
						A_FireProjectile("BlunderShot",random(-1,1),0,0,0,0,random(-2,2));
						A_FireProjectile("BlunderShot",random(-7,7),0,0,0,0,random(-2,2));
					}
				}
				else
				if (CountInv("BlunderShotUpgrade") >= 2)
				{
					if (random(1,8) <= 1)
					{
						A_FireProjectile("BlunderShot",random(-1,1),0,0,0,0,random(-1,1));
						A_FireProjectile("BlunderShot",random(-5,5),0,0,0,0,random(-1,1));
					}
					if (random(1,16) <= 1)
					{
						A_FireProjectile("BlunderShot",random(-1,1),0,0,0,0,random(-2,2));
						A_FireProjectile("BlunderShot",random(-9,9),0,0,0,0,random(-2,2));
					}
				}
				else
				if (CountInv("BlunderShotUpgrade") >= 1)
				{
					if (random(1,12) <= 1)
					{
						A_FireProjectile("BlunderShot",random(-1,1),0,0,0,0,random(-2,2));
						A_FireProjectile("BlunderShot",random(-7,7),0,0,0,0,random(-2,2));
					}
				}
				else
				{
					if (random(1,16) <= 1)
					{
						A_FireProjectile("BlunderShot",random(-1,1),0,0,0,0,random(-2,2));
						A_FireProjectile("BlunderShot",random(-9,9),0,0,0,0,random(-2,2));
					}
				}
				if (CountInv("BlunderShotUpgrade") >= 3) { A_FireProjectile("BlunderShot",random(-2,2),0,0,0,0,random(-2,2)); }
				A_FireProjectile("BlunderShot",random(-3,3),0,0,0,0,random(-1,1));
				if (CountInv("BlunderShotUpgrade") >= 1) { A_FireProjectile("BlunderShot",random(-4,4),0,0,0,0,random(-1,1)); }
				A_FireProjectile("BlunderShot",random(-5,5),0,0,0,0,random(-1,1));
				if (CountInv("BlunderShotUpgrade") >= 1) { A_FireProjectile("BlunderShot",random(-6,6),0,0,0,0,random(-1,1)); }
				A_FireProjectile("BlunderShot",random(-7,7),0,0,0,0,random(-1,1));
				if (CountInv("BlunderShotUpgrade") >= 3) { A_FireProjectile("BlunderShot",random(-8,8),0,0,0,0,random(-2,2)); }
				
				invoker.rrecoil = frandom(4.8,7.2) * (1.0 + (CountInv("BlunderShotUpgrade") * 0.125));
				//Console.Printf("%.8f", invoker.rrecoil);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) invoker.rrecoil *= 0.2;
				A_Recoil(invoker.rrecoil);
				A_TakeInventory("BlunderAmmo",1);
			}
			BLAX C 3 Bright
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					if (CountInv("BlunderShotUpgrade") >= 3)
					{
						A_SetTics(random(3,4));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 2)
					{
						A_SetTics(random(2,3));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 1)
					{
						A_SetTics(random(1,3));
					}
					else
					{
						A_SetTics(random(1,2));
					}
				} 
				else 
				{
					if (CountInv("BlunderShotUpgrade") >= 3) 
					{
						A_SetTics(randompick(4,4,5));
					}
					else if (CountInv("BlunderShotUpgrade") >= 2) 
					{
						A_SetTics(randompick(3,4,4));
					}
					else if (CountInv("BlunderShotUpgrade") >= 1) 
					{
						A_SetTics(randompick(3,4));
					}
					else 
					{
						A_SetTics(randompick(3,3));
					}
				}
			}
			BLAX DE 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					if (CountInv("BlunderShotUpgrade") >= 3)
					{
						A_SetTics(randompick(3,4,4,4));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 2)
					{
						A_SetTics(randompick(2,2,3,3));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 1)
					{
						A_SetTics(randompick(1,2,2,2));
					}
					else
					{
						A_SetTics(randompick(0,1,1,2));
					}
				}
				else
				{
					if (CountInv("BlunderShotUpgrade") >= 3)
					{
						A_SetTics(randompick(4,4,5,5,5)); 
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 2)
					{
						A_SetTics(randompick(3,3,4)); 
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 1)
					{
						A_SetTics(randompick(2,3,3)); 
					}
					else
					{
						A_SetTics(randompick(2,2)); 
					}
				}
			}
			BLAX FF 7
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					if (CountInv("BlunderShotUpgrade") >= 3)
					{
						A_SetTics(randompick(5,6,6,6));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 2)
					{
						A_SetTics(randompick(4,4,5,5));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 1)
					{
						A_SetTics(randompick(3,4,4,4));
					}
					else
					{
						A_SetTics(randompick(3,4));
					}
				}
				else
				{
					if (CountInv("BlunderShotUpgrade") >= 3)
					{
						A_SetTics(randompick(9,9,10));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 2)
					{
						A_SetTics(randompick(8,8,9));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 1)
					{
						A_SetTics(randompick(7,8,8));
					}
					else
					{
						A_SetTics(randompick(7,7));
					}
				}
			}
			BLAX D 8
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					if (CountInv("BlunderShotUpgrade") >= 3)
					{
						A_SetTics(randompick(6,6,7));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 2)
					{
						A_SetTics(randompick(5,5,6));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 1)
					{
						A_SetTics(randompick(4,4,5));
					}
					else
					{
						A_SetTics(random(3,5));
					}
				}
				else
				{
					if (CountInv("BlunderShotUpgrade") >= 3)
					{
						A_SetTics(randompick(10,11,11));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 2)
					{
						A_SetTics(randompick(9,9,10));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 1)
					{
						A_SetTics(randompick(8,8,9));
					}
					else
					{
						A_SetTics(randompick(8,8));
					}
				}
			}
			BLAX A 9 
			{
				A_Refire();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					if (CountInv("BlunderShotUpgrade") >= 3)
					{
						A_SetTics(randompick(5,6,6));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 2)
					{
						A_SetTics(randompick(5,5,6));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 1)
					{
						A_SetTics(randompick(4,5,5));
					}
					else
					{
						A_SetTics(random(4,5));
					}
				}
				else
				{
					if (CountInv("BlunderShotUpgrade") >= 3)
					{
						A_SetTics(randompick(11,11,12));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 2)
					{
						A_SetTics(randompick(10,10,11));
					}
					else
					if (CountInv("BlunderShotUpgrade") >= 1)
					{
						A_SetTics(randompick(9,10,10));
					}
					else
					{
						A_SetTics(randompick(9,9));
					}
				}
			}
			goto Ready;
	}
}

class BlunderPuff : DDPuff
{
	default
	{
		Tag "BlunderAxe Chop";
		+NOBLOCKMAP
		+NOGRAVITY
		//+NOEXTREMEDEATH
		+PUFFONACTORS
		RenderStyle "Translucent";
		Alpha 0.6;
		SeeSound "MalletHit";
		AttackSound "MalletWall";
		VSpeed 1;
		DamageType "Chop";
	}
	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				if (random(1,6) == 1) { bFORCEPAIN = true; }
			}
			CHOP ABC 4 Bright;
			Stop;
		Melee:
			TNT1 A 0
			{
				if (random(1,6) == 1) { bFORCEPAIN = true; }
			}
			CHOP ABC 4 Bright;
			Stop;
		Crash:
			TNT1 A 0
			{
				if (random(1,6) == 1) { bFORCEPAIN = true; }
			}
			CHOP ABC 4 Bright;
			Stop;
	}
}  

class BlunderShot : DDProjectile
{
	default
	{
		Tag "BlunderShot";
		Radius 3;
		Height 3;
		Speed 70;
		DamageFunction (finaldamagedealt);
		Scale 0.5;
		DamageType "Lead";
		Projectile;
		RENDERSTYLE "Normal";
		SeeSound "blundershot";
		//+NOEXTREMEDEATH
		+FORCERADIUSDMG
	}
	
	override void PostBeginPlay()
	{
		finaldamagedealt = (4 * random(2,16));
		A_SetSize(3,3);
		if (target && target.CountInv("BlunderShotUpgrade"))
		{
			if (target.CountInv("BlunderShotUpgrade") >= 3) 
			{
				finaldamagedealt = (4 * (random(11,16) + randompick(0,0,1,1,2,2,3))); // 44-76
				A_SetSize(1,2);
			}
			else if (target.CountInv("BlunderShotUpgrade") >= 2) 
			{
				finaldamagedealt = (4 * (random(7,16) + randompick(0,1,2))); // 28-68
				A_SetSize(2,2);
			}
			else if (target.CountInv("BlunderShotUpgrade") >= 1) 
			{
				finaldamagedealt = (4 * (random(4,16) + randompick(0,0,1))); // 16-68
				A_SetSize(2,3);
			}
		}
		if (dydudebug_rangedmg) Console.Printf("damage: %d", finaldamagedealt);
		Super.PostBeginPlay();
	}
	
	States
	{
		Spawn:
			BSHT AB 3;
			loop;
		Death:
			BBOM A 0
			{
				if (target && target.CountInv("BlunderShotUpgrade"))
				{
					if (target.CountInv("BlunderShotUpgrade") >= 3) { A_Explode(8,32,0,0,8); }
					if (target.CountInv("BlunderShotUpgrade") == 2) { A_Explode(4,16,0,0,4); }
					if (target.CountInv("BlunderShotUpgrade") == 1) { A_Explode(2,8,0,0,2); }
				}
			}
			BBOM A 4 Bright;
			BBOM BCD 4 Bright;
			stop;
		Crash:
			BBOM A 0
			{
				if (target && target.CountInv("BlunderShotUpgrade"))
				{
					if (target.CountInv("BlunderShotUpgrade") >= 3) { A_Explode(16,16,0,0,8); }
					if (target.CountInv("BlunderShotUpgrade") == 2) { A_Explode(8,8,0,0,4); }
					if (target.CountInv("BlunderShotUpgrade") == 1) { A_Explode(4,4,0,0,2); }
				}
			}
			BBOM A 4 Bright;
			BBOM BCD 4 Bright;
			stop;
		XDeath:
			TNT1 A 1 
			{
				bNOGRAVITY = true;
			}
			stop;
	}
}

class BadBlundershot : Blundershot
{
	default
	{
		Speed 35;
		Damage 5;
		+FORCERADIUSDMG
	}
}

class BlunderAmmo : Ammo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 3; // 6
		Inventory.MaxAmount 48; // 36
		Ammo.BackpackAmount 3; // 6
		Ammo.BackpackMaxAmount 72;
		Inventory.Icon "BAMOI0";
		Inventory.PickupMessage "A fistful of blundershot";
		+FLOATBOB
	}
	States
	{
		Spawn:
			BAMO ABCD 5;
			Loop;
	}
}

class BlunderAmmoBig : BlunderAmmo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 9; // 6
		Inventory.MaxAmount 48; // 36
		Ammo.BackpackAmount 9; // 6
		Ammo.BackpackMaxAmount 72;
		Inventory.Icon "BAMOI0";
		Inventory.PickupMessage "A cluster of blundershot";
		+FLOATBOB
	}
	States
	{
		Spawn:
			BAMO EFGH 5;
			Loop;
	}
}

//*************
//* Scrambler *
//*************
class ScramblerSwingShieldPart : SwingShieldPart
{
	default
	{
		-AIMREFLECT
		+DEFLECT
		Radius 8; // out of 32
		Height 16; // out of 32
		Scale 0.5;
	}
	
	states
	{
		Spawn:
			HEXA C 2 bright NoDelay
			{
				//A_SetTics(randompick(1,2,2,2,3));
				//if (CountInv("PlayingDoom64")) { A_SetSize(19,19); }
			}
			stop;
		Pain:
			TNT1 A 1 bright 
			{
				//A_StartSound("CricketBat/ShieldHit", CHAN_WEAPON);
			}
			stop;
	}
}

class ScramblerSwingPartNoReflect : SwingShieldPartNoReflect
{
	default
	{
		Radius 8; // out of 32
		Height 16; // out of 32
		Scale 0.5;
	}
	
	states
	{
		Spawn:
			HEXA A 2 bright NoDelay
			{
				//A_SetTics(randompick(1,2,2,2,3));
				//if (CountInv("PlayingDoom64")) { A_SetSize(19,19); }
			}
			stop;
		Pain:
			TNT1 A 1 bright 
			{
				//A_StartSound("CricketBat/ShieldHit", CHAN_WEAPON);
			}
			stop;
	}
}

class Scrambler : DinahWeapon replaces SuperShotgun
{
	default
	{
		//$Category RPWeapons
		Weapon.SelectionOrder 300;
		Weapon.SlotNumber 3;
		Weapon.Kickback 75;
		Weapon.AmmoType2 "EggAmmo";
		Weapon.AmmoGive2 3;
		//Weapon.AmmoUse2 1;
		+WEAPON.NOALERT
		+WEAPON.MELEEWEAPON
		+PUFFONACTORS
		+FLOATBOB
		Inventory.Icon "FPANP0";
		Inventory.Pickupsound "DinahWeap";
		Inventory.PickupMessage "Scrambler";
		inventory.pickupsound "misc/w_pkup"; //"Dinah/marvelous"
		Tag "Scrambler: Normal attack is a melee whack. Alt-attack throws a fractal egg that splits into multiple smaller ones. Melee occasionally 'confuses' enemies, lessing their chance to attack. Swings can also affect enemy projectiles.";
		Obituary "%k scored a point with %o.";
	}
	
	action void A_ScramblerSwing(int type = 0, double dist = 72.0)
	{
		string vispart = "ScramblerSwingPartNoReflect";
		if (random(1,32) <= random(10,12)) vispart = "ScramblerSwingShieldPart";

		double yoffset = frandompick(-0.1625,0,0.1625);

		double distx, disty, distz;
		double heightmulti = 0.5;
		double heightmultivari = 0.2;
		double yseperation = -7.6;
		double sa = sin(angle);
		double ca = cos(angle);
		if (dydudebug_cricketbatguard) Console.Printf("angle sine: %.3f, angle cosine: %.3f", sa, ca);
		double sp = sin(pitch);
		double cp = cos(pitch);
		if (dydudebug_cricketbatguard) Console.Printf("pitch sine: %.3f, pitch cosine: %.3f", sp, cp);
		int m = dist;

		if (type == 1) m *= 1.334;
		int m2 = m;

		distx = (m * frandom(0.95,1.05));
		disty = 0.0;
		distz = (height * heightmulti) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		distx = (m * frandom(0.90,0.95));
		disty = (yseperation * 2);
		distz = (height * heightmulti) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty *= -1;
		distz = (height * heightmulti) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty = yseperation;
		distz = (height * (heightmulti - heightmultivari)) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty *= -1;
		distz = (height * (heightmulti - heightmultivari)) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty = yseperation;
		distz = (height * (heightmulti + heightmultivari)) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		disty *= -1;
		distz = (height * (heightmulti + heightmultivari)) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);

		if ((random (1,64) <= 63) || (type == 1 && (random (1,512) <= 511)))
		{
			m = (m2 * 0.667);

			distx = (m * frandom(0.95,1.05));
			disty = 0.0;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = (m * frandom(0.90,0.95));
			disty = (yseperation * 2);
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = yseperation;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = yseperation;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		}


		if ((random (1,32) <= 27) || (type == 1 && (random (1,256) <= 253)))
		{
			m = (m2 * 0.334);

			distx = (m * frandom(0.95,1.05));
			disty = 0.0;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = (m * frandom(0.90,0.95));
			disty = (yseperation * 2);
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = yseperation;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = yseperation;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		}

		let MiscItem = PlayerStatItem(player.mo.FindInventory("PlayerStatItem"));
		if (MiscItem) MiscItem.CricketBatSwingBuffTimer = randompick(3,3,3,3,3,3,4,4,4);
	}
	
	States
	{
		Spawn:
			FPAN P 6;
			loop;
		Ready:
			FPAN A 1 
			{
				A_KickDecelerate();
				A_WeaponReady();
			}
			loop;
		Deselect:
			FPAN A 1
			{
				A_KickDecelerate();
				A_Lower(12);
			}
			loop;
		Select: 
			FPAN A 1
			{
				A_KickDecelerate();
				A_Raise(12);
			}
			loop;
		Fire:
			FPAN A 2
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			FPAN B 2 
			{
				A_StartSound("MalletSwing",CHAN_WEAPON);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
				if (random(1,32) <= 1 && !CountInv("PlayingStrife",AAPTR_PLAYER1)) { A_AlertMonsters(); }
			}
			FPAN C 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_SetTics(1); 
					A_ScramblerSwing(1);
				}
				else
				{
					A_ScramblerSwing(0);
				}
			}
			FPAN D 2 
			{
				int dmg = (random(10,12) * random(1,8));
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) dmg *= 10;
				if (dydudebug_meleedmg) Console.Printf("dmg: %d", dmg);
				A_CustomPunch(dmg, true, 0, "PanPuff", 72);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
				{
					A_SetTics(1);
					A_ScramblerSwing(1);
				}
				else
				{
					A_ScramblerSwing(0);
				}
			}
			FPAN E 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_SetTics(1); 
					A_ScramblerSwing(1);
				}
				else
				{
					A_ScramblerSwing(0);
				}
			}
			FPAN FG 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			TNT1 A 5
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(random(2,3)); }
			}
			FPAN B 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(random(0,1)); }
			}
			goto Ready;
		AltFire:
			FPAN A 0
			{
				if (!CountInv("EggAmmo")) { return resolvestate("Fire"); }
				return resolvestate(null);
			}
			FPAN A 2
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			FPAN B 2 
			{
				A_StartSound("MalletSwing",CHAN_WEAPON);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
				if (random(1,8) <= 1 && !CountInv("PlayingStrife",AAPTR_PLAYER1)) { A_AlertMonsters(); }
			}
			FPAN C 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_SetTics(1); 
					A_ScramblerSwing(1);
				}
				else
				{
					A_ScramblerSwing(0);
				}
			}
			FPAN D 2 
			{
				A_StartSound("panclang",CHAN_WEAPON);

				int dmg = (random(10,12) * random(1,8));
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) dmg *= 10;
				if (dydudebug_meleedmg) Console.Printf("dmg: %d", dmg);
				A_CustomPunch(dmg, true, 0, "PanPuff", 72);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
				{
					A_SetTics(1);
					A_ScramblerSwing(1);
					A_FireProjectile("EggShotBerserk",0,1,0,0);
				}
				else
				{
					A_ScramblerSwing(0);
					A_FireProjectile("EggShot",0,1,0,0);
				}
				A_TakeInventory("EggAmmo",1);
			}
			FPAN E 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_SetTics(1); 
					A_ScramblerSwing(1);
				}
				else
				{
					A_ScramblerSwing(0);
				}
			}
			FPAN FG 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			TNT1 A 5
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(random(2,3)); }
			}
			FPAN B 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(random(0,1)); }
			}
			goto Ready;
	}
}

class PanPuff : DDPuff
{
	default
	{
		Tag "Scrambler Whack";
		+NOBLOCKMAP
		+NOGRAVITY
		//+NOEXTREMEDEATH
		+PUFFONACTORS
		+FORCERADIUSDMG
		RenderStyle "Translucent";
		Alpha 0.6;
		SeeSound "PanClang";
		AttackSound "PanClang";
		VSpeed 1;
		DamageType "Bonk";
	}
	
	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				if (random(1,5) == 1) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
		Melee:
			TNT1 A 0
			{
				if (random(1,5) == 1) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
		Crash:
			TNT1 A 0
			{
				if (random(1,5) == 1) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
	}
}

class EggShot : DDProjectile
{
	bool success;
	actor EggShots;
	default
	{
		Tag "Large Fractal Egg";
		Radius 3;
		Height 3;
		Speed 70;
		Damage 12;
		DamageType "Breakfast";
		Scale 2;
		Projectile;
		-NOGRAVITY
		//+NOEXTREMEDEATH
		RENDERSTYLE "Normal";
		DeathSound "blunderfire";
		Explosiondamage 96;
	}

	States
	{
		Spawn:
			EGGM ABCDE 3;
			loop;
		Death:
			TNT1 A 0 
			{
				A_CheckHitCeiling();
				bNOGRAVITY = true;
				A_AlertMonsters();
				target = PlayerPawn(players[0].mo);
				if (target && dydudebug_eggfractals) Console.Printf("\c[fire]target [%s]:\c- %s", GetClassName(), target.GetClassName());
			}
			EGBL A 4 Bright A_Explode(24,96);
			EGBL B 1 Bright 
			{
				if (hitaceiling) { [success, EggShots] = A_Throwgrenade("EggGrenade",-2,random(1,6),random(-12,-6),0); }
										else { [success, EggShots] = A_Throwgrenade("EggGrenade",2,random(1,6),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShots) // && success) 
				{
					EggShots.target = PlayerPawn(players[0].mo); // EggShots.target = self.target;
					if (EggShots.target && dydudebug_eggfractals) Console.Printf("EggShots.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShots.target.GetClassName());
				}
			}
			EGBL B 1 Bright
			{
				if (hitaceiling) { [success, EggShots] = A_Throwgrenade("EggGrenade",-2,random(1,8),random(-12,-6),0); }
										else { [success, EggShots] = A_Throwgrenade("EggGrenade",2,random(1,8),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShots) // && success) 
				{
					EggShots.target = PlayerPawn(players[0].mo); // EggShots.target = self.target;
					if (EggShots.target && dydudebug_eggfractals) Console.Printf("EggShots.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShots.target.GetClassName());
				}
			}
			EGBL B 1 Bright
			{
				if (hitaceiling) { [success, EggShots] = A_Throwgrenade("EggGrenade",-2,random(1,8),random(-12,-6),0); }
										else { [success, EggShots] = A_Throwgrenade("EggGrenade",2,random(1,8),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShots) // && success) 
				{
					EggShots.target = PlayerPawn(players[0].mo); // EggShots.target = self.target;
					if (EggShots.target && dydudebug_eggfractals) Console.Printf("EggShots.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShots.target.GetClassName());
				}
			}
			EGBL B 1 Bright 
			{
				if (hitaceiling) { [success, EggShots] = A_Throwgrenade("EggGrenade",-2,random(1,10),random(-12,-6),0); }
										else { [success, EggShots] = A_Throwgrenade("EggGrenade",2,random(1,10),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShots) // && success) 
				{
					EggShots.target = PlayerPawn(players[0].mo); // EggShots.target = self.target;
					if (EggShots.target && dydudebug_eggfractals) Console.Printf("EggShots.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShots.target.GetClassName());
				}
			}
			EGBL C 4 Bright;
			Stop;
	}
}

class EggShotBerserk : EggShot
{
	default
	{
		Tag "-Large Fractal Egg-";
		Radius 3;
		Height 3;
		Speed 140;
		Damage 60;
		DamageType "Breakfast";
		Scale 2;
		Projectile;
		-NOGRAVITY
		//+NOEXTREMEDEATH
		RENDERSTYLE "Normal";
		DeathSound "blunderfire";
		Explosiondamage 480;
	}
	
	States
	{
		Spawn:
			EGGM ABCDE 3;
			loop;
		Death:
			TNT1 A 0 
			{
				A_CheckHitCeiling();
				bNOGRAVITY = true;
				A_AlertMonsters();
				target = PlayerPawn(players[0].mo);
				if (target && dydudebug_eggfractals) Console.Printf("\c[fire]target [%s]:\c- %s", GetClassName(), target.GetClassName());
			}
			EGBL A 4 Bright A_Explode(120,96);
			EGBL B 1 Bright 
			{
				if (hitaceiling) { [success, EggShots] = A_Throwgrenade("EggGrenadeBerserk",-37,random(1,6),random(-12,-6),0); }
										else { [success, EggShots] = A_Throwgrenade("EggGrenadeBerserk",2,random(1,6),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShots) // && success) 
				{
					EggShots.target = PlayerPawn(players[0].mo); // EggShots.target = self.target;
					if (EggShots.target && dydudebug_eggfractals) Console.Printf("EggShots.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShots.target.GetClassName());
				}
			}
			EGBL B 1 Bright
			{
				if (hitaceiling) { [success, EggShots] = A_Throwgrenade("EggGrenadeBerserk",-37,random(1,8),random(-12,-6),0); }
										else { [success, EggShots] = A_Throwgrenade("EggGrenadeBerserk",2,random(1,8),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShots) // && success) 
				{
					EggShots.target = PlayerPawn(players[0].mo); // EggShots.target = self.target;
					if (EggShots.target && dydudebug_eggfractals) Console.Printf("EggShots.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShots.target.GetClassName());
				}
			}
			EGBL B 1 Bright
			{
				if (hitaceiling) { [success, EggShots] = A_Throwgrenade("EggGrenadeBerserk",-37,random(1,8),random(-12,-6),0); }
										else { [success, EggShots] = A_Throwgrenade("EggGrenadeBerserk",2,random(1,8),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShots) // && success) 
				{
					EggShots.target = PlayerPawn(players[0].mo); // EggShots.target = self.target;
					if (EggShots.target && dydudebug_eggfractals) Console.Printf("EggShots.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShots.target.GetClassName());
				}
			}
			EGBL B 1 Bright 
			{
				if (hitaceiling) { [success, EggShots] = A_Throwgrenade("EggGrenadeBerserk",-37,random(1,10),random(-12,-6),0); }
										else { [success, EggShots] = A_Throwgrenade("EggGrenadeBerserk",2,random(1,10),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShots) // && success) 
				{
					EggShots.target = PlayerPawn(players[0].mo); // EggShots.target = self.target;
					if (EggShots.target && dydudebug_eggfractals) Console.Printf("EggShots.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShots.target.GetClassName());
				}
			}
			EGBL C 4 Bright;
			Stop;
	}
}

class EggGrenade : DDProjectile
{
	bool success;
	actor EggShot;
	default
	{
		Tag "Fractal Egg";
		Radius 3;
		Height 3;
		Speed 10;
		Damage 9;
		DamageType "Breakfast";
		Scale 1.5;
		Projectile;
		-NOGRAVITY
		//+NOEXTREMEDEATH
		+FORCERADIUSDMG
		RENDERSTYLE "Normal";
		DeathSound "blunderfire";
		ExplosionDamage 64;
		BounceCount 1;
	}
	States
	{
		Spawn:
			EGGM ABCDE 3;
			loop;
		Death:
			TNT1 A 0 
			{
				A_CheckHitCeiling();
				bNOGRAVITY = true;
				target = PlayerPawn(players[0].mo);
				if (target && dydudebug_eggfractals) Console.Printf("\c[fire]target [%s]:\c- %s", GetClassName(), target.GetClassName());
			}
			EGBL A 5 Bright A_Explode(64,64);
			EGBL B 1 Bright 
			{
				if (hitaceiling) { [success, EggShot] = A_Throwgrenade("EggMini",-37,random(1,8),random(-12,-6),0); }
										else { [success, EggShot] = A_Throwgrenade("EggMini",2,random(1,8),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShot) // && success) 
				{
					EggShot.target = self.target;
					if (EggShot.target && dydudebug_eggfractals) Console.Printf("EggShot.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShot.target.GetClassName());
				}
			}
			EGBL B 1 Bright 
			{
				if (hitaceiling) { [success, EggShot] = A_Throwgrenade("EggMini",-37,random(1,10),random(-12,-6),0); }
										else { [success, EggShot] = A_Throwgrenade("EggMini",2,random(1,10),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShot) // && success) 
				{
					EggShot.target = self.target;
					if (EggShot.target && dydudebug_eggfractals) Console.Printf("EggShot.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShot.target.GetClassName());
				}
			}
			EGBL C 4 Bright;
			Stop;
	}
}

class EggGrenadeBerserk : EggGrenade
{
	default
	{
		Tag "-Fractal Egg-";
		Radius 3;
		Height 3;
		Speed 15;
		Damage 23;
		DamageType "Breakfast";
		Scale 1.5;
		Projectile;
		-NOGRAVITY
		//+NOEXTREMEDEATH
		+FORCERADIUSDMG
		RENDERSTYLE "Normal";
		DeathSound "blunderfire";
		ExplosionDamage 160;
		BounceCount 1;
	}
	States
	{
		Spawn:
			EGGM ABCDE 3;
			loop;
		Death:
			TNT1 A 0 
			{
				A_CheckHitCeiling();
				bNOGRAVITY = true;
				target = PlayerPawn(players[0].mo);
				if (target && dydudebug_eggfractals) Console.Printf("\c[fire]target [%s]:\c- %s", GetClassName(), target.GetClassName());
			}
			EGBL A 5 Bright A_Explode(160,64);
			EGBL B 1 Bright 
			{
				if (hitaceiling) { [success, EggShot] = A_Throwgrenade("EggMiniBerserk",-37,random(1,8),random(-12,-6),0); }
										else { [success, EggShot] = A_Throwgrenade("EggMiniBerserk",2,random(1,8),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShot) // && success) 
				{
					EggShot.target = self.target;
					if (EggShot.target && dydudebug_eggfractals) Console.Printf("EggShot.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShot.target.GetClassName());
				}
			}
			EGBL B 1 Bright 
			{
				if (hitaceiling) { [success, EggShot] = A_Throwgrenade("EggMiniBerserk",-37,random(1,10),random(-12,-6),0); }
										else { [success, EggShot] = A_Throwgrenade("EggMiniBerserk",2,random(1,10),random(6,12),0); }
				if (dydudebug_eggfractals) Console.Printf("\c[blue]success [%s]:\c- %d", GetClassName(), success);
				if (EggShot) // && success) 
				{
					EggShot.target = self.target;
					if (EggShot.target && dydudebug_eggfractals) Console.Printf("EggShot.\c[fire]target [\c[sapphire]%s\c-]:\c- %s", GetClassName(), EggShot.target.GetClassName());
				}
			}
			EGBL C 4 Bright;
			Stop;
	}
}

class EggMini : DDProjectile
{
	default
	{
		Tag "Small Fractal Egg";
		Radius 3;
		Height 3;
		Speed 10;
		Damage 6;
		DamageType "Breakfast";
		Projectile;
		-NOGRAVITY
		//+NOEXTREMEDEATH
		+FORCERADIUSDMG
		RENDERSTYLE "Normal";
		DeathSound "blunderfire";
		ExplosionDamage 32;
		BounceCount 2;
	}
	
	States
	{
		Spawn:
			EGGM ABCDE 3;
			loop;
		Death:
			TNT1 A 0 
			{
				A_CheckHitCeiling();
				bNOGRAVITY = true;
				target = PlayerPawn(players[0].mo);
				if (target && dydudebug_eggfractals) Console.Printf("\c[fire]target [%s]:\c- %s", GetClassName(), target.GetClassName());
			}
			EGBL A 5 Bright A_Explode(32,32);
			EGBL BC 5 Bright;
			Stop;
	}
}

class EggMiniBerserk : EggMini
{
	default
	{
		Tag "-Small Fractal Egg-";
		Radius 3;
		Height 3;
		Speed 13;
		Damage 9;
		DamageType "Breakfast";
		Projectile;
		-NOGRAVITY
		//+NOEXTREMEDEATH
		+FORCERADIUSDMG
		RENDERSTYLE "Normal";
		DeathSound "blunderfire";
		ExplosionDamage 48;
		BounceCount 2;
	}
	
	States
	{
		Spawn:
			EGGM ABCDE 3;
			loop;
		Death:
			TNT1 A 0 
			{
				A_CheckHitCeiling();
				bNOGRAVITY = true;
				target = PlayerPawn(players[0].mo);
				if (target && dydudebug_eggfractals) Console.Printf("\c[fire]target [%s]:\c- %s", GetClassName(), target.GetClassName());
			}
			EGBL A 5 Bright A_Explode(48,32);
			EGBL BC 5 Bright;
			Stop;
	}
}

class EggAmmo : Ammo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 2; // 4
		Inventory.MaxAmount 28; // 20
		Ammo.BackpackAmount 2; // 4
		Ammo.BackpackMaxAmount 42;
		Scale 1;
		Inventory.Icon "EGAMI0";
		Inventory.PickupMessage "A fractal chicken egg";
		+FLOATBOB
	}
	States
	{
		Spawn:
			EGGC ABCB 6;
			Loop;
	}
}

class EggAmmoBig : EggAmmo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 6; // 4
		Inventory.MaxAmount 28; // 20
		Ammo.BackpackAmount 6; // 4
		Ammo.BackpackMaxAmount 42;
		Scale 1;
		Inventory.Icon "EGAMI0";
		Inventory.PickupMessage "A set of fractal chicken eggs";
		+FLOATBOB
	}
	States
	{
		Spawn:
			EGGC DEFE 6;
			Loop;
	}
}

//*************
//* APPLEJACK *
//*************
class AppleJackSwingShieldPart : SwingShieldPart
{
	default
	{
		-AIMREFLECT
		+DEFLECT
		Radius 6; // out of 32
		Height 12; // out of 32
		Scale 0.375;
	}
	
	states
	{
		Spawn:
			HEXA C 4 bright NoDelay
			{
				//A_SetTics(randompick(1,2,2,2,3));
				//if (CountInv("PlayingDoom64")) { A_SetSize(19,19); }
			}
			stop;
		Pain:
			TNT1 A 1 bright 
			{
				//A_StartSound("CricketBat/ShieldHit", CHAN_WEAPON);
			}
			stop;
	}
}

class AppleJackSwingPartNoReflect : SwingShieldPartNoReflect
{
	default
	{
		Radius 6; // out of 32
		Height 12; // out of 32
		Scale 0.375;
	}
	
	states
	{
		Spawn:
			HEXA A 2 bright NoDelay
			{
				//A_SetTics(randompick(1,2,2,2,3));
				//if (CountInv("PlayingDoom64")) { A_SetSize(19,19); }
			}
			stop;
		Pain:
			TNT1 A 1 bright 
			{
				//A_StartSound("CricketBat/ShieldHit", CHAN_WEAPON);
			}
			stop;
	}
}

class AppleJack : DinahWeapon replaces Chaingun
{
	default
	{
		//$Category RPWeapons
		Weapon.SelectionOrder 100;
		Weapon.SlotNumber 4;
		Weapon.Kickback 75;
		Weapon.AmmoType2 "JackAmmo";
		Weapon.AmmoGive2 12;
		//Weapon.AmmoUse2 1;
		+WEAPON.NOALERT
		+WEAPON.MELEEWEAPON
		+PUFFONACTORS
		+FLOATBOB
		Inventory.Icon "AJAKP0";
		Inventory.Pickupsound "DinahWeap";
		Inventory.PickupMessage "Apple Jack";
		inventory.pickupsound "misc/w_pkup"; //"Dinah/marvelous"
		Tag "Apple Jack: Normal attack is a melee swing that hit twice. Alt attack is a ranged toss of an aggro-apple that can usually block incoming projectiles. Swings can also affect enemy projectiles.";
		Obituary "%k kept the doctor away from %o.";
	}
	
	action void A_AppleJackSwingShield(int type = 0, double dist = 96.0)
	{
		string vispart = "AppleJackSwingPartNoReflect";
		if (random(1,32) <= 5) vispart = "AppleJackSwingShieldPart";

		double yoffset = frandompick(-0.1625,0,0.1625);

		double distx, disty, distz;
		double heightmulti = 0.5;
		double heightmultivari = 0.0625;
		double yseperation = -3.467;
		double sa = sin(angle);
		double ca = cos(angle);
		//Console.Printf("angle sine: %.3f, angle cosine: %.3f", sa, ca);
		double sp = sin(pitch);
		double cp = cos(pitch);
		//Console.Printf("pitch sine: %.3f, pitch cosine: %.3f", sp, cp);
		int m = dist;

		if (type == 1) m *= 1.2;
		int m2 = m;

		if ((random (1,64) <= 63) || (type == 1 && (random(1,256) <= 255)))
		{
			distx = (m * frandom(0.95,1.05));
			disty = 0.0;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = (m * frandom(0.90,0.95));
			disty = (yseperation * 2);
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = yseperation;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty = yseperation;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			disty *= -1;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
	
			if ((random (1,16) <= 11) || (type == 1 && (random(1,32) <= 28)))
			{
				m = (m2 * 0.667);
	
				distx = (m * frandom(0.95,1.05));
				disty = 0.0;
				distz = (height * heightmulti) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				distx = (m * frandom(0.90,0.95));
				disty = (yseperation * 2);
				distz = (height * heightmulti) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				disty *= -1;
				distz = (height * heightmulti) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				disty = yseperation;
				distz = (height * (heightmulti - heightmultivari)) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				disty *= -1;
				distz = (height * (heightmulti - heightmultivari)) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				disty = yseperation;
				distz = (height * (heightmulti + heightmultivari)) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				disty *= -1;
				distz = (height * (heightmulti + heightmultivari)) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			}
	
	
			if ((random (1,16) <= 8) || (type == 1 && (random(1,16) <= 11)))
			{
				m = (m2 * 0.334);
	
				distx = (m * frandom(0.95,1.05));
				disty = 0.0;
				distz = (height * heightmulti) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				distx = (m * frandom(0.90,0.95));
				disty = (yseperation * 2);
				distz = (height * heightmulti) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				disty *= -1;
				distz = (height * heightmulti) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				disty = yseperation;
				distz = (height * (heightmulti - heightmultivari)) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				disty *= -1;
				distz = (height * (heightmulti - heightmultivari)) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				disty = yseperation;
				distz = (height * (heightmulti + heightmultivari)) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
				disty *= -1;
				distz = (height * (heightmulti + heightmultivari)) + yoffset;
				A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			}
	
			let MiscItem = PlayerStatItem(player.mo.FindInventory("PlayerStatItem"));
			if (MiscItem) MiscItem.CricketBatSwingBuffTimer = randompick(3,3,3,3,3,3,4,4,4);
		}
	}
	
	States
	{
		Spawn:
			AJAK P -1;
			stop;
		Ready:
			AJAK A 1
			{
				A_KickDecelerate();
				A_WeaponReady();
			}
			loop;
		Deselect:
			AJAK A 1
			{
				A_KickDecelerate();
				A_Lower(12);
			}
			loop;
		Select: 
			AJAK A 1
			{
				A_KickDecelerate();
				A_Raise(12);
			}
			loop;
		Fire:
			AJAK B 2
			{
				A_StartSound("MalletSwing",CHAN_WEAPON);
				if (random(1,32) <= 1 && !CountInv("PlayingStrife",AAPTR_PLAYER1)) { A_AlertMonsters(); }
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			AJAK C 2
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			AJAK D 2
			{
				int dmg = (random(6,8) * random(1,8));
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) dmg *= 10;
				if (dydudebug_meleedmg) Console.Printf("dmg: %d", dmg);
				A_CustomPunch(dmg, true, 0, "ApplePuff", 96);

				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
				{
					A_AppleJackSwingShield(1);
					A_SetTics(1);
				}
				else
				{
					A_AppleJackSwingShield(0);
				}
			}
			AJAK E 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			AJAK F 2
			{
				int dmg = (random(6,8) * random(1,8));
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) dmg *= 10;
				if (dydudebug_meleedmg) Console.Printf("dmg: %d", dmg);
				A_CustomPunch(dmg, true, 0, "ApplePuff", 96);

				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
				{
					A_AppleJackSwingShield(1);
					A_SetTics(1);
				}
				else
				{
					A_AppleJackSwingShield(0);
				}
			}
			AJAK G 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			TNT1 A 3
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(random(1,2)); }
			}
			AJAK BA 3
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(random(1,2)); }
			}
			goto Ready;
		AltFire:
			AJAF C 0
			{
				if (!CountInv("JackAmmo")) { return resolvestate("Fire"); }
				return resolvestate(null);
			}
			AJAF CDE 2
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			AJAF F 2 
			{
				if (random(1,32) <= 31) { A_AlertMonsters(); }
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{ 
					A_SetTics(1); 
					A_FireProjectile("JackShotBerserk",0,1,0,0);
				}
				else
				{
					A_FireProjectile("JackShot",0,1,0,0);
				}
				A_TakeInventory("JackAmmo",1);
			}
			AJAF GHI 2 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			TNT1 A 3
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(random(1,2)); }
			}
			AJAK BA 2
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(1); }
			}
			goto Ready;
	}
}

class ApplePuff : BatPuff
{
	default
	{
		Tag "AppleJack Bash";
		+NOBLOCKMAP
		+NOGRAVITY
		//+NOEXTREMEDEATH
		+PUFFONACTORS
		+FORCERADIUSDMG
		RenderStyle "Translucent";
		Alpha 0.6;
		SeeSound "MalletHit";
		AttackSound "MalletWall";
		VSpeed 1;
		DamageType "Bonk";
	}
	
	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				if (random(1,7) == 1) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
		Melee:
			TNT1 A 0
			{
				if (random(1,7) == 1) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
		Crash:
			TNT1 A 0
			{
				if (random(1,7) == 1) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
	}
}

class JackShotShieldPart : ShieldPartNoReflect
{
	default
	{
		Radius 9;
		Height 9;
		Scale 1.5;
		RenderStyle "Add"; // Add
		Alpha 0.375; // 0.003125
	}

	States
	{
		Spawn:
			ABAL A 0 NoDelay;
		Idle:
			ABAL AA 1
			{
				A_SetTics(randompick(1,1,2));
				A_FadeOut(0.125);
				A_SetScale(scale.x*0.5,scale.y*0.5);
			}
			Stop;
	}
}

class JackShotShieldPartBerserk : ShieldPartNoReflect
{
	default
	{
		Radius 12;
		Height 12;
		Scale 2;
		RenderStyle "Add"; // Add
		Alpha 0.4375; // 0.003125
	}

	States
	{
		Spawn:
			ABAL A 0 NoDelay;
		Idle:
			ABAL AAA 1
			{
				A_SetTics(randompick(1,1,2));
				A_FadeOut(0.109375);
				A_SetScale(scale.x*0.67,scale.y*0.67);
			}
			Stop;
	}
}

class JackShot : DDProjectile
{
	default
	{
		Tag "Aggro-Apple";
		Radius 6;
		Height 6;
		Speed 50;
		Damage 20;
		DamageType "Bonk";
		Projectile;
		+DONTREFLECT
		+FORCERADIUSDMG
		//+NOEXTREMEDEATH
		RENDERSTYLE "Normal";
		SeeSound "axe/throw";
		DeathSound "axe/hit";
	}
	
	States
	{
		Spawn:
			ABAL AABB 1 NoDelay
			{
				A_SpawnItemEx("JackShotShieldPart",0,0,0,0.0,0.0,0.0,0,SXF_SETTARGET|SXF_NOCHECKPOSITION);
			}
			Loop;
		Death:
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
	}
}

class JackShotBerserk : JackShot
{
	default
	{
		Tag "-Aggro-Apple-";
		Speed 75;
		Damage 100;
	}
	
	States
	{
		Spawn:
			ABAL AABB 1 NoDelay
			{
				A_SpawnItemEx("JackShotShieldPartBerserk",0,0,0,0.0,0.0,0.0,0,SXF_SETTARGET|SXF_NOCHECKPOSITION);
			}
			Loop;
		Death:
			BASH A 0
			{
				A_Explode(64,64,0);
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
	}
}

class Badjackshot : Jackshot
{
	default
	{
		Speed 20;
		Damage 3;
	}
	
	States
	{
		Spawn:
			ABAL AB 2;
			Loop;
		Death:
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
	}
}

class JackAmmo : Ammo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 3; // 6
		Inventory.MaxAmount 64; // 48
		Ammo.BackpackAmount 3; // 6
		Ammo.BackpackMaxAmount 96;
		Inventory.Icon "AJAMI0";
		Inventory.PickupMessage "An aggro-apple!";
		+FLOATBOB
	}
	
	States
	{
		Spawn:
			AJAM A -1;
			Loop;
	}
}

class JackAmmoBig : JackAmmo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 9; // 6
		Inventory.MaxAmount 64; // 48
		Ammo.BackpackAmount 9; // 6
		Ammo.BackpackMaxAmount 96;
		Inventory.Icon "AJAMI0";
		Inventory.PickupMessage "An set of aggro-apples!";
		+FLOATBOB
	}
	
	States
	{
		Spawn:
			AJAM B -1;
			Loop;
	}
}

//***************
//* WIZARD PIKE *
//***************
class WizardPike : DinahWeapon replaces RocketLauncher
{
	default
	{
		//$Category RPWeapons
		Weapon.SelectionOrder 400;
		Weapon.SlotNumber 5;
		Weapon.Kickback 25;
		Weapon.AmmoType2 "PikeAmmo";
		Weapon.AmmoGive2 2;
		//Weapon.AmmoUse2 0;
		+WEAPON.NOALERT
		+WEAPON.MELEEWEAPON
		+PUFFONACTORS
		+FLOATBOB
		Inventory.Icon "SCPPA0";
		Inventory.PickupMessage "Pike";
		inventory.pickupsound "misc/w_pkup"; //"Dinah/marvelous"
		Tag "Pike: Normal attack is a quick melee jab. Alt attack launches a wave of magical shots.";
		Obituary "%k fed %o to a hungry pike.";
	}
	
	States
	{
		Spawn:
			SCPP ABCDEFGH 6 Bright;
			loop;
		Ready:
			SCEP A 1
			{
				A_KickDecelerate();
				A_WeaponReady();
			}
			loop;
		Deselect:
			SCEP A 1
			{
				A_KickDecelerate();
				A_Lower(12);
			}
			loop;
		Select: 
			SCEP A 1
			{
				A_KickDecelerate();
				A_Raise(12);
			}
			loop;
		Fire:
			SCEP E 1 bright A_StartSound("Malletswing",CHAN_WEAPON);
			SCEP F 1 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			SCEP G 1;
			SCEP H 1 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			SCEP I 1;
			SCEP J 5
			{
				if (random(1,32) <= 1 && !CountInv("PlayingStrife",AAPTR_PLAYER1)) { A_AlertMonsters(); }
				int dmg = (random(6,8) * random(1,8));
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) dmg *= 10;
				if (dydudebug_meleedmg) Console.Printf("dmg: %d", dmg);
				A_CustomPunch(dmg, true, 0, "PikePuff", 96);
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
				{
					A_SetTics(random(2,3));
				}
				else
				{
				}
			}
			SCEP I 1;
			SCEP H 1 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			SCEP G 1;
			SCEP F 1 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(0); }
			}
			goto Ready;
		AltFire:
			SCEP A 0
			{
				if (!CountInv("PikeAmmo")) { return resolvestate("Fire"); }
				return resolvestate(null);
			}
			SCEP A 2 bright 
			{
				A_StartSound("Handmother/Zap",CHAN_WEAPON);
				if (random(1,32) <= 31) { A_AlertMonsters(); }
			}
			SCEP B 1 bright A_FireProjectile("ZapShot",0,0,0,0);
			SCEP A 1 bright;
			SCEP B 1
			{
				A_FireProjectile("miniZapShot",0,0,48,0);
				A_FireProjectile("miniZapShot",0,0,-48,0);
			}
			SCEP C 1 bright;
			SCEP B 1 bright 
			{
				A_FireProjectile("ZapShot",0,0,0,0);
			}
			SCEP C 1 bright;
			SCEP C 0
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_Recoil(frandom(0.64,0.96)); } else { A_Recoil(frandom(3.2,4.8)); }
			}
			SCEP D 6 bright
			{
				A_FireProjectile("miniZapShot",0,0,48,0);
				A_FireProjectile("miniZapShot",0,0,-48,0);
				A_FireProjectile("miniZapShot",0,0,0,40);
				A_FireProjectile("ZapShot",0,0,0,0);
				A_TakeInventory("PikeAmmo",1);
			}
			SCEP CBA 2 bright;
			goto Ready;
	}
}

class Pike_Flipped : CustomInventoryExt
{
	default
	{
		//$Category RPPropsFlipped
		Height 20;
		Radius 20;
		Tag "Pike (Flipped)";
		+FLOATBOB
		+NOGRAVITY
		Inventory.PickupMessage "Pike";
		inventory.pickupsound "misc/w_pkup"; //"Dinah/marvelous";
	}
	
	States
	{
		Spawn:
			SCPP ZYXWVUTS 6 Bright;
			Loop;
		Pickup:
			TNT1 A 1 A_GiveInventory("WizardPike");
			Stop;
	}
}

class PikePuff : BatPuff
{
	default
	{
		Tag "Pike Poke";
		+NOBLOCKMAP
		+NOGRAVITY
		//+NOEXTREMEDEATH
		+PUFFONACTORS
		+FORCERADIUSDMG
		RenderStyle "Translucent";
		Alpha 0.6;
		SeeSound "MalletHit";
		AttackSound "MalletWall";
		VSpeed 1;
		DamageType "Bonk";
	}
	
	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				if (random(1,4) <= 3) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
		Melee:
			TNT1 A 0
			{
				if (random(1,4) <= 3) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
		Crash:
			TNT1 A 0
			{
				if (random(1,4) <= 3) { bFORCEPAIN = true; }
			}
			BASH ABC 4 Bright;
			BASH DE 3 bright;
			Stop;
	}
}  

class PikeTracer : DDPuff
{
	default
	{
		Tag "Pike Blast";
		+NOBLOCKMAP
		+NOGRAVITY
		//+NOEXTREMEDEATH
		+NOGRAVITY
		RenderStyle "Translucent";
		Alpha 0.8;
		DamageType "zap";
	}
	
	States
	{
		Spawn:
			ZBUX A 4 Bright A_Explode;
			ZBUX BCD 4 Bright;
			Stop;
	}
}  

class ZapShot : DDFastProjectile
{
	default
	{
		Tag "Pike Blast";
		Radius 3;
		Height 3;
		Speed 80;
		Damage 12;
		Scale 1;
		DamageType "Zap";
		Projectile;
		RENDERSTYLE "Normal";
		deathsound "croquet/ballhit";
		+FORCERADIUSDMG
		//+NOEXTREMEDEATH
	}
	
	States
	{
		Spawn:
			ZBUL ABCD 3 Bright;
			loop;
		Death:
			ZBUX A 4 Bright A_Explode;
			ZBUX BCD 4 Bright;
			stop;
	}
}

class MiniZapShot : DDFastProjectile
{
	default
	{
		Tag "Mini Pike Blast";
		Radius 3;
		Height 3;
		Speed 80;
		Damage 8;
		Scale 0.5;
		DamageType "Zap";
		Projectile;
		RENDERSTYLE "Normal";
		deathsound "croquet/ballhit";
		+FORCERADIUSDMG
		//+NOEXTREMEDEATH
	}
	
	States
	{
		Spawn:
			ZBUL ABCD 3 Bright;
			loop;
		Death:
			ZBUX A 3 Bright;
			ZBUX BCD 3 Bright;
			stop;
	}
}

class BadZapshot : Zapshot
{
	default
	{
		Speed 20;
		Scale 0.75;
		Damage 5;
		+FORCERADIUSDMG
	}
	States
	{
		Spawn:
			ZBUL ABCD 3 Bright;
			loop;
		Death:
			ZBUX A 4 Bright ;
			ZBUX BCD 4 Bright;
			stop;
	}
}

class Lightningbolt : DDProjectile
{
	default
	{
		Height 32;
		Radius 20;
		Scale 2;
		Seesound "zappo";
	}
	
	States
	{
		Spawn:
			LITN ABAB 5 bright;
			LITN A 0 A_Die;
			Goto Death;
		Death:
			LITN CDE 5 bright A_Explode();
			LITN F 5 bright;
			Stop;
	}
}

class BarrierBeam : Zapshot 
{
	default
	{
		Height 16;
		Radius 20;
		Seesound "";
		Deathsound "";
	}
}

class PikeAmmo : Ammo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 1; // 2
		Inventory.MaxAmount 12; // 10
		Ammo.BackpackAmount 1; // 2
		Ammo.BackpackMaxAmount 18;
		Scale 1;
		Inventory.Icon "SCPAI0";
		Inventory.PickupMessage "A pint of devil's food";
		+FLOATBOB
	}
	
	States
	{
		Spawn:
			SCPA ABC 6 Bright;
			Loop;
	}
}

class PikeAmmoBig : PikeAmmo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 3; // 2
		Inventory.MaxAmount 12; // 10
		Ammo.BackpackAmount 3; // 2
		Ammo.BackpackMaxAmount 18;
		Scale 1;
		Inventory.Icon "SCPAI0";
		Inventory.PickupMessage "Many pints of devil's food";
		+FLOATBOB
	}
	
	States
	{
		Spawn:
			SCPA DEF 6 Bright;
			Loop;
	}
}

//************
//* SUPERVAC *
//************
class SuperVac : DinahWeapon replaces PlasmaRifle
{
	default
	{
		+SPECTRAL
		//$Category RPWeapons
		Weapon.SelectionOrder 900;
		Weapon.SlotNumber 6;
		Weapon.Kickback 0;
		Weapon.AmmoType2 "VacAmmo";
		Weapon.AmmoGive2 0;
		//Weapon.AmmoUse2 8;
		+WEAPON.NOALERT
		+WEAPON.MELEEWEAPON
		+PUFFONACTORS
		Inventory.Icon "VACMP0";
		Inventory.Pickupsound "DinahWeap";
		Inventory.PickupMessage "SuperVac";
		inventory.pickupsound "misc/w_pkup"; //"Dinah/marvelous"
		Tag "SuperVac: Normal attack is a constant vaccum/sucking attack that usually absorbs/erases that which it kills into ammo for the alt-fire. Alt fire requires 8 units of ammo, launches a trio of bouncing dust tornadoes as a super attack. Weighs you down, slowing speed and lowering jump height, more so with more collected ammo.";
		Obituary "%o sucks.";
	}

	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				if (CountInv("SuperVac",AAPTR_PLAYER1))
				{
					A_SpawnItemEx("VacAmmo",0,0,0,0,0,0,SXF_NOCHECKPOSITION);
					Thing_Remove(0); 
				}
			}
			VACM P 1;
			Loop;
		Ready:
			VACM A 1
			{
				A_KickDecelerate();
				A_WeaponReady();
			}
			loop;
		Deselect:
			VACM A 1
			{
				A_KickDecelerate();
				A_Lower(12);
			}
			loop;
		Select: 
			VACM A 1
			{
				A_KickDecelerate();
				A_Raise(12);
			}
			loop;
		Full:
			VACM A 0 A_StartSound("VacEmpty",CHAN_WEAPON);
			VACM AB 2;
			Goto Ready;
		Fire:
			VACM A 0
			{
				if (CountInv("BackPack",AAPTR_PLAYER1) || CountInv("ItemSatchel",AAPTR_PLAYER1))
				{
					if (CountInv("VacAmmo",AAPTR_PLAYER1) >= 24) { return resolvestate("Full"); }
					return resolvestate(null);
				}
				else
				{
					if (CountInv("VacAmmo",AAPTR_PLAYER1) >= 16) { return resolvestate("Full"); }
					return resolvestate(null);
				}
				return resolvestate(null);
			}
			VACM B 0 
			{
				A_StartSound("VacSuck");
				if (random(1,32) <= 29) { A_AlertMonsters(); }
			}
			VACM BA 2
			{
				int dmg = (random(3,6) * random(1,8));
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) dmg *= frandompick(1.0,1.0,1.125,1.125,1.125,1.125,1.125,1.25,1.25);
				if (dydudebug_meleedmg) Console.Printf("dmg: %d", dmg);
				if (random(1,16) <= 1)
				{
					A_CustomPunch(dmg, true, 0, "VacPuff", 80, frandompick(0.01,0.05,0.1), (health*0.05));
				}
				else
				{
					A_CustomPunch(dmg, true, 0, "VacPuff", 80);
				}
			}
			goto Ready;
		AltFire:
			DBID A 0
			{
				if (CountInv("VacAmmo") < 8) { return resolvestate("Fire"); }
				return resolvestate(null);
			}
			VACM A 4
			{
				int basechance = 192;
				if (random(1,256) <= basechance)
				{
					string voicenm;
					double voicevol = frandom(1.25,1.70);
					if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) voicevol *= frandompick(1.125,1.125,1.125,1.25,1.25,1.5);
					int randvoice = random(1,5);
					if (randvoice >= 1 && randvoice <= 3) 
					{
						if (exex_dinahextravoices) A_SetTics(random(2,4)*4);
						voicenm = "dinah/howsthis";
					}
					if (randvoice == 4) 
					{
						if (exex_dinahextravoices) A_SetTics(random(4,6)*4);
						voicenm = "dinah/thiswillhurt";
					}
					if (randvoice == 5) 
					{
						if (exex_dinahextravoices) A_SetTics(random(5,7)*4);
						voicenm = "dinah/thiswillendit";
					}
					if (exex_dinahextravoices)
					{
						A_StopSound(CHAN_VOICE);
						A_StartSound(voicenm,CHAN_VOICE,CHANF_DEFAULT,voicevol); 
					}
				} 
				//dinah/howsthis
			}
			VACM B 4 
			{
				A_StartSound("VacDed",CHAN_WEAPON);
				if (random(1,32) <= 21) { A_AlertMonsters(); }
			}
			VACM C 4
			{
				A_FireProjectile("VacShot",15,0,0,0);
				A_FireProjectile("VacShot",0,12,0,0);
				A_FireProjectile("VacShot",-15,0,0,0);
				A_TakeInventory("VacAmmo",8);
			}
			VACM B 3;
			VACM A 3;
			goto Ready;
	}
}

class VacPuff : DDPuff
{
	default
	{
		Tag "SuperVac Attack";
		+NOBLOCKMAP
		+NOGRAVITY
		+NOEXTREMEDEATH
		+PUFFONACTORS
		+PUFFGETSOWNER
		+BLOODLESSIMPACT
		RenderStyle "Translucent";
		Alpha 0.6;
		VSpeed 1;
		DamageType "Suck";
	}
	
	States
	{
		Spawn:
		Melee:
		Crash:
			TNT1 A 0 NoDelay
			{
				if (random(1,12) <= 1) 
				{
					bFORCEPAIN = true; 
				}
			}
			BASH DE 3 bright;
			Stop;
	}
} 

class VacShot : DDProjectile
{
	default
	{
		Tag "Dust Devil";
		Radius 3;
		Height 8;
		Speed 20;
		Damage 20;
		Scale 1;
		Projectile;
		DamageType "Dust";
		DontHurtShooter;
		RENDERSTYLE "Normal";
		seesound "Weapons/RocketFire";
		deathsound "croquet/ballhit";
	
		+BOUNCEONWALLS
		+BOUNCEONFLOORS
		+BOUNCEONCEILINGS
		+BOUNCEONACTORS
		+NOBOUNCESOUND
		+EXPLODEONWATER
		+DONTBOUNCEONSHOOTABLES
		+SKYEXPLODE
		+CANBOUNCEWATER
		+DONTREFLECT
		BounceType "Hexen";
		BounceFactor 1.03125;
		WallBounceFactor 1.03125;
		BounceCount 5;
		+RIPPER
		+FORCERADIUSDMG
		//+NOEXTREMEDEATH
	}
	
	States
	{
		Spawn:
			VSHT ABC 3 Bright A_Explode(41,64,0,0,16);
			loop;
		Death:
			TNT1 A 4 A_Explode(82,128,0,0,32);
			stop;
	}
}

class VacShot2 : DDProjectile
{
	default
	{
		Tag "Dust Devil";
		Radius 3;
		Height 8;
		Speed 20;
		Damage 20;
		Scale 1;
		Projectile;
		DamageType "Dust";
		DontHurtShooter;
		RENDERSTYLE "Normal";
		seesound "Weapons/RocketFire";
		deathsound "croquet/ballhit";
		+RIPPER
		+FORCERADIUSDMG
		//+NOEXTREMEDEATH
	}
	
	States
	{
		Spawn:
			VSHT ABC 3 Bright A_Explode(41,64,0,0,16);
			loop;
		Death:
			TNT1 A 4 A_Explode(82,128,0,0,32);
			stop;
	}
}

class VacAmmo : Ammo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 1;
		Inventory.MaxAmount 16; // 12
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 24;
		Inventory.Icon "VACMJ0";
		Inventory.PickupMessage "This bag is full. Ammo for SuperVac +1!";
	}
	
	States
	{
		Spawn:
			VACM Q -1;
			Loop;
	}
}

class VacAmmoBig : VacAmmo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 3;
		Inventory.MaxAmount 16; // 12
		Ammo.BackpackAmount 3;
		Ammo.BackpackMaxAmount 24;
		Inventory.Icon "VACMJ0";
		Inventory.PickupMessage "These bags are full. Ammo for SuperVac +3!";
	}
	
	States
	{
		Spawn:
			VACM R -1;
			Loop;
	}
}

//**************
//* Grimophone *
//**************
class Grimophone : DinahWeapon replaces BFG9000
{
	int musictype;
	int recordenergy;
	int recordalttimer;
	int dmg;
	int fulldist;
	int dist;
	int altflags;
	int altflags2;
	int modtimer;
	int levelcheck;
	default
	{
		//$Category RPWeapons
		Weapon.SelectionOrder 800;
		Weapon.Ammotype1 "MusicAmmo";
		Weapon.Ammouse1 1;
		Weapon.Ammotype2 "";
		//Weapon.Ammouse2 0;
		Weapon.Ammogive1 20;
		Weapon.Ammogive2 0;
		Weapon.SlotNumber 7;
		inventory.pickupsound "misc/w_pkup"; //"Dinah/marvelous"
		Inventory.Pickupmessage "Grimophone";
		Tag "Grimophone: Normal attack is a dual-shot of records per unit of ammo. Alt-attack plays a cacophony of music that deals constant low-level damage within 1024 units, costing a unit of ammo roughly every ten seconds. Weighs you down, causing speed and jump height to lower while equipping it.";
		//SpawnID 31981
		+FLOATBOB
	}
	
	action void A_GrimophoneLevelCheck()
	{
		let MiscItem = PlayerStatItem(player.mo.FindInventory("PlayerStatItem"));
		if (MiscItem) 
		{
			invoker.levelcheck = MiscItem.PlayerLevel;
			//Console.Printf("levelcheck: %d", invoker.levelcheck);
		}
	}

	action void A_GrimophoneAltReset()
	{
		invoker.recordalttimer = 0;
		invoker.modtimer = 90;
		let MiscItem = PlayerStatItem(player.mo.FindInventory("PlayerStatItem"));
		if (MiscItem) MiscItem.GrimophoneDebuffTimer = 0;
	}
	
	States
	{
		Spawn:
			RPLY P 1;
			loop;
		Ready:
			RPLY A 1
			{
				A_GrimophoneAltReset();
				A_KickDecelerate();
				A_StopSound(65);
				A_WeaponReady();
			}
			loop;
		Select:
			RPLY A 1
			{
				A_GrimophoneAltReset();
				A_KickDecelerate();
				A_Raise(12);
			}
			Loop;
		Deselect:
			RPLY A 1
			{
				A_GrimophoneAltReset();
				A_KickDecelerate();
				A_Lower(12);
			}
			TNT1 A 0 A_StopSound(65);
			Loop;
		Fire:
			RPLY A 0 
			{
				invoker.musictype = random(1,16);
				if (invoker.musictype >= 1 && invoker.musictype <= 14) { A_StartSound("grimophone/jam",65,CHANF_LOOPING,1.0,ATTN_NORM,frandom(0.92,1.08)); }
				else if (invoker.musictype == 15) { A_StartSound("sa/rickroll",65,CHANF_LOOPING,1.0,ATTN_NORM,frandom(0.92,1.08)); }
				else if (invoker.musictype == 16) { A_StartSound("sa/vuvuzela",65,CHANF_LOOPING,1.0,ATTN_NORM,frandom(0.92,1.08)); }
			}
		Fire2:
			NULL A 0 
			{
				A_GunFlash();
			}
			RPLY B 1 Bright 
			{
				let record = A_FireProjectile("recordshot",0,1);
				if (record)
				{
					if (invoker.musictype == 15) { record.stamina = 3; }
					else if (invoker.musictype == 16) { record.stamina = 5; }
				}
			}
			RPLY B 1;
			RPLY B 1;
			RPLY C 1;
			RPLY C 1;
			RPLY C 1;
			RPLY B 1 Bright 
			{
				let record = A_FireProjectile("recordshot",0,0);
				if (record)
				{
					if (invoker.musictype == 15) { record.stamina = 3; }
					else if (invoker.musictype == 16) { record.stamina = 5; }
				}
			}
			RPLY B 1;
			RPLY B 1;
			RPLY C 1;
			RPLY C 1;
			RPLY C 1;
			RPLY C 0 
			{
				A_Refire("Fire2");
			}
			RPLY A 0 A_StopSound(65);
			Goto Ready;
		AltFire:
			RPLY A 0 
			{
				invoker.musictype = random(1,16);
				if (invoker.musictype >= 1 && invoker.musictype <= 14) { A_StartSound("grimophone/jam",65,CHANF_LOOPING,1.0,ATTN_NORM,frandom(0.92,1.08)); }
				else if (invoker.musictype == 15) { A_StartSound("sa/rickroll",65,CHANF_LOOPING,1.0,ATTN_NORM,frandom(0.92,1.08)); }
				else if (invoker.musictype == 16) { A_StartSound("sa/vuvuzela",65,CHANF_LOOPING,1.0,ATTN_NORM,frandom(0.92,1.08)); }
				
				invoker.modtimer = 90;
			}
		AltFire2:
			NULL A 0 
			{
				A_GunFlash();
				if (invoker.recordenergy <= 0)
				{
					if (CountInv("MusicAmmo") > 0)
					{
						A_TakeInventory("MusicAmmo",1);
						invoker.recordenergy += 42;
					}
					else
					{
						return resolvestate("Ready");
					}
					return resolvestate(null);
				}
				return resolvestate(null);
			}
			RPLY BBCC 2
			{
				invoker.dmg = random(2,4);
				if (invoker.musictype == 15) invoker.dmg = random(6,12); // V:
				if (invoker.musictype == 16) invoker.dmg = random(10,20); // LUL :V
				invoker.dist = 1024;
				invoker.fulldist = (invoker.dist * frandompick(0.375,0.5,0.625));
				invoker.recordalttimer += 2;
				invoker.altflags = XF_NOTMISSILE|XF_NOSPLASH;
				invoker.altflags2 = RTF_NOTMISSILE|RTF_NOIMPACTDAMAGE;
				if (dydudebug_grimophonealtfire) Console.Printf("recordalttimer %d", invoker.recordalttimer);
				
				if (invoker.recordalttimer > 0 && invoker.recordalttimer % invoker.modtimer == 0)
				{
					invoker.altflags = XF_HURTSOURCE|XF_NOTMISSILE|XF_NOSPLASH;
					invoker.altflags2 = RTF_AFFECTSOURCE|RTF_NOTMISSILE|RTF_NOIMPACTDAMAGE;
				}

				if (invoker.recordalttimer > 2520)
				{
					if (invoker.recordalttimer % 30) invoker.modtimer -= 1;
				}

				if (invoker.recordalttimer > 2430)
				{
					if (invoker.recordalttimer % 32) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 2340)
				{
					if (invoker.recordalttimer % 34) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 2250)
				{
					if (invoker.recordalttimer % 36) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 2160)
				{
					if (invoker.recordalttimer % 38) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 2070)
				{
					if (invoker.recordalttimer % 40) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 1980)
				{
					if (invoker.recordalttimer % 45) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 1890)
				{
					if (invoker.recordalttimer % 50) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 1800)
				{
					if (invoker.recordalttimer % 55) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 1620)
				{
					if (invoker.recordalttimer % 60) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 1350)
				{
					if (invoker.recordalttimer % 75) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 990)
				{
					if (invoker.recordalttimer % 85) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 540)
				{
					if (invoker.recordalttimer % 95) invoker.modtimer -= 1;
				}
				else
				if (invoker.recordalttimer > 90)
				{
					if (invoker.recordalttimer % 105) invoker.modtimer -= 1;
				}
				if (invoker.modtimer < 10) invoker.modtimer = 10;

				A_Explode(invoker.dmg,invoker.dist,invoker.altflags,1,invoker.fulldist,0,0,"","Beats");
				A_RadiusThrust((invoker.dmg*-1),invoker.dist,invoker.altflags2,(invoker.fulldist*-1));
				if (random(1,64) == 1)
				{
					A_Explode((invoker.dmg*5),invoker.dist,XF_NOTMISSILE|XF_NOSPLASH,1,invoker.fulldist,0,0,"","Beats");
					A_RadiusThrust((invoker.dmg*-5),invoker.dist,RTF_NOTMISSILE|RTF_NOIMPACTDAMAGE,(invoker.fulldist*-1));
				}
				
				let MiscItem = PlayerStatItem(player.mo.FindInventory("PlayerStatItem"));
				if (MiscItem) MiscItem.GrimophoneDebuffTimer += 4;
			}
			RPLY C 0 
			{
				if (random(1,32) <= 31) 
				{
					invoker.recordenergy--; 
				}
				else
				{
					if (random(1,2) == 1) { invoker.recordenergy -= 2; } 
				}
				if (dydudebug_grimophonealtfire) Console.Printf("recordenergy %d", invoker.recordenergy);
				if (invoker.recordenergy <= 0)
				{
					if (CountInv("MusicAmmo") <= 0)
					{
						A_StopSound(65);
						return resolvestate("Ready");
					}
					else
					{
						A_Refire("AltFire2");
					}
					return resolvestate(null);
				}
				else
				{
					A_Refire("AltFire2");
				}
				return resolvestate(null);
			}
			RPLY A 0 A_StopSound(65);
			Goto Ready;
	}
}

class BadMusic : SingleDamageRipper
{
	default
	{
		Radius 16;
		Height 8;
		Speed 50;
		DamageFunction (random(2,5)); //
		Projectile;
		-SOLID
		+BLOODLESSIMPACT
		+DONTREFLECT
		+NOBLOCKMAP
		+RIPPER
		+RANDOMIZE
		+NOEXTREMEDEATH
		+STEPMISSILE
		-ACTIVATEIMPACT
		-ACTIVATEMCROSS
		-ACTIVATEPCROSS
		-CANPUSHWALLS
		-CANBLAST
		DamageType "Musak";
		RenderStyle "translucent";
    Alpha 0.5;
    Scale 0.06;
		Obituary "$OB_MPPLASMARIFLE";
	}
	States
	{
		Spawn:
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			MUSN A 1;
			Goto Death; // Loop
		Death:
			TNT1 A 1;
			Stop;
	}
}

class RecordShot : DDProjectile
{
	int seekstrength;
	int seekchance;
	int seekdist;
	default
	{
		Tag "RazorRecord";
		Radius 6;
		Height 6;
		Speed 30;
		DamageFunction (finaldamagedealt);
		DamageType "Beats";
		Projectile;
		+SEEKERMISSILE
		+DONTREFLECT
		+FORCERADIUSDMG
		//+NOEXTREMEDEATH
		RENDERSTYLE "Normal";

		+BOUNCEONWALLS
		+BOUNCEONFLOORS
		+BOUNCEONCEILINGS
		+BOUNCEONACTORS
		+NOBOUNCESOUND
		+EXPLODEONWATER
		+DONTBOUNCEONSHOOTABLES
		+SKYEXPLODE
		+CANBOUNCEWATER
		BounceType "Hexen";
		BounceFactor 1.03125;
		WallBounceFactor 1.03125;
		BounceCount 2;
		SeeSound "axe/throw";
		DeathSound "axe/hit";
	}
	
	override void PostBeginPlay()
	{
		finaldamagedealt = (12*random(1,8));
		if (Stamina == 3) finaldamagedealt *= 3;
		if (Stamina >= 5) finaldamagedealt *= 5;
		if (dydudebug_rangedmg) Console.Printf("finaldamagedealt: %d", finaldamagedealt);
		super.PostBeginPlay();
	}
	
	States
	{
		Spawn:
			RBUL A 0 NoDelay
			{
				seekstrength = 18;
				seekchance = 50;
				seekdist = 10;
				if (target && target.GetClassName() == "DinahPlayer")
				{
					let MiscItem = PlayerStatItem(target.player.mo.FindInventory("PlayerStatItem"));
					if (MiscItem) 
					{
						seekstrength += (MiscItem.PlayerLevel * 0.36);
						seekchance += (MiscItem.PlayerLevel * 0.75);
						seekdist += (MiscItem.PlayerLevel * 0.10);
					}
				}
			}
			RBUL ABAB 1
			{
				if (random(1,4) == 1) { A_ScaleVelocity(1.0025); }
			}
			RBUL ABAB 1
			{
				if (random(1,2) == 1) { A_ScaleVelocity(1.0375); }
			}
			RBUL ABAB 1
			{
				if (random(1,4) <= 3) { A_ScaleVelocity(1.005); }
			}
			RBUL ABAB 1
			{
				if (random(7,8) <= 7) { A_ScaleVelocity(1.005); }
			}
		Spawn2:
			RBUL AB 1 
			{
				A_SeekerMissile(seekstrength,seekstrength,SMF_LOOK|SMF_PRECISE,seekchance);
				A_ScaleVelocity(1.000125);
			}
			Loop;
		Death:
			BASH A 0
			{
				user_randompain = 16;
				if (target && target.GetClassName() == "DinahPlayer")
				{
					let MiscItem = PlayerStatItem(target.player.mo.FindInventory("PlayerStatItem"));
					if (MiscItem) user_randompain += (MiscItem.PlayerLevel * 0.16);
				}
				if (random(1,100) <= user_randompain) { bFORCEPAIN = true; }
			}
			BASH ABC 3 Bright;
			BASH DE 2 bright;
			Stop;
	}
}

class MusicAmmo : Ammo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 3; // 6
		Inventory.MaxAmount 66; // 50
		Ammo.BackpackAmount 3; // 6
		Ammo.BackpackMaxAmount 99;
		Inventory.Icon "RAMOI0";
		Inventory.PickupMessage "A musical record";
		+FLOATBOB
	}
	
	States
	{
		Spawn:
			RAMO A -1;
			Loop;
	}
}

class MusicAmmoBig : MusicAmmo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 9; // 6
		Inventory.MaxAmount 66; // 50
		Ammo.BackpackAmount 9; // 6
		Ammo.BackpackMaxAmount 99;
		Inventory.Icon "RAMOI0";
		Inventory.PickupMessage "A few musical records";
		+FLOATBOB
	}
	
	States
	{
		Spawn:
			RAMO B -1;
			Loop;
	}
}

// MORPHED WEAPONS
class RatNose : DDBeak
{
	default
	{
		Weapon.SelectionOrder 10000;
		+WEAPON.DONTBOB
		+WEAPON.MELEEWEAPON
		Weapon.YAdjust 15;
		Obituary "$OB_MPRAT";
		AttackSound "Rat/Hit";
	}
	
	States
	{
		Ready:
			RATW AAAAAAAA 1 A_WeaponReady();
			RATW A 0 A_Jump(16,1);
			Loop;
			RATW B 1 A_StartSound("Rat/Active", CHAN_WEAPON);
			RATW BBB 1;
			Loop;
		Deselect:
			RATW A 1
			{
				A_Lower(12);
			}
			Loop;
		Select:
			RATW A 1 
			{
				A_Raise(12);
			}
			Loop;
		Fire:
			RATW A 0 A_StartSound("Rat/Attack", CHAN_WEAPON);
			RATW A 8
			{
				if (CountInv("PowerStrength",AAPTR_PLAYER1) || CountInv("PowerStrengthDD",AAPTR_PLAYER1))
				{
					A_CustomPunch((1*10),false);
				}
				else
				{
					A_CustomPunch(1,false);
				}
			}
			RATW B 8;
			Goto Ready;
	}
}

class RavenWeapon : DDBeak
{
	default
	{
		Weapon.SelectionOrder 10000;
		+Weapon.DontBob
		+Weapon.MeleeWeapon
		+Weapon.NoAlert
	}
	States
	{
		Ready:
			TNT1 A 1 A_WeaponReady();
			Loop;
		Deselect:
			TNT1 A 1
			{
				A_Lower(12);
			}
			Loop;
		Select:
			TNT1 A 1 A_BeakRaise();
			Loop;
		Fire:
			TNT1 A 18 A_Punch();
			Goto Ready;
	}
}

//********************
//* Roman CandleWhip *
//********************
class WhipShieldPart : ShieldPart
{
	default
	{
		-AIMREFLECT
		+DEFLECT
		Radius 6; // out of 32
		Height 12; // out of 32
		Scale 0.375;
	}
	states
	{
		Spawn:
			HEXA C 2 bright NoDelay
			{
				//A_SetTics(randompick(1,2,2,2,3));
				//if (CountInv("PlayingDoom64")) { A_SetSize(19,19); }
			}
			stop;
		Pain:
			TNT1 A 1 bright 
			{
			}
			stop;
	}
}

class WhipShieldPartNoReflect : ShieldPartNoReflect
{
	default
	{
		Radius 6; // out of 32
		Height 12; // out of 32
		Scale 0.375;
	}
	states
	{
		Spawn:
			HEXA A 2 bright NoDelay
			{
				//A_SetTics(randompick(1,2,2,2,3));
				//if (CountInv("PlayingDoom64")) { A_SetSize(19,19); }
			}
			stop;
		Pain:
			TNT1 A 1 bright 
			{
			}
			stop;
	}
}

class CandleWhip : DinahWeapon
{
	int range, rangebase;
	int dmg;
	int shotcounter, shotcountermax;
	default
	{
		//$Category RPWeapons
		Weapon.SelectionOrder 200;
		Weapon.SlotNumber 8;
		Weapon.Kickback 0;
		Weapon.AmmoType2 "CandleAmmo";
		Weapon.AmmoGive2 20;
		Weapon.AmmoUse2 0;
		+WEAPON.MELEEWEAPON
		+WEAPON.NOALERT
		+PUFFONACTORS
		+FLOATBOB
		Inventory.Icon "RCAIA0";
		Inventory.PickupMessage "\c[gold]Is... is this a Roman Candle? It seems to have a function as a whip too... Niiiiiice... :D";
		inventory.PickupSound "misc/w_pkup"; //"Dinah/marvelous"
		Tag "Roman Candlewhip";
		HitObituary "%k gave %o some major whiplash.";
	}
	
	action void A_CandleWhipCrack(int type = 0, double dist = 128.0)
	{
		//A_BatGuardDashOff();
		string vispart = "WhipShieldPartNoReflect";
		if (random(1,64) <= 1) vispart = "WhipShieldPart";

		double yoffset = frandompick(-0.1625,0,0.1625);

		double distx, disty, distz;
		double heightmulti = 0.5;
		double heightmultivari = 0.125;
		if (type == 1) heightmultivari = 0.1875;
		double yseperation = -2.6;
		double sa = sin(angle);
		double ca = cos(angle);
		if (dydudebug_cricketbatguard) Console.Printf("angle sine: %.3f, angle cosine: %.3f", sa, ca);
		double sp = sin(pitch);
		double cp = cos(pitch);
		if (dydudebug_cricketbatguard) Console.Printf("pitch sine: %.3f, pitch cosine: %.3f", sp, cp);
		int m = dist;

		int m2 = m;
		int m3 = (m * frandom(0.95,1.05));

		distx = m3;
		disty = 0.0;
		distz = (height * heightmulti) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		distx = m3;
		disty = 0.0;
		distz = (height * (heightmulti + heightmultivari)) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		distx = m3;
		disty = 0.0;
		distz = (height * (heightmulti - heightmultivari)) + yoffset;
		A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);

		if ((random (1,32) <= 31) || (type == 1 && (random (1,64) <= 63)))
		{
			m = (m2 * 0.833);
			m3 = (m * frandom(0.95,1.05));

			distx = m3;
			disty = 0.0;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = m3;
			disty = 0.0;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = m3;
			disty = 0.0;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		}

		if ((random (1,32) <= 31) || (type == 1 && (random (1,64) <= 63)))
		{
			m = (m2 * 0.667);
			m3 = (m * frandom(0.95,1.05));

			distx = m3;
			disty = 0.0;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = m3;
			disty = 0.0;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = m3;
			disty = 0.0;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		}

		if ((random (1,16) <= 12) || (type == 1 && (random (1,16) <= 15)))
		{
			m = (m2 * 0.500);
			m3 = (m * frandom(0.95,1.05));

			distx = m3;
			disty = 0.0;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = m3;
			disty = 0.0;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = m3;
			disty = 0.0;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);

			m = (m2 * 0.334);
			m3 = (m * frandom(0.95,1.05));

			distx = m3;
			disty = 0.0;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = m3;
			disty = 0.0;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = m3;
			disty = 0.0;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);

			m = (m2 * 0.1667);
			m3 = (m * frandom(0.95,1.05));

			distx = m3;
			disty = 0.0;
			distz = (height * heightmulti) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = m3;
			disty = 0.0;
			distz = (height * (heightmulti + heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
			distx = m3;
			disty = 0.0;
			distz = (height * (heightmulti - heightmultivari)) + yoffset;
			A_SpawnItemEx(vispart, (cos(-pitch) * A_SetShieldPieceDist(distx)), disty, (A_SetShieldPieceDist(distz) + (sin(-pitch) * A_SetShieldPieceDist(distx))), 0, 0, 0, 0, SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERPITCH|SXF_NOCHECKPOSITION);
		}
	}
	
	action void A_CandleWhipHit()
	{
		A_CustomPunch((invoker.dmg), true, CPF_NOTURN, "WhipPuff", invoker.range);
		//A_RailAttack((invoker.dmg),0,0,"","",RGF_SILENT,0,"WhipPuff",0,0,invoker.range,0,0,0,"",0);
	}
	
	action void A_CandleSetMaxShots()
	{
		invoker.shotcountermax = randompick(1,1,2,2,2,2,2,2,3,3);
	}

	States
	{
		Spawn:
			RCAI AAABBBCCCDDDEEEFFFGGGHHH 2 bright
			{
				if (CountInv("CandleWhip",AAPTR_PLAYER1))
				{
					A_SpawnItemEx("CandleAmmo",0,0,0,0,0,0,SXF_NOCHECKPOSITION);
					Thing_Remove(0); 
				}
			}
			loop;
		Ready:
			RCAN A 1
			{
				A_KickDecelerate();
				if (invoker.shotcountermax <= 0) { A_CandleSetMaxShots(); }
				A_WeaponReady();
			}
			loop;
		Deselect:
			RCAN Z 1 
			{
				A_KickDecelerate();
				if (invoker.shotcountermax <= 0) { A_CandleSetMaxShots(); }
				A_Lower(12);
			}
			loop;
		Select: 
			RCAN Z 1 
			{
				A_KickDecelerate();
				if (invoker.shotcountermax <= 0) { A_CandleSetMaxShots(); }
				A_Raise(12);
			}
			loop;
		Fire:
			RCAN Z 0 bright
			{
				invoker.rangebase = randompick(112,120,120,128,128,128,128,128,136,136,144);
				invoker.dmg = (random(8,12) * randompick(1,2,2,2,3,3,3,3,3,4,4,4,5));
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					invoker.dmg *= 10;
					invoker.range *= frandompick(1.0,1.0,1.0,1.125,1.125,1.25);
				}
				invoker.dmg *= frandompick(0.15,0.2,0.2,0.2,0.2,0.25);
				if (invoker.dmg < 1) invoker.dmg = 1;
				if (dydudebug_meleedmg) Console.Printf("%d",invoker.dmg);
			}
			RCAN Z 3 bright
			{
				invoker.range = (invoker.rangebase * 0.59);
				A_SetAngle(angle+75);
				A_CandleWhipHit();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_SetTics(random(1,2));
					if (random(1,8) <= 5) { A_CandleWhipCrack(1,invoker.range); }
				}
				else
				{
					if (random(1,8) <= 5) { A_CandleWhipCrack(0,invoker.range); }
				}
				A_SetAngle(angle-75);
			}
			RCAN F 2 bright 
			{
				invoker.range = (invoker.rangebase * 0.73);
				A_SetAngle(angle+56.25);
				A_CandleWhipHit();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_SetTics(1);
					if (random(1,8) <= 5) { A_CandleWhipCrack(1,invoker.range); }
				}
				else
				{
					if (random(1,8) <= 5) { A_CandleWhipCrack(0,invoker.range); }
				}
				A_SetAngle(angle-56.25);

				A_StartSound("candlecrack");

				if (CountInv("PlayingStrife",AAPTR_PLAYER1))
				{
					if (random(1,8) >= 7) { A_AlertMonsters(512); }
				}
				else
				{
					if (random(1,8) >= 7) { A_AlertMonsters(); }
				}
			}
			RCAN G 2 bright
			{
				invoker.range = (invoker.rangebase * 0.85);
				A_SetAngle(angle+37.5);
				A_CandleWhipHit();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_SetTics(1);
					if (random(1,16) <= 9) { A_CandleWhipCrack(1,invoker.range); }
				}
				else
				{
					if (random(1,16) <= 9) { A_CandleWhipCrack(0,invoker.range); }
				}
				A_SetAngle(angle-37.5);
			}
			RCAN H 2 bright
			{
				invoker.range = (invoker.rangebase * 0.94);
				A_SetAngle(angle+18.75);
				A_CandleWhipHit();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_CandleWhipCrack(1,invoker.range);
					A_SetTics(1); 
				}
				else
				{
					A_CandleWhipCrack(0,invoker.range);
				}
				A_SetAngle(angle-18.75);
			}
			RCAN H 2 bright
			{
				invoker.range = (invoker.rangebase * 1.0);
				A_CandleWhipHit();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD"))
				{
					A_CandleWhipCrack(1,invoker.range);
					A_SetTics(1); 
				}
				else
				{
					A_CandleWhipCrack(0,invoker.range);
				}
			}
			RCAN I 3 bright
			{
				invoker.range = (invoker.rangebase * 0.94);
				A_SetAngle(angle-18.75);
				A_CandleWhipHit();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_SetTics(random(1,2));
					if (random(1,32) <= 25) { A_CandleWhipCrack(1,invoker.range); }
				}
				else
				{
					if (random(1,32) <= 25) { A_CandleWhipCrack(0,invoker.range); }
				}
				A_SetAngle(angle+18.75);
			}
			RCAN J 3 bright
			{
				invoker.range = (invoker.rangebase * 0.85);
				A_SetAngle(angle-37.5);
				A_CandleWhipHit();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_SetTics(random(1,2));
					if (random(1,16) <= 9) { A_CandleWhipCrack(1,invoker.range); }
				}
				else
				{
					if (random(1,16) <= 9) { A_CandleWhipCrack(0,invoker.range); }
				}
				A_SetAngle(angle+37.5);
			}
			RCAN K 3 bright
			{
				invoker.range = (invoker.rangebase * 0.73);
				A_SetAngle(angle-56.25);
				A_CandleWhipHit();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_SetTics(random(1,2));
					if (random(1,8) <= 5) { A_CandleWhipCrack(1,invoker.range); }
				}
				else
				{
					if (random(1,8) <= 5) { A_CandleWhipCrack(0,invoker.range); }
				}
				A_SetAngle(angle+56.25);
			}
			RCAN L 3 bright
			{
				invoker.range = (invoker.rangebase * 0.59);
				A_SetAngle(angle-75);
				A_CandleWhipHit();
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) 
				{
					A_SetTics(random(1,2));
					if (random(1,4) <= 1) { A_CandleWhipCrack(1,invoker.range); }
				}
				else
				{
					if (random(1,4) <= 1) { A_CandleWhipCrack(0,invoker.range); }
				}
				A_SetAngle(angle+75);
			}
			RCAN A 1
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(randompick(0,0,0,1)); }
			}
			goto Ready;
		AltFire:
			RCAN A 0
			{
				if (!CountInv("CandleAmmo")) { return resolvestate("Fire"); }
				return resolvestate(null);
			}
			RCAN A 0 
			{
				A_StartSound("candleshot",1);
			}
			RCAN B 3 Bright
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(randompick(2,3,3,3,3)); }
				A_FireBullets(0,0,0,(5*random(1,3)),"candlepuff");
				
				invoker.shotcounter++;
				if (invoker.shotcounter >= invoker.shotcountermax)
				{
					A_TakeInventory("CandleAmmo",1);
					A_CandleSetMaxShots();
					invoker.shotcounter = 0;
				}
			}
			RCAN C 3 Bright
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(randompick(2,3,3,3,3)); }
			}
			RCAN D 4
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(randompick(3,4,4,4)); }
			}
			RCAN E 4 
			{
				if (CountInv("PowerStrength") || CountInv("PowerStrengthDD")) { A_SetTics(randompick(3,4,4,4)); }
				A_Refire();
			}
			goto Ready;
	}
}

class WhipPuff : DDPuff
{
	int basechance;
	default
	{
		Tag "Roman CandleWhiplash";
		//+ALWAYSPUFF
		+NOBLOCKMAP
		+NOGRAVITY
		//+NOEXTREMEDEATH
		+PUFFONACTORS
		+PUFFGETSOWNER
		RenderStyle "Translucent";
		Alpha 0.6;
		SeeSound "MalletHit";
		AttackSound "MalletWall";
		VSpeed 0.25;
		DamageType "Fire";
	}
	
	void A_CheckFPain()
	{
		basechance = 4;
		if (target && target.GetClassName() == "DinahWick" && (target.CountInv("PowerStrength") || target.CountInv("PowerStrengthDD"))) basechance /= 2;
		if (random(1,basechance) <= 1)
		{
			bFORCEPAIN = true; 
			//Console.Printf("bFORCEPAIN");
		}
	}
	
	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				A_CheckFPain();
			}
			CHOP ABC 4 Bright;
			Stop;
		Melee:
			TNT1 A 0
			{
				A_CheckFPain();
			}
			CHOP ABC 4 Bright;
			Stop;
		Crash:
			TNT1 A 0
			{
				A_CheckFPain();
			}
			CHOP ABC 4 Bright;
			Stop;
	}
}  

class CandlePuff : DDPuff
{
	int basechance;
	default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+NOEXTREMEDEATH
		+PUFFONACTORS
		+PUFFGETSOWNER
		RenderStyle "Translucent";
		Alpha 0.8;
		Scale 0.5;
		SeeSound "croquet/ballhit";
		AttackSound "croquet/ballhit";
		VSpeed 0.25;
		DamageType "Fire";
	}
	
	void A_CheckFPain()
	{
		basechance = 8;
		if (random(1,basechance) <= 1)
		{
			bFORCEPAIN = true; 
			//Console.Printf("bFORCEPAIN");
		}
	}
	
	States
	{
		Spawn:
			CANX ABC 0 NoDelay
			{
				A_CheckFPain();
			}
			CANX ABC 4 Bright;
			CANX DE 3 bright;
			Stop;
	}
}  

class CandleAmmo : Ammo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 10;
		Inventory.MaxAmount 75;
		Ammo.BackpackAmount 10;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "RCAIA0";
		Inventory.PickupMessage "";
		+FLOATBOB
	}
	
	override bool TryPickup (in out Actor toucher)
	{
		if (Ammo.TryPickup(toucher))
		{
			if (!toucher.CountInv("CandleWhip")) 
			{
				toucher.A_GiveInventory("CandleWhip", 1);
				PickupSound = "misc/w_pkup";
				Console.Printf("\c[gold]Is... is this a Roman Candle? It seems to have a function as a whip too... Niiiiiice... :D");
			}
			else
			{
				Console.Printf("\c[gold]Another Roman Candle.");
			}
			return true;
		}
		return false;
	}

	States
	{
		Spawn:
			RCAI AAABBBCCCDDDEEEFFFGGGHHH 2;
			Loop;
	}
}

class CandleAmmoBig : CandleAmmo
{
	default
	{
		//$Category RPAmmo
		Inventory.Amount 30;
		Inventory.MaxAmount 75;
		Ammo.BackpackAmount 30;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "RCALA0";
		Inventory.PickupMessage "";
		+FLOATBOB
	}
	
	override bool TryPickup (in out Actor toucher)
	{
		if (Ammo.TryPickup(toucher))
		{
			if (!toucher.CountInv("CandleWhip")) 
			{
				toucher.A_GiveInventory("CandleWhip", 1);
				PickupSound = "misc/w_pkup";
				Console.Printf("\c[gold]Are... are these a batch of Roman Candles? They seem to have a function as whips too... Niiiiiice... :D");
			}
			else
			{
				Console.Printf("\c[gold]A set of more Roman Candles...");
			}
			return true;
		}
		return false;
	}

	States
	{
		Spawn:
			RCAL AAABBBCCCDDDEEEFFFGGGHHH 2;
			Loop;
	}
}